### ISSUE TITLE
Warrants Discord channel feature

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#1012]
### Describe the feature

![image](https://user-images.githubusercontent.com/25211271/182421724-2679a3f4-5422-45af-9144-24692cb81a94.png)

Can we add one for WARRANTS too? :)

**Comment by ViolentMinds** [comment]
If BOLO's are separate shouldn't Warrants be too? They are even more important than BOLO's

**Comment by Dev-CasperTheGhost** [comment]
they're something completely different. Warrants are connected to a citizen's record

**Comment by ViolentMinds** [comment]
Well the warrant gets served by LEO then the person is arrested. But a list of warrants to be served by LEO is what is needed. So they can see an easy list of warrants they need to execute rather than it being blended into the same logs channel as tickets and things.
