### ISSUE TITLE
Feature: Active Warrants list

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#1014]
### Describe the feature

- Ability for Courthouse members to see Active Warrant list and delete them or create them.
On the Courthouse page and LEO Dashboard.

- Permissions Feature: Option to **only** allow courthouse members to Create Warrant/Delete Warrant (and not regular LEO or LEO Supervisor)? or maybe LEO Supervisor and Courthouse members only.

(BOLO can be created or deleted by anyone I think it makes sense that way because warrants are usually issued by a DOJ Judge)

**Comment by Dev-CasperTheGhost** [comment]
> Permissions Feature: Option to only allow courthouse members to Create Warrant/Delete Warrant (and not regular LEO or LEO Supervisor)? or maybe LEO Supervisor and Courthouse members only.

Like said before, this won't be fully possible because it would introduce a too large breaking change.

**Comment by Dev-CasperTheGhost** [comment]
> Permissions Feature: Option to only allow courthouse members to Create Warrant/Delete Warrant (and not regular LEO or LEO Supervisor)? or maybe LEO Supervisor and Courthouse members only.

I was able to figure out a solution to this breaking change, making it a non-breaking change now!
