### ISSUE TITLE
[BUG] Pagination not working when sorting applied

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#1018]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.18.3 13781cb

### Describe the Bug

Example page: /admin/values/vehicle
- Apply sorting for "Value" column
- Pagination not working (Pagination working only for NOT sorted data)
![image](https://user-images.githubusercontent.com/4976837/182682342-75aea39e-e9d4-47db-90cd-611c692ae38b.png)

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
This is currently not possible due to the way the API is setup. This could possible be added in the future.
