### ISSUE TITLE
[UI improvement] 10 code - Add colorpicker

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#103]
### Describe the feature

1. Add colorpicker on the tencode creation and editing page
![kiss_80kb 1635804159 1](https://user-images.githubusercontent.com/4976837/139749778-40022dcb-bd0c-4c72-8f80-68def291ac23.png)

2. Change the field name for the color to "Color (HEX)"
![kiss_3kb 1635804231 1](https://user-images.githubusercontent.com/4976837/139749796-19379e29-6b49-4fba-8a65-d67976407fda.png)

3. Add a clarification that HEX must start with a # 
![kiss_16kb 1635805031 1](https://user-images.githubusercontent.com/4976837/139749812-603805ec-c846-4e35-8e10-3491ca6a4751.png)

or add a check:
1. If the string length = 6, then it must contain
2. If the length of the string = 7, then it must contain [] and start with the "#" character

**Comment by Dev-CasperTheGhost** [comment]
https://user-images.githubusercontent.com/53900565/139800583-26e27fee-7611-4f1c-ba16-203ab4435b49.mov
