### ISSUE TITLE
[CRITICAL BUG] Values from DB are not loaded

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#104]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### Describe the Bug

Values from DB are not loaded into **ALL** list fields

![kiss_14kb 1635839541 1](https://user-images.githubusercontent.com/4976837/139806804-c5efa1ad-0f59-4477-9b0a-9ce05395d5de.png)

![kiss_25kb 1635839606 1](https://user-images.githubusercontent.com/4976837/139806973-bee9b6d1-2547-4697-8386-1309fd1ae9ce.png)

### Expected Behavior

--

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost still reproduce for vehicles and weapons

**Comment by Dev-CasperTheGhost** [comment]
ah, this is because of #100. Will fix in a few minutes.

**Comment by Dev-CasperTheGhost** [comment]
Ok, should be fully fixed now! Thanks for reporting!
