### ISSUE TITLE
Fatal Error in Client with Dashboard since new update

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#1040]
### What version of Node.js are you using?

17.3.0

### What version of npm are you using?

7.10.0

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

1.21.0

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/185275172-b0d3dfb8-dd9e-4113-af57-328381827233.png)
![image](https://user-images.githubusercontent.com/25211271/185275402-5b5bfb11-aa94-4e50-8f11-9f3746cc0dce.png)
![image](https://user-images.githubusercontent.com/25211271/185276389-0e146fab-8f9a-42b1-b57d-f2c6e8890253.png)

### Expected Behavior

To load Dashboard

### To Reproduce

Dashboard does not load

**Comment by Dev-CasperTheGhost** [comment]
I'm not home today, so I won't be able to fix this. Will do my best to resolve this ASAP

**Comment by ViolentMinds** [comment]
![image](https://user-images.githubusercontent.com/25211271/185303029-2b94240e-789d-4668-a378-c037adfd30ab.png)

Not sure if this helps or not either
