### ISSUE TITLE
Feature Idea: Paying for tickets, tickets marked as PAID/UNPAID

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#1053]
### Describe the feature

Trying to think of an idea where we can have a checkbox on the tickets that says PAID or UNPAID.,
For now, our Courthouse members can edit the ticket NOTES and we just add (PAID)
But it would be nice to have something more official.
Because our state uses economy where people have to pay their tickets.
If you can come up with any ideas to make this option a checkbox or something visible that would be cool! Accessible to the Courthouse permission only. 

![image](https://user-images.githubusercontent.com/25211271/187149598-0b2175fc-571d-4ce2-9d91-3cdb31638b93.png)

**Comment by Dev-CasperTheGhost** [comment]
Sure! Will work on this soon.

**Comment by Dev-CasperTheGhost** [comment]
For now this will be accessible to all officers, I'm not sure where the courthouse members would edit the information?

**Comment by ViolentMinds** [comment]
Under Edit Ticket. Which I assume is Edit Citizen Records. I worry that if
all officers can Edit tickets they might be corrupt and remove tickets from
their own citizen profiles too.
