### ISSUE TITLE
Feature Request: Ability to clear BOLO/WARRANTS/OTHER BOLOS

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#1062]
### Describe the feature

Ability to clear BOLO/WARRANTS/OTHER BOLOS all at once. I have so many that are no longer applicable. I think it would be nice to be able to clear them all once and a while rather than one at a time. Just takes up database space and clutters the page. Or maybe a timer on them where they automatically clear after 2 weeks or something like that.

**Comment by Dev-CasperTheGhost** [comment]
> Or maybe a timer on them where they automatically clear after 2 weeks or something like that.

Yeah, the same system could be used like there is for 911-calls/units
