### ISSUE TITLE
Location fields for 911s and incidents

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1063]
### Describe the feature

Can we get a location field that is API read/write for calls and incidents that allow us to store and retrieve game world X, Y, Z and heading?

This would allow us to give accurate routing via the API.

**Comment by Dev-CasperTheGhost** [comment]
Would this only be editable via the API or also via the client via a dispatcher?

**Comment by jxckUK** [comment]
> Would this only be editable via the API or also via the client via a dispatcher?

It's probably too much for a dispatcher to be able to process so I would say just the API. No need for this to be viewable or editable in the client.

**Comment by Dev-CasperTheGhost** [comment]
`x`, `y` and `z` would be a number and `heading` a string?

**Comment by jxckUK** [comment]
> `x`, `y` and `z` would be a number and `heading` a string?

Heading also a number/float :) 

> heading of an entity in degrees

**Comment by Dev-CasperTheGhost** [comment]
Example body for the call data could be:

PUT /911-calls/:callId

```json
{
  "location": "test",
  "name": "test",
  "gtaMapPosition": {
    "x": 0,
    "y": 0,
    "z": 0,
    "heading": 360
  }
}
```
