### ISSUE TITLE
User can't create officer

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1067]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

v1.23.3 814a262

### Describe the Bug

I have a user who when he clicks create on officer it just does not create the officer as requested. There are no visible client side errors or anything to indicate information is invalid or incorrect.

### Expected Behavior

N/A - Should create a user or provide an error that allows the user to remediate any issues.

### To Reproduce

[cad.projecthyde.com-1661978426551 (1).log](https://github.com/SnailyCAD/snaily-cadv4/files/9489070/cad.projecthyde.com-1661978426551.1.log)

Attached is the client side logs for the user when it is attempted.

**Comment by Dev-CasperTheGhost** [comment]
Unfortunately I can't do much with this information. Is the user able to send the data they entered?

**Comment by Dev-CasperTheGhost** [comment]
Any update on this issue?

**Comment by jxckUK** [comment]
> Any update on this issue?

Still trying to get details apologies, I'll close this until such a time where I can provide more information.
