### ISSUE TITLE
Live Map issues 

### ISSUE THREAD

**Issue by dexslab** [SnailyCAD/snaily-cadv4#1069]
### What version of Node.js are you using?

17

### What version of npm are you using?

yarn 1.22.18

### What operating system are you using?

Winblows 10

### What version of SnailyCAD are you currently using?

V1.23.3

### Describe the Bug

When accessing live map we are having issues with multiple markers being placed and not removed when a players position is updated. When accessing the LiveMap with Dispatch and LiveMap permissions we get an error related to accessing the `api/v1/dispatch/[steamid]` to obtain information about active units. There is also an error for 400 when attempting to get active deputies from error being thrown due to not having an active deputy or active officer (fixed these in my version by just returning null and not throwing the error in both respective files `activeOfficer.ts [line 118]` and `ems-fd.ts [line 72]`)

![image](https://cdn.discordapp.com/attachments/792479048457912363/1016393086315790476/unknown.png)

![image](https://user-images.githubusercontent.com/1696130/188493887-6f3e66e7-bd8c-4300-851d-ebe9acb97f42.png)

### Expected Behavior

- Live map should remove markers and replace with new every player position update
- Should not get 400 when attempting to access livemap as dispatch if you dont have active officer or deputy
- Should not get permission denied when accessing active units

### To Reproduce

Create a server with livemap resource
Connect cad to your livemap resource
make sure you have proper LiveMap and Dispatch permissions
Log into cad go to live map in dispatch and watch the console for errors

If you would like to see the errors directly DM me on discord and we can set up with our CAD and the proper permissions so you can investigate it in the wild 😄

**Comment by Dev-CasperTheGhost** [comment]
#1073 will fix the listed issues and has some minor improvements
