### ISSUE TITLE
[UI improvement] One container width on all pages

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#107]
### Describe the feature

Use the same width for the container on all pages - 100rem / 1568px.

The styles for the current pages are shown below.

72rem / 1120px:
- /citizen
- /citizen/[id]
- /citizen/create
- /taxi
- /bleeter
- /truck-logs
- /courthouse
- /business
- /tow
- /tow/logs
- /officer/my-officers
- /officer/my-officer-logs
- /officer/impound-lot
- /ems-fd/my-deputies
- /admin/*

100rem / 1568px:
- /officer
- /ems-fd
- /dispatch

**Comment by Dev-CasperTheGhost** [comment]
Good idea. I don't actually remember why I did this lol 😅
