### ISSUE TITLE
[BUG] Support for images loading from allowed domains not working

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#1080]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.24.0 4529dd7

### Describe the Bug

Support for images loading from allowed domains not working

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
what exactly is the issue? Since the PR won't fix the problem where images fail to load

**Comment by pp2amd6** [comment]
With current REGEX (imgur) images from Discord CDN won`t loaded.

**Comment by Dev-CasperTheGhost** [comment]
With this regex, it will allow any URL that is possibly malicious. Will take a look later today with a fix to support Discord's CDN.
