### ISSUE TITLE
[BUG] Discord connector incorrectly manages roles

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#1082]
### What version of Node.js are you using?

v16.11.0

### What version of npm are you using?

8.0.0

### What operating system are you using?

Ubuntu 20.04.5 LTS

### What version of SnailyCAD are you currently using?

v1.24.0 4529dd7

### Describe the Bug

Sometimes the Discord connector removes roles from a user in the Discord community and adds other roles.

**Example:**
In the discord community, the user has a set of roles
![image](https://user-images.githubusercontent.com/4976837/189360037-2e43fa41-3dfe-4b27-9dd7-75b410eda1b9.png)

Granting access to the CAD is carried out according to one of the roles
![image](https://user-images.githubusercontent.com/4976837/189360380-96342415-7e4b-4dd8-8fb1-b4ec6ad35567.png)

For some users, the discord connector removes all roles and adds others
![image](https://user-images.githubusercontent.com/4976837/189360683-b37edca6-dba7-4bf8-996f-de23e02b826f.png)

As we can see in the last image, the discord connector removed all roles and added another one.
It should be noted that he added a role (#CAD), which is not specified anywhere in the CAD settings (this role was used earlier as whitelist role).
![image](https://user-images.githubusercontent.com/4976837/189362077-0bfe5080-bf39-447b-9169-d0343112d080.png)

### Expected Behavior

The discord connector should not manage the user's roles, but only perform authorization if the user has the necessary rights.

**Comment by jxckUK** [comment]
I have also noticed this occur; it seems to be its triggered for me when manually (as an admin) adding a user's Discord ID. Upon which the next time they logon they get all their roles removed and replaced with a single role which is the one assigned as the LEO permission.

**Comment by Dev-CasperTheGhost** [comment]
This will only occur when an admin updates a user's permissions. That should be the expected behavior?

**Comment by pp2amd6** [comment]
> That should be the expected behavior?

No. Changes in CAD shouldn't affect members roles in discord.

Example: I have two players. In discord, they have the role of "Officer LEO". For one of them, I set additional rights (mange units) in the CAD user profile, and the role in discord should not change.
