### ISSUE TITLE
[BUG] The user is not getting the correct permissions

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#1083]
### What version of Node.js are you using?

v16.11.0

### What version of npm are you using?

8.0.0

### What operating system are you using?

Ubuntu 20.04.5 LTS

### What version of SnailyCAD are you currently using?

v1.24.0 4529dd7

### Describe the Bug

Sometimes new users with the LEO role are not assigned all of the specified permissions

LEO Role settings:
![image](https://user-images.githubusercontent.com/4976837/189367298-4ef42d5c-24a6-45f8-9629-bf7a48ace360.png)

User can have only LEO or LEO and Manage Warrants for example.

### Expected Behavior

Permissions must be granted according to the role settings

### To Reproduce

I couldn't find a reason or pattern why the user is not getting the rights

**Comment by Dev-CasperTheGhost** [comment]
I can't do much without proper reproduction steps. I have however pushed a small update that could prevent this issue

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost 
> proper reproduction steps
1. Set role and permissions for LEO in CAD
![image](https://user-images.githubusercontent.com/4976837/189474890-fb6402b6-f606-4e55-afd6-4a17302c839d.png)

2. Set roles for the member in Discord
![image](https://user-images.githubusercontent.com/4976837/189474918-3f6e7170-3f0b-49f1-9187-0f126da7b789.png)

3. Login in CAD for the first time
![image](https://user-images.githubusercontent.com/4976837/189474939-092d2ff1-190e-47f4-a0b3-c7549ecd8c19.png)
