### ISSUE TITLE
[improvement] DB refactoring #1

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#109]
### Describe the feature

Some tables have "createdAt" and "updatedAt" fields, and some tables do not.

1. Add these fields to all tables
2. Fill in the values for these fields to transfer to the function that the trigger will call.

Function:
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

Trigger (example):
CREATE TRIGGER value_upd_trigger
BEFORE UPDATE ON updatedAt
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();

The logic for working with such fields must be transferred to the database side, since incorrect data may be transferred from the application (including from the API).

**Comment by Dev-CasperTheGhost** [comment]
I've added them to a more models where I think it's necessary. Let me know if there are more!

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost what about trigger for create and update action?

**Comment by Dev-CasperTheGhost** [comment]
> 
> 
> @Dev-CasperTheGhost what about trigger for create and update action?

what exactly would this do?

**Comment by pp2amd6** [comment]
The trigger will fire when a record is created and when a record is updated.

This is correct because the logic for updating these fields will be on the database side and the data will be generated automatically.

This solution will reduce the amount of data that will need to be prepared on the FiveM side and transferred through the API.

Also, this solution will allow you to avoid mistakes when preparing data by a third-party system (fivem script).
I, as a developer, do not need to prepare dates, bring them into the required format + I will not be able to transfer incorrect data

I will show you on the example of creating a tow call.

Creation method (towCallCreate):
```
[
    userId: ckvhsf6c0002273przwwdcyul,
    location: 7212 Los Santos,
    description: --,
]
```
Receiving method (towCallGet):
```
[
    userId: ckvhsf6c0002273przwwdcyul,
    location: 7212 Los Santos,
    description: --,
    ...
    createdAt: 2021-11-02 08:42:12.172,
    updatedAt: 2021-11-02 14:12:21.12,
]
```

**Comment by pp2amd6** [comment]
So after all, the procedure and the trigger are not created...

Here is an example of procedures and trigger for the towCall table
```
CREATE TRIGGER "tow_create_tr" BEFORE INSERT ON "public"."TowCall"
FOR EACH ROW
EXECUTE PROCEDURE "public"."set_createdAt_timestamp"();
```
```
CREATE TRIGGER "tow_updade_tr" BEFORE UPDATE ON "public"."TowCall"
FOR EACH ROW
EXECUTE PROCEDURE "public"."set_updatedAt_timestamp"();
```
```
CREATE OR REPLACE FUNCTION "public"."set_updatedAt_timestamp"()
  RETURNS "pg_catalog"."trigger" AS $BODY$BEGIN
	BEGIN
	NEW."updatedAt" = NOW();
	RETURN NEW;
	END;

END$BODY$
  LANGUAGE plpgsql
```
```
CREATE OR REPLACE FUNCTION "public"."set_createdAt_timestamp"()
  RETURNS "pg_catalog"."trigger" AS $BODY$BEGIN
	BEGIN
	NEW."createdAt" = NOW();
	RETURN NEW;
	END;

END$BODY$
  LANGUAGE plpgsql
```

And you need to remove the NOT NULL parameter for the "createdAt" and "updatedAt" fields
