### ISSUE TITLE
Editing Citizen via Admin menu regenerates/ignores input field for Social Security Number

### ISSUE THREAD

**Issue by ArgonGlow** [SnailyCAD/snaily-cadv4#1090]
### What version of Node.js are you using?

16.17.0

### What version of npm are you using?

8.19.1

### What operating system are you using?

Windows

### What version of SnailyCAD are you currently using?

1.24.1

### Describe the Bug

Citizens edited and saved through Admin>Manage Citizens have their Social Security Number regenerated (and thus overwritten) whether the field is empty or not.

- Doesn't occur when clicking 'cancel' or switching sections, only when the edit is confirmed through the 'save' button.
- Does not occur when editing a citizens via the user's own citizen list.

### Expected Behavior

When saving changes to a citizen through Admin>Manage Citizens their Social Security Number is set to the value in the input field, unless the field is empty, in which case one will be generated.

### To Reproduce

1. Edit a citizen's details through Admin>Manage Citizens
2. Save the changes.
3. Review the Social Security number through the edit form or in the user's Citizen tab.

**Comment by Dev-CasperTheGhost** [comment]
Will take a look soon.

**Comment by ArgonGlow** [comment]
cool! Tried to have a look myself to submit a more specific report, but not familiar with typescript/react yet.

**Comment by Dev-CasperTheGhost** [comment]
> cool! Tried to have a look myself to submit a more specific report, but not familiar with typescript/react yet.

ah, well. Just know you're always welcomed to make PR's with other fixes :)! This issue should be fixed now too.

**Comment by ArgonGlow** [comment]
> > cool! Tried to have a look myself to submit a more specific report, but not familiar with typescript/react yet.
> 
> ah, well. Just know you're always welcomed to make PR's with other fixes :)! This issue should be fixed now too.

Will definitely be tinkering around with it to fit our needs. I'll be sure to to make a PR if it amounts to something that could be of value to others :)

**Comment by Dev-CasperTheGhost** [comment]
you can always create a feature request for me and others to look at and implement.
