### ISSUE TITLE
[BUG] Tencodes colors not shows for LEO units table

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#1095]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.25.0 b8d2487

### Describe the Bug

Tencodes colors not shows for LEO units table

LEO Unit table
![image](https://user-images.githubusercontent.com/4976837/189873280-fde8c61b-6039-4092-80f7-c81d81a55edc.png)

CAD Settings - tencodes
![image](https://user-images.githubusercontent.com/4976837/189873399-fc9b652c-996e-426f-9fc6-348e2bc71b24.png)

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
Oh, worked locally for me, will troubleshoot once home.
