### ISSUE TITLE
Fine Paid

### ISSUE THREAD

**Issue by dexslab** [SnailyCAD/snaily-cadv4#1108]
### Describe the feature

Add a flag for tickets saying if the fines were paid and how much was paid for a Ticket/Arrest Record

**Comment by Dev-CasperTheGhost** [comment]
You can already mark tickets as paid: 
![image](https://user-images.githubusercontent.com/53900565/191813597-d5da5c69-e5c0-4be4-9e4f-8e3fe1ce0e65.png)
