### ISSUE TITLE
Anytime I try to upload background image for auth page I get an API error

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#1109]
### What version of Node.js are you using?

17.3.0

### What version of npm are you using?

7.10.0

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

v1.26.2 a10e4d2

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/191809418-bd06367d-ca18-4725-8fc9-f34ddfccd2fb.png)
![image](https://user-images.githubusercontent.com/25211271/191809511-9bd1c3d9-1699-4c51-9654-08166231f46a.png)

### Expected Behavior

To be able to upload an image

**Comment by Dev-CasperTheGhost** [comment]
Ah I see, will fix shortly.

**Comment by ViolentMinds** [comment]
Note, this seems... I'm just guessing, if the image is above 1.0MB maybe? I uploaded a different image that was 750kb and it worked? I dont know. Either that or its random

**Comment by Dev-CasperTheGhost** [comment]
hm, nevermind. I seem to be unable to reproduce this error

**Comment by Dev-CasperTheGhost** [comment]
Are you able to share the image you're trying to upload?

**Comment by ViolentMinds** [comment]
![1889690](https://user-images.githubusercontent.com/25211271/191818340-0706ad5e-350a-49c8-aabf-d689e5bd2900.jpg)

**Comment by Dev-CasperTheGhost** [comment]
This seems to be an issue with certain images. Try change the format to `png` or `webp`. I'm unable to reproduce this error consistently, therefore unable to figure out where this comes from.

This could also be an issue with the webserver, like I said, I'm not sure.
