### ISSUE TITLE
QbCore

### ISSUE THREAD

**Issue by RealZotty** [SnailyCAD/snaily-cadv4#112]
### Describe the feature

Make a optional cad intergration for qbcore

**Comment by pp2amd6** [comment]
@RealZotty you can integrate the framework using the CAD API

**Comment by Dev-CasperTheGhost** [comment]
Can you elaborate on what QbCore is? Some links would be useful. @RealZotty

**Comment by pp2amd6** [comment]
https://github.com/qbcore-framework

**Comment by Dev-CasperTheGhost** [comment]
This is a framework that seems to be written in LUA. I don't know any LUA nor do I have the time to currently learn it, though as pp2amd6 said, you can use the [Public API Access feature](https://cad-docs.netlify.app/other/public-api) to create your own integration.
