### ISSUE TITLE
Security - Logs - Tones

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#1120]
### Describe the feature

Is there a way we can disable Dispatch section in the main menu? Our server doesn't use it because there is no good LiveMap script that works anymore. And we've had people abusing the Tones system to send inappropriate messages and troll. Unfortunately, over 2000 members have Dispatch perms because we had it set to auto user properties. So no clue who was doing it.

![image](https://user-images.githubusercontent.com/25211271/193385672-b2c50f81-fccc-4155-9f7d-cf82d1504551.png)

And there is no logs for who the officer was.

**Comment by Dev-CasperTheGhost** [comment]
Disable the entire Dispatch section? Or only the tones?

**Comment by ViolentMinds** [comment]
Both would be nice haha. In case someone does have Dispatch enabled, they should still have some logs with the tones. For trouble makers.

**Comment by Dev-CasperTheGhost** [comment]
Disabling the entire Dispatch section will be difficult, I'll add the ability to disable tones and add the username from the user who enabled the tone

**Comment by ViolentMinds** [comment]
I would suggest just hiding from the menu as a solution. Remove the hyperlink.

But thank you! The tone issue was a pain. <3
