### ISSUE TITLE
Create Citizen Date of Birth Bug

### ISSUE THREAD

**Issue by tigerdesignsolutions** [SnailyCAD/snaily-cadv4#1124]
### What version of Node.js are you using?

16.6

### What version of npm are you using?

Unsure.

### What operating system are you using?

Ubuntu 20.04

### What version of SnailyCAD are you currently using?

1.26.7

### Describe the Bug

When creating a citizen, and putting in their date of birth, you're able to enter the month and day by just typing it in, but when you go to type in the year, it tries to only type the last number of the year, and you have to manually use up or down to find the year or use the calendar button.

![chrome_3yHPV0dJzV](https://user-images.githubusercontent.com/18332675/193498669-3aacd6c8-2b7e-40f3-8388-813d1aaf9665.gif)

### Expected Behavior

Should be able to type in the year for the date of birth as a 4 digit number.

### To Reproduce

Create Citizen, and attempt to manually type the date of birth, specifically the year.

**Comment by Dev-CasperTheGhost** [comment]
This seems to be an issue with the browser, rather than an issue with SnailyCAD? Can verify it works properly on a different site, please?

**Comment by MrJDubYou** [comment]
Tried this in Microsoft Edge with same result. Internet Explorer wouldn't even let me login, seems to be a separate issue there. no other browsers installed.

(Same person, different account)

**Comment by Dev-CasperTheGhost** [comment]
alright, will take a look.
