### ISSUE TITLE
Provide Option for Citizens to manage their own License statuses

### ISSUE THREAD

**Issue by MrJDubYou** [SnailyCAD/snaily-cadv4#1126]
### Describe the feature

Currently only an Officer with the "LEO" permission can access and manage a citizen's licenses. On a citizens view, they can only see what they have and not manage them in any way.

This would allow for servers using Scenario based roleplay to allow the citizen change it on the fly for their character.

**Comment by Dev-CasperTheGhost** [comment]
This is already supported and enabled by default. Please check your CAD-settings' features tab and enable `Allow citizens to update licenses`

![image](https://user-images.githubusercontent.com/53900565/193512499-f17e4ee6-72f4-4eb4-bdd5-16450bf3508c.png)
