### ISSUE TITLE
Add Exams for Pilot License and Water License

### ISSUE THREAD

**Issue by MrJDubYou** [SnailyCAD/snaily-cadv4#1127]
### Describe the feature

Currently you can only enable exams for drivers license and firearms license.

**Comment by Dev-CasperTheGhost** [comment]
Note to self: 
- Combine all license exams pages
- Allow citizens to request an exam from their citizen page

**Comment by dexslab** [comment]
While modifying this allow LEO to revoke/suspend licenses

**Comment by dexslab** [comment]
Something to that affect or just tag the license itself as invalid

**Comment by Dev-CasperTheGhost** [comment]
sure, will take a look soon

**Comment by Dev-CasperTheGhost** [comment]
yup, was planning on that :)

**Comment by Dev-CasperTheGhost** [comment]
Who is allowed to remove the suspended license/reset the license?

cc @dexslab

**Comment by MrJDubYou** [comment]
I'd say whoever can issue originally. Be it officer or self depending on config.

**Comment by dexslab** [comment]
I would agree with that

**Comment by Dev-CasperTheGhost** [comment]
What do we think?

![image](https://user-images.githubusercontent.com/53900565/193775319-02b296e3-7f21-4ba5-951b-97e2e1ff1f55.png)


![image](https://user-images.githubusercontent.com/53900565/193775281-000fe030-6f78-4bbd-82d6-797b6326759e.png)
