### ISSUE TITLE
Date of Birth not displaying the same date across pages

### ISSUE THREAD

**Issue by MrJDubYou** [SnailyCAD/snaily-cadv4#1128]
### What version of Node.js are you using?

16.6

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

1.26.7

### Describe the Bug

When viewing the Citizen page, the Date of Birth is not the same date as the one showing in the Edit Citizen page, in this case 1 day difference.

View Citizen Page
https://i.imgur.com/DyKUdwQ.png

Edit Citizen Page
https://i.imgur.com/oaV41g0.png

### Expected Behavior

Date of birth should be the same across viewing pages.

### To Reproduce

View a citizen page, and edit a citizen.

**Comment by Dev-CasperTheGhost** [comment]
This has happened before, if you're able to update and verify if it works now? That'd be great.

**Comment by MrJDubYou** [comment]
Just ran an update and restarted, issue still remains.

**Comment by Dev-CasperTheGhost** [comment]
I'm unable to reproduce this, if you try any other date (day) does it work properly then?
