### ISSUE TITLE
New Date Picker has issues

### ISSUE THREAD

**Issue by tigerdesignsolutions** [SnailyCAD/snaily-cadv4#1132]
### What version of Node.js are you using?

16.6

### What version of npm are you using?

N/A

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

v1.26.7 abec934

### Describe the Bug

When entering the date of birth, every time you type a character in any of the 3 date fields, the "day" number decreases by 1 each time.

### Expected Behavior

Other fields like Month and Year shouldn't change the properties of the Day field.

### To Reproduce

Enter a date, and then change that date.

https://user-images.githubusercontent.com/18332675/193646112-3e075814-2643-4a0d-bdb1-bde6c6e25b54.mp4

**Comment by Dev-CasperTheGhost** [comment]
It's so weird that I'm unable to reproduce this issue: 

https://user-images.githubusercontent.com/53900565/193647003-c86a3690-5492-4f67-90e6-90b75dcd8c62.mp4

**Comment by MrJDubYou** [comment]
I'm using a number pad if that makes a difference.

**Comment by Dev-CasperTheGhost** [comment]
Okay, I was able to reproduce when using a different timezone. Will get this fixed soon!

**Comment by Dev-CasperTheGhost** [comment]
Damn, timezones suck in JS lmao. Fixed now though :)
