### ISSUE TITLE
Adding a unique Driver's License Number field

### ISSUE THREAD

**Issue by MrJDubYou** [SnailyCAD/snaily-cadv4#1135]
### Describe the feature

Add a field on the citizen creation page for a Driver's License Number (Alpha-Numeric), and require it to be a unique value (no 2 citizens with the same number). Also making it a searchable field when doing a name search, similar to how SSN can be looked up.

Also maybe making it an option to allow/disable search by DL#/SS#

**Comment by Dev-CasperTheGhost** [comment]
What would be the length of this field?

**Comment by MrJDubYou** [comment]
To match California, 8 characters, usually the first is a letter.

**Comment by Dev-CasperTheGhost** [comment]
Would this also be generated for other licenses (pilot, firearm, water)?

**Comment by MrJDubYou** [comment]
Firearm 8 digits [# only]
Pilot 6 digit [# only]

**Comment by Dev-CasperTheGhost** [comment]
Is this an autogenerated field? Or does it require manual input of the user?

**Comment by joshwhittleblogs** [comment]
> Is this an autogenerated field? Or does it require manual input of the user?

I'd make it random. If you can for the driver's license make the randomizer require the first character to be a letter, that would be even better.

**Comment by Dev-CasperTheGhost** [comment]
![image](https://user-images.githubusercontent.com/53900565/195976638-b10d9b45-55bf-4211-92e6-ab9c8916c1bd.png)

![image](https://user-images.githubusercontent.com/53900565/195976687-a2615a2b-0590-4041-8800-9ddb9e85de70.png)
