### ISSUE TITLE
Possible Bug with Inactive warrant showing as Active?

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#1153]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

v1.26.7 7ecc014

### Describe the Bug

I'm not sure if its a bug or not? It says active warrant but if you look at the drop down it says Inactive is selected?

![image](https://user-images.githubusercontent.com/25211271/194399367-e27b010f-2e8c-4f43-b638-76b2ee7d5b8e.png)

![image](https://user-images.githubusercontent.com/25211271/194399255-5a10bb98-2f4d-47d3-857c-701a1a70b1cf.png)

### Expected Behavior

Perhaps if its more clear

**Comment by dexslab** [comment]
I can confirm this behavior as a valid bug

**Comment by Dev-CasperTheGhost** [comment]
Thanks for confirming! I'll take a  look shortly
