### ISSUE TITLE
Drivers License Missing from Create Character Page

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#1158]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

v1.27.1 0483009

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/194787257-e18096ef-54ca-41a5-aa98-97c84622c092.png)

### Expected Behavior

To be able to create drivers license.

**Comment by Dev-CasperTheGhost** [comment]
You need to disable the `LICENSE_EXAMS` feature.
