### ISSUE TITLE
[FEATURE] Ability to turn off the display of the item "What's new"

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#1161]
### What version of Node.js are you using?

doesn`t matter

### What version of npm are you using?

doesn`t matter

### What operating system are you using?

doesn`t matter

### What version of SnailyCAD are you currently using?

v1.27.1 5850065

### Describe the Bug

Ability to turn off the display of the item "What's new"
![image](https://user-images.githubusercontent.com/4976837/195087463-e5c29440-43f0-455c-a20e-311e7e80807b.png)

This is not critical functionality, but it will add more logic:
- there will be no intersection of the RP of the world and the real world;
- for many users, information about updating dependencies is useless, for example :)

The display of "What's new" can be disabled by the administrator in the portal settings (/admin/manage/cad-settings), Features tab
![image](https://user-images.githubusercontent.com/4976837/195089389-c8f5f4a2-5888-4cf6-a149-6f75b5457886.png)

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
Completely disabling I see now point of. I will however remove the green dot.
