### ISSUE TITLE
Automatic 911 Call events

### ISSUE THREAD

**Issue by Creizy** [SnailyCAD/snaily-cadv4#1166]
### Describe the feature

For example, when an officer is attached to the call, in the call section events, it automatically sends a message: 1A-1 John Doe attached to call.

Officer arrives at the scene and marks himself as 10-23 (Arrived on the scene) The event log automatically generates 1A-1 John Doe arrived on the scene.

Probably hard to implement but would be cool to see.

### Additional Context

![image](https://user-images.githubusercontent.com/100074335/195454316-a76ce168-d5ce-447a-9615-03fefad33c5d.png)

It would also be cool if as soon as the officer is attached to a call, he automatically gets a status change to en route. (You could toggle that here)
![image](https://user-images.githubusercontent.com/100074335/195454641-99fb3dbf-ce30-48c7-9ebc-fe10408ebdb7.png)

**Comment by Dev-CasperTheGhost** [comment]
> It would also be cool if as soon as the officer is attached to a call, he automatically gets a status change to en route. (You could toggle that here)

This had been removed since others had complained about this feature

**Comment by Dev-CasperTheGhost** [comment]
Current progress: 
![image](https://user-images.githubusercontent.com/53900565/195638542-c7b54c18-09e2-4b05-a0fe-effd6ad3f23a.png)

Still need to implement the arrived on-scene and en-route

**Comment by Dev-CasperTheGhost** [comment]
If an officer is assigned to multiple calls, would it only do this for the "Active Call" or for all the calls the officer is assigned to? 

cc @pp2amd6 @jxckUK @Creizy @MrJDubYou (pinging because you all provide amazing feedback :))

**Comment by MrJDubYou** [comment]
If there's a way to stack calls it would be smart to be able to change the "active call" somehow and the status change should only apply to the active call. Having both the officer and dispatcher be able to change the active call by maybe a drop down from a list of attached calls?

**Comment by MrJDubYou** [comment]
I like the status feed within the call though and being able to view it both on the dispatcher and officer side of the call.

**Comment by Creizy** [comment]
> I like the status feed within the call though and being able to view it both on the dispatcher and officer side of the call.

You can already see it both as an officer and dispatch

**Comment by Creizy** [comment]
> If an officer is assigned to multiple calls, would it only do this for the "Active Call" or for all the calls the officer is assigned to?
> 
> cc @pp2amd6 @jxckUK @Creizy @MrJDubYou (pinging because you all provide amazing feedback :))

If you can stack them, then most likely only active call.

**Comment by jxckUK** [comment]
> If an officer is assigned to multiple calls, would it only do this for the "Active Call" or for all the calls the officer is assigned to?
> 
> cc @pp2amd6 @jxckUK @Creizy @MrJDubYou (pinging because you all provide amazing feedback :))

I think in *most* cases officers should only be assigned to one call, so making it the active call ensures that sort of information is only present on the most relevant.

**Comment by Creizy** [comment]
> > If an officer is assigned to multiple calls, would it only do this for the "Active Call" or for all the calls the officer is assigned to?
> > cc pp2amd6 jxckUK Creizy MrJDubYou (pinging because you all provide amazing feedback :))
> 
> I think in _most_ cases officers should only be assigned to one call, so making it the active call ensures that sort of information is only present on the most relevant.

True, completely forgot to mention it. As you said mostly officers are attached only to one call. Rarely multiple because either it’s probably the same call. Which shouldn’t really be an issue since we can merge calls.

**Comment by MrJDubYou** [comment]
> > If an officer is assigned to multiple calls, would it only do this for the "Active Call" or for all the calls the officer is assigned to?
> 
> > 
> 
> > cc @pp2amd6 @jxckUK @Creizy @MrJDubYou (pinging because you all provide amazing feedback :))
> 
> 
> 
> I think in *most* cases officers should only be assigned to one call, so making it the active call ensures that sort of information is only present on the most relevant.
> 
> 
> 
> EDIT: I'm glad to see this issue being implemented as I currently do this via the API so I can reduce some of my code! 😄 
> 
> 
> 
> 

They could get stacked calls especially supervisors so they know the info for their next call ahead of time or for non priorities.

**Comment by jxckUK** [comment]
> They could get stacked calls especially supervisors so they know the info for their next call ahead of time or for non priorities.

I think we should handle stacked calls separately; I like the idea, but it needs a proper implementation in my opinion. Eg. Having calls they aren't assigned to until they're "free" is a good idea.

**Comment by pp2amd6** [comment]
I don't quite understand how an officer can be assigned to multiple calls at once :)

I understand that multiple calls can be made about the same situation, but an **officer can only be on one call**.

I can suggest making an alias for the call and then the event mechanism will work logically.

Example:
- the dispatcher receives a fight call from a witness (call # 1)
- the dispatcher receives a fight call from a witness at the same address (call # 2)
- the dispatcher receives a fight call from the victim at the same address (call # 3)
- the dispatcher indicates that call 2 and 3 refer to call 1
![image](https://user-images.githubusercontent.com/4976837/195928059-7f8ef7c4-e0ee-4ac0-ab82-53a4e4b8643e.png)

- in the table, call 2 and 3 will be listed as an alias
![image](https://user-images.githubusercontent.com/4976837/195927413-4c07d59b-4619-4f64-a2e7-ca21f92c1e76.png)

- if an officer changes status, it will be displayed on the call page

**Comment by jxckUK** [comment]
> I don't quite understand how an officer can be assigned to multiple calls at once :)
> 
> I understand that multiple calls can be made about the same situation, but an **officer can only be on one call**.

Much agree with this to be honest.

> I can suggest making an alias for the call and then the event mechanism will work logically.
> 
> Example:
> 
> * the dispatcher receives a fight call from a witness (call # 1)
> * the dispatcher receives a fight call from a witness at the same address (call # 2)
> * the dispatcher receives a fight call from the victim at the same address (call # 3)
> * the dispatcher indicates that call 2 and 3 refer to call 1
>   ![image](https://user-images.githubusercontent.com/4976837/195928059-7f8ef7c4-e0ee-4ac0-ab82-53a4e4b8643e.png)
> * in the table, call 2 and 3 will be listed as an alias
>   ![image](https://user-images.githubusercontent.com/4976837/195927413-4c07d59b-4619-4f64-a2e7-ca21f92c1e76.png)
> * if an officer changes status, it will be displayed on the call page

I like this idea, but I do also see merit in "stacking" calls for them to move onto next which I believe is why other users are currently assigning multiple calls to a single unit. If we can implement effective stacking, we may not need to be too concerned about multiple call assignments!

**Comment by pp2amd6** [comment]
What does call stacking mean? What will it look like and what is it used for?

**Comment by jxckUK** [comment]
> What does call stacking mean? What will it look like and what is it used for?

In my eyes it means the following:

Assigning an additional call to a user to attend *after* their current call, when the previous call clears/closes or the unit becomes available they are automatically placed on the first stacked call.

Eg. User is on Call1, is stack assigned to Call2. Call1 ends and the unit is assigned to Call2 automatically. Stacks should be able to go as deep as a dispatcher likes.

**Comment by Dev-CasperTheGhost** [comment]
Call stacking should probably be added in a new issue so this one can be closed then. @jxckUK, if you're able to open a feature request. That'd be great!
