### ISSUE TITLE
Draggable modals

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [SnailyCAD/snaily-cadv4#1167]
### Describe the feature

The ability to drag modals around the page. With this, we should add the ability for dispatchers to fully interact with the page while having the modal opened. 

Possibilities:
 - Drag/drop units to active calls
 - Directly connect active incidents with active calls
 - toggle signal 100
 - move modals around so multiple modals can be interacted with at the same

**Comment by MrJDubYou** [comment]
Reminds me of the Senoran CAD style look which I am hugely in favor of.

https://sonorancad.com/images/layout.gif

**Comment by Dev-CasperTheGhost** [comment]
It wouldn't look the same, Sororan has more "windows" like look; I'm still going for the modals look but with the added ability to interact outside the modals (see above)

**Comment by Dev-CasperTheGhost** [comment]
Closing this for now. Will re-open when I have resources to work on this
