### ISSUE TITLE
Active call list with permission system

### ISSUE THREAD

**Issue by MrJDubYou** [SnailyCAD/snaily-cadv4#1171]
### Describe the feature

Maybe this is already a feature that I just haven’t seen but on the dashboard having a section listing all active calls, with the ability to view and attach to calls. Also having separate permissions selectable for viewing the call list and being able to self attach as an officer.

### Additional Context

Adding an always showing modal of active calls maybe by splitting columns on the page with something, simple list with maybe a case/incident/call number and title of call. Bonus points for maybe adding a number next to it for number of attached units.

opening the call would provide all the info for those with perms and a button for self attach for officers with that perm.

**Comment by Dev-CasperTheGhost** [comment]
You can already view the list of all active calls though?

>  Also having separate permissions selectable for viewing the call list and being able to self attach as an officer.

An officer can already self-assign them to a call.

![image](https://user-images.githubusercontent.com/53900565/195971122-b3801a9d-216d-48ad-a61c-cd1cf4e9eaaa.png)
