### ISSUE TITLE
[Bug] Shows officer "None"

### ISSUE THREAD

**Issue by Creizy** [SnailyCAD/snaily-cadv4#1172]
### What version of Node.js are you using?

18.2.0

### What version of npm are you using?

8.9.0

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

v1.27.2 88e1dad

### Describe the Bug

![image](https://user-images.githubusercontent.com/100074335/195967282-c66fe2cd-a03a-41b0-865a-641416b9c7ab.png)
Upon creating an arrest report, ticket, or written warning, even when on duty, it shows "Officer None".

I can confirm that it is both on LEO page and on Dispatch.

### Expected Behavior

Might just be wrong something for me, but could be a bug.

### To Reproduce

Simply make an arrest report, ticket, or written warning

**Comment by Dev-CasperTheGhost** [comment]
This has been fixed in [bc63ef3](https://github.com/SnailyCAD/snaily-cadv4/commit/bc63ef3c45e47693284fd82df1646349f559697b)
