### ISSUE TITLE
Better license suspension

### ISSUE THREAD

**Issue by Creizy** [SnailyCAD/snaily-cadv4#1173]
### Describe the feature

When an officer is suspending a license, you could add a field where you either select that the license is being suspended indefinitely or for a custom time that the officer could enter.
After the time passes (if custom time is entered) it would automatically remove the suspension.

Could be made as a togglable feature in case someone has license exams enabled. Because if someone is trying to make somewhat of a real-world replica, then after license suspension you would have to take the exam again.

### Additional Context

Would be cool to see, but I understand if not.
Would like to hear some opinions on this one as well. :)

**Comment by Dev-CasperTheGhost** [comment]
Something like this? 
![image](https://user-images.githubusercontent.com/53900565/196482786-c6c4994c-3533-46cb-a999-5ee49adb7ea6.png)

**Comment by Dev-CasperTheGhost** [comment]
Actually now that I think of it, I might be better to use a date-picker so the officer can select "Suspended until: <DATE>"

@Creizy
