### ISSUE TITLE
Call Stacking

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1176]
> What does call stacking mean? What will it look like and what is it used for?

In my eyes it means the following:

Assigning an additional call to a user to attend *after* their current call, when the previous call clears/closes or the unit becomes available they are automatically placed on the first stacked call.

Eg. User is on Call1, is stack assigned to Call2. Call1 ends and the unit is assigned to Call2 automatically. Stacks should be able to go as deep as a dispatcher likes.

__Originally posted by @jxckUK in https://github.com/SnailyCAD/snaily-cadv4/issues/1166#issuecomment-1279447895__

**Comment by Dev-CasperTheGhost** [comment]
Something like this, correct?

https://user-images.githubusercontent.com/53900565/196717167-3c836a39-10da-44aa-b69a-08714b52a03a.mp4

**Comment by jxckUK** [comment]
Looks good! Does this work for control/dispatch as this is where I see the practice being used rather than by individuals?

Is there a way to get a view to see as control/dispatch what the call queue for a unit is?

**Comment by Dev-CasperTheGhost** [comment]
it's all automatic, 

1. unit is assigned to multiple calls (**1** & **2**) with active call **1**
2. gets unassigned from call **1**
3. active call becomes **2**
