### ISSUE TITLE
Voilation count (idk how to call it)

### ISSUE THREAD

**Issue by Creizy** [SnailyCAD/snaily-cadv4#1177]
### Describe the feature

So basically when adding violations (tickets, arrests, etc.) There would be an additional window for each charge, where you could enter charge counts.

Example: Officers are engaged in a high-speed pursuit and enter the city, they decide to terminate the pursuit due to civilian safety. Later they spot the same vehicle/person and engage in another pursuit. Upon arrest, They would charge him with 2 counts of Evading a peace officer.

### Additional Context

It could be placed somewhere here.
![image](https://user-images.githubusercontent.com/100074335/196023511-d25b8c4e-3a9d-4f79-8e10-8578aec43968.png)

I honestly couldn't find if someone had suggested this before or not :D

**Comment by Dev-CasperTheGhost** [comment]
This only accounts for "Fines"? Or also for jail time and bail?

**Comment by Creizy** [comment]
Now that you've mentioned it, probably all of them.
Like let's say 
Evading a peace officer (2 counts)
Fines 5000$ x2
Jail time 60s x2
Bail 1000$ x2

which would make a better placement for it somewhere here ig 
![image](https://user-images.githubusercontent.com/100074335/196025973-5411a71e-c9db-4d9b-b23d-1b0c93ffca22.png)

**Comment by Dev-CasperTheGhost** [comment]
![image](https://user-images.githubusercontent.com/53900565/196208837-381411a7-b0a7-4a61-8974-cbd6b7ab659d.png)
