### ISSUE TITLE
discord variables

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#1179]
### Describe the feature

when setting the channel of a discord webhook and adding an additional message, there should be set variables to access certain things like the users id of whatever is happening.

this is mainly so when a webhook gets sent out we can set it up so that it @s the users that webhook is for, obviously this wouldnt be for every webhook like bolo log wouldn't need this, 911, etc.

**Comment by Dev-CasperTheGhost** [comment]
Can you provide an example for this?

**Comment by subtosharki** [comment]
this would be in the additional message box:


User: {discordID}

would print

User: 836262827252783

**Comment by Dev-CasperTheGhost** [comment]
Right, I know that, but for which actions will this be used? I’m asking fora real world example so I know what’s possible.

**Comment by subtosharki** [comment]
what do you mean by actions? webhooks?

**Comment by Dev-CasperTheGhost** [comment]
No. Where will you use the "{userId}"? Where is it needed? How is it useful? etc. That's what I'm asking. Actions meaning the current options for creating the webhooks (911-calls, bolos, warrants, ...)

**Comment by Dev-CasperTheGhost** [comment]
@subtosharki please see previous comment :)

**Comment by subtosharki** [comment]
it was a request by a member so when citations get sent out to discord we can set it up so the webhook @ the user thr citation is going to, same for arrest and all that

**Comment by Dev-CasperTheGhost** [comment]
Since this won't be supported in all webhook types, I'm not sure yet if this is necessary. Will see what I can do today/tomorrow

**Comment by Dev-CasperTheGhost** [comment]
Only `{userId}` is supported for `Citizen Records` webhook. Other webhook types don't have any Discord data. Out now, please update you CAD.
