### ISSUE TITLE
[BUG] Reloading the page breaks the avatar path

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#118]
### What version of Node.js are you using?

does not matter

### What operating system are you using?

does not matter

### Describe the Bug

/citizen

Before reload
![kiss_19kb 1635893414 1](https://user-images.githubusercontent.com/4976837/139962471-498a303e-9fd3-4d16-886a-f2a3ab1c32c1.png)

After reload
![kiss_12kb 1635893440 1](https://user-images.githubusercontent.com/4976837/139962508-8cff8dcf-90e5-4a04-b271-62e9e1b0a612.png)

Before reload
![kiss_62kb 1635893634 1](https://user-images.githubusercontent.com/4976837/139962816-651487d8-1823-4cf7-b326-27ef3c8f27d4.png)

After reload
![kiss_17kb 1635893666 1](https://user-images.githubusercontent.com/4976837/139962853-524f4d2f-ae24-4556-be0f-a71e62201642.png)

Console: Failed to load resource: net::ERR_NAME_NOT_RESOLVED
![kiss_12kb 1635893762 1](https://user-images.githubusercontent.com/4976837/139963010-12d8bc7a-132e-492f-8202-4e39beedc46c.png)

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
This should be fixed now. Let me know if it's not!

**Comment by pp2amd6** [comment]
No, it still doesn't work

**Comment by Dev-CasperTheGhost** [comment]
> 
> 
> No, it still doesn't work

Are you able to run `yarn` in the root folder of the CAD. Then re-build the client, then check if it works? There is a new package that has to be installed

**Comment by pp2amd6** [comment]
I always do this after updating the repository

**Comment by pp2amd6** [comment]
Everything is working now. Cool!
