### ISSUE TITLE
Changing priority of the call

### ISSUE THREAD

**Issue by We5t1** [SnailyCAD/snaily-cadv4#1182]
### Describe the feature

An ability for dispatch to choose a main call when they start code 100. This call will be displayed in another colour.
Also if unit presses panic button while he is attached to a call, this call changes its colour.

**Comment by Dev-CasperTheGhost** [comment]
Are you able to provide an image example for this? I'm not 100% sure what you mean here

**Comment by We5t1** [comment]
> Are you able to provide an image example for this? I'm not 100% sure what you mean here
> 

So when press code 100 button you can choose one active call and will become red, will have a red dot near it or something like that. Because not everybody understands who has an emergency traffic and who must hold their messages on radio.
