### ISSUE TITLE
feat: dropdown for address and postals

### ISSUE THREAD

**Issue by Creizy** [SnailyCAD/snaily-cadv4#1184]
### Describe the feature

Shortly: Add dropdown menus for anywhere where you can enter address/postal.
You could also add "Manage Addresses" to the admin menu. Where you could import/change the addresses and postal, in case you need.

### Additional Context

Can provide addresses and postals if necessary. I'll work on multiple portal files so they could support multiple maps.

The file would contain smth like this:
(`name`, `county`)
example:
('Abattoir Avenue', 'Los Santos County')
('Zancudo Trail', 'Blaine County')
('Route 68', 'State')
(266, '1000', 'Postal')

^ However you need to format the file, just lmk Casper :D

Dropdowns would be the same as the rest ones, just different values.
![image](https://user-images.githubusercontent.com/100074335/196986453-f630a7ff-ee5e-4d81-9e12-4c1ba658240a.png)

**Comment by Dev-CasperTheGhost** [comment]
Format of the files would be `json`, with template: 

```json
[
	{
		"value": "[NAME]",
		"county": "[COUNTY]",
		"postal": "[POSTAL]"
	}
]
```


where `postal` is nullable.

**Comment by Creizy** [comment]
If you could make it a toggle feature would be great since probably not everyone is using the default postal map.

Sent you the file in dm's :3
