### ISSUE TITLE
Allow citizens to add criminal history on creation

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1188]
### Describe the feature

As an optional and toggleable feature, could we enable members to add civilians with existing flags and criminal history?

This would only be available on initial creation, as to avoid them amending it after the fact or amending new records police add.

**Comment by Dev-CasperTheGhost** [comment]
How would the flow be then?

**Comment by jxckUK** [comment]
> How would the flow be then?

1. Feature is enabled/disabled as with other optional features in the admin dashboard.
1. User during citizen creation is permitted to add flags and criminal history (eg. previous charges)

Added to this form here:

![image](https://user-images.githubusercontent.com/48030374/197339549-637dc062-e42b-4c60-a559-acf6796b623d.png)

2. Civilian is created with that data, but that data is then only amended by an officer in the standard way via the policing dashboards, this is no change to existing behaviour.

3. Civilian cannot amend or delete this type of information once a civilian is created, which again presents no change to existing behaviour.

**Comment by Dev-CasperTheGhost** [comment]
So the data entered in the citizen creation form, must first be approved by a supervisor? Or is that data directly accessible by any officer

**Comment by jxckUK** [comment]
> So the data entered in the citizen creation form, must first be approved by a supervisor? Or is that data directly accessible by any officer without any approval status

I would say without any approval status but that may be something other communities differ on, so it is perhaps worth being an option?

**Comment by Creizy** [comment]
This is an interesting one

**Comment by jxckUK** [comment]
Any update on this one? 😄

**Comment by Dev-CasperTheGhost** [comment]
Haven't been able to get to this yet, will try this weekend. Sorry for any delays 😅

**Comment by Dev-CasperTheGhost** [comment]
> Civilian is created with that data, but that data is then only amended by an officer in the standard way via the policing dashboards

What do you mean exactly by this?

**Comment by jxckUK** [comment]
> > Civilian is created with that data, but that data is then only amended by an officer in the standard way via the policing dashboards
> 
> What do you mean exactly by this?

Sorry for the delay - what I mean is that they can't amend record data on their citizen after creation. Otherwise, any civilian could just edit their own records which wouldn't be good, this is only to create a "history" for roleplay scenarios.

**Comment by Dev-CasperTheGhost** [comment]
Ahh, okay. I’ll implement this once #1211 is finished. UX will be better then

**Comment by Dwohakin** [comment]
that'd be cool. I had same idea tho

**Comment by Dev-CasperTheGhost** [comment]
I'm almost able to merge #1216, once it's merged I can finally work on this issue. It shouldn't take long after #1216 has been merged :)

**Comment by Dev-CasperTheGhost** [comment]
Soon:tm:
![image](https://user-images.githubusercontent.com/53900565/202486074-a7e04404-81ab-499d-94ad-76ccf2460926.png)
