### ISSUE TITLE
Impound Webhook not sending to Discord

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#1190]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

1.28.0

### Describe the Bug

For some reason when someone marks a car as impounded it does not show up in the Discord Webhook even though its set in the settings

### Expected Behavior

For vehicle to show up in the Discord as impounded

**Comment by Dev-CasperTheGhost** [comment]
fixed now!
