### ISSUE TITLE
Image Issues

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#1196]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

v1.29.2 194f8ba

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/198711171-49bd0aa3-f12e-457b-ade3-4a9dbe3a0bb8.png)

Cannot upload CAD Logo. It seems to have broken. Including all Civilian images and such.
Auth Screen header and background image are fine though.

I may have updated too soon without waiting for release maybe thats why?

### Expected Behavior

CAD logo / Citizen Photos loading

**Comment by Dev-CasperTheGhost** [comment]
Can you share your `next.config.js` file, located in `apps/client`? There might be something missing?

**Comment by ViolentMinds** [comment]
`/* eslint-disable @typescript-eslint/no-unnecessary-condition */
const { withSentryConfig } = require("@sentry/nextjs");
// const analyze = require("@next/bundle-analyzer");

/**
 * @template {import("next").NextConfig} T
 * @typedef {T}
 */
const nextConfig = {
  i18n: {
    locales: ["en", "en-gb", "ru", "cn", "tc", "fr-FR", "de-DE"],
    defaultLocale: "en",
  },
  cleanDistDir: true,
  eslint: {
    ignoreDuringBuilds: true,
  },
  // prettier-ignore
  images: { // start images
    domains: ["i.imgur.com", "cdn.discordapp.com", "localhost"]
  }, // end images
  // prettier-enable
  webpack(config, { webpack }) {
    config.plugins.push(
      new webpack.DefinePlugin({
        __SENTRY_DEBUG__: false,
      }),
    );
    return config;
  },
  sentry: {
    hideSourceMaps: false,
  },
}; // end config

const withSentryNextConfig = withSentryConfig?.(nextConfig, {
  org: "snailycad",
  setCommits: true,
  project: "snailycad-client",
  authToken: "bce2b8a2e79f4336a3b115f171e675ab639d2d1f809a40919ca4493257a9c0e0",
  release: "default",
  silent: true,
  hideSourceMaps: false,
});

/** @type {typeof nextConfig} */
const config = withSentryNextConfig ?? nextConfig;

/** @type {typeof nextConfig} */
// module.exports = analyze({ enabled: true })(nextConfig);
module.exports = config;
`

I also see this for images that it cannot find, and if I click on one I see **"url" parameter is not allowed** but not sure if thats normal or not anyways lol
![image](https://user-images.githubusercontent.com/25211271/198879485-cb38dc8e-08c0-4f88-ae62-8fd49b98483d.png)

**Comment by Dev-CasperTheGhost** [comment]
Can you run the following script in the root folder of SnailyCAD, then rebuild the client:

```bash
node scripts/create-images-domain.mjs
```

**Comment by ViolentMinds** [comment]
Fixed it! Thanks!!!
