### ISSUE TITLE
Warrant Requests Perms

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#1209]
### Describe the feature

The perms page doesnt have any option for Warrants
So nobody can approve them it seems
No one with Courthouse permission can see them

![image](https://user-images.githubusercontent.com/25211271/200098326-5496abbd-7ab7-4d46-a338-82d077e06669.png)

**Comment by ViolentMinds** [comment]
While I'm hear I was thinking wouldn't be better to put the Name Change Requests, Expungement Requests, Warrant Approval Requets on the Courthouse dashboard? Rather than in another section like it is now?

**Comment by Dev-CasperTheGhost** [comment]
> The perms page doesnt have any option for Warrants
So nobody can approve them it seems
No one with Courthouse permission can see them

This is located at `LEO`, you can simply search for `warrants` and it'll be listed.

**Comment by Dev-CasperTheGhost** [comment]
> While I'm hear I was thinking wouldn't be better to put the Name Change Requests, Expungement Requests, Warrant Approval Requets on the Courthouse dashboard? Rather than in another section like it is now?

These are in a different sections because the one at /courthouse are for the user to see, the ones at /admin/courthouse are for users with the respective permissions to manage the requests
