### ISSUE TITLE
Consistent API data approach (Calls & Incidents)

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1217]
### Describe the feature

When using GET v1/911-calls/ it returns only active calls and has switches to permit all data, as well as including closed calls.

When using GET v1/incidents/ it returns all calls with no switches and no ability to adjust returned data.

Could we make them consistent, so the behaviour is the same between them both? The same options and behaviour as 911 calls if possible.

**Comment by Dev-CasperTheGhost** [comment]
Will have the following options soon:tm::

- `includeActive` => include active incidents with non-active incidents
- `includeAll` => include all incidents in a single response (without pagination)

**Comment by jxckUK** [comment]
> Will have the following options soon™️:
> 
> * `includeActive` => include active incidents with non-active incidents
> * `includeAll` => include all incidents in a single response (without pagination)

Sounds good! Will this provide a way to see *only* active incidents (as the current default for 911-calls is this) as this is the use case I most need.

**Comment by Dev-CasperTheGhost** [comment]
> Will this provide a way to see only active incidents (as the current default for 911-calls is this) as this is the use case I most need.

will add that too, will be for tomorrow though

**Comment by Dev-CasperTheGhost** [comment]
For fetching incidents, `includeActive` has been changed to `activeType`. You can choose out of `active`, `inactive` and `all` once #1219 gets merged.
