### ISSUE TITLE
Trying to remove a department but its not working

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#1220]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

v1.29.2 194f8ba

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/200443050-aea5eccf-1774-47a5-a802-5a2effd3d50a.png)
![image](https://user-images.githubusercontent.com/25211271/200443162-24cd514d-23de-4bba-bd02-7540f585c05c.png)
![image](https://user-images.githubusercontent.com/25211271/200443258-254bdb0e-a129-429a-8e59-8190550c63a7.png)

![image](https://user-images.githubusercontent.com/25211271/200443418-43b2d049-56ae-410b-913b-754537d467d3.png)
But what item? Could it be ranks?

### Expected Behavior

To be able to remove Department
Which should then place officers that were in that department into a default department again

**Comment by Dev-CasperTheGhost** [comment]
this is not a bug, but rather a feature request. One cannot remove used values because it breaks things
