### ISSUE TITLE
API route to get all vehicle plates

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1224]
### Describe the feature

A bit of an odd request but would dramatically improve the functionality of my internal scripts.

At the moment, I pull down all vehicle details and have over 17,000 vehicles. This is a huge amount of data that I don't actually need. All I need are the registrations (plates) for all 17,000. The data size is far too large to make the request stable.

I was wondering if it would be possible for a simple route to be added that allows me to collect all registered plates. This ideally would have a switch to allow me to filter only non-user registered vehicles (not attached to a user account).

Would this be possible? If so, would it be much easier for the API to process than full data for 17,000 records?

**Comment by Dev-CasperTheGhost** [comment]
> Would this be possible? If so, would it be much easier for the API to process than full data for 17,000 records?

Possible yes. It should also decrease the length of the response - making it faster.

**Comment by Dev-CasperTheGhost** [comment]
It will return `Array<{ plate: string }>`

**Comment by Dev-CasperTheGhost** [comment]
API Route: `/admin/import/vehicles/plates`

**Comment by jxckUK** [comment]
Thanks Casper - you're a legend!

**Comment by jxckUK** [comment]
> This ideally would have a switch to allow me to filter only non-user registered vehicles (not attached to a user account).

Is there a way (possibly using the filter?) to identify only plates that are non-user registered? :)
