### ISSUE TITLE
Ccannot edit units on Manage Units it will not save

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#1225]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

v1.32.0 8235a89

### Describe the Bug

Manage Units page is not saving changes on any units

`{
  "DEBUG": {
    "message": "Request failed with status code 400",
    "status": 400,
    "response": {
      "data": {
        "name": "BAD_REQUEST",
        "message": "badRequest",
        "status": 400,
        "errors": [
          {
            "badgeNumber": "Required"
          }
        ]
      },
      "status": 400,
      "statusText": "Bad Request",
      "headers": {
        "content-length": "96",
        "content-type": "application/json; charset=utf-8"
      },
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "Content-Type": "application/json",
          "Session": "",
          "is-from-dispatch": "false"
        },
        "url": "https://api.enemyofthestaterp.com/v1/admin/manage/units/cl5bbgm7f309823nctmw3dabuxc",
        "method": "put",
        "data": "{\"status\":\"9b6599b7-b3e8-4767-b9cc-19c4f46f02b4\",\"department\":\"ckyby050c1514724tmbnb8upux\",\"division\":null,\"divisions\":[\"ckyc3r88h3007824tm990y7gdf\"],\"callsign\":\"PO\",\"callsign2\":\"34\",\"rank\":\"cl1wft9po66500xwtm7bt48alp\",\"position\":\"\",\"suspended\":false}",
        "withCredentials": true
      },
      "request": {
        "__sentry_xhr__": {
          "method": "PUT",
          "url": "https://api.enemyofthestaterp.com/v1/admin/manage/units/cl5bbgm7f309823nctmw3dabuxc",
          "body": "{\"status\":\"9b6599b7-b3e8-4767-b9cc-19c4f46f02b4\",\"department\":\"ckyby050c1514724tmbnb8upux\",\"division\":null,\"divisions\":[\"ckyc3r88h3007824tm990y7gdf\"],\"callsign\":\"PO\",\"callsign2\":\"34\",\"rank\":\"cl1wft9po66500xwtm7bt48alp\",\"position\":\"\",\"suspended\":false}",
          "status_code": 400
        }
      }
    },
    "method": "put",
    "data": "{\"status\":\"9b6599b7-b3e8-4767-b9cc-19c4f46f02b4\",\"department\":\"ckyby050c1514724tmbnb8upux\",\"division\":null,\"divisions\":[\"ckyc3r88h3007824tm990y7gdf\"],\"callsign\":\"PO\",\"callsign2\":\"34\",\"rank\":\"cl1wft9po66500xwtm7bt48alp\",\"position\":\"\",\"suspended\":false}",
    "url": "https://api.enemyofthestaterp.com/v1/admin/manage/units/cl5bbgm7f309823nctmw3dabuxc"
  }
}`

DevTools failed to load source map: Could not load content for https://cad.enemyofthestaterp.com/admin/manage/units/4c9e2a747c7bda40.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Expected Behavior

To be able to save changes on units

**Comment by ViolentMinds** [comment]
![image](https://user-images.githubusercontent.com/25211271/201112279-e9ce8459-160f-4140-b131-ea92255443f5.png)

**Comment by Dev-CasperTheGhost** [comment]
Okay, fixed now. Not tested but 99% sure it works now
