### ISSUE TITLE
Features: Move Active Incidents Up, Allow Dispatch To Give Accommodation Awards

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1226]
### Describe the feature

1. Could we move Active Incidents above Active Officers?
Or at least above Bolos/Warrants section?

This would be more noticeable and easier for Dispatch to work with

2. Could we allow Dispatch to Manage Unit with adding Award/Qualifications?

**Comment by Creizy** [comment]
I guess that would go under #1167

**Comment by Dev-CasperTheGhost** [comment]
> Could we allow Dispatch to Manage Unit with adding Award/Qualifications?

I'm not sure on this one though. If I add a new permission this wouldn't be feasible. Giving the entire dispatch permission access to that isn't very interesting too IMO? Since not every dispatcher should be allowed to give them awards, that'd be supervisors who do that?

**Comment by ViolentMinds** [comment]
Supervisors are useless.

Honestly we just wanted something more interesting for Dispatchers to do.
Dispatchers are talking to LEO constantly on the ground. They would know very well if a LEO is good at working well with Dispatch and can give an award if a LEO does a great job with communication with them. Just an idea. If its too hard then thats ok.

**Comment by Creizy** [comment]
> Supervisors are useless.

xD. Honestly, if this feature gets implemented, make it a togglable one instead of mandatory, since not everyone would like it probably

**Comment by ViolentMinds** [comment]
? Well its not like people have to use it they can simply not give awards

**Comment by Creizy** [comment]
There are so many ways it could still be abused

**Comment by ViolentMinds** [comment]
? But how theres only a set number of people with Dispatch permission or Supervisor permission in the first place

**Comment by Creizy** [comment]
Ehh, I don’t want to argue. 

Imma just say my thoughts, in case this gets added, make it a toggle feature that you can enable or disable

**Comment by jxckUK** [comment]
Sorry, this caught my eye and wanted to chime in, think it would certainly be good to add supervisor access to awards outside of the admin panel. Not sure that dispatch is the correct place for it though.

Might be worth placing this as a new page under officers that has an explicit permission that you can assign to dispatchers if you want or supervisors for the majority of cases?

**Comment by Dev-CasperTheGhost** [comment]
I'll try to go for a `ManageAwardsAndQualifications` permission. Soon:tm:
