### ISSUE TITLE
API route to return all valid value paths

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1236]
### Describe the feature

As discussed on Discord, a path that allows retrieval of valid value paths. Eg. the content that is returned when providing an incorrect value:

`"license", "gender", "ethnicity", "vehicle", "weapon", "blood_group", "business_role", "codes_10", "penal_code", "department", "officer_rank", "division", "driverslicense_category", "impound_lot", "vehicle_flag", "citizen_flag", "penal_code_group", "qualification", "call_type", "address"`

This would allow me to iterate through all available values that could be updated via new features/updates.

**Comment by Dev-CasperTheGhost** [comment]
Now supported: `/v1/admin/values/all`, make sure to update:)
