### ISSUE TITLE
Snaily doesn't work in ingame tablets

### ISSUE THREAD

**Issue by Dwohakin** [SnailyCAD/snaily-cadv4#1239]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

-

### What operating system are you using?

Windows 10

### What version of SnailyCAD are you currently using?

Latest

### Describe the Bug

Snaily doesnt work in tablets ingame (Iframe), and when it works it doesn't work the way its supposed to (can't login etc..)

### Expected Behavior

Use CAD ingame as leo or civ via ingame tablet

**Comment by Dev-CasperTheGhost** [comment]
This is not a bug. You **must** have a valid domain with a valid SSL certificate (https). The easiest thing you can do is setup a reverse proxy such as NGINX (Linux) or Apache (Windows).

In the near future the docs will feature guides how to setup reverse proxies. For now I recommend [this one for NGINX](https://www.digitalocean.com/community/tutorial_collections/how-to-install-nginx)

**Comment by Dev-CasperTheGhost** [comment]
A guide for Linux systems has been created on how to make a proxy: https://cad-docs.caspertheghost.me/docs/installations/reverse-proxies/nginx

**Comment by Local9** [comment]
After adding SSL, if the CAD still doesn't load in an iframe (or what ever tab resource you're using) you may need to edit the `X-FRAME-OPTIONS` header.

For nginx for example you will need edit your sites config in `/etc/nginx/sites-available/cad-client` & `cad-api`, replace the `add_header X-Frame-Options` line with `proxy_hide_header x-frame-options;`

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
