### ISSUE TITLE
Easier way to update single values for civilians

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1245]
### Describe the feature

I'm finding it quite difficult to update single values for citizens when I don't have a requirement to amend any other values. It makes the code more complex when I need to first get all the values and then add them to the PUT request even when the data isn't changing.

For example, I have a use case where I simply want to update `appearance`, to update appearance I must retrieve and send at least:
```
      name
      surname
      gender
      ethnicity
      dateOfBirth
      weight
      height
      hairColor
      eyeColor
      address
```

All of which I do not want to amend at all.

This makes it more complex and inefficient when it should be a simple edit of one field. This is also similar to 911 calls which require a baseline amount of data that sometimes I have no interest in changing.

Is there anything other than PATCH API calls that can help here?

**Comment by Dev-CasperTheGhost** [comment]
This is on the roadmap right now, currently no ETA for this.

**Comment by jxckUK** [comment]
> This is on the roadmap right now, currently no ETA for this.

Would there be a possibility of a temporary API call directly for appearance whilst we await the full roadmap item? This would allow me to set an appearance for a specified civilian ID without providing any other values?

**Comment by jxckUK** [comment]
> I’ll see what I can do for that, it’ll be easier to do this in one PR.

That would be good thanks! just in the short term so I can start actively using the appearance field which is quite a priority internally as I know when we spoke before the concept around PATCH requests etc was a major piece of work that could take some time.

**Comment by Dev-CasperTheGhost** [comment]
**Note to self:**  https://zod.dev/?id=partial


```ts
function partialize(schema: z.any) {
	return schema.partial();
}
```
