### ISSUE TITLE
Bug of greyed out/disabled buttons

### ISSUE THREAD

**Issue by MrLilian24** [SnailyCAD/snaily-cadv4#1253]
### What version of Node.js are you using?

18.12.1

### What version of npm are you using?

8.19.2

### What operating system are you using?

Windows

### What version of SnailyCAD are you currently using?

1.32.0

### Describe the Bug

The shaded boxes (in Dispatch but surely elsewhere) do not prevent the action of the box from being performed.

### Expected Behavior

That we cannot launch the action of the button when the box and the cursor are grayed out

**Comment by Dev-CasperTheGhost** [comment]
Admins are able to perform some actions no matter they're active or not. Please see #1133
