### ISSUE TITLE
Feature: Citizen Notes by LEO

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1268]
### Describe the feature

![image](https://user-images.githubusercontent.com/25211271/204115082-36ab1785-3253-4153-8282-804f414bb180.png)

Could we have a section added to Citizen Information that LEO can edit about a citizen? Such as this example.
This is useful for the case where someone is not actually charged formally, or, warned formally. But they could be someone who is always involved with the police in some way. Even for example as a witness. Something suspicious like that where they keep coming up on scenes but haven't actually been charged yet. Citizen notes by law enforcement could be useful in some way to let LEO know to be careful/keep an eye out just in case on a citizen.

**Comment by Dev-CasperTheGhost** [comment]
You can already add notes to citizens, scroll in the tabs list and you'll see a "notes" tab.
