### ISSUE TITLE
[FEATURE REQUEST] Suggestions for entered data

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#127]
### Describe the feature

Implement a mechanism for preloading data into input fields with an indication of the number of characters when the mechanism starts to work.

Principle of operation:
- the user enters data into the field
- if the length of the entered data >= the value specified for the field, then a hint on the data is displayed

Data search is carried out on any part
![unknown 1](https://user-images.githubusercontent.com/4976837/140520764-257a06c9-95ef-4c82-9bbf-faa036a70c15.png)

Add such functionality for the BOLO creation card (auto, citizen). If there are many values, display 8 values and apply a scroll to the dropdown.
![kiss_5kb 1636121098 1](https://user-images.githubusercontent.com/4976837/140523248-a1fbbf06-a80d-45d3-9f43-f3207d9f38dd.png)

Add such functionality for the Create Warrant

**Comment by Dev-CasperTheGhost** [comment]
Made some good progress on this in a short time. Should be able to release this tomorrow 🚀!
