### ISSUE TITLE
Feature: Password Reset Option

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1276]
### Describe the feature

Allow people to reset their password with temporary somehow. We get so many people asking us to do it and its really time consuming.

**Comment by Dev-CasperTheGhost** [comment]
This is currently not really possible without some sort of email. I don't want to add email support because I know many people host SnailyCAD unsecured. For now I'll close this until I have a better solution. 

You could also temporary create a strict rule about users losing their passwords?
