### ISSUE TITLE
CAD changing languages ​​temporarily when tab in admin is selected

### ISSUE THREAD

**Issue by wesleymoura** [SnailyCAD/snaily-cadv4#1286]
### What version of Node.js are you using?

17.6.0

### What version of npm are you using?

8.5.1

### What operating system are you using?

Windows

### What version of SnailyCAD are you currently using?

1.35.4 (last)

### Describe the Bug

When I click on "Gerenciar Funções Customizadas (Manage Custom Roles" in the administration area, all CAD in that tab returns to **EN** while it is selected. and returns to **pt-BR** when exited. 

### Expected Behavior

Don't change language when selected.

### To Reproduce

1 - Select the language **pt-BR**
2 - Go to the **Admin Area**
3 - Click on **"Gerenciar Funções Customizadas"**

Done, the CAD must have changed language, click on any other tab and it will go back to the **pt-BR** language, select it again and it will go to **en** while they are selected.

![pt-BR to en](https://user-images.githubusercontent.com/14825927/205994479-7ba51c5f-4041-4d04-9193-4e64ad47c693.gif)

**Comment by Dev-CasperTheGhost** [comment]
Fixed now :)!
