### ISSUE TITLE
Bug with JSON DOCTYPE and saving Department values

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1287]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

https://github.com/SnailyCAD/snaily-cadv4/commit/aa5f726

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/206058957-e2ca41d7-fd3f-4ee0-96e4-eea05d91ad0f.png)

Values are not saving. This is the error I have in console.

### Expected Behavior

To be able to save values like Officer Ranks.

Also Department updates/edits.

**Comment by Dev-CasperTheGhost** [comment]
that error is not related to this bug report. Are you able to clarify not being able to update values?

**Comment by Legacy-TacticalGamingInteractive** [comment]
I added a new officer rank

the new rank is not showing in default rank drop down for department

**Comment by Legacy-TacticalGamingInteractive** [comment]
![image](https://user-images.githubusercontent.com/25211271/206123741-cae2a5a2-b9d9-47f6-8d63-03a64fb6192d.png)


trying to edit HSO-GSO-PPS default rank and it wont remove it or even find the new one in the list that i want to change it do

**Comment by Dev-CasperTheGhost** [comment]
does it show up after a page refresh? I'm unable to reproduce this error

**Comment by Legacy-TacticalGamingInteractive** [comment]
It does not :( 

Even logged out and back in.

I give up.

I even updated Snaily just now and it still wont work

I make the new rank... it says the rank is there on the Officer Rank page.
I go to Department
I go to edit Default Rank
Option is not there in the drop down.
I also cannot remove the Default rank to set it as None.
The only thing that works is changing the default rank to an existing rank in the drop down but that doesn't help lol.

**Comment by Dev-CasperTheGhost** [comment]
Check your Discord DM's please :)
