### ISSUE TITLE
[FRENCH] Missing Translations

### ISSUE THREAD

**Issue by MrLilian24** [SnailyCAD/snaily-cadv4#1291]
### What version of Node.js are you using?

18.12.1

### What version of npm are you using?

8.19.2

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

1.35.5

### Describe the Bug

There is a lack of French translation (FR-fr) in some parts (see PDF). But also with error messages that are in English (when a field is incorrectly filled for example).

**PDF (in french and english):**
[missing-translate (2).pdf](https://github.com/SnailyCAD/snaily-cadv4/files/10178353/missing-translate.2.pdf)

### Expected Behavior

Add missing translations to JSON (same for other languages if missing).

**Comment by Dev-CasperTheGhost** [comment]
If you’re able to do this, that’d be great. If not this should be closed since I’m not in charge of the FR lang.

cc @SunlightKim

**Comment by SunlightKim** [comment]
Missing translations are under progress. Will be added ASAP.

**Comment by SunlightKim** [comment]
Missing translations done.
@MrLilian24 please note: some text are in the code itself (TS files) so I cannot translate them. This would require make a all new fork and completely translate everything while maintaining the fork updated.

**Comment by Dev-CasperTheGhost** [comment]
half-closed by #1293. Thanks a lot @SunlightKim!! Will work on adding those missing translations that aren't in the translation files yet

**Comment by Dev-CasperTheGhost** [comment]
All have been added except for the CAD-Settings ones. It's currently too much work. Possible something for the near future
