### ISSUE TITLE
Panic Button

### ISSUE THREAD

**Issue by MrLilian24** [SnailyCAD/snaily-cadv4#1292]
### What version of Node.js are you using?

18.12.1

### What version of npm are you using?

8.19.2

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

1.35.5

### Describe the Bug

- The Panic Button cannot be deactivated when you click on it again after activating it.
- The unit is not displayed in red for us or dispatch.
- When you refresh the page it comes off.

[> YouTube video <](https://youtu.be/t4p4aXVjTeM)

### Expected Behavior

That when we click on the Panic Button, it activates once, then we click a second time if we want to disable it.
That it also remains displayed as long as the officer in question or the Dispatch has not deactivated it.
And finally, that the unit having the Panic Button activated is displayed in red (even blinking gently if possible) in the list of active Officers/Agents.

**Comment by Dev-CasperTheGhost** [comment]
For now a quick fix is to create a 10 code with type Panic Button. Wil get this properly fixed later

**Comment by Dev-CasperTheGhost** [comment]
You're now required to have a panic button 10-code. Otherwise this feature will not work as-expected. The panic button button will be hidden until there's a panic button code created.

**Comment by jxckUK** [comment]
> You're now required to have a panic button 10-code. Otherwise this feature will not work as-expected. The panic button button will be hidden until there's a panic button code created.

Is this a breaking change for those of us who haven’t made any changes? :)
