### ISSUE TITLE
feat: Persistent tones

### ISSUE THREAD

**Issue by MrLilian24** [SnailyCAD/snaily-cadv4#1297]
### What version of Node.js are you using?

18.12.1

### What version of npm are you using?

8.19.2

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

1.35.5

### Describe the Bug

I think this is normal but it seems strange to me I can’t explain it. Hoping that the video will help.

[> YouTube Video <](https://youtu.be/y0EqIzXnPUU)

### Expected Behavior

That the tones are persistent, that is to say they only last a maximum time set by the admin. And that they don’t disappear as soon as we update the page.

**Comment by Dev-CasperTheGhost** [comment]
Tones were never persistent. I'm going to mark this as a feature request for now, will see what is possible :)
