### ISSUE TITLE
Class of Firearm

### ISSUE THREAD

**Issue by MrLilian24** [SnailyCAD/snaily-cadv4#1299]
### Describe the feature

Add a field with categories for firearms. The types of these categories can be added via the admin section.
For example: Semi-automatic, Automatic, Shotgun, A, B, C, D, etc...
Also allowing to sort firearms, because when have a lot it can be complicated.

**Comment by Dev-CasperTheGhost** [comment]
This already exists: 

![image](https://user-images.githubusercontent.com/53900565/206366947-c8240107-1266-46cf-a646-450aa7e9b23f.png)

**Comment by Dev-CasperTheGhost** [comment]
> Also allowing to sort firearms, because when have a lot it can be complicated.

You can already search for your citizen's weapons/vehicles.

**Comment by MrLilian24** [comment]
I meant one category but based on the firearm. Not a licence.
