### ISSUE TITLE
View of tickets

### ISSUE THREAD

**Issue by MrLilian24** [SnailyCAD/snaily-cadv4#1300]
### Describe the feature

Currently, when a police officer searches for an individual’s name, you can see his profile but nothing is displayed in the fines/tickets section. That is, even if he has a fine/ticket paid or unpaid, an officer cannot see it (except in the Citizen Logs).

It may be a bug, I don’t know, but it’s really a shame because the tab is there but you can’t see anything.
It’s the same for the citizen himself he doesn’t see it (I tested her after I paid it) on his profile of his citizen.
And in the Citizen Logs, the Status is bugged because it doesn't display "Paid" or "Non-Paid"

**Comment by Dev-CasperTheGhost** [comment]
Are you looking for the correct citizen? It works as expected for me.
