### ISSUE TITLE
CAD Incident TTS Updates - Alert units assigned on call with notification of an update from events tab.

### ISSUE THREAD

**Issue by GamingFlamin** [SnailyCAD/snaily-cadv4#1308]
### Describe the feature

It would be a neat while small extra feature to have alerts and notifications about recent new events that have been added for a call that's in progress (would only alert units who were assigned to the call)

Usually this is a text to speech with something like **"Your incident has been updated"** to alert a unit to any new details.  

Optionally as well maybe a notification icon next to call details for the officers. 
![image](https://user-images.githubusercontent.com/4467576/206839188-7dab8a2a-e758-4be4-aba3-7d8e65229d3b.png)

Currently right now in the current state with the cad I don't think any notification system alerts units and unless they have been told to check it via dispatcher, they won't be aware of any event details. I feel this could be helpful in using the live events updates more often without having to communicate every detail over radio or so.
![image](https://user-images.githubusercontent.com/4467576/206838458-534de7fc-2496-49ae-93e6-0fec5613ecee.png)

To prevent probable spam and annoyance, this should be optional and maybe some sort of option that can be added right near the "**add event button**" if to notify units via text to speech (a generic message of an event) if it's an important update.

This is really overall a more extra type feature that would expand on the current TTS system that's in place to alert to being assigned to a call and such. 

### Additional Context

_credit for the idea came from a friend who suggested this would be a good small detail._
_Along with that some real CADS have something similar to this. (from watching bodycam videos and hearing the audio heh)_

Overall, it's maybe just a gimmick, who knows. It could add just that extra little bit of detail.

**Comment by GamingFlamin** [comment]
I should note that the 
> Optionally as well maybe a notification icon next to call details for the officers.
is really another idea *and probably a gimmick* and I think it would be perfectly fine with just a TTS alert of new events since I would assume more units would know which call they were already on. But figured I'd mention it.

**Comment by Dev-CasperTheGhost** [comment]
> Optionally as well maybe a notification icon next to call details for the officers.

where exactly would this be displayed?.

**Comment by Creizy** [comment]
Since we talking about calls, maybe make the assigned call highlight a bit more noticeable?

**Comment by Dev-CasperTheGhost** [comment]
Sure, will take a look

**Comment by Dev-CasperTheGhost** [comment]
> Since we talking about calls, maybe make the assigned call highlight a bit more noticable?

maybe something like this?
![image](https://user-images.githubusercontent.com/53900565/206841925-dfbeb10a-d938-40a6-865e-4c76115938dc.png)

**Comment by Creizy** [comment]
Hmmm most sure tbh

**Comment by Dev-CasperTheGhost** [comment]
what color should be used you rekin?

**Comment by Creizy** [comment]
I honestly don’t know 😅🤣

**Comment by GamingFlamin** [comment]
That looks pretty good actually and color wise, hm. Maybe it could be customizable, but if that's too much heh, maybe a soft orange? Something warning or alert color.

**Comment by GamingFlamin** [comment]
Some hex code ideas
#CB6C26
#a34212
#8c2e03
Not sure how it'll look.

**Comment by Dev-CasperTheGhost** [comment]
Something like this is fine: 
![image](https://user-images.githubusercontent.com/53900565/206842384-1a97ee39-f84f-4821-ab74-9ef999374e1b.png)

**Comment by Creizy** [comment]
Uuuu yes

**Comment by GamingFlamin** [comment]
Yep that looks great, and would the TTS implementation be fine too?

**Comment by Dev-CasperTheGhost** [comment]
yep!

**Comment by Dev-CasperTheGhost** [comment]
TTS implementation will take a bit longer since it's some work to figure out what was updated in the call and such

**Comment by GamingFlamin** [comment]
Yea, and again the TTS doesn't need to be overdone, just something with that the incident got updated would be perfectly fine, don't think anyone would want to listen to text to speech read out an entire event text heh.

**Comment by Creizy** [comment]
“Call updated”

**Comment by GamingFlamin** [comment]
Yep that can work too, just want to make sure we have some safeguards in place to not have a "rapid repeat" situation heh.

**Comment by Dev-CasperTheGhost** [comment]
maybe a checkbox "update with notification?" ?

**Comment by GamingFlamin** [comment]
Yep that can work
