### ISSUE TITLE
[FEATURE REQUEST] Penal codes, tickets, warnings, arrests

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#131]
### Describe the feature

It is necessary to improve the functionality of creating warnings, tickets and arrests

### 1. Changes to the card of articles of the Penal Code

Increase the size of the modal window to 1000 x 600px.

Add a radio group with two elements:
- Warning applicable
- Warning not applicable

When you switch the radio button, different sets of fields appear.
If "Warning applicable" is selected, the entry fields for the amount of the penalty are displayed.
![kiss_11kb 1636194012 1](https://user-images.githubusercontent.com/4976837/140621712-57b1905c-637d-44cc-8d55-f5f0cd7aae7e.png)

If "Warning not applicable" is selected, then the fields for entering the amount of the penalty and the fields for entering the amount of the deposit are shown.
If "Warning not applicable" is selected, this means that the violation is serious enough and does not warrant a written warning.
![kiss_13kb 1636211801 1](https://user-images.githubusercontent.com/4976837/140621752-5f6a2899-94a6-4f70-910e-bd1bf14ecc06.png)

Example:
- the citizen crossed the road in the wrong place. The officer can issue a written warning or issue a fine ("Warning applicable" will be selected in the article)
- a citizen has exceeded the speed limit in a residential area. The officer will issue a fine ("Warning not applicable" will be selected in the article)
- a citizen robbed a bank. The officer cannot impose a fine, only a prison term or the amount of bail ("Warning not applicable" will be selected in the article)

How the fields work:
If the "Fines" checkbox is set, it means that a penalty may be applied to the article.
If the "Prison term" checkbox is checked, it means that a prison term may apply to the article.
If the "Prison term" checkbox is not selected, then the "Bail" checkbox and its fields are unavailable.
If the "Bail" checkbox is set, it means that the amount of the bail can be applied to the article.

Numeric values are accepted as values for fields "field1" and "field2".

The fields "field1" and "field2" indicate the range of values.
Example for "fines":
- if "field1" = 200, and "field2" = 400, then the officer can issue a fine in the range from 200 to 400 dollars
- if "field1" = 200 and "field2" = 200, then the officer can issue a fine ONLY 200 dollars.

Rules for fields:
- "field1" must be greater than or equal to 0
- "field2" must be greater than or equal to "field1", but greater than 0
- "field1" and "field2" are required

### 2. Sorting articles of the code
Add sorting of articles, as in task #42

### 3. Change the mechanism for specifying articles
Articles are selected separately and fields are loaded for each indicating the amount of the fine or the term of imprisonment (if applicable).
![kiss_37kb 1636223418 1](https://user-images.githubusercontent.com/4976837/140621779-f5e45c4c-cae2-4a63-b306-ef3374958ecf.png)

Note:
- in the ticket creation card, it will only show the input fields for the amount of the fine
- in the arrest creation card, it will show the fields for entering the amount of the fine, entering the prison time and bail

### 4. Written Warning Creation Card
Only those articles for which "Warning applicable" was specified in the article settings are shown in the "Violations" field. Required field.
The fields for specifying the amount of the penalty are not shown.

### 5. Card for creating a ticket
The "Violations" field shows all articles for which the penalty is specified. Required field.

### 6. Card of creation of arrest
All articles are shown in the "Violations" field. NOT required field.

For each article, the order settings are loaded: if a penalty value is specified, then show the penalty fields and similarly for other fields.

At the end of the block, the TOTAL amount of fines, time of imprisonment and bail is shown.

When an arrest is created, the status "Arrested" is set for the citizen

### 7. Jail
Add the "Jail" tab to the officer's menu.
![kiss_20kb 1636224449 1](https://user-images.githubusercontent.com/4976837/140621792-a48444d4-8f18-4eb8-9cfb-636db1d445b4.png)

Show records of citizens who have been arrested on the page.
![kiss_24kb 1636225947 1](https://user-images.githubusercontent.com/4976837/140621797-86483e8c-eea2-4eaa-92ee-b1ec129acf25.png)

If you click on the "Release" button, a modal window will open, where you will need to select the type of release: time has run out or a bail has been made.

If a bail is made, then you need to indicate the citizen who made the bail (drop-down list with the choice of a citizen).

### 8. Management of seized items

When a citizen is arrested, items that need to be registered may be confiscated from him.
It is necessary to create a block for entering information about such items in the arrest card under the block of violations.
![kiss_7kb 1637164425 1](https://user-images.githubusercontent.com/4976837/142235267-e11fe52e-076c-4c2d-9ff6-cf262e5847fb.png)

When the officer clicks the "Add" button, a line is added to the block for entering data.
The officer must indicate the name of the item, its quantity and status of legality.

This data will facilitate the return of items when the citizen is released from jail.

- [x] change the card of work with the Penal Code
- [x] change the card for creating a written warning
- [x] change the ticket creation card
- [x] change the arrest creation card
- [x] add jail functionality
- [ ] management of seized items

### Additional Context

@Dev-CasperTheGhost if the functionality is complex, tell me, I'll try to simplify

**Comment by NCC-Gnisha** [comment]
For the Penal Code, can there be an option for Felony or Misdemeanor?

**Comment by pp2amd6** [comment]
@NCC-Gnisha What is it about? Where will this data be displayed?

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost block for "Management of seized items" was added in task description

**Comment by Dev-CasperTheGhost** [comment]
The sorting penal-codes task will be moved to #189

**Comment by Dev-CasperTheGhost** [comment]
> @Dev-CasperTheGhost block for "Management of seized items" was added in task description

this hasn't been added yet, but will be implemented soon! I'm still keeping track of it, let me know if there are things you'd like to see changed as well :)!

@pp2amd6
