### ISSUE TITLE
Department Officer Pruning

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1314]
### Describe the feature

Wanted to add onto this. Pruning feature for Officers in departments. Because we have so many inactive and since we cannot remove the department this might be the best thing. Ideally I wanted to just delete the entire department and remake it. But a pruning tool that removes them from the department including their rank and unit would be ideal. Somehow. We have hundreds of people in some departments that don't even exist anymore on our server or the department itself doesn't exist anymore and cannot be removed.

**Comment by Creizy** [comment]
You’re thinking like something that discord has for pruning?

like: if inactive for 7, 14, 30 days then prune

Smth like that or?

**Comment by Legacy-TacticalGamingInteractive** [comment]
> You’re thinking like something that discord has for pruning?
> 
> like: if inactive for 7, 14, 30 days then prune
> 
> Smth like that or?


Sure that would be great if automatic or manual pruning is fine too.

**Comment by Legacy-TacticalGamingInteractive** [comment]
<3

**Comment by Dev-CasperTheGhost** [comment]
To sum up: when pruning selected departments:

- will delete the department
- will delete any rank with ONLY that department
- will delete any unit with that department

**Comment by Legacy-TacticalGamingInteractive** [comment]
**Entire Department Removal**
This option could be a last resort. If you have so many inactive/old members or problems in the department maybe its easier to start fresh. (We might do that ourselves because we have hundreds of people in some departments many who are not active or don't play in that department anymore for months)

**Inactive Department Members:**
Will delete any unit that is inactive in the department for xxxx amount of time.

Activity check based on **time and/or if possible last time logged into Officer Dashboard?**
If its possible to determine who is inactive as an officer versus in general as a user of the CAD?
However you would figure that out I'm not sure.

It would be ideal to prune members of a department without deleting the entire department (so it only keeps the recently active ones there) and removes the others giving them the default department instead (if CAD owner has one set) or no department at all.

**Ranks:**
_Ignore._ It may be best to avoid deleting ranks. Many are used across multiple departments. Like for our Sergeant rank. Its tied to more than one department.

**Comment by Dev-CasperTheGhost** [comment]
> Inactive Department Members:
Will remove any unit that is inactive in the department for xxxx amount of time.
It would just give them default department if one is set or no department.

Sure, this is possible. So this is more a "Unit Prune" than a "Department Prune"?

> How would it know if they are inactive? Maybe activity check based on time and/or if possible last time logged into Officer Dashboard or something with that unit? If its possible to determine who is inactive as an officer versus in general as a user of the CAD? Or whatever.

Probably last time a unit log was logged?

> Ranks:
Ignore. It may be best to avoid deleting ranks. Many are used across multiple departments. Like for our Sergeant rank. Its tied to more than one department.

👍

**Comment by Legacy-TacticalGamingInteractive** [comment]
> > Inactive Department Members:
> > Will remove any unit that is inactive in the department for xxxx amount of time.
> > It would just give them default department if one is set or no department.
> 
> Sure, this is possible. So this is more a "Unit Prune" than a "Department Prune"?
> 
> > How would it know if they are inactive? Maybe activity check based on time and/or if possible last time logged into Officer Dashboard or something with that unit? If its possible to determine who is inactive as an officer versus in general as a user of the CAD? Or whatever.
> 
> Probably last time a unit log was logged?
> 
> > Ranks:
> > Ignore. It may be best to avoid deleting ranks. Many are used across multiple departments. Like for our Sergeant rank. Its tied to more than one department.
> 
> 👍

Yes I suppose so.
A general unit prune could be useful in any case for any department on the server really. Maybe some users are only active as Citizen and not LEO. So removing their unit that is tied to a department is a good idea to clean up CAD.

**Comment by Dev-CasperTheGhost** [comment]
![image](https://user-images.githubusercontent.com/53900565/215149393-c4a5fee3-5e2e-438e-9aee-4c1f9b47606c.png)

@Legacy-TacticalGamingInteractive

**Comment by Legacy-TacticalGamingInteractive** [comment]
AMAZING. LOVE IT.

**Comment by Legacy-TacticalGamingInteractive** [comment]
![image](https://user-images.githubusercontent.com/25211271/215180679-c8ab3d6e-153b-4a6c-9a2c-693e6ee7056a.png)
Example
