### ISSUE TITLE
Support for Discord Linked Roles

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1322]
### Describe the feature

Add the ability for us to add metadata via our configured Discord authentication bots and point the `LINKED ROLES VERIFICATION URL` to an endpoint on the CAD that can verify if the user is registered and linked with Discord, and provide information like how many citizens, officers that they have.

### Additional Context

https://discord.com/developers/docs/tutorials/configuring-app-metadata-for-linked-roles

https://support.discord.com/hc/en-us/articles/8063233404823

https://support.discord.com/hc/en-us/articles/8063233404823

**Comment by Dev-CasperTheGhost** [comment]
Discord doesn't allow for the current complexity of SnailyCAD's permission system.

**Comment by Dev-CasperTheGhost** [comment]
After a short discussion in Discord, this is supported :o
