### ISSUE TITLE
Custom `sna-live-map` script

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [SnailyCAD/snaily-cadv4#1329]
### Describe the feature

It is clear that the current script created by [TGRHavoc](https://github.com/TGRHavoc/live_map) isn't really working anymore. The demand seems fairly high for a properly working script. 

Some starting guides: 

- https://fivemods.net/product/219/?prel=1&pri=all
- https://github.com/TGRHavoc/live_map
- https://github.com/TGRHavoc/live_map/tree/master/example_client
- https://github.com/supernovaplus/ttmap
- https://docs.fivem.net/docs/scripting-reference/runtimes/lua/functions/GetPlayerIdentifiers/
- https://github.com/SnailyCAD/snaily-cadv4/blob/22c00bb26b67f58e7d470bb016768ca03e6944e9/apps/api/src/controllers/dispatch/DispatchController.ts#L283

### Additional Context

- Allow **BOTH** Discord and Steam identifiers

**Comment by jxckUK** [comment]
Would love to see this brought inside the Snaily system, have never managed to get the external dependency live map working! 

Whilst this is still a concept/idea can I also mention that it would be fantastic if it supported other identifiers such as Discord instead of Steam.

**Comment by Dev-CasperTheGhost** [comment]
> Whilst this is still a concept/idea can I also mention that it would be fantastic if it supported other identifiers such as Discord instead of Steam.

Sure, added it to the additional context. Thanks for the suggestion!

**Comment by PLU12** [comment]
not sure if your already planning to do this but if possible i think it would be good to see on the live map if the active unit is in a vehicle or on foot

**Comment by Dev-CasperTheGhost** [comment]
> not sure if your already planning to do this but if possible i think it would be good to see on the live map if the active unit is in a vehicle or on foot

That's already possible
