### ISSUE TITLE
Extend new live map logic to 911 calls

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1336]
### Describe the feature

As discussed in Discord, currently the CAD processes a players in game position and determines a map position. 

This logic would be useful to extend to 911 calls if a in game location is passed eg. Coordinates. This would allow for accuracy when displaying the call on the map and also allow for moving targets such as fleeing suspects or pursuits to be monitored by control.

**Comment by Dev-CasperTheGhost** [comment]
Now supported!
