### ISSUE TITLE
Emergency vehicles on live map

### ISSUE THREAD

**Issue by Creizy** [SnailyCAD/snaily-cadv4#1337]
### Describe the feature

If emergency vehicles have their lights enabled, could they be shown on the live map, with smth like flashing lights on top of the car?

**Comment by jxckUK** [comment]
This is a nice idea but I would guess its highly dependent on what ELS script the server is operating, if any at all?

**Comment by Dev-CasperTheGhost** [comment]
No? There's a global `IsVehicleSironOn`. Does this work with ELS?

**Comment by jxckUK** [comment]
> No? There's a global `IsVehicleSironOn`. Does this work with ELS?

It's still script dependent I think but possibly, I think you'd cover a majority if you used that native.

**Comment by jxckUK** [comment]
> Are you able to share the ELS script for FiveM?

I can't share mine as it's unfortunately a paid resource that we've heavily modified but the most common are:

https://github.com/matsn0w/MISS-ELS
https://github.com/MrDaGree/ELS-FiveM

Here is a snippet from ours that suggests you may be able to check that native:

**Comment by Dev-CasperTheGhost** [comment]
Would it be possible providing a flashing lights icon I could use for the map? Having trouble finding one

**Comment by Creizy** [comment]
Honestly I don’t have any atm, I could make one on photoshop rq. I just noticed that on one Russian dudes video. They were like flashing on top of the car, but static would do as well

**Comment by Creizy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/100074335/209316221-7f9d6cd8-2886-4db8-ba7e-5de88ede2b29.gif)

**Comment by Creizy** [comment]
> Are you able to share the ELS script for FiveM?

another one: https://github.com/TrevorBarns/luxart-vehicle-control

**Comment by Dev-CasperTheGhost** [comment]
Supported now


> **Warning**
> This requires `v0.0.7` of [`sna-live-map`](https://github.com/SnailyCAD/live-map/releases/tag/0.0.7)
