### ISSUE TITLE
[BUG] Citizen creation - Driving license categories are incorrectly assigned

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#134]
### What version of Node.js are you using?

does not matter

### What operating system are you using?

does not matter

### Describe the Bug

1. When specifying the categories of driver's and flight licenses, then the flight categories apply to all.
2. In edit mode, the flight category cannot be deleted from the driver's license.
3. A citizen with a problem category is not removed

https://user-images.githubusercontent.com/4976837/140659545-f9affa45-1d3c-46f3-b961-11bbcb3dc7bd.mp4

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
I get nightmares about this one 😅, had this in dev too and seemed to be fixed. Will take a look!
