### ISSUE TITLE
Add more register values (pre-registered user)

### ISSUE THREAD

**Issue by bartusek27** [SnailyCAD/snaily-cadv4#1342]
### Describe the feature

I am currently making some connector to our Character Creation so we can create a new Citizen inside the CAD as soon as the character is created. And I don't want to create a citizen without any link to a user since it would be annoying for admins when they connect each Citizen manually to our users.

If I saw the docs correctly, there is no way to create a blank user just with discordId, so as soon as they connect into the CAD with their Discord account, they would already see their Citizens.

I was thinking about changing /v1/auth/register to also have optional parameters discordId and steamId that would be accessible via API request. If there is a possibility to make it that you need at least one of the parameters (password or discordId or steamId), it would be easy to create via API new user that is just waiting to be used already with prefilled data.

**Comment by Dev-CasperTheGhost** [comment]
this would still require a username to be passed in. I can make it so either `password`, `discordId` or `steamId` is required
