### ISSUE TITLE
Bolos clear on page refresh

### ISSUE THREAD

**Issue by TheConwayy** [SnailyCAD/snaily-cadv4#1344]
### What version of Node.js are you using?

18.12.1

### What version of npm are you using?

8.19.2

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

1.40.0 - a0521a6

### Describe the Bug

When a BOLO is created *(either on the LEO or Dispatch end)*, it will show up on both ends, as normal.

*However,* when you refresh the page and/or log in and out, the bolo is no longer there. 
The same happens when you interact with anything else on the page

### Expected Behavior

It is expected that the BOLO remain on the screen for the entirety of the session, and when you first log in, not just have it disappear after any other interaction with the page.

### To Reproduce

Create a BOLO, and then refresh the page and/or interact with anything else on the page

**Comment by Dev-CasperTheGhost** [comment]
Do created citizens show on the page? If not, you have something incorrectly configured in your .env file. I’m currently not able to test, but will do when home

**Comment by TheConwayy** [comment]
> t

Yes, when you go to create a civilian bolo, created civilians show.

**Comment by Dev-CasperTheGhost** [comment]
Okay, I’ll try reproduce when I’m home.

**Comment by Dev-CasperTheGhost** [comment]
Alright, fixed now
