### ISSUE TITLE
Businesses can create their own business roles

### ISSUE THREAD

**Issue by bartusek27** [SnailyCAD/snaily-cadv4#1347]
### Describe the feature

Currently, it is only possible to let admin create some business roles, or owners have to hope that admins make at least some generic ones they have to use.

The idea is to let owners create their roles the same way as possible in the Admin tab. These roles would also be updated if they are global (predefined) or scoped only for a specific business.

**Comment by Dev-CasperTheGhost** [comment]
I should be able to pick up this feature again this weekend/next week

**Comment by Dev-CasperTheGhost** [comment]
Closed by #1481
