### ISSUE TITLE
Don't require a division to create an emergency vehicle

### ISSUE THREAD

**Issue by TheConwayy** [SnailyCAD/snaily-cadv4#1349]
### Describe the feature

When creating an emergency vehicle, it currently does not allow you to *unless* you have a division selected for it.

There is no error saying that the field is required or anything, it just straight does not work.

I think that this should not be a requirement, especially if you have divisions disabled *(like I did, before I turned them back on to create the vehicles)*

**Comment by Dev-CasperTheGhost** [comment]
Fixed now
