### ISSUE TITLE
Jailing a citizen already on jail-list (greyed out) doesn't mark them as arrested + cannot be released

### ISSUE THREAD

**Issue by ArgonGlow** [SnailyCAD/snaily-cadv4#1361]
### What version of Node.js are you using?

16.18.1

### What operating system are you using?

Windows

### What version of SnailyCAD are you currently using?

1.41.0

### Describe the Bug

When arresting a citizen that is still present on the jail list, but greyed out (released), their 'arrested' property isn't set to 'true.'
This means that a retrieved list that is filtered by said value comes back incorrectly, and that the citizen can no longer be released (error 400: citizenNotArrested).

### Expected Behavior

The 'arrested' value of an already present (greyed out) citizen in the jail list is set to 'true' if they are arrested again.
Or an arrested citizen is removed from the jail list instead of greyed out, circumventing the issue.

### To Reproduce

Arrest a citizen and let the timer expire resulting in their release (with supporting settings enabled). Arrest the same citizen again.

Unsure whether this is limited to citizens that were automatically released by time out the first time, or if it's also applicable to manually released citizens.

**Comment by Dev-CasperTheGhost** [comment]
Does a page refresh work?

**Comment by ArgonGlow** [comment]
Unfortunately not. It's 'arrested' not being set to true, which the delete request checks for.

**Comment by Dev-CasperTheGhost** [comment]
will have to take a look later today/tomorrow.

**Comment by ArgonGlow** [comment]
No worries. I'll just clear the list on the DB end while testing. Let me know if you need any more details.

**Comment by Dev-CasperTheGhost** [comment]
wasn't able to test, let me know if it was fixed!
