### ISSUE TITLE
Department based colours

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1371]
### Describe the feature

With the addition of the new live map, it would be a nice feature if we could set a [colour](https://docs.fivem.net/docs/game-references/blips/#blip-colors) that the units would appear as on the live map if they're in that department. 

This would allow us to quickly distinguish units on the map and would also provide a colour that could be used in the API to set unit blips within the game too.

**Comment by Dev-CasperTheGhost** [comment]
This won't be possible currently
