### ISSUE TITLE
[BUG] Admin - 10 codes - Colorpicker freezes the page

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#138]
### What version of Node.js are you using?

does not matter

### What operating system are you using?

does not matter

### Describe the Bug

Page freeze on sec 04

https://user-images.githubusercontent.com/4976837/140813245-1a28b87d-36be-403f-b4f5-03bde5d44619.mp4

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
Does it freeze the entire page, or only that part of the colorpicker @pp2amd6?

**Comment by pp2amd6** [comment]
entire page

**Comment by Dev-CasperTheGhost** [comment]
Are you able to confirm whether this bug has been fixed; this might be related to #139?

**Comment by pp2amd6** [comment]
Colorpicker and menu are working now. Thanks, @Dev-CasperTheGhost
