### ISSUE TITLE
CAD access speed is slow and operation delay is very high

### ISSUE THREAD

**Issue by warrior12333** [SnailyCAD/snaily-cadv4#1389]
### What version of Node.js are you using?

16.18.1

### What version of npm are you using?

9.2.0

### What operating system are you using?

CentOS7

### What version of SnailyCAD are you currently using?

1.42.0

### Describe the Bug

My CAD operations are very late and slow to load. But there is no error in the background. What is the situation?

### Expected Behavior

Quickly open CAD. Low operation delay

**Comment by SunlightKim** [comment]
What do you use to host your CAD? (VPS/VDS/Dedicated -> specs and if NGINX/Appache etc)

**Comment by jxckUK** [comment]
Also be helpful to know specifics such as which pages you are experiencing slow loading with and/or what actions you are performing that appear slow.

Could be related to https://github.com/SnailyCAD/snaily-cadv4/issues/1301.

**Comment by Dev-CasperTheGhost** [comment]
Probably not related to that linked issue. It’s most likely the way the CAD is hosted. You should use a proxy like NGINX or Apache to improve site traffic and performance
