### ISSUE TITLE
[BUG] Dispatch - Call 911 - RMB menu not working and freeze page

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#139]
### What version of Node.js are you using?

does not matter

### What operating system are you using?

does not matter

### Describe the Bug

When press RMB on unit placehlolder, page freeze

https://user-images.githubusercontent.com/4976837/140817010-14b06780-5ef0-493a-8487-3fbb200f5bd1.mp4

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
I'm not able to reproduce this error. What browser are you using and how many 10-codes do you have?

**Comment by pp2amd6** [comment]
1. Google Chrome, Version 95.0.4638.69 (Official Build) (64-bit)
2. Microsoft Edge, Version 95.0.1020.44 (Official build) (64-bit)

I have 7 records of 10 codes

**Comment by Dev-CasperTheGhost** [comment]
Seems to be related with https://github.com/radix-ui/primitives/issues/863. will be disabling Preact for now and see what happens in the future!
