### ISSUE TITLE
Developer View

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1391]
### Describe the feature

I've come to realise that I rely on /api-docs/ to retrieve things like department and division IDs as I use these within our scripts. 

I think it would be beneficial if there was a way to view this in the /admin/values/ screen so that I don't need to run API queries to get ID references. This could be hidden behind a user option if you feel it will clutter normal views.

The Unit and Civilian sections both put the ID in the URL so its much easier to retrieve when viewing them.

**Comment by Dev-CasperTheGhost** [comment]
I’m not sure what you mean

**Comment by jxckUK** [comment]
> I’m not sure what you mean

For example divisions:

![image](https://user-images.githubusercontent.com/48030374/211536181-fd7ddc2d-bb8e-4043-8dcf-cf65767456ba.png)

I need the division ID for "Command & Control" but I cannot view this quickly here, I would need to go to the API and retrieve the ID which is: ckxjneaub6457s41hao6czt39

**Comment by Dev-CasperTheGhost** [comment]
Ahh, like that. I could show the id no matter what tbh? It doesn’t have to be behind a dev flag

**Comment by jxckUK** [comment]
> Ahh, like that. I could show the id no matter what tbh? It doesn’t have to be behind a dev flag

Yeah that's great I just didn't know if you had any reservations about cluttering the table/UI. :D
