### ISSUE TITLE
Prune Users is selecting ACTIVE users?

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1392]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

v1.42.0 e6a8371

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/211541634-a0cd17b9-1a4e-488e-9060-ff0197a7441e.png)

### Expected Behavior

For it to select actual inactive users

**Comment by Dev-CasperTheGhost** [comment]
By ACTIVE you mean the whitelisted status?

**Comment by Legacy-TacticalGamingInteractive** [comment]
What do you mean?

![image](https://user-images.githubusercontent.com/25211271/211552065-3bbcb8fc-0660-4715-819a-410e567a8211.png)

These users are still actively using the CAD I think. Because even my name came up. Implying that I am going to be deleted if I prune these users. I think it is selecting active users to prune instead of inactive.

**Comment by Dev-CasperTheGhost** [comment]
It’s checks via the updateAt property of the user object.

I can add some more checks to see if other things were changed.

**Comment by Dev-CasperTheGhost** [comment]
Sure that’d work but that means the feature will not be available for some time

**Comment by SunlightKim** [comment]
That's alright. Not all updates can be done in 2 minutes, just take your time 😀 You can always just put a temporary warning.

**Comment by Dev-CasperTheGhost** [comment]
I've added a `lastSeen` tag to the user. This updates only when the user does a login. So that should work. Will try improve this in the future too

Right now, this won't work until the minimum days option has expired. iirc that's 30 days, so you may have to wait some time to get proper results in the prune

**Comment by Legacy-TacticalGamingInteractive** [comment]
Thats ok. Thank you! This should be more accurate. Phew.
Glad I didn't almost delete people that shouldn't be haha.
