### ISSUE TITLE
Unit Logs - Automatic Timeout - Logging

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1398]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

v1.42.0 e6a8371

### Describe the Bug

MANUAL 10-7 OFF DUTY logs in Unit Logs are working.
But...
AUTOMATIC Timeout 10-7 OFF DUTY does not log and are not working :(

Can we change this to be logged please?

_No response_

**Comment by Dev-CasperTheGhost** [comment]
the unit logs should appear now after an update. Will look into the latter, later today

**Comment by Dev-CasperTheGhost** [comment]
This should be fully fixed now!
