### ISSUE TITLE
/v1/incidents option consistency with /v1/911-calls

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1401]
### Describe the feature

Could we please get the switches available on 911-calls added to the incidents GET API call too. Including the new filter for IDs which has helped me cut out lots of inefficient code.

- [ ] department
- [ ] division
- [x] assignedUnit
- [x] includeEnded - this would show active and inactive incidents respectively the same behaviour as 911 calls

**Comment by Dev-CasperTheGhost** [comment]
`includeEnded` is already supported using `activeType`: 

- `active`: return only active incidents
- `inactive`: return only inactive incidents
- `all`: return all incidents

**Comment by Dev-CasperTheGhost** [comment]
> department
> division

Will not be supported because there's no direct saved item in the database. I could check where an assigned unit has these options though, but that could slow down the API request

**Comment by jxckUK** [comment]
> > department
> > division
> 
> Will not be supported because there's no direct saved item in the database. I could check where an assigned unit has these options though, but that could slow down the API request

That's okay! The most important one was understanding activeType and assignedUnit - I agree we don't want to add anything that slows the API request 😄

**Comment by Dev-CasperTheGhost** [comment]
Cool, will close this now then :)
