### ISSUE TITLE
activeCallId does not clear

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1402]
### What version of Node.js are you using?

N/A

### What version of npm are you using?

N/A

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

v1.42.0 baa3e8b

### Describe the Bug

A unit has an active call ID that no longer exists in the system and is not being replaced with the units only current active call:

![image](https://user-images.githubusercontent.com/48030374/211844368-a82dd023-0fcb-47e8-96e7-b30e4b05303d.png)

![image](https://user-images.githubusercontent.com/48030374/211844429-e765688f-71fd-4013-95a7-27ca3ca3f4b0.png)

![image](https://user-images.githubusercontent.com/48030374/211844935-368c81ac-9224-469b-9f59-43984afdfb4f.png)

### Expected Behavior

The users activeCallId should always be removed if the call itself is no longer available or is now closed/ended as it is no longer an "active" call.

This behaviour should be replicated for incidents.

**Comment by Dev-CasperTheGhost** [comment]
looks like this happened when a call is ended automatically via the inactivity timeout setting. Should be fixed now!

**Comment by jxckUK** [comment]
Is that the same for incidents or do we think incidents are unaffected? I haven't been able to test both!

(ps. thanks for fixing so fast!)

**Comment by Dev-CasperTheGhost** [comment]
All is fixed now!
