### ISSUE TITLE
`activeIncidentId` does not return a usable ID

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1415]
### What version of Node.js are you using?

N/A

### What version of npm are you using?

N/a

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

v1.43.0 2abe76b

### Describe the Bug

The `activeIncidentID` is not usable as the ID is not included in the data of `v1/incidents` and therefore can't be linked.

### Expected Behavior

`activeCallId` returns an ID that can be retrieved from `v1/911-calls` and it would be good if this was the same for incidents.

**Comment by Dev-CasperTheGhost** [comment]
When fetching incidents, make sure to fetch **all** incidents. By default it will only fetch `inactive` incidents. 

Use `/v1/incidents?activeType=all` or `/v1/incidents?activeType=active`

**Comment by jxckUK** [comment]
> When fetching incidents, make sure to fetch **all** incidents. By default it will only fetch `inactive` incidents.
> 
> Use `/v1/incidents?activeType=all` or `/v1/incidents?activeType=active`

I specifically use `incidents?activeType=active&includeAll=true&assignedUnit=` as that is the data I need to return but the IDs presented here do not correlate with the ID that is added to activeIncidentID hence the issue and I don't see how I can get around that?
