### ISSUE TITLE
Deprecated bugs and also really slow CAD since todays update f7d3043

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1418]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

[f7d3043](https://github.com/SnailyCAD/snaily-cadv4/commit/f7d304326af0cd522381f2302b9e7400092f7e8c)

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/212551703-37add081-ac16-4bea-89a6-bf9456cb359b.png)
![image](https://user-images.githubusercontent.com/25211271/212551786-be06ff12-9043-49bd-9d8d-61a280b40572.png)
![image](https://user-images.githubusercontent.com/25211271/212551901-4ffd4c0c-b919-4387-8db0-6ec06995907c.png)
![image](https://user-images.githubusercontent.com/25211271/212552029-1e8337b3-c513-4dee-98c4-039844fa92ac.png)

### Expected Behavior

Just reporting it

**Comment by Dev-CasperTheGhost** [comment]
Not a bug. Just a warning, has already been fixed.
