### ISSUE TITLE
Temporary Units

### ISSUE THREAD

**Issue by HenryCpr** [SnailyCAD/snaily-cadv4#1428]
### Describe the feature

Make dispatch have a option to Manually add Temporary Units through the dispatch panel and manage them like normal officers so dispatch can be standalone and other officers don't need to join the cad.

**Comment by jxckUK** [comment]
This could be quite powerful/useful actually, we sometimes get users that haven't yet registered on the CAD and the ability for dispatch to see a unit that isn't yet registered would be handy. Would be good if this was supported by the API to send additional details and create a temporary unit, before removing it after a period of inactivity or another API call.

**Comment by Dev-CasperTheGhost** [comment]
Will take a look into this. Sounds like a cool idea, just not 100% sure how to correctly implement yet

**Comment by HenryCpr** [comment]
Well so I was thinking there should be a button on this bar
![image](https://user-images.githubusercontent.com/75713727/213701658-e9d76398-4190-4783-afd4-a1c04e2c2c64.png)

Also When you click then it would show up something like this 

![image](https://user-images.githubusercontent.com/75713727/213702229-09489e71-4467-45d5-84c6-08dfaab6c332.png)

Then you will see that unit on the "Active Units" Panel

**Comment by jxckUK** [comment]
It would need to have support for call/incident attachment in my opinion and I suspect that's where it gets more complex. It also needs to have an assigned status, callsign and in most cases, you'd want to be able to set their division/department for whatever they are running as.

For full compatibility this would also need extending to EMS/FD and to have API routes so they can be created and deleted (via playerDropped) events as well as enriching the creation with details available to FiveM (eg. name and callsign based on source like Unit 11 for a user connected with the source ID 11).

They wouldn't need a user or civilian but the CAD requires those in some form so it would need to have some form of dummy record I suspect? Not sure, think that is where the complexity stems from.

**Comment by HenryCpr** [comment]
Well if the Temp officer was created It would just act like a real officer so you can assign calls and such but you can delete it by right clicking and such. I was thinking that this feature wasn't connected with FiveM as it would get more complex.

**Comment by Dev-CasperTheGhost** [comment]
I have some ideas in mind, it shouldn’t be *that* complicated

**Comment by HenryCpr** [comment]
10-4

**Comment by Dev-CasperTheGhost** [comment]
Technically this wont' be a "temporary unit" since even when it goes off-duty it will remain in the database to keep records data. 

Creating an officer/ems-fd requires creating a citizen - no way out from that. So what I can do is add a `isTemporary` Boolean field to `Officer` and `EmsFdDeputy`. This will allow admins to see what type of unit it is. 

What do you think @jxckUK @HenryCpr?

**Comment by jxckUK** [comment]
> Technically this wont' be a "temporary unit" since even when it goes off-duty it will remain in the database to keep records data.
> 
> Creating an officer/ems-fd requires creating a citizen - no way out from that. So what I can do is add a `isTemporary` Boolean field to `Officer` and `EmsFdDeputy`. This will allow admins to see what type of unit it is.
> 
> What do you think @jxckUK @HenryCpr?

That works - I had some concern about how much data we'd create here for example if a new user joins for ten minutes and the next five do the same, but unit purging and being able to tie the unit to an identifier (eg. Discord/License/Steam) would solve this! That way if the same player re-joins, I can use the API to collect the temporary unit previously created right? I could then delete temporary units if a permanent unit is created for that user.

This would be a **huge** feature for us to get, we'd essentially be a lot more accommodating to new players.

**Comment by HenryCpr** [comment]
It would be lovely if I could have a vc with Casper to explain my suggestion

**Comment by HenryCpr** [comment]
> Technically this wont' be a "temporary unit" since even when it goes off-duty it will remain in the database to keep records data.
> 
> Creating an officer/ems-fd requires creating a citizen - no way out from that. So what I can do is add a `isTemporary` Boolean field to `Officer` and `EmsFdDeputy`. This will allow admins to see what type of unit it is.
> 
> What do you think @jxckUK @HenryCpr?

Well I was thinking it didn't store on the database after deletion as it's temporary

**Comment by HenryCpr** [comment]
> > Well I was thinking it didn't store on the database after deletion as it's temporary
> 
> How the database works, that's not possible. It will be saved in the db until deleted

Ahh I see, but can you make it so dispatch can add it manually and a player login is not required

**Comment by Dev-CasperTheGhost** [comment]
> Ahh I see, but can you make it so dispatch can add it manually and a player login is not required

yes

**Comment by HenryCpr** [comment]
> > Ahh I see, but can you make it so dispatch can add it manually and a player login is not required
> 
> yes

Thanks

**Comment by Dev-CasperTheGhost** [comment]
>  able to tie the unit to an identifier (eg. Discord/License/Steam) would solve this! That way if the same player re-joins, I can use the API to collect the temporary unit previously created right? 

I'll add an `identifiers` column to the Officer and EmsFdDeputy table. This allows you to store an array of strings of identifiers such as fivem license, discord id, steam id, etc. 


> I could then delete temporary units if a permanent unit is created for that user.
I can also add the ability for admins to connect a user to a temporary unit via the admin dashboard?

**Comment by HenryCpr** [comment]
Lovely, but make the identifiers a optional field too :)

**Comment by jxckUK** [comment]
> I'll add an `identifiers` column to the Officer and EmsFdDeputy table. This allows you to store an array of strings of identifiers such as fivem license, discord id, steam id, etc. 

Perfect! 

> I can also add the ability for admins to connect a user to a temporary unit via the admin dashboard?

Yeah that sounds good.

**Comment by Dev-CasperTheGhost** [comment]
Note to self:

- Allow admins to add user to temporary unit (+ audit-logs)
- Allow admins to filter by temporary units (+ audit-logs)
- Allow dispatch* to create temporary units (+ audit-logs)
- Cleanup code

**Comment by Dev-CasperTheGhost** [comment]
This will be released in beta later today so you can test it out and provide feedback:)!
