### ISSUE TITLE
Invalid option on /citizen 911 creation

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1432]
### What version of Node.js are you using?

N/A

### What version of npm are you using?

N/A

### What operating system are you using?

N/A

### What version of SnailyCAD are you currently using?

v1.44.1 1734eda

### Describe the Bug

![image](https://user-images.githubusercontent.com/48030374/213167381-282af056-557e-4b25-91d9-6a56d85cf319.png)

As discussed in Discord, civilians have the option to open the modal which they can't do so it does nothing.

### Expected Behavior

Citizens should not have the option to manage a 911 call after creation and in this instance the option does not work anyway.

**Comment by Dev-CasperTheGhost** [comment]
Fixed now
