### ISSUE TITLE
Unable to see call history

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1439]
### What version of Node.js are you using?

N/A

### What version of npm are you using?

N/A

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

v1.44.1 1734eda

### Describe the Bug

Currently, call history only show active calls, I can't see any that are no longer available but they are retrievable from the API so they haven't been purged. 

### Expected Behavior

N/A - Should see the history.

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/213256600-c4eb4c12-7485-4b08-b8f5-736181a82540.png)

**Comment by Dev-CasperTheGhost** [comment]
I can't reproduce this? I can see all calls via the API and via the /call-history UI

**Comment by jxckUK** [comment]
Does it purge calls automatically if the timeout is set?

**Comment by Dev-CasperTheGhost** [comment]
calls don't get purged automatically

**Comment by jxckUK** [comment]
I'm so confused, something is removing 911-calls from my call history and its not someone removing them as that would appear in audit logs correct?

When I run `911-calls/?includeEnded=true?includeAll=true` I only see active calls, no historic records. But I can put an ID in and get an older calls directly.

**Comment by Dev-CasperTheGhost** [comment]
> 911-calls/?includeEnded=true?includeAll=true

Is incorrect syntax; this will probably not return correct results. Use `/911-calls?includeEnded=true&includeAll=true`

**Comment by Dev-CasperTheGhost** [comment]
Closing as this works correctly. Will add the purge 911 calls to audit logs
