### ISSUE TITLE
`extraFields` expansion

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1445]
### Describe the feature

Back again with an `extraFields` request, is it possible to have an option within the admin section of the client under the values to edit `extraFields` with a simple text box? As it is a jsonb field it would be best if this was just a plain text or code based input field?

At the moment I do this directly in the database but it would be helpful if I could give other users the ability to modify `extraFields`!

Additionally could we add this field to 911-calls, again would be required for this to be editable via partial PUT if possible.

### Additional Context

https://github.com/SnailyCAD/snaily-cadv4/issues/1373

https://github.com/SnailyCAD/snaily-cadv4/issues/1281

**Comment by Dev-CasperTheGhost** [comment]
So to recap: a textbox/json editor to edit `extraFields` on `Dvision value`, `Department value` and `911 calls`?

**Comment by jxckUK** [comment]
> So to recap: a textbox/json editor to edit `extraFields` on `Dvision value`, `Department value` and `911 calls`?

Division and Department values yes please! 😄

911 calls just needs the field added to the record structure, I don't see a requirement to add an editor as they won't be present in admin pages anyway.

**Comment by Dev-CasperTheGhost** [comment]
Sounds good!

**Comment by Dev-CasperTheGhost** [comment]
All done - for now the editor is a simple text field since most editors are not supported with Next.js. Will look again in the future to have a better code editor
