### ISSUE TITLE
[FEATURE REQUEST] FiveM Script Pack

### ISSUE THREAD

**Issue by RKMMods** [SnailyCAD/snaily-cadv4#145]
### Describe the feature

Please include FiveM Script in-game to use with this CAD. Here are some examples below:

Phone UI to Call 911

MDT UI for Officers to use

Dispatch Livemap for attaching units

Impound Script/dv script that syncs to the CAD

Duty Script that syncs to the CAD

**Comment by Dev-CasperTheGhost** [comment]
I don't have the expertise in creating scripts for FiveM, though I will create a simple script like there is for v3 (`/calltow`, `/calltaxi`, `/call911`). 

I think such scripts you mentioned should be created by the community itself too since it's not the same for every community.
