### ISSUE TITLE
CAD Crash due to Invalid Fines or something

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1454]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

1.44.4

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/213864759-3b7c02ff-ead4-4283-8675-0bc42f2e2fbb.png)

### Expected Behavior

Continued uptime. Random crashed.

**Comment by Dev-CasperTheGhost** [comment]
this it the same error as previously that crashed your CAD. the weird thing is, this only happens on your system :/. What version of nodejs are you using?

**Comment by Legacy-TacticalGamingInteractive** [comment]
16.13.1 node js

**Comment by Legacy-TacticalGamingInteractive** [comment]
when I turn on CAD i see this as well 
![image](https://user-images.githubusercontent.com/25211271/213866867-f1c01d38-8a74-4a27-80d1-233b91aa31b5.png)

**Comment by Dev-CasperTheGhost** [comment]
Is it possible for you to upgrade to a higher version of node?

**Comment by Legacy-TacticalGamingInteractive** [comment]
It is the latest version it wont let me update any further

**Comment by Dev-CasperTheGhost** [comment]
Download the latest from: https://nodejs.org/en/

**Comment by Legacy-TacticalGamingInteractive** [comment]
Alright I've installed it suppose ill restart CAD now and hope for the best? lol

**Comment by Dev-CasperTheGhost** [comment]
Yeah, let me know when it happens again. This error message is also so annoying, it doesn't provide anything useful :/

**Comment by Dev-CasperTheGhost** [comment]
Closing since this should've been fixed now. It shouldn't crash the API if there's an error
