### ISSUE TITLE
Extend paired unit logic to EMS/FD

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1458]
### Describe the feature

The paired unit logic is fantastic and used often in my server, could we extend it to support EMS/FD pairings as well?

**Comment by Dev-CasperTheGhost** [comment]
I can look into this this week

**Comment by Dev-CasperTheGhost** [comment]
Started on this, not 100% sure on some things yet so still experimenting before fully committing to that solution.
