### ISSUE TITLE
Accepting/Declining Civilian 911s

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1459]
### Describe the feature

It would be great if incoming 911 calls (from the /citizens page only, not API created) were accepted/declined before being added to the dispatch section. This should be an optional feature and should only be available when a dispatcher is active or when signal 100 is enabled.

**Comment by Dev-CasperTheGhost** [comment]
How would the UI work before the call is accepted?

**Comment by jxckUK** [comment]
> How would the UI work before the call is accepted?

The call would be submitted, civilian wouldn't get a response as to status so that would remain unchanged.

On the dispatch dashboard incoming calls from civilians would have the state "Pending" until approved and wouldn't count as an "active" 911 for the API etc, and would allow dispatchers time to make changes and categorise the call urgency, type etc. Once "Accepted" it would come into the system as a new active 911 call, similar to how it works now.

**Comment by Dev-CasperTheGhost** [comment]
![image](https://user-images.githubusercontent.com/53900565/214110583-9d89befd-eef1-442f-8d82-a9eef5f754cd.png)

**Comment by Dev-CasperTheGhost** [comment]
![image](https://user-images.githubusercontent.com/53900565/214318310-9a750b88-7632-4994-b164-1a5906731c1b.png)
