### ISSUE TITLE
[improvement] Disable HTML Form Input Autocomplete and Autofill

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#146]
### Describe the feature

Autocomplete overrides the suggested data.
![kiss_10kb 1636718922 1](https://user-images.githubusercontent.com/4976837/141464848-1e9219d2-82b9-4fb9-8d29-3533865c1f2e.png)

Disable via autocomplete="off"
https://www.w3schools.com/tags/att_form_autocomplete.asp

**Comment by Dev-CasperTheGhost** [comment]
Fixed 🎉!

**Comment by pp2amd6** [comment]
Autofill in Chrome still work. I found this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164

**Comment by Dev-CasperTheGhost** [comment]
it should be disabled now, @pp2amd6
