### ISSUE TITLE
Announcement if Civilist has Flags.

### ISSUE THREAD

**Issue by Justin2211** [SnailyCAD/snaily-cadv4#1461]
### Describe the feature

I would have a suggestion for the future.
That e.g. if an officer searches a civilian in CAD under Officer -> Name Search, and the civilian has flags like "Armed" or "Dangerous". That these flags are played as sound. 

So as an example:
Officer enters a name under Name Search. Then he finds the civilian, clicks on it, and then the entered flags are read out.

**Comment by Dev-CasperTheGhost** [comment]
Flags might be to excessive, but maybe announcing if the citizen has a warrant or is pronounced dead

**Comment by Justin2211** [comment]
So I mean the flags that are set under Admin->Manage Citizen flags.
That these would simply be read out via text to speech.
So that would be my idea.

**Comment by Dev-CasperTheGhost** [comment]
Yeah, no I know. Still I think it’s to much to pronounce all the flags possibly connected to a citizen

**Comment by Justin2211** [comment]
Yes I understand. Maybe under Admin->Manage Citizen flags at the respective values, toggle switches could be used to determine whether the respective tag is read out.
