### ISSUE TITLE
Warning: Potential Security Risk Ahead when accessing the CAD

### ISSUE THREAD

**Issue by Creizy** [SnailyCAD/snaily-cadv4#1463]
### What version of Node.js are you using?

18.2.0

### What version of npm are you using?

8.9.0

### What operating system are you using?

Ubuntu 20.04

### What version of SnailyCAD are you currently using?

1.44.7 - 577a518

### Describe the Bug

Was originally reported on discord: https://discord.com/channels/792479048457912360/903877466572087347/1067214697847341147

I want to add more info. I have the same problem, and when trying to access the CAD, im getting the same error, as well as redirected either to home page of my website, or completely different subdomain.
Wasn't having this issue before whilst on v1.44.2

For me the issue is on any browser.

https://user-images.githubusercontent.com/100074335/214174720-f47a0c83-ed3e-4a78-97c7-366f08f47db5.mp4

On mozzila for example, Instead of redirecting, im getting this 
![image](https://user-images.githubusercontent.com/100074335/214175056-94090547-ccd9-4fa7-952b-8408d4da1fb5.png)

EDIT: Very weird, every browser gets different things. Indexing part I thought was me setting up proxy wrong or cache, however I checked everything. And before I updated, I was on 1.44.2, didn’t have any issues. This honestly is weird. 

### Expected Behavior

CAD accessible as usual, fix of potential security risk

**Comment by Dev-CasperTheGhost** [comment]
Let’s keep this to Discord only because I’m not sure whether this is something I can fix.
