### ISSUE TITLE
Dispatching through LEO/EMS/Fd

### ISSUE THREAD

**Issue by ALamX** [SnailyCAD/snaily-cadv4#1468]
### What version of Node.js are you using?

latest

### What version of npm are you using?

latest

### What operating system are you using?

Windows

### What version of SnailyCAD are you currently using?

1.44.7?

### Describe the Bug

When active and assigned to a call, the view call modal becomes the one a dispatcher sees, so the deputy is able to end the call and assign additional units while a dispatcher is on-duty.

### Expected Behavior

Full control over units through dispatching and only view permissions for a deputy/officer

### To Reproduce

Go on duty, create call and assign self to call. Open manage call modal through officer/deputy

**Comment by Dev-CasperTheGhost** [comment]
This is expected behaviour if there are 0 active dispatchers. Will take a look
