### ISSUE TITLE
Missing drop down items

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1470]
### What version of Node.js are you using?

N/A

### What version of npm are you using?

N/A

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

v1.44.7 577a518

### Describe the Bug

Some users report that drop down options are not available but when I check the items are there for me so it seems like some client side bug?

### Expected Behavior

It should show what is visible in the first picture, which is the screenshot I took at the same time as the user submitted the second screenshot to me.

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/214684656-6d89e2df-9360-4888-a3d3-831ba56199aa.png)
![image](https://user-images.githubusercontent.com/48030374/214684671-af83bdd9-4e99-4d60-afc2-6d5d8a83787e.png)

**Comment by Dev-CasperTheGhost** [comment]
Values are cached for some time, so if these are new values this is expected

**Comment by jxckUK** [comment]
> Values are cached for some time, so if these are new values this is expected

They are not new values no, they've been in for months.
