### ISSUE TITLE
Possibility to create vehicle without having to specify Citizen

### ISSUE THREAD

**Issue by Justin2211** [SnailyCAD/snaily-cadv4#1475]
### Describe the feature

I would like to be able to create vehicles with license plates without having to specify a citizen, because you don't always know who owns the vehicle.

Sincerely

**Comment by Dev-CasperTheGhost** [comment]
Where should this possible? I'm not sure why this should be implemented...

**Comment by Justin2211** [comment]
Hi, for example when you see a vehicle (Possibly also from an NPC) and you want to set notes for that.
Or if a vehicle with a certain license plate behaves in a conspicuous manner, e.g.

Sincerely

**Comment by Justin2211** [comment]
Addendum: NPC's are always other vehicles but e.g. there is a vehicle which is not registered and no owner is stored. That you can then create the vehicle itself.

**Comment by Dev-CasperTheGhost** [comment]
> Hi, for example when you see a vehicle (Possibly also from an NPC) and you want to set notes for that.
> Addendum: NPC's are always other vehicles but e.g. there is a vehicle which is not registered and no owner is stored. That you can then create the vehicle itself.

This is already possible. Enable: 
![image](https://user-images.githubusercontent.com/53900565/215134563-755e13e8-f88e-4be1-9f6f-0a6fa19f1f20.png)

**Comment by Justin2211** [comment]
Yes exactly, I have already activated that. But I mean when you create a vehicle, you have to specify an owner.
If this "constraint" would be omitted, it would be great.
