### ISSUE TITLE
Feature: Sort by Date Range - Unit Hours

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1479]
### Describe the feature

For the purposes of Payroll. 

Department command are asking if we could also add an ability to not just see total hours and last online but how many hours they had during a specific date range. Like the last 2 weeks for example. So they can pay them in game for their hours on duty.

Is it possible?

**Comment by Dev-CasperTheGhost** [comment]
Should be possible, yeah. Will look into this soon

**Comment by Dev-CasperTheGhost** [comment]
Note to self: https://github.com/prisma/prisma/discussions/11443

**Comment by Legacy-TacticalGamingInteractive** [comment]
Example:
![image](https://user-images.githubusercontent.com/25211271/215180724-5ccd28db-cf61-4ad5-9d3a-e239b9551743.png)

**Comment by Dev-CasperTheGhost** [comment]
![image](https://user-images.githubusercontent.com/53900565/215253394-5f7484a0-d705-4db6-bfd6-7346de97ec4f.png)
