### ISSUE TITLE
Request Failed With Status Code 404

### ISSUE THREAD

**Issue by MKingPT** [SnailyCAD/snaily-cadv4#1497]
### What version of Node.js are you using?

18.13.0

### What version of npm are you using?

9.4.0

### What operating system are you using?

Windows Server

### What version of SnailyCAD are you currently using?

1.46.2 - d9ecfe4

### Describe the Bug

I can start SnailyCAD normally but when i try to log in or register I always get the same error: 

Request Failed With Status Code 404 (Request Failed With Status Code 404)
An unexpected error occurred

I can´t understand what it is that i'm missing

### Expected Behavior

It should accept new users from Registration and Log In already registered useres.

**Comment by Dev-CasperTheGhost** [comment]
You’re missing the /v1 for the NEXT_PUBLIC_PROD_ORIGIN

https://cad-docs.caspertheghost.me/docs/installations/methods/standalone#31-env-info
