### ISSUE TITLE
Maximum BOLO Amount

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1499]
### Describe the feature

Would be nice to have this as well. Because I'm tired of seeing 6 pages of BOLOS lol.

Or maybe the inactive bolo timeout isnt working (we have it set to 20 minutes) but it also seems that it goes back to default whenever we update CAD so maybe its not saving at all

**Comment by Dev-CasperTheGhost** [comment]
Looks like this is a bug, isn't saving for me either. Will have to investigate soon

**Comment by Dev-CasperTheGhost** [comment]
Fixed!
