### ISSUE TITLE
[improvements] Update 911 call block when record is deleted

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#150]
### Describe the feature

When a 911 call is added, the block is automatically updated and the record is added without reloading the page.
When the 911 call is removed, the entry from the block is not removed, although it should.
![kiss_13kb 1636746031 1](https://user-images.githubusercontent.com/4976837/141525530-53ab80ba-6466-4e0a-a3bf-b43d448262ae.png)

**Comment by Dev-CasperTheGhost** [comment]
This is actually a bug 😅!
