### ISSUE TITLE
Custom CSS/HTML Support

### ISSUE THREAD

**Issue by Carson2121** [SnailyCAD/snaily-cadv4#1517]
### Describe the feature

I think if you add custom CSS and or HTML support for front end devs to make the cad more customizable and use like a template system. I feel like people can hire devs for cheap to get their cad with how they like it.

**Comment by Dev-CasperTheGhost** [comment]
This will not work since SnailyCAD uses TailwindCSS to style its components. There are no styles to easily overwrite.
