### ISSUE TITLE
Support Multiple discord servers with the bot

### ISSUE THREAD

**Issue by Carson2121** [SnailyCAD/snaily-cadv4#1518]
### Describe the feature

The bot should be able to be used in multiple discord servers because most servers use more than one discords for their server, like one community discord, and one leo server. that way you dont need to use another bot to sync roles, ect.

**Comment by Dev-CasperTheGhost** [comment]
This is now supported. Docs have been updated, see: 

![image](https://user-images.githubusercontent.com/53900565/218128016-a6fe2593-ecbf-48d3-a988-a7deaff17eb5.png)
