### ISSUE TITLE
Courthouse and Manage Warrants Features/Bugs

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1527]
### Describe the feature

- [x] Could we have the Manage Warrants option enabled via Discord Courthouse role? Right now I only see an option for Expungement Requests and Name Change requests as permissions under it. On the Admin panel when setting up Discord Role permissions.

- [x] Also reporting a bug. Manage Warrants permission under User Permissions is not working for the Pending Warrants page. Courthouse members cannot see the Pending Warrants tab at all. They can only see Name Change and Expungement Requests. I have someone who has the permission for their user as well but they cannot see the Pending Warrants page. They can only see the inactive warrant on a citizens profile in Dashboard and thats it.

- [ ] Inactive Warrants - can these be hidden by default from everyone? Officers are confusing this and they think its an active warrant. (They are stupid, its FiveM after all) so maybe it should be entirely hidden when its inactive and only show in Dashboard when its active.

**Comment by Dev-CasperTheGhost** [comment]
Permissions issue has been fixed. You'll have to grant the user `ManagePendingWarrants`/`Manage Pending Warrants` permission:

![image](https://user-images.githubusercontent.com/53900565/218524300-8e37341d-c0e9-47a8-a410-ca0d398a3386.png)

**Comment by Dev-CasperTheGhost** [comment]
> Inactive Warrants - can these be hidden by default from everyone? Officers are confusing this and they think its an active warrant. (They are stupid, its FiveM after all) so maybe it should be entirely hidden when its inactive and only show in Dashboard when its active.

Where are these shown exactly again?

**Comment by Legacy-TacticalGamingInteractive** [comment]
When you search a criminal by name. But I think its fixed now? I don't see Inactive Warrant on their character anymore from LEO Dashboard which is good.

---

Is it possible to also add Manage Courthose tab here instead of it only being accessible from Admin panel?
![image](https://user-images.githubusercontent.com/25211271/219125868-375aafd6-ff5d-4caa-8476-76c846e0359a.png)

**Comment by Dev-CasperTheGhost** [comment]
> Another Question:

> Is it possible to also add Manage Courthose tab here instead of it only being accessible from Admin panel?

Sure, will try add this later tonight or tomorrow!

**Comment by Dev-CasperTheGhost** [comment]
The link has been added! Will close this issue for now since that last item seemed fixed
