### ISSUE TITLE
Cloudflare continuing to return Error 520, but for a different reason.

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#153]
### What version of Node.js are you using?

v16.13.0

### What version of npm are you using?

8.1.3

### What operating system are you using?

Ubuntu Server 20.04

### Describe the Bug

When using Cloudflare's proxying and SSL service with the API, [Cloudflare returns](https://cdn.discordapp.com/attachments/625715899353268254/910092477040578610/unknown.png) `Error 520: Web server is returning unknown error`

This doesn't allow the CAD to connect to the API, with the [console returning the same Error 520](https://cdn.discordapp.com/attachments/625715899353268254/910091652239097886/unknown.png). When connecting to the API, [it _does_ return a `200 OK`](https://cdn.discordapp.com/attachments/625715899353268254/910092218457542656/unknown.png), but that isn't sufficient for Cloudflare.

### Expected Behavior

A displayed webpage, [as such](https://cdn.discordapp.com/attachments/625715899353268254/910093385925296148/unknown.png).

Due to how Cloudflare (in my experience) checks to see if your server is responding, it requires a displayed web page, or, it responds with an Error 520. 

### To Reproduce

It would be kind of hard to reproduce this. But, if you wish to try, you're going to need a valid domain, a Cloudflare account, Kemp LoadMaster (I have the free tier), and a lot of time on your hands. But, I did find why the issue is occurring, so, probably no need for that.

**Comment by Dev-CasperTheGhost** [comment]
instead of returning a 200 response code, It will return some simple JSON. Let me know if this issue is resolved! If not, please re-open this one :).

**Comment by Thomaswill1** [comment]
The issue is still persisting.

**Comment by Dev-CasperTheGhost** [comment]
Are you able to contact Cloudflare support? There isn't much I can do without the exact reason why it's not working.

**Comment by Thomaswill1** [comment]
As I have provided in the [example above](https://cdn.discordapp.com/attachments/625715899353268254/910093385925296148/unknown.png), there needs to be a displayed webpage.

**Comment by Dev-CasperTheGhost** [comment]
> 
> 
> As I have provided in the [example above](https://cdn.discordapp.com/attachments/625715899353268254/910093385925296148/unknown.png), there needs to be a displayed webpage.

This looks like a response of `200` and `Content-Type: text/html`, correct?

**Comment by Thomaswill1** [comment]
It is an HTML file, yes. It doesn't really matter how it's done, or what it says, it just needs a webpage.

**Comment by Dev-CasperTheGhost** [comment]
> 
> 
> It is an HTML file, yes. It doesn't really matter how it's done, or what it says, it just needs a webpage.

Will take another look soon!

**Comment by Dev-CasperTheGhost** [comment]
Can you update your local and test again? @Thomaswill1

**Comment by Thomaswill1** [comment]
It seems Linux has changed some ports around. What is the default port for the API?

**Comment by Dev-CasperTheGhost** [comment]
8080

**Comment by Thomaswill1** [comment]
That doesn't seem to be working... By chance, do you have the API set to only respond to GET/POST requests from only the CAD?

**Comment by Dev-CasperTheGhost** [comment]
That's not going to be possible.

**Comment by Thomaswill1** [comment]
What do you mean by that?

**Comment by Dev-CasperTheGhost** [comment]
There are other methods like PUT, DELETE and PATCH that are used in the API. These are essential to be used. I cannot simply not use them

**Comment by Thomaswill1** [comment]
Ah, I see the misunderstanding. What I meant was is, does the API only respond to requests from the CAD? Instead of requests from anywhere.

**Comment by Dev-CasperTheGhost** [comment]
oh, It should be able to respond from anywhere 😅. Try setting the `CORS_ORIGIN_URL` to `*`

**Comment by Thomaswill1** [comment]
Hmmm. I already have the `CORS_ORIGIN_URL` set to be wildcarded.

**Comment by Dev-CasperTheGhost** [comment]
hm, weird. I don't think I can help any further tho, to me this looks like an issue on Cloudflare's end?

**Comment by Thomaswill1** [comment]
I don't think it's an issue with Cloudflare, as I have other servers running, and currently using Cloudflare. The only service that returns a 520 is just the API. I'll do some digging around to see if this is user error. I've checked it like a million times at this point though.

**Comment by Thomaswill1** [comment]
May I send you a DM on Discord of my .env file to see if I may have miss configured something?

**Comment by Dev-CasperTheGhost** [comment]
Sure
