### ISSUE TITLE
Return Partial Bolos From API Request

### ISSUE THREAD

**Issue by Denominator765** [SnailyCAD/snaily-cadv4#1533]
### Describe the feature

It would be useful if you could create a bolo with a partial plate, and have that bolo returned when making an API request with the full plate.

**Comment by Dev-CasperTheGhost** [comment]
This is already possible via the UI. When your start typing it will show available vehicles with that plate. 

It is not possible to do that via 1 API request

**Comment by Denominator765** [comment]
Ok. I assumed it was possible since it already works in the inverse. (Doing /bolos?query=68p returns the bolo for plate "68P0Y984")

**Comment by Dev-CasperTheGhost** [comment]
that's not the same though. bolos?query= is searching for existing BOLO's. The other API route is for creating BOLO's

**Comment by Denominator765** [comment]
Sorry, I must not have stated that the right way. I was looking for creating a BOLO in the UI with a partial (say "XLT"), and being able to make an API request of /bolos?query=XLT573 and receive back the BOLO created with the partial. Essentially, I am modifying my install of the sna-alpr and wk_wars2x such that, the WRAITH plate reader does an automatic request for each plate it reads to check for BOLO's, and I am trying to get it so that, should a BOLO of a partial be created, WRAITH will react to any plate that matches the partial.

**Comment by Dev-CasperTheGhost** [comment]
Can you share code possibly? I'm not 100% certain what you're trying to do

**Comment by Denominator765** [comment]
I am looking for /v1/bolos?query=XLT573 to return a BOLO created for plate "XLT".

**Comment by Dev-CasperTheGhost** [comment]
Will try take a look today then. So will re-open this issue

**Comment by Denominator765** [comment]
Sorry for the confusion.

**Comment by Dev-CasperTheGhost** [comment]
No worries

**Comment by Dev-CasperTheGhost** [comment]
This is actually already possible: 
<img width="737" alt="Screenshot 2023-02-16 at 15 35 38" src="https://user-images.githubusercontent.com/53900565/219394173-f51dc165-c09c-4a99-b1cc-b4bd8f6fdd81.png">

**Comment by Denominator765** [comment]
The "contains" allows you to do a partial query on a full plate BOLO (so /bolo's?query=XFT will return a bolo for XFT572), but I am asking about the inverse (where /bolo's?query=XFT572 will return a bolo for XFT).

Now seeing the specific section of code, I can see that that would require more processing to pull off though.

**Comment by Dev-CasperTheGhost** [comment]
I'm still not sure what you mean with this. You want to provide a FULL plate (XFT572), but only want a part of that plate returned?

**Comment by Denominator765** [comment]
Correct. Let's say someone calls in a report of a car, but they only got a partial of the plate (could read XFT, but wasn't sure the rest of the plate), it would be useful to be able to create the BOLO with only XFT, and get the return for that BOLO when an officer has attained the rest of the plate (XFT572).

**Comment by Dev-CasperTheGhost** [comment]
That's already possible though?

**Comment by Denominator765** [comment]
Through the UI yes, but not through the /bolo's?query API.

**Comment by Dev-CasperTheGhost** [comment]
Right, but how would this even be supported via the API? There is no way for a user to "select" the correct plate 🤔

**Comment by Denominator765** [comment]
To be fair, a user of the API would have to do any handling of partials on their end. So, for this instance, an officer receiving a partial BOLO would then have to also check if there is a matching vehicle description, and approach the vehicle with the knowledge that it isn't a 100% match. This could be mitigated with another parameter (ie. "/bolo's?query=XFT572&includePartials=true", with includePartials being defaulted to false) to allow users of the API to choose if they want to deal with the extra complexity of partial BOLOs.

**Comment by Dev-CasperTheGhost** [comment]
Feel free to create a PR for this, I'm not sure how this should be handled

**Comment by Denominator765** [comment]
Alright. I will take a look this evening after work. I'll attach a video as well showing the use-case for it.

**Comment by Dev-CasperTheGhost** [comment]
👍; will review it tomorrow

**Comment by Denominator765** [comment]
So I never worked with TypeScript or Prisma before, but now having done my research, I see why this is such a difficult ask. Prisma does not currently support the functionality that would be necessary to perform this action. If we so wanted, there are 2 options that I can think of to achieve this functionality, each with its own drawbacks.

Option 1: I could replace the findMany with a manually created database query through prisma.%queryRaw. Of course, this manually created query would be PostgreSQL specific, and so would not be compatible with the other databases supported by Prisma.

Option 2: I pull all BOLOs and manually check each one to see if the BOLO plate matches as a substring of the query. Aside from the cost of having to process every single entry in the database, this would also be difficult to integrate with searching the other columns and implementing the take, skip, and orderBy correctly.

To be fair, I could also just update my sna-alpr to request all bolos and just do the processing on my end to find if at least one entry matches what I am looking for.

**Comment by Dev-CasperTheGhost** [comment]
Yeah, I think it's easier if you'd do that locally in the script. So get all the bolos and filter that way in the script :)

**Comment by Denominator765** [comment]
If Prisma ever adds that filter condition, that might be a nice to have in the API, but at this point, I completely agree in order to preserve the sanctity of the publicly available codebase.

**Comment by Legacy-TacticalGamingInteractive** [comment]
@Denominator765 aside from your partial plate stuff did you ever modify Wraith properly to automatically read instead of with locking on manually?
