### ISSUE TITLE
Business Fines & Features

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1538]
### Describe the feature

• Ability to search Businesses from Dashboard
• Ability to fine a Business
• Business Records (tickets/fines/notes for Courthouse/Officers to see about business)

This is useful for things like when a server has penal codes for business violations. Like health code violations, building codes, open after hours fines, serving illegal alcohol, operating without a Business license etc. As well as if someone wants to sue a business in RP through the courts like say they slipped on ice in winter in front of business.

**Comment by Dev-CasperTheGhost** [comment]
Finished the business search in development. Going to work on the business records next. There is a chance that I will release the business search before the Business records are finished :).

**Comment by Dev-CasperTheGhost** [comment]
Business search has been merged. Will work on business records further

**Comment by Legacy-TacticalGamingInteractive** [comment]
Awesome progress so far! I'm patiently waiting for next update when its all done!
