### ISSUE TITLE
Support for Multiple Discord Roles

### ISSUE THREAD

**Issue by WhitigolProd** [SnailyCAD/snaily-cadv4#1539]
### Describe the feature

When setting Discord Roles in CAD Settings, it would be nice to have support for using multiple roles for the same setting.

Not sure if this is on the plan board already, feel free to remove if it is, or has already been requested.

Finally getting back into using the CAD for a community I'm helping with and really like what's been done so far!

**Comment by Dev-CasperTheGhost** [comment]
In what context? Provide a bit more info where this isn’t yet supported

**Comment by WhitigolProd** [comment]
Ah okay. Just notice now that this is supported. I was trying it with Admin and it doesn't work. So I guess my suggestion would be to support multiple roles for Admin.

**Comment by Dev-CasperTheGhost** [comment]
There was a reason I didn’t want to do this, I’ll check tomorrow

**Comment by WhitigolProd** [comment]
Sounds good. I guess my view on it is; in many communities, there are several different admin roles. Which some of them should 
in cases give access to admin permissions in CAD.
