### ISSUE TITLE
License Points

### ISSUE THREAD

**Issue by Leveecius88** [SnailyCAD/snaily-cadv4#1540]
### Describe the feature

I think it would be nice and make things a bit more realistic to add a points system for Licenses.  Each Penal code can be set for a certain number of points per infraction.  After say 20 points, the system can flag for suspension or revocation of license.

**Comment by Creizy** [comment]
This has been discussed on discord some time ago as well. https://discord.com/channels/792479048457912360/1042892617798647838

**Comment by Dev-CasperTheGhost** [comment]
I’d guess this should also be a toggable feature?

**Comment by Creizy** [comment]
yea probably. would give CAD owners a choice if they want to use it or not

**Comment by Leveecius88** [comment]
Just like the optional Jail and Bail times, could just make it a checkbox

**Comment by Dev-CasperTheGhost** [comment]
Note to self: https://discord.com/channels/792479048457912360/1042892617798647838
