### ISSUE TITLE
Webhooks besides discord

### ISSUE THREAD

**Issue by dexslab** [SnailyCAD/snaily-cadv4#1543]
### Describe the feature

So  basically i would like to receive webhooks that are not automagically converted to Discord. Just a straight JSON webhook with the data for when those particular objects are created.

**Comment by Dev-CasperTheGhost** [comment]
Where and how would this be used @dexslab?

**Comment by dexslab** [comment]
So like a ticket is made for a person speeding. The data from the ticket would be sent to the webhook in json. Then I could take the fine data and create an esx billing request for the fine amount so the user can then pay it after it's paid I can post back to the CAD to say it was properly paid

**Comment by Dev-CasperTheGhost** [comment]
So an option for owner* to provide a Webhook URL for each webhook type, this would simply send the respective data, right?

Would this send the raw data, or somewhat already formatted data such as units, etc?

**Comment by dexslab** [comment]
It would basically send the raw data as json like hitting the API request. Then owner would be able to parse and use what info needed. Like fine amount and character being fined.
