### ISSUE TITLE
Updating sometimes results in newer version (in package.json) than the latest release

### ISSUE THREAD

**Issue by WhitigolProd** [SnailyCAD/snaily-cadv4#1548]
### What version of Node.js are you using?

N/A

### What version of npm are you using?

N/A

### What operating system are you using?

Windows

### What version of SnailyCAD are you currently using?

1.48.2

### Describe the Bug

When updating the CAD, if the value in the `package.json` is newer than the latest release, in the Admin dashboard, this will result in displaying the (update available) message. And not showing values in the "what's new" area.

### Expected Behavior

When updating the CAD, regardless of version, if it's greater than or equal to the latest version, the "new version" message in the admin dashboard should not be shown.

### To Reproduce

No steps to reproduce since it's self explanatory, but I'll use this field to add some additional notes.

Not sure if this was intended or not, so feel free to let me know if it is! I just noticed that when updating, the repo had a `1.48.3` as it's latest version, instead of matching the latest release (`1.48.2`).

**Comment by Dev-CasperTheGhost** [comment]
Can you elaborate? Not exactly sure what you mean

**Comment by WhitigolProd** [comment]
So, I just updated the CAD today. When updating, the CAD updated to the latest files in the repo. But since the `package.json` in the repo shows `v1.48.3` instead of the latest release (`v1.48.2`), inside the admin dashboard on the CAD shows that there's still an update available.

Not sure if this was intended, or maybe a caching issue?

**Comment by WhitigolProd** [comment]
Line here: https://github.com/SnailyCAD/snaily-cadv4/blob/272b0144a5654b721e1dde13ba2f25396e0a1d3b/package.json#L4

**Comment by Dev-CasperTheGhost** [comment]
this is not a bug; I just forgot to release it on GitHub. Will probably release 1.48.4 today or tomorrow instead
