### ISSUE TITLE
Vehicle Trim Levels

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#1549]
### Describe the feature

For more realism, admin's can define trim levels for vehicles in the Manage Vehicles menu. When registering a vehicle, citizens and officers can select the trim level of their vehicle.

This can especially helpful for officers because they could label their vehicle as unmarked, marked, or ghost.

**Comment by Dev-CasperTheGhost** [comment]
This is already supported. You can use `Vehicle Flags`.

**Comment by Thomaswill1** [comment]
Trim Levels and Flags are different. Trim Levels describe the equipment and performance of a vehicle while flags are more for pointing things out.
Example of Trim Levels: The Model 3 has 3 trim levels, Standard, Long Range, and Performance.
I could not list all vehicle trim levels in flags because all vehicles would have access to trim levels of other vehicles. A Ford Explorer doesn't have a trim level of "Performance" because it's trim level is "ST".

**Comment by Dev-CasperTheGhost** [comment]
This is editable by the citizen then?

**Comment by Thomaswill1** [comment]
Sorry for not responding.

Trim Levels shouldn't be in their own menu but added to the Manage Vehicles menu because not all cars have the same trims. It should be added to each car individually, or at least, not let all cars have access to them.
