### ISSUE TITLE
Updating causes custom sounds to be replaced.

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#1551]
### What version of Node.js are you using?

16.13.2

### What version of npm are you using?

8.1.2

### What operating system are you using?

Windows

### What version of SnailyCAD are you currently using?

1.49.0

### Describe the Bug

When you update the CAD to a newer version, custom sounds will be replaced with default sounds.

### Expected Behavior

Ignore custom sounds or not try and install sounds during update, only first time install.

### To Reproduce

1. Install CAD
2. Replace sounds and test
3. Update CAD
Sounds will now be replaced

**Comment by Dev-CasperTheGhost** [comment]
These are already in the gitignore so should not be overwritten. There isn't much I can do about this :/
