### ISSUE TITLE
vehicleNotFound error when assigning patrol vehicle

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#1552]
### What version of Node.js are you using?

16.13.2

### What version of npm are you using?

8.1.2

### What operating system are you using?

Windows

### What version of SnailyCAD are you currently using?

1.49.0

### Describe the Bug

When going 10-8 as an officer, assigning a Patrol vehicle causes a `vehicleNotFound` error, and will not proceed. Autofill works, and the vehicle is in the CAD's Emergency Vehicles menu. This will only happen to some vehicles, not all.
![image](https://user-images.githubusercontent.com/34800953/221386391-20cf64da-f6b0-4e8e-b9ce-f989fa32692c.png)

### Expected Behavior

All vehicles that have been listed by admins in the CAD's settings should be found.

**Comment by Dev-CasperTheGhost** [comment]
This somewhat expected behavior. That emergency vehicle's departments list doesn't include the department of that officer.   

I will make sure this isn't possible when searching for the vehicle
