### ISSUE TITLE
Vehicle Model Years

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#1567]
### Describe the feature

Some cars have a ton of model years. Instead of having to make a new vehicle entry for every model year, add years to one vehicle to label it as that model year. May work like vehicle trims, but instead of a list that is maintained by CAD admins, it could just be a predefined list of years, from 1960 to current.

**Comment by Dev-CasperTheGhost** [comment]
I see no point in this? It will still require the admin to do the same - or even more - work?

**Comment by Thomaswill1** [comment]
Yeah, now thinking about it, I realized that it could create more work for admins and could conflict with vehicle trims since they aren't always the same from year to year.
