### ISSUE TITLE
Vehicle Trim Improvements

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#1572]
### Describe the feature

Only 2 improvements

1. Only 1 vehicle trim can be assigned to a vehicle as a civilian registering a vehicle.
2. Put the Vehicle Trims menu in the Vehicle menu, as trims are only designated for one vehicle. So, instead of a drop-down for vehicle trims in the Vehicles menu, have a text box that separates values by a comma instead. Citizens can then choose one value for their vehicle the normal way.

**Comment by Dev-CasperTheGhost** [comment]
These are both breaking changes will require one to reset data. This won't be possible anymore at this time
