### ISSUE TITLE
Court Entries (Arrest Reports)

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1579]
### Describe the feature

Can we make these editable as well by Courthouse perm?

Right now I think its only LEO Supervisor/Arresting Officer who can edit the charges/arrest report/court entries.

If they go to court and the charge gets changed to a smaller charge there is no way to edit the record.

**Comment by Dev-CasperTheGhost** [comment]
sorry for the late reply. On what page would this be required :)? @Legacy-TacticalGamingInteractive

**Comment by Legacy-TacticalGamingInteractive** [comment]
Looking into it more. I realize the Save button is not functioning if someone Edits a report. Not sure why. Permission bug maybe? See here:
![image](https://user-images.githubusercontent.com/25211271/228557315-f233a45f-1c1f-40b8-be2d-ff4b4db36951.png)

**Comment by Dev-CasperTheGhost** [comment]
Can you provide a video reproduction for this? Can't currently reproduce this

**Comment by Legacy-TacticalGamingInteractive** [comment]
do you still have account on our cad to test live perhaps?

**Comment by Dev-CasperTheGhost** [comment]
I do still have the account, I'll take a look later today.

**Comment by Dev-CasperTheGhost** [comment]
> Looking into it more. I realize the Save button is not functioning if someone Edits a report. Not sure why. Permission bug maybe? See here: ![image](https://user-images.githubusercontent.com/25211271/228557315-f233a45f-1c1f-40b8-be2d-ff4b4db36951.png)

This is a bug, not permissions related it seems though

**Comment by Dev-CasperTheGhost** [comment]
That bug should be fixed now. Again, on what page would this feature be required :)?

**Comment by Legacy-TacticalGamingInteractive** [comment]
I think thats it actually! We can close it now.

**Comment by Dev-CasperTheGhost** [comment]
Ah alright, sounds good!
