### ISSUE TITLE
[FEATURE REQUEST] The mechanism for uncombining units

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#158]
### Describe the feature

The function refers to #47 

The function allows officers split paired unit to separate units.

What should an officer do?
Click on the corresponding button (or the functionality of the right mouse button) and select "Split"
![kiss_10kb 1637252677 1](https://user-images.githubusercontent.com/4976837/142455197-737b1ca6-6a71-4474-be10-fc33ee339c6b.png)

**Comment by Dev-CasperTheGhost** [comment]
This would "unmerge" the unit, but this is only available to the officers in that unit, correct?

**Comment by pp2amd6** [comment]
Yes, unmerge units and function allowed only for officers in pair unit
