### ISSUE TITLE
Feat: On Duty Command Sent In Game Too?

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1586]
### Describe the feature

I have NO clue if this is possible.
But we have a custom 911 system where someone just types `/duty` then they can see 911 calls. Its not connected to CAD.

Would it be possible if anyone knows to send a `/duty` command as if someone typed it in game but automatically when they go 10-8 in CAD?

This would probably require them to put in their FiveM identifier or Discord on their CAD profile to use the feature so it can detect them in game, I'd imagine.

Thoughts?

### Additional Context

We seem to have a lot of people who simply forget to type `/duty` because they are stupid. But whatever lol. This would just be a really cool feature.

I would have loved to get my 911 system to work with CAD. But I never could figure it out how.

**Comment by Dev-CasperTheGhost** [comment]
Closing this here since it's been added to the Discord Suggestions
