### ISSUE TITLE
Incident Purging

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1593]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

1.53

### Describe the Bug

Add Event button seems to be missing now on Incidents
![image](https://user-images.githubusercontent.com/25211271/229215572-d3b58710-30ea-406c-84e2-04048a4d14b7.png)

### Expected Behavior

To be able to Add Events to Incidents

**Comment by Legacy-TacticalGamingInteractive** [comment]
Additional Request:

Ended Incident Pruning.
Can we have Ended incidents automatically pruned every 2 weeks or something? Because right now we have like 10 pages of Incidents built up lol.

**Comment by Dev-CasperTheGhost** [comment]
The bug has been fixed. Working on the purging now
