### ISSUE TITLE
Steam browser trouble 

### ISSUE THREAD

**Issue by sl1ki0** [SnailyCAD/snaily-cadv4#1598]
### What version of Node.js are you using?

16.18.1

### What version of npm are you using?

8.19.2

### What operating system are you using?

Alma Linux

### What version of SnailyCAD are you currently using?

1.53.0

### Describe the Bug

Hey! If you know, somebody uses SnailyCAD with Steam in-game overlay browser (whic can be opened by pressing Shift+Tab) and when you open SnailyCAD in this browser it's not working. Look at screen shot, theme is broken, buttons don't work. But it's still working when you're using a normal browser such as Opera, Chrome and etc.
![image](https://user-images.githubusercontent.com/126953670/230185651-55524e4a-fb53-4820-9aea-bc9c6d25339f.png)

### Expected Behavior

It think it should works properly like when you using a normal browser.

**Comment by Dev-CasperTheGhost** [comment]
This will not worked on, the Steam browser is outdated and does not live up to modern web standards
