### ISSUE TITLE
[BUG] Incorrect merge with paired unit #2

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#160]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### Describe the Bug

When trying to merge a paired unit with a third officer, we will get an error and a new paired unit with one officer

https://user-images.githubusercontent.com/4976837/142689156-338ac5cc-a2c4-4b8f-bb98-e71bdbd0f848.mp4

### Expected Behavior

The merge shouldn't work because merging with a paired unit is not currently provided

**Comment by Dev-CasperTheGhost** [comment]
Just pushed a hot-fix so it doesn't merge the units. Will soon push out another update so it doesn't show the merge button in the UI when it's not possible to merge.
