### ISSUE TITLE
Declare Dead permissions

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1601]
### Describe the feature

Is it possible to make this link show only to EMS/FD medical personnel and not LEO?
![image](https://user-images.githubusercontent.com/25211271/230650379-daff34dc-384a-4146-9361-17d0443856fe.png)

**Comment by Dev-CasperTheGhost** [comment]
The button will be hidden for anyone without the permission. The permissions is not granted by default so you will need to explicitly set the permission on EMS/FD
