### ISSUE TITLE
New Section - Hospitals / Medical Services

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1602]
### Describe the feature

I have an idea for a new section.
Citizen | Officer | EMS/FD | Dispatch | Courthouse | **Hospital / Medical Services**

This could have roles/options like:

• Hospital Staff:
Doctor, Nurse, Coroner

• Morgue:
When someone is Marked as Dead, then their Citizen is sent to the Morgue
(just like when someone impounds a vehicle into the Impound Yard)

Someone with Medical permission can Mark as Dead or Release From Morgue as well.
_Maybe tie permission to EMS/FD so its easier. Since EMS are medical as well technically._

**Comment by Dev-CasperTheGhost** [comment]
Sounds quite interesting, will have time later this week to work on this :)
