### ISSUE TITLE
Livemap-Dispatch-Request 

### ISSUE THREAD

**Issue by EWANZO101** [SnailyCAD/snaily-cadv4#1612]
### Describe the feature

If there could be a way for when a 911 call comes in it pops up on live map and the data from it like postal and reason for 911 u could click create call on it and it would auto put the info in

**Comment by TheAFKGamer10** [comment]
It already does that when somebody makes a 911 call. It pops up a call on the map, and on the side of the screen, then you can click manage call, and all of the information will pop up.

**Comment by Dev-CasperTheGhost** [comment]
What TheAFKGamer10 said
