### ISSUE TITLE
Visibility of IDs on client

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1614]
### Describe the feature

Allow visibility of IDs within modals such as the call and incident modals and anywhere that the ID is not present in the URL.

This helps developers link data and makes troubleshooting a little easier for custom API calls.

This should probably be an optional feature but also would be nice if it only showed for administrators or for people with a permission key.

This is similar to the change that shows IDs for departments/divisions which has saved me an awful lot of time. It isn't required for citizen pages as the ID is present in the URL when browsing those.

### Additional Context

Example modals:

![image](https://user-images.githubusercontent.com/48030374/231998351-e688b063-e5df-4bcb-b803-b9afb1ae3182.png)

![image](https://user-images.githubusercontent.com/48030374/231999020-f283a99d-baad-4cb4-b72f-3b1003668678.png)

**Comment by Dev-CasperTheGhost** [comment]
With this I’ll introduce a developer mode, this will also affect the ids shown in the values tables ;)
