### ISSUE TITLE
Allow Tow to use impound with Business as Company (not just LEO)

### ISSUE THREAD

**Issue by dexslab** [SnailyCAD/snaily-cadv4#1618]
### Describe the feature

Basically if you are able to tow vehicles you can also impound them. This will allow for a tow business with access to tow cad the ability to log vehicles recovered and kept. (ps will allow me to keep vehicles from spawning if they are seized :smiling_imp: )

**Comment by Dev-CasperTheGhost** [comment]
You can give them the manage impound lot permission? That will allow them to impound and release the vehicle?

**Comment by dexslab** [comment]
I'm sure we could but the issue is the ability to search plates is only an officer thing which is what's needed to allow vehicle impounds. Also impounding does it to department if I'm not mistaken not the business

**Comment by Dev-CasperTheGhost** [comment]
> Also impounding does it to department if I'm not mistaken not the business

what exactly do you mean here?

**Comment by dexslab** [comment]
> > Also impounding does it to department if I'm not mistaken not the business
> 
> what exactly do you mean here?

When you go to impound a vehicle as an officer, it automatically puts the department in as the entity holding the vehicle.

**Comment by Dev-CasperTheGhost** [comment]
No? 

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/53900565/232198561-67cc05cf-8506-4328-93f5-1feb8e04c347.png">

**Comment by dexslab** [comment]
nvm i will just write a script to do the plate search and allow for proper impound of vehicles and store the impound fees
