### ISSUE TITLE
Discord Id / Custom User Attributes

### ISSUE THREAD

**Issue by Dalrae1** [SnailyCAD/snaily-cadv4#162]
### Describe the feature

With my server I store all permissions in Discord. I am currently just using the "steam id" field to store the Discord Id automatically, but it would be nice to have a Discord ID field/custom user attributes that work like these values
![image](https://user-images.githubusercontent.com/52721173/144140920-74d7ac92-4c36-4e91-9405-37acdbbf7a6f.png)

**Comment by Dev-CasperTheGhost** [comment]
closed by #166
