### ISSUE TITLE
Warrant Approval Bug

### ISSUE THREAD

**Issue by jayquellz** [SnailyCAD/snaily-cadv4#1628]
### What version of Node.js are you using?

16.0.0

### What version of npm are you using?

latest

### What operating system are you using?

Debian 11

### What version of SnailyCAD are you currently using?

1.5.1

### Describe the Bug

Warrant Status Approval is turned on. When units submit a warrant as "active", it instantly shows as an active warrant upon a search of that citizen's name. It does show up in Manage Courthouse as a Pending Warrant (as expected), and until approved they do not show up on the Officer Dashboard (as expected). The main issue is that the warrants show as active upon a search of the citizen's name, prior to warrant approval.

### Expected Behavior

When a unit submits a warrant as "active", the warrant should not show as active anywhere in the CAD for that citizen until it has been approved in Manage Courthouse.

### To Reproduce

Turn Warrant Status Approval on. File a test warrant on a citizen, with the status set as "active". Search the citizen's name, and you will see the red flag as well as the active warrant PRIOR to warrant approval in Manage Courthouse.

**Comment by Dev-CasperTheGhost** [comment]
This has been fixed. Please update your CAD :)
