### ISSUE TITLE
errors when using yarn

### ISSUE THREAD

**Issue by josilv3296** [SnailyCAD/snaily-cadv4#1639]
### What version of Node.js are you using?

3.5.0

### What version of npm are you using?

8.5.1

### What operating system are you using?

ubuntu

### What version of SnailyCAD are you currently using?

1.58.0

### Describe the Bug

`➤ YN0000: ┌ Resolution step
➤ YN0002: │ @react-aria/dialog@npm:3.5.2 [144e3] doesn't provide react-dom (p5079b), requested by @react-aria/overlays
➤ YN0002: │ @react-aria/dialog@npm:3.5.2 [20ae9] doesn't provide react-dom (p417c2), requested by @react-aria/overlays
➤ YN0002: │ @snailycad/api@workspace:apps/api doesn't provide @tsed/logger (p9ecb1), requested by @tsed/di
➤ YN0002: │ @snailycad/api@workspace:apps/api doesn't provide @tsed/logger (p3a2ff), requested by @tsed/platform-express
➤ YN0002: │ @snailycad/api@workspace:apps/api doesn't provide @tsed/logger (p575cf), requested by @tsed/socketio
➤ YN0002: │ @snailycad/api@workspace:apps/api doesn't provide @tsed/openspec (p49374), requested by @tsed/platform-express
➤ YN0002: │ @snailycad/api@workspace:apps/api doesn't provide @tsed/platform-middlewares (p90505), requested by @tsed/socketio
➤ YN0002: │ @snailycad/api@workspace:apps/api doesn't provide body-parser (p762a0), requested by @tsed/platform-express
➤ YN0002: │ @snailycad/api@workspace:apps/api doesn't provide react (pc4af0), requested by use-intl
➤ YN0002: │ @snailycad/client@workspace:apps/client doesn't provide eslint (pd2d25), requested by eslint-config-next
➤ YN0002: │ @snailycad/client@workspace:apps/client doesn't provide socket.io (pe35de), requested by @casper124578/use-socket.io
➤ YN0002: │ react-hot-toast@npm:2.4.1 [ba53c] doesn't provide csstype (p0c7e8), requested by goober
➤ YN0002: │ snailycad@workspace:. doesn't provide @typescript-eslint/parser (p417de), requested by @typescript-eslint/eslint-plugin
➤ YN0002: │ snailycad@workspace:. doesn't provide next (p79a82), requested by @casper124578/eslint-config-next
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 1s 254ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:1.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zod@npm:3.21.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zustand@npm:4.3.8 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zwitch@npm:2.0.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 7s 777ms
➤ YN0000: ┌ Link step
➤ YN0007: │ turbo@npm:1.9.9 must be built because it never has been before or the last one failed
➤ YN0007: │ bcrypt@npm:5.1.0 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.17.19 must be built because it never has been before or the last one failed
➤ YN0007: │ sharp@npm:0.32.1 must be built because it never has been before or the last one failed
➤ YN0007: │ @swc/core@npm:1.3.60 [9f797] must be built because it never has been before or the last one failed
➤ YN0007: │ @prisma/engines@npm:4.14.1 must be built because it never has been before or the last one failed
➤ YN0007: │ @sentry/cli@npm:1.75.2 must be built because it never has been before or the last one failed
➤ YN0009: │ @prisma/engines@npm:4.14.1 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-f21426d4/build.log)
➤ YN0009: │ sharp@npm:0.32.1 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-66c4f620/build.log)
➤ YN0007: │ snailycad@workspace:. must be built because it never has been before or the last one failed
➤ YN0007: │ prisma@npm:4.14.1 must be built because it never has been before or the last one failed
➤ YN0009: │ prisma@npm:4.14.1 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-2bb64ef1/build.log)
➤ YN0007: │ @prisma/client@npm:4.14.1 [9f797] must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 1m 9s
➤ YN0000: Failed with errors in 1m 19s
`

### Expected Behavior

i suppose it should detect dependencies and install them

### To Reproduce

i tried with auto installer and with standalone options

**Comment by Dev-CasperTheGhost** [comment]
Please use Discord for general support. Make sure you're on the required versions of Node.js & npm.
