### ISSUE TITLE
Feat: Pets

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1640]
### Describe the feature

Our server has pets that people can have who follow them around and you can also make them attack people etc.

So, we have Citizen and we have Officer
Can we have Animal/Pet character?
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/25211271/ecf4ca6c-5897-4b76-a846-7726232e80b7)

Animal Name
Animal Breed/Type
Animal Medical History

The pet can have **medical records** and **notes** for example if they go to the vet, have rabies, have attacked someone or were lost and found by Animal Services and they are at the pound. Some people may even want to keep illegal exotic pets for roleplay like a Monkey or something. 

Some people have Livestock like Cows for example as well when they are doing Farming roleplay.

It would be neat. Very unique.

We even have an animal clinic :) where animal services work from too. So it would be kind of cool to have them in CAD.
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/25211271/3aeff679-5676-4539-8043-cd4c8a1318e7)
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/25211271/631afc45-df33-47b3-a906-5a6f85fdc3aa)
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/25211271/15f8eba3-bed9-46f0-b06e-6fa96771ff6c)

**Comment by Dev-CasperTheGhost** [comment]
I love the idea, going to work on this very soon!

**Comment by Dev-CasperTheGhost** [comment]
@Legacy-TacticalGamingInteractive are pets connected to a citizen in the CAD, or not connected at all?

**Comment by Legacy-TacticalGamingInteractive** [comment]
> @Legacy-TacticalGamingInteractive are pets connected to a citizen in the CAD, or not connected at all?

I think its better if connected to a citizen. So you can see who owns the pet.

**Comment by Dev-CasperTheGhost** [comment]
A part one of this is released. Update your SnailyCAD instance to the latest version and let me know what you think @Legacy-TacticalGamingInteractive! **Feedback is appreciated!**
