### ISSUE TITLE
Panic Button

### ISSUE THREAD

**Issue by QUINTONH101** [SnailyCAD/snaily-cadv4#1660]
### What version of SnailyCAD are you currently using?

1.58.0

### Describe the Bug

When you add the "10-Codes" for a "Panic Button" a button is displayed along with the other 10 Code buttons such as "10-41, 10-08, etc." AND there is a button displayed in the "Utility Panel" near the "Notepad" button.

### Expected Behavior

If Panic Button is enabled in the cad settings the button in the "Utility Panel" should appear and the two should not be linked together and act as one button. You should not have to have a 10-Code panic button in order to see the panic button on the Utility Panel.

**Comment by Dev-CasperTheGhost** [comment]
This should've worked before, I'll try take a look today

**Comment by Dev-CasperTheGhost** [comment]
actually, looking at the code, this should work as expected @QUINTONH101

**Comment by QUINTONH101** [comment]
[Panic Button.zip](https://github.com/SnailyCAD/snaily-cadv4/files/11672804/Panic.Button.zip)

**Comment by JustCreizy** [comment]
You have to add a 10 code for the panic button

**Comment by Dev-CasperTheGhost** [comment]
It’s actually not required @JustCreizy. This is a valid bug ;)

**Comment by JustCreizy** [comment]
Sry my bad then
