### ISSUE TITLE
Photo ID not adding and existing photo fails to load on enlargement.

### ISSUE THREAD

**Issue by QUINTONH101** [SnailyCAD/snaily-cadv4#1662]
### What version of SnailyCAD are you currently using?

v1.58.0

### Describe the Bug

Before updating the version of the cad for the panic button released you did the images were working fine for IDs however now you can not add new ID photos and when you click to enlarge existing photos it says Failed to Load Image. Assuming this isn't correlated to the release but maybe was edited on accident.

### Expected Behavior

Should be able to add new photos to IDs and when enlarged via clicking on the image it should appear as did before.

### Extra Notes

The image also no longer appears on the Law Enforcement side in the search panels.

**Comment by Dev-CasperTheGhost** [comment]
Image uploads still work, but the images fail to load, correct? @QUINTONH101

**Comment by QUINTONH101** [comment]
Yeah. The image uploads and appears on the “Citizen” page for a split second but is also blurred out then disappears. Already existing photos appear as normal but cannot be enlarged. 

PS. I am still unable to see the panic button on LEO without needing the corresponding 10-code(have updated the cad)

**Comment by Dev-CasperTheGhost** [comment]
> Yeah. The image uploads and appears on the “Citizen” page for a split second but is also blurred out then disappears. Already existing photos appear as normal but cannot be enlarged.

Now I'm not following, can you record a video for that too? I think I know what's going on, but not certain

**Comment by QUINTONH101** [comment]
Let me get my computer up then I’ll send a vid

**Comment by QUINTONH101** [comment]
[2023-06-08 00-40-43.zip](https://github.com/SnailyCAD/snaily-cadv4/files/11684098/2023-06-08.00-40-43.zip)

**Comment by Dev-CasperTheGhost** [comment]
can you share the Browser Console error logs?

**Comment by QUINTONH101** [comment]
![Screenshot (251)](https://github.com/SnailyCAD/snaily-cadv4/assets/68574519/7a58e7f5-a15b-465a-9f85-7d8332696445)

**Comment by Dev-CasperTheGhost** [comment]
okay, it is the error what I thought it was. Perform the following steps: 

1. Backup any changes done to the locales (if any), then run `git stash`
2. Stop your SnailyCAD instance
3. Run the following commands: `node scripts/copy-env.mjs --client --api && yarn turbo run build --filter="{packages/**/**}" && yarn turbo run build --filter="{apps/**/**}"`
4. Start your SnailyCAD instance
5. All done, issue should be gone. 

Let me know if these steps fixed it, please!

**Comment by Dev-CasperTheGhost** [comment]
No, you will need to copy the contents and save them somewhere else temporarily

**Comment by QUINTONH101** [comment]
That fixed the issue. I appreciate all of your support, it is so appreciated. Most developers take FOREVER or just never help. Keep up the amazing work!

**Comment by Legacy-TacticalGamingInteractive** [comment]
Photos still disappearing even after doing that attempted fix.

![image](https://github.com/SnailyCAD/snaily-cadv4/assets/25211271/1d274755-0ef8-40aa-9285-95e5c3df35af)
