### ISSUE TITLE
Callsign Templates

### ISSUE THREAD

**Issue by Internal3247** [SnailyCAD/snaily-cadv4#1668]
### Describe the feature

Instead of having a callsign template assigned globally for all departments, we should be able to assign a callsign template based on the department, this can be useful for servers who have different callsign formats for each department, i.e SAHP = ####, LSPD = ##L##, BCSO = L##. Users who are active as a certain division or have a certain rank should also be able to override the template and have whatever callsign they would like. 

```[tasklist]
### Tasks
- [x] Department callsign template
- [ ] Permissions to allow custom user defined template
```

**Comment by Dev-CasperTheGhost** [comment]
>  Users who are active as a certain division or have a certain rank should also be able to override the template and have whatever callsign they would like.

For this I could create a permission instead.

**Comment by Internal3247** [comment]
Awesome, probably better then it being based on rank.
