### ISSUE TITLE
Custom Sounds for button presses.

### ISSUE THREAD

**Issue by Internal3247** [SnailyCAD/snaily-cadv4#1669]
### Describe the feature

Some departments have a sound or text to speech voice when an officer opens up a certain menu such as vehicle search, ped search, etc, it would be awesome if we could upload our own sounds and do the same similar to how we can do the same for other features listed here: https://docs.snailycad.org/docs/guides/product/how-set-custom-sounds.

### Additional Context

Real life example : https://www.youtube.com/watch?v=4_jQvOHzrNA

**Comment by Dev-CasperTheGhost** [comment]
This sounds really unnecessary IMHO and will only bloat the system?

**Comment by Internal3247** [comment]
Maybe, thought it was missing with the current version since we already have sounds for other buttons like changing status, attaching to calls, etc

**Comment by Dev-CasperTheGhost** [comment]
I don't think this will add much benefit, tts/voice isn't the most fun to work with either, so I'm not planning on adding this.
