### ISSUE TITLE
[BUG] CAD settings - authenticate with Discord option not saved

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#167]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### Describe the Bug

CAD settings - authenticate with Discord option not saved

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
What do you mean exactly? All works fine for me..

**Comment by pp2amd6** [comment]
Set option to Enable, press Save button. Refresh page - option in Disable

**Comment by Dev-CasperTheGhost** [comment]
Did you set the .env values?

**Comment by pp2amd6** [comment]
> Did you set the .env values?
Nope. Please add link to docs near option
![DJxST2l 1](https://user-images.githubusercontent.com/4976837/145998502-3fe43e89-2505-470c-a55a-4807a87fcb92.png)
