### ISSUE TITLE
[:globe_with_meridians: Localization] Missing locale strings in 1.59.0 update

### ISSUE THREAD

**Issue by LynxarA-Coding** [SnailyCAD/snaily-cadv4#1671]
The latest 1.59.0 update has added almost all of the previously missing locale strings, which is great. However, there are still a few strings that are missing. Here is the list of the remaining missing strings with their respective positions:

The following issues have numbers before them. They are screenshots of the issues (clickable)

- [[1]](https://i.imgur.com/exsBYC1.png) Tables have their first title as a `"Value"` (not localized)
Can be found in the CAD Admin tables like:
  - `Addresses`
  - `Blood Types`
  - `Call Types`
  ... and etc

- [[2]](https://i.imgur.com/9vd9PQg.png) Login Page
	- `Username` and `Password` titles are not localized
	- `Show` button name is not localized
- CAD Settings
	- [[3]](https://i.imgur.com/XacGSRW.png) Admin. `Custom Text Fields` has an "Add" option. The pop-up has not localized the `Category` title and `Cancel` button
	- [[4]](https://i.imgur.com/dCEaGXJ.png) Prison Time Scaling has unused locales for time (it's not shown. Example: `MiscSettingsTab.Minutes` instead)
	- [[5]](https://i.imgur.com/fxcKL2h.png) Live Map and other settings that include `Choose file` option lack a localization of this interactive element
	- [[6]](https://i.imgur.com/SK9PLnp.png) 70% of strings in pop-ups are not localized. (Example:` Import` pages, when you click the `Import` button)
	- [[7]](https://i.imgur.com/2eEPauS.png) Most of the custom Form fields are not localized. (Example: `Add qualification` form lacks titles translations)

Screenshots of the issues can be also found in the Discord thread: [link](https://discord.com/channels/792479048457912360/1117218837251752026)

It would be great if these missing strings could be added in a future update. Thank you for your attention to this matter.

**Comment by Dev-CasperTheGhost** [comment]
Thanks a lot for putting in this effort to the translation! All these issues should be fixed now except for the `Choose File..`, this is browser defined text that I cannot change. If you change the language of your browser, this text will change too
