### ISSUE TITLE
Ability for PD/EMS/FD to complete citizens profile

### ISSUE THREAD

**Issue by bartusek27** [SnailyCAD/snaily-cadv4#1698]
### Describe the feature

For better roleplaying feel, lots of RP servers are "hardening" the work of PDs by not having all the data regarding the citizens in their system. That is for example a photo. For example in our community, the photo of the citizen is always uploaded by the arresting officer.
Also same for their phone number or address and possibly more. Not that many countries IRL are also in possession of everything regarding the citizens.

I think the best approach would be creating new permission scope for "Editing citizen records", that would give an officer a button "Edit Citizen" when searching for citizen and that would redirect the officer for the page where users are editing their own citizens. So the permission scope would only give permission for editing other profiles, the question might be to what extent and if it can be easily implemented.

**Comment by Dev-CasperTheGhost** [comment]
For this feature, I'll also 2 more items: 

- Make this toggable 
- Add a permission for this so only select units can edit citizens


> when searching for citizen and that would redirect the officer for the page where users are editing their own citizens. So the permission scope would only give permission for editing other profiles, the question might be to what extent and if it can be easily implemented.

I'd rather open a large modal with the form, this'll be a bit easier for navigating around.
