### ISSUE TITLE
Citizen Photos Disappearing

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1704]
### What version of Node.js are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

v1.62.1 a97814f

### Describe the Bug

![image](https://github.com/SnailyCAD/snaily-cadv4/assets/25211271/1c2b89ff-80d7-481b-81b0-cdd981060798)

### Expected Behavior

Created a new citizen. The photo uploaded. But when I clicked CREATE the photo disappears from the profile.

**Comment by Dev-CasperTheGhost** [comment]
Can you try these steps please: https://github.com/SnailyCAD/snaily-cadv4/issues/1662#issuecomment-1582798818

**Comment by Dev-CasperTheGhost** [comment]
@Legacy-TacticalGamingInteractive, any news here?

**Comment by bartusek27** [comment]
The solution mentioned in that ticket didn't helped. For me, the address that is trying to get the image loaded ( for me, it is 
https://{CAD_DOMAIN}/_next/image?url=https%3A%2F%2F{API_DOMAIN}%2Fstatic%2Fcad%2Fcli4hpm2k0003m95y1yi86spz-sagov_logo.webp&w=32&q=80 ). The response is `400` and `"url" parameter is not allowed`

**Comment by Legacy-TacticalGamingInteractive** [comment]
> @Legacy-TacticalGamingInteractive, any news here?

That did not work for me.

**Comment by Dev-CasperTheGhost** [comment]
New fix: `git stash && node scripts/copy-env.mjs --client --api && yarn workspace @snailycad/client create-images-domain && yarn turbo run build --filter="{packages/**/**}" && yarn turbo run build --filter="{apps/**/**}"`

**Comment by bartusek27** [comment]
Same problem, not fixed. Let me know if you need anything to be provided.

**Comment by Legacy-TacticalGamingInteractive** [comment]
> Same problem, not fixed. Let me know if you need anything to be provided.

TRY running `yarn workspace @snailycad/client create-images-domain`
