### ISSUE TITLE
Importing Weapons and Vehicles during Import Citizen bug

### ISSUE THREAD

**Issue by spencerlocks** [SnailyCAD/snaily-cadv4#1716]
### What version of Node.js are you using?

v16.13.2

### What operating system are you using?

Ubuntu 20.04 LTS

### What version of SnailyCAD are you currently using?

1.63.0 ec5b21c

### Describe the Bug

When importing a citizen, I have the weapons and vehicle structures built in. The weapons and vehicles nicely show up in the CAD under the civilian that it should, but when I go to edit that vehicle or weapon and click save, and error pops up
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/96554330/c5854fbe-d537-4919-aee7-66c1e8688177)

Below is the exact code I run:

[
    {
        "userId": "clixqhacq00009guf9tlofdaj",
        "name": "Spencer",
        "surname": "Lockhart",
        "dateOfBirth": "1995-01-26",
        "occupation": "Former SASP Commissioner",
        "gender": "clijqawor05ni9g7c3lvngzr1",
        "ethnicity": "clijqaqou05na9g7cg601fprd",
        "hairColor": "Black",
        "eyeColor": "Green",
        "postal": "564",
        "address": "Whispymound Drive",
        "weight": "120",
        "height": "5'6\"",
        "driversLicenseId": "clijqb61p05nq9g7ca9l99g8d",
        "vehicles": [
            {
                "plate": "LOCKMAN4",
                "modelId": "clijq884z03bq9g7co0xbqecd",
                "registrationStatusId": "clijqb61p05nq9g7ca9l99g8d",
                "color": "Blue & White",
                "insuranceStatus": "clijqb61p05nq9g7ca9l99g8d"
            },
            {
                "plate": "LOCKMAN2",
                "modelId": "clijq887h03ft9g7cixcu03wp",
                "registrationStatusId": "clijqb61p05nq9g7ca9l99g8d",
                "color": "Red & White",
                "insuranceStatus": "clijqb61p05nq9g7ca9l99g8d"
            },
            {
                "plate": "LOCKMAN3",
                "modelId": "clijq89bt050e9g7c78qze6lk",
                "registrationStatusId": "clijqb61p05nq9g7ca9l99g8d",
                "color": "Red, Black & Gold",
                "insuranceStatus": "clijqb61p05nq9g7ca9l99g8d"
            },
            {
                "plate": "LOCKMANS",
                "modelId": "clijq885w03da9g7cj1jnidkd",
                "registrationStatusId": "clijqb61p05nq9g7ca9l99g8d",
                "color": "Blue",
                "insuranceStatus": "clijqb61p05nq9g7ca9l99g8d"
            },
            {
                "plate": "LOCKHART",
                "modelId": "clijq881q036u9g7cepebmfgj",
                "registrationStatusId": "clijqb61p05nq9g7ca9l99g8d",
                "color": "Silver",
                "insuranceStatus": "clijqb61p05nq9g7ca9l99g8d"
            },
            {
                "plate": "REDNBLUE",
                "modelId": "clijq87uc02vu9g7ctzrfw74j",
                "registrationStatusId": "clijqb61p05nq9g7ca9l99g8d",
                "color": "Blue",
                "insuranceStatus": "clijqb61p05nq9g7ca9l99g8d"
            }
        ],
        "weapons": [
            {
                "modelId": "clijq8zij05i29g7c0gdb5kq7",
                "registrationStatusId": "clijqb61p05nq9g7ca9l99g8d"
            },
            {
                "modelId": "clijq8zik05ia9g7c086hfv33",
                "registrationStatusId": "clijqb61p05nq9g7ca9l99g8d"
            },
            {
                "modelId": "clijq8zhw05bm9g7cb3qnbai8",
                "registrationStatusId": "clijqb61p05nq9g7ca9l99g8d"
            },
            {
                "modelId": "clijq8zh5057i9g7cahukobc8",
                "registrationStatusId": "clijqb61p05nq9g7ca9l99g8d"
            }
        ]
    }
]

### Expected Behavior

I would expect that generating the weapons and vehicles from the import citizen POST api would generate the vehicles and weapons so that they can then be edited further by the user that the civilian has as it's owner.

### To Reproduce

Feel free to message me on discord "Tangent" lockman228 if you would like to have me share my screen while replicating the problem.

I'm using matlab to generate my JSON code for all the citizens, maybe I am missing some key value pair I need?
I turned off Bureau of Firearms slider to see if that would help, but it didn't do anything.

**Comment by Dev-CasperTheGhost** [comment]
This is now fixed. However, you will have to remove this citizen and re-import it. There was a bug in the importing behaviour

**Comment by spencerlocks** [comment]
Can confirm this fixed the bug, thanks!!
