### ISSUE TITLE
Cannot attribute a role custom to someone 

### ISSUE THREAD

**Issue by AndyyFC** [SnailyCAD/snaily-cadv4#1723]
### What version of Node.js are you using?

19.8.1

### What operating system are you using?

Debian

### What version of SnailyCAD are you currently using?

1.63

### Describe the Bug

Unable to click on custom roles and assign a Discord role to a custom role

### Expected Behavior

Only when you click on the custom role. The role is added to the user. And that when the Discord role is clicked, it is added to the custom role

### To Reproduce

Go to Admin>Custom role>Add a custom role 

And 

Admin>User management>manage users>Add custom role

**Comment by Dev-CasperTheGhost** [comment]
This was actually just fixed 2 min ago :)!
