### ISSUE TITLE
Status changing not presenting drop down

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1725]
### What version of Node.js are you using?

Unknown

### What operating system are you using?

Unknown

### What version of SnailyCAD are you currently using?

Unknown

### Describe the Bug

On behalf of _ch1efta1n_ on Discord.

The drop down does not appear to function when attempting to set statuses from the live map.

### Expected Behavior

That the drop down is presented to allow status changes to be applied to units.

### To Reproduce

https://streamable.com/ans2ep

**Comment by Dev-CasperTheGhost** [comment]
Cannot reproduce
