### ISSUE TITLE
Still having ID photo issue

### ISSUE THREAD

**Issue by QUINTONH101** [SnailyCAD/snaily-cadv4#1735]
### What version of Node.js are you using?

N/A

### What operating system are you using?

N/A

### What version of SnailyCAD are you currently using?

1.64.1

### Describe the Bug

I have been having issue with getting ID photos to work on civilians. After doing the fix that indeed corrected it the first time it is now not giving any result. All of the issues with this detail are the exact same as in the past.

### Expected Behavior

Images show on Citizen panel and Officer panel when searched.

### To Reproduce

Search or load anything that is tied with a citizen that has an image uploaded for ID photo.

**Comment by Dev-CasperTheGhost** [comment]
Try the steps again, if it still doesn’t work, contact via Discord since this isn’t a bug.
