### ISSUE TITLE
Medical Record textboxes are too small

### ISSUE THREAD

**Issue by bartusek27** [SnailyCAD/snaily-cadv4#1738]
### Describe the feature

When you add medical record to citizen, either in modal window, or just viewing already created records, the input boxes are too small. When you create medical record, mostly it is far more than just a few words, thus it would also make sense to make the text rich by markdown as in incident reports.

**Comment by bartusek27** [comment]
Still an issue - textboxes are small. Also in citizen card in EMS panel, you can't see the text properly since the windows are too small. 
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/11354418/cd3db757-80c5-4d30-821c-8e55ff3cc1b2)

**Comment by Dev-CasperTheGhost** [comment]
It becomes larger automatically once you type inside of that box.
