### ISSUE TITLE
Create fire reports

### ISSUE THREAD

**Issue by AndyyFC** [SnailyCAD/snaily-cadv4#1740]
### Describe the feature

In the "EMS/FD" section, add the possibility of creating fire reports, as well as a section for searching the report via the address of the fire location.

### Additional Context

https://imgur.com/a/mtdA1dE

I've made some sample images that fire reports might look like

**Comment by Dev-CasperTheGhost** [comment]
What information would be stored in the fire report? @AndyyFC 

PS: sorry for taking this long to get to this feature request

**Comment by AndyyFC** [comment]
Good evening, here is the type of information that would be stored in the fire raports:

Address
Date/Time
Vehicle involved
Unit on scene ( Can one or more units be assigned via dispatch? )
Type of fire
Description 
Add images to report (Optional)
