### ISSUE TITLE
Citizen Generated Records Bug

### ISSUE THREAD

**Issue by spencerlocks** [SnailyCAD/snaily-cadv4#1746]
### What version of Node.js are you using?

V16.13.2

### What operating system are you using?

Ubuntu 20.04

### What version of SnailyCAD are you currently using?

1.64.1 f75d920

### Describe the Bug

With the slider setting on, citizens cannot create their own citizens, or at least there isn't a button to do so on the citizen's page.

### Expected Behavior

I was expecting a button on the top right to appear in the records section of the citizen's page on their dashboard to say "Add Record"

![image](https://github.com/SnailyCAD/snaily-cadv4/assets/96554330/fac984d0-9848-45a8-b88d-d48f6d8226ab)

**Comment by Dev-CasperTheGhost** [comment]
This is not a bug, rather a feature. Citizens cannot manage their own records.

**Comment by spencerlocks** [comment]
Okay, Is there a chance we can add that feature in the future?
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/96554330/b3d45d3a-70f2-4882-bf96-a72fcb6ef1c4)

**Comment by Dev-CasperTheGhost** [comment]
I don't see a point in adding this? They already append it when the citizen is first created though, if that's what you're looking for, that's also that feature you're referring in that screenshot.

**Comment by spencerlocks** [comment]
Oh, I created the characters using the API, but I didn't port over any of the records. I was hoping that the citizens would be able to create their own records to enhance RP while developing their characters, or add to them over time themselves so if it's been a while since they used that citizen, it doesn't look like that citizen was frozen in time, but would have a natural record between getting actual records from LEOs.
