### ISSUE TITLE
Pagination does not work on Business/Employees

### ISSUE THREAD

**Issue by dexslab** [SnailyCAD/snaily-cadv4#1747]
### What version of Node.js are you using?

 17.9.1

### What operating system are you using?

Debian

### What version of SnailyCAD are you currently using?

v1.66.0 55a90a2

### Describe the Bug

When you click to go to the next page for employees when you have a lot the page does not change like it should

### Expected Behavior

Second page of employees should show

### To Reproduce

Hit me up on Discord

**Comment by Dev-CasperTheGhost** [comment]
Will try take a look when back from vacation next week. Currently not able to do much work

**Comment by dexslab** [comment]
Take your time we have a workaround in place for the time being 😄

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed now! I wasn't able to test so please verify for me :)

**Comment by Dev-CasperTheGhost** [comment]
Fixed!
