### ISSUE TITLE
Pictures of vehicles for LEOs

### ISSUE THREAD

**Issue by bartusek27** [SnailyCAD/snaily-cadv4#1749]
### Describe the feature

For LEOs to be able to identify vehicles better, it would be nice to have the ability to see images of vehicle models. There are also two variants of how to approach this feature:
1. Just to be able to upload/define vehicle image inside /admin/values/vehicle, that would be visible to LEOs inside the modal with Searching vehicles
2. Additionally to have possibility to upload custom image of the vehicle for LEOs. If there is none, show the default image defined in the first point.

**Comment by Dev-CasperTheGhost** [comment]
Are you able to elaborate a bit on your first bullet point?

**Comment by bartusek27** [comment]
> Are you able to elaborate a bit on your first bullet point?

Sure - basic thing is being able to define default picture for each vehicle model type. That is must-have so officers actually can see how that vehicle looks like. If you feel like it, then you can upgrade this feature by adding possibility to upload custom image to each vehicle record which will then override the default picture stored for that model. So officers can take photos of a vehicle by themselves to have more accurate picture of it.
