### ISSUE TITLE
Lodon Studios SmartSigns integration (Live Map)

### ISSUE THREAD

**Issue by casperiv0** [SnailyCAD/snaily-cadv4#1752]
Allow dispatchers to select any active smart sign on the live map and update its content

1. FiveM integration that syncs the SmartSigns to the CAD on Live Map page load (sna-live-map)
2. Show all the sign locations on the live map (cad)
3. Allow dispatch to edit them in the live map (cad)
4. Push the update to the live-map integration (socket.io, sna-live-map)

**Comment by Legacy-TacticalGamingInteractive** [comment]
that would be pretty cool we also use that resource
