### ISSUE TITLE
demo indicator

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [SnailyCAD/snaily-cadv4#1754]
We will soon have a demo CAD up and running again. Stay tuned for more details. I want to add a banner that states it's a demo CAD and instructions how to use.

PS: I might also simply add docs for using SnailyCAD in general.

**Comment by WhitigolProd** [comment]
> PS: I might also simply add docs for using SnailyCAD in general.

I think this is a fantastic idea. It can be confusing to firstcomers, and would be very useful to new people!

**Comment by Dev-CasperTheGhost** [comment]
I've added the indicator to SnailyCAD itself, will try to add some docs for creating an account and all that today.
