### ISSUE TITLE
Show Ranks only for Business/Department

### ISSUE THREAD

**Issue by dexslab** [SnailyCAD/snaily-cadv4#1773]
### Describe the feature

When setting ranks for a Business or Department the cad by default pulls all from the values. Can you add a filter that filters out and only shows ranks for that specific department or business. thanks

**Comment by casperiv0** [comment]
This is already the case for departments, no?

**Comment by dexslab** [comment]
No it is not we have this issue now and it makes my life a pita as i use the ids to determine rank when officers go on duty in the server and they sometimes set ranks from other departments

**Comment by casperiv0** [comment]
@dexslab, can you share the location of this bug, I'm not 100% certain where this would occur

**Comment by dexslab** [comment]
So when ur in admin managing units and changing their rank.

In business when your changing managing employees roles.

**Comment by casperiv0** [comment]
Interesting, the rank one should already have filters in place. I'll have a look soon
