### ISSUE TITLE
'Stop Roleplay' button.

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#178]
### Describe the feature

A 'Stop Roleplay' button in the Admin panel that would display a red 'Stop Roleplaying' banner across the entire CAD and maybe even plays a sound, signaling to everyone logged in to stop roleplaying. Like how Signal 100 works, but CAD-wide.

**Comment by pp2amd6** [comment]
There is already a "Signal 100" button for this.

**Comment by Dev-CasperTheGhost** [comment]
What should the text of the alert say? Simply: "Stop Roleplay"?

**Comment by Thomaswill1** [comment]
The alert could say 'Admins issued all players to stop all roleplay.'

And, I don't mean that this _is_ Signal 100 since that only applies to dispatch and LEOs. This would display for everyone logged into the CAD.

**Comment by Dev-CasperTheGhost** [comment]
Will work on this very soon!

**Comment by Dev-CasperTheGhost** [comment]
Head over to the CAD-settings page and there will now be a toggle to "disable roleplay"!
