### ISSUE TITLE
BUG: Sorting Issue - Department Time Logs Not Sorting Chronologically

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1797]
### What version of Node.js are you using?

--

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

v1.67.2 8ae798d

### Describe the Bug

Department Time logs are not sorting properly by date in a chronological fashion.

Could we also see about potentially adding more results on a singular page? (Unless its not good for optimization)

Notice the dates below:
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/25211271/3e7d81b3-d576-4327-ab1e-eff1e731015a)

### Expected Behavior

To sort by date, in chronological order.

### To Reproduce

Click on any header and it will try to sort. But the order of the sorting is wrong.

**Comment by casperiv0** [comment]
I'm not doing any server-side sorting for any tables. So this is somewhat correct. Not sure if there's a way to fix this currently

**Comment by Legacy-TacticalGamingInteractive** [comment]
How about an export feature to .csv or text then? Is that possible?

Then we can manually sort for now some other way.

**Comment by bartusek27** [comment]
I could reproduce this behavior on #2f77965, but I think that all other columns apart those with dates are working correctly. It seems that the sorting ability of the table header is not working for the dates and rather sorts the table by Hours in any case.

**Comment by casperiv0** [comment]
I don't think it's related to that. It's simply not able to sort the formatted dates. This is not be a straight forward fix at the moment

**Comment by Legacy-TacticalGamingInteractive** [comment]
:( </3
