### ISSUE TITLE
BUG: Dispatch Page Issues

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1798]
### What version of Node.js are you using?

--

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

v1.67.2 8ae798d

### Describe the Bug

- Dispatch Page active units. The Next Page/Page 2 button does not work. Nothing happens when clicked.
- Feature Request: Search feature on this page to sort through active units easier.

Reason: We often have 50+ units online. Dispatch cannot assign calls currently as they can only see the first few on the first page.

### Expected Behavior

To be able to click to the next page when there are too many units online.

### To Reproduce

See if you can simulate enough units online to have this bug tested on the Dispatch page.

**Comment by casperiv0** [comment]
These have all been improved in the latest version. Please do an updated :)
