### ISSUE TITLE
[FEATURE REQUEST] Add badge number field for PD officer, FD/EMS card

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#18]
Add badge number field for PD officer, FD/EMS card

![yJTuBi0 1](https://user-images.githubusercontent.com/4976837/138120326-6eca5b72-4245-4a1d-b7ca-6b17652f55fd.png)

Example of LAPD officer badge
![oW4Gf46 1](https://user-images.githubusercontent.com/4976837/138120811-6474cb58-b954-417b-ac2c-b275f2998a96.png)

**Comment by Dev-CasperTheGhost** [comment]
Officer badge number has been implemented. EMS/FD will come once starting on EMS/FD dashboard.
