### ISSUE TITLE
Penal Codes Cannot Be Edited or Deleted

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1803]
### What version of Node.js are you using?

--

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

01c526f

### Describe the Bug

Penal code descriptions are not saving when edited.
Cannot delete penal codes either. Unknown error. No errors in console.

### Expected Behavior

To be able to edit or delete penal codes.

**Comment by casperiv0** [comment]
I'm unable to reproduce this. Please send a video reproduction and please also check the API/command prompt for errors

**Comment by bartusek27** [comment]
I can't reproduce this either on 2f77965
Only strange behavior I have seen is that unchecking Is Primary is not saved, but I believe that it is intended?

**Comment by Legacy-TacticalGamingInteractive** [comment]
Suddenly today the editing is working when yesterday it wasn't. I didn't restart the CAD either. Wtf.

Deleting penal codes still doesn't work though. So I have just been editing them to say DO NOT USE and putting them in Ungrouped.

How can I view API errors from SnailyCAD Manager because the Logs don't come up when I click the button.

**Comment by casperiv0** [comment]
> Deleting penal codes still doesn't work though. So I have just been editing them to say DO NOT USE and putting them in Ungrouped.

It might be that these penal codes are in-use, therefore cannot be deleted. 

> How can I view API errors from SnailyCAD Manager because the Logs don't come up when I click the button.

CTRL+L in the manager app to view logs
