### ISSUE TITLE
Rename "Water" license to "Marine" license & add category for hunting & fishing licenses.

### ISSUE THREAD

**Issue by Alfa1561** [SnailyCAD/snaily-cadv4#1808]
### Describe the feature

As the title describes - rename the "Water" license category to be "Marine" as this sounds more formal and correct.

Also adding a category for hunting and fishing licenses would be really nice for game warden roleplay and similar. It would make sense for this to be separate from the weapon and marine licenses since hunting and fishing licenses arent tied to your status to operate boats or handle weapons.

**Comment by casperiv0** [comment]
If you are the owner of this CAD, please use the docs to add [custom translations](https://docs.snailycad.org/docs/guides/product/how-to-translate). If you're not the owner of this CAD, please contact your owner/developer.

**Comment by Alfa1561** [comment]
Are there any plans regarding the hunting and fishing license category, or is there a way to create something similar?

**Comment by Alfa1561** [comment]
I see. The reason I suggested it is because sometimes someone might have an expired fishing permit but their boat license is still valid, or their weapons license is valid but their hunting license is expired/suspended. But for now I'll work something out.
