### ISSUE TITLE
License Categories broken for Hunting & Fishing Licenses

### ISSUE THREAD

**Issue by Alfa1561** [SnailyCAD/snaily-cadv4#1816]
### What version of Node.js are you using?

18.17.1

### What operating system are you using?

Linux

### What version of SnailyCAD are you currently using?

1.73.1

### Describe the Bug

![image_2023-10-02_194524974](https://github.com/SnailyCAD/snaily-cadv4/assets/29956969/e0089e27-0015-4c9d-928d-6aa5ef85f551)
![image_2023-10-02_194540962](https://github.com/SnailyCAD/snaily-cadv4/assets/29956969/0ab1b0be-3f77-4684-86a7-a8a9d782c769)

When trying to add a license category for hunting or fishing on the civ page, it shows the water license category options.

When trying to add new license category types on the admin panel for hunting or fishing licenses, they fail to add correctly. It simply does not add them to the list.

### Expected Behavior

On the civ page, hunting & fishing license categories should display options from their own types, not the water license category.

On the admin panel, it should accept new license categories for hunting and fishing licenses.

**Comment by Legacy-TacticalGamingInteractive** [comment]
On this, I am not able to add any new categories either.
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/25211271/d9eba924-18ca-4d5f-aea5-4a87249fc345)

**Comment by bartusek27** [comment]
Same for me +1

**Comment by casperiv0** [comment]
Fixed now!
