### ISSUE TITLE
`t.map is not a function` when changing smart motorway signs

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1818]
### What version of Node.js are you using?

18.17.0

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

v1.73.2 6f1762a

### Describe the Bug

When changing a smart motorway sign and leaving any lane **above** as the default value it will cause the live map to present a client error for all users until the resource is reset.

Eg. changing lane 1 only will work, but changing 3 only will result in a crash.

### Expected Behavior

Changing a single lane without changing the other values should not result in an error.

### To Reproduce

![image](https://github.com/SnailyCAD/snaily-cadv4/assets/48030374/71642fa1-9c92-4185-bc4d-c579c4d0aa44)

**Comment by casperiv0** [comment]
This is partially fixed now. Will still have to verify something later today or tomorrow

**Comment by casperiv0** [comment]
tested and should be working again
