### ISSUE TITLE
Feature to assign already registered vehicles to existing business

### ISSUE THREAD

**Issue by bartusek27** [SnailyCAD/snaily-cadv4#1821]
### Describe the feature

Currently, there is only a possibility to create a new vehicle in the business dashboard. If the car already exists, in the client it is not possible to assign a vehicle to a business.

Ideally:
- have an API endpoint to add a vehicle to a business (maybe this can be accomplished by updating existing vehicle? PUT /v1/vehicles/)
- have a way to assign a business to a vehicle (I highly recommend having it in the same way as transferring the vehicle to different citizen - through special modal - rather than using Edit Vehicle modal

**Comment by casperiv0** [comment]
> have a way to assign a business to a vehicle (I highly recommend having it in the same way as transferring the vehicle to different citizen - through special modal - rather than using Edit Vehicle modal

It will use the same modal, however, will allow you to select to transfer to a business or a citizen.

Can it only be transferred to owned businesses or all businesses? @bartusek27

**Comment by bartusek27** [comment]
Good question - I would leave it to all since you have it the same for citizens - our own script also needs confirmation from the receiving party (so for example if some citizen would commit a crime with that vehicle, they could transfer that car to a different citizen or business to falsely implicate them).
