### ISSUE TITLE
10 Codes are Not Arranging When I adjust them in the Manage Values

### ISSUE THREAD

**Issue by Grey-704** [SnailyCAD/snaily-cadv4#1831]
### What version of Node.js are you using?

Unknown - Setup by Mellow Services

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

1.73.2

### Describe the Bug

When rearranging the 10 codes in the manage values section it does not rearrange the 10 codes in the LEO dashboard. 

### Expected Behavior

I was under the impression by talking to people in the discord support that rearranging in the manage values section would automatically adjust those in 10  codes on the LEO panel. It is not doing that for me. I did batch upload 10 codes into the CAD but I rearranged the codes and they did not change the order.

### To Reproduce

Navigated to admin tab (I am CAD owner) 
Navigate to Manage 10 Codes under values
Rearrange 10 codes in order of value  10-3, 10-5, 10-6 etc...
There is no option to save so I navigate to the Officer tab and open the dashboard and the 10 codes don't change.

**Comment by casperiv0** [comment]
This works fine after testing. Please make sure you don't instantly click away from the page as it may still be saving the order. I will implement a visual loader to let you know that's it been saved or is saving.
