### ISSUE TITLE
Potential Permissions Bug? Warrants

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1834]
### What version of Node.js are you using?

--

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

1.73.2

### Describe the Bug

![image](https://github.com/SnailyCAD/snaily-cadv4/assets/25211271/53b4bc88-6ad1-4e58-b088-32da3b6ea2b4)

### Expected Behavior

Shouldn't there only be one permission for Warrants?

**Comment by casperiv0** [comment]
This is intended :).
