### ISSUE TITLE
Ability to export whole citizen ticket/arrest report in one PDF

### ISSUE THREAD

**Issue by bartusek27** [SnailyCAD/snaily-cadv4#1837]
### Describe the feature

It makes sense for better RP to be able as LEO to export a PDF with all tickets/arrests/records in one PDF as a "Criminal Record". It can be then used for citizens to show it to their employers in realistic RP.

**Comment by bartusek27** [comment]
So the button would have multiple choices to generate - Full record, Felony record.
The reasoning behind this is that when a person wants his criminal record, they don't care about fines and care only about felony arrests so their employer can verify the have not been arrested for anything criminal. The full record is for detectives or citizens so they can see their full history.

You will not have any details of any crimes, just the same data as is in each row in Citizen search modal - 
Arrests/Fines:
Case Number / Notes / Violations / Officer (again, badge number would be preferrable) / Fines & Years / Payment Status / Created At

So the final layout would look like this:
Criminal Record (header)
Date of export / Badge number of an officer who created the export (nice to have)
Citizen Info (would leave the same as is in individual export, that one is great)
Arrests (one per row)
Fines (one per row, only in Full record export)

**Comment by casperiv0** [comment]
Will try to include this in the next release!
