### ISSUE TITLE
Cannot change order of penal code groups - unexpected error occurred

### ISSUE THREAD

**Issue by Alfa1561** [SnailyCAD/snaily-cadv4#1846]
### What version of Node.js are you using?

18.17.1

### What operating system are you using?

Linux

### What version of SnailyCAD are you currently using?

v1.74.0

### Describe the Bug

When trying to re-arrange the order of penal code groups, the following error occurs:
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/29956969/bfa3e8a6-6ae7-462c-866b-5fec4ba44e96)

### Expected Behavior

As I have owner permissions, I should be able to re-order the penal code groups as I please.

**Comment by casperiv0** [comment]
Do you have a `rank` of `Owner`? Or do you simply have `Manage CAD Settings` permissions? Since that's a very large difference. Will also investigate this issue.

**Comment by casperiv0** [comment]
Ah, nvm. This is now fixed. You still require `Manage Value Penal Code` permissions.
