### ISSUE TITLE
Vehicle Registration Page - Dropdowns are now broken since latest update

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1849]
### What version of Node.js are you using?

--

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

ed46dba

### Describe the Bug

Broken dropdowns on Register Vehicle page for example Registration Status

No errors in console

### Expected Behavior

Drop downs should be working

**Comment by casperiv0** [comment]
Already reported. Please standby
