### ISSUE TITLE
Description for emergency vehicles

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1878]
### Describe the feature

Please could we get a description added to the emergency vehicle values, that would then show in a tooltip when hovering over it on the dispatch pages.

### Additional Context

![image](https://github.com/SnailyCAD/snaily-cadv4/assets/48030374/5b37eefb-f809-486d-9f27-13c2034dd081)

**Comment by casperiv0** [comment]
Will try add this weekend. No clue when I have time thoughh
