### ISSUE TITLE
Changing the language value results in changing the link

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#188]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

When changing the language file value of myOfficers and myOfficersLogs in common.json it also changes the URL which then results in a 404.

![image](https://user-images.githubusercontent.com/48030374/147349026-51d3a33f-7450-4583-b229-ccd951a5f439.png)

### Expected Behavior

As with the rest of the language amendments I believe the expected behaviour is that it changes the clients value on display but retains the URL to ensure it can still reach the pages.

### To Reproduce

Change myOfficers and myOfficerLogs to a custom language value to also amend the URL link.

**Comment by jxckUK** [comment]
Just to add - is it expected behaviour for the 404 page to display an original navigation including links to disabled features such as Tow?

**Comment by Dev-CasperTheGhost** [comment]
> Just to add - is it expected behaviour for the 404 page to display an original navigation including links to disabled features such as Tow?

Yes, but also no. I'll get that fixed together with this issue!

**Comment by Dev-CasperTheGhost** [comment]
Wasn't able to fix that disabled features one yet. I'll fix it later since I have to go now.
