### ISSUE TITLE
Citizen cards not displaying correctly

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1882]
### What version of Node.js are you using?

18.17.0

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

v1.78.4

### Describe the Bug

Searching for a ped results in a faded blank screen.

### Expected Behavior

The card should return with the citizen details.

### To Reproduce

1. Search for a citizen
2. Select desired citizen
3. Screen dims but does not bring citizen card up

https://streamable.com/f74ev7 (User Provided)

**Comment by casperiv0** [comment]
Is it possible that the screen size is the factor here? Possible for this user to test on a larger display or zoom their page out to 50%?

**Comment by casperiv0** [comment]
Closed by 989e7779f
