### ISSUE TITLE
Callsign Example Incorrect

### ISSUE THREAD

**Issue by JemmaSinclair** [SnailyCAD/snaily-cadv4#1883]
### What version of Node.js are you using?

18.19.0

### What operating system are you using?

Ubuntu 20.04

### What version of SnailyCAD are you currently using?

1.78.4

### Describe the Bug

The callsign variables gives {callsign} for callsign 1, but this does not work.  {callsign1} does in fact work.

### Expected Behavior

The variables to be accurate (this seems a bit aggressive i just needed to put something for this required field).

**Comment by casperiv0** [comment]
I've updated the template to use `callsign1` since that's more correct. However, I've also added support for using `callsign` which will resolve to `callsign1`.
