### ISSUE TITLE
API Endpoints for Frameworks

### ISSUE THREAD

**Issue by DrMxrcy** [SnailyCAD/snaily-cadv4#1884]
### Describe the feature

Create API Endpoints to create and edit characters, linked to Snailycad through Discord or SteamID, to add the ability to integrate with frameworks like Nat215Ks Framework.

**Comment by casperiv0** [comment]
this already exists. https://docs.snailycad.org/docs/developer/public-api

**Comment by DrMxrcy** [comment]
> https://docs.snailycad.org/docs/developer/public-api

I see a generic import that is not linked to accounts in the API. The docs are slim so If you could put me on the right direction that be appreciated!
