### ISSUE TITLE
Citizens aren't released from jail automatically when time scaling is set to hours

### ISSUE THREAD

**Issue by AjaxTheGod** [SnailyCAD/snaily-cadv4#1885]
### What version of Node.js are you using?

1.78.5

### What operating system are you using?

Debian12

### What version of SnailyCAD are you currently using?

1.78.5

### Describe the Bug

Our time scaling is set to "Hours" and citizens aren't being automatically released from jail. We tested it with minutes and it worked just fine, however. Never tested with seconds.

### Expected Behavior

Citizens should be released from jail automatically when their sentence in CAD has concluded.

### To Reproduce

Set time scaling to hours in CAD settings and jail a citizen for 1 hour then check back. They will still be in jail.

**Comment by casperiv0** [comment]
This has already been fixed. See the Discord thread.
