### ISSUE TITLE
Permissions - Retroactively Edit Mass Permission

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1889]
### Describe the feature

I have an issue where for some reason Create Business permission is turned off for so many people even though its set to be allowed by default. People keep opening tickets to complain about it and its impossible to edit 5000 plus users.

is there a way we can retroactively update that permission for everyone? as its also not a permission that I see available to my needs in Discord roles either on the CAD

### Additional Context

Create Business permission is turned off for many people

I have this set. As it always has been. But its not working.
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/25211271/b9156865-9ea5-42ba-8a9f-7db1688945a3)

**Comment by Legacy-TacticalGamingInteractive** [comment]
@casperiv0

**Comment by casperiv0** [comment]
I get your notifications. Please don't ping here, for updates follow the Discord server. I'm currently very busy and don't have time to look into SnailyCAD things a whole lot anymore.

**Comment by Infiniti-Development** [comment]
Hey @Legacy-TacticalGamingInteractive if you reopen the setting's is it then turned off again or still on?

Because if it is off again check #1895

**Comment by Infiniti-Development** [comment]
@Legacy-TacticalGamingInteractive Did this work for you?

**Comment by Infiniti-Development** [comment]
No more reaction.
