### ISSUE TITLE
Add categories to penal codes

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#189]
### Describe the feature

In the new feature release for penal codes (https://github.com/SnailyCAD/snaily-cadv4/issues/131 and https://github.com/SnailyCAD/snaily-cadv4/pull/132) could we also get the ability to categorise them so they're a bit easier to manage?

**Comment by Dev-CasperTheGhost** [comment]
Could you elaborate the categorisation a bit more please?

**Comment by jxckUK** [comment]
> Could you elaborate the categorisation a bit more please?

Sure! - For example it would be good to be able to set up 'penal code categories' and place different codes into different categories.

I might have a code that relates to 'Public Order' and I can place it in that category and it'll be organised into that in both the admin panel and in the drop downs if possible? Maybe even asking people to select a category first, then showing them all the codes within that category?

In my example we're using penal codes as 'Charges' for UK and one example of a category and charge would be:

Public Order > Breach of the Peace

As you can imagine once you have a fair few of these codes/laws/charges it becomes quite lengthy.

**Comment by Dev-CasperTheGhost** [comment]
Possibly something like this for the categorization? Ignore the bad UI, it's just a simple sketch 😅 

https://user-images.githubusercontent.com/53900565/147364794-1b5bf1f9-8f52-4ab4-a62a-6e3d17dc3c09.mov

**Comment by jxckUK** [comment]
> Possibly something like this for the categorization? Ignore the bad UI, it's just a simple sketch 😅
> 
>  Screen.Recording.2021-12-24.at.17.31.15.mov

That looks fantastic!

**Comment by Dev-CasperTheGhost** [comment]
The grouping will looks something like this once finished:

https://user-images.githubusercontent.com/53900565/147553235-0aff5861-943b-4dda-9a40-ad7809b196c4.mov
