### ISSUE TITLE
Permissions Not Saving

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1895]
### What version of Node.js are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

v1.78.4 b3409e6

### Describe the Bug

When I go to manually save permissions for someone using the classic method. For example, adding one permission then simply hitting Save. It shows that its saved and it works. But sometime after that, if I hit refresh or load back into the CAD to check their permission. Then the permission is turned off again.

The permission I'm having issues with at this moment is the Create Business permission. I have not tried others.

### Expected Behavior

The permission to be changed to the proper state.

### To Reproduce

Change a permission.
Save.
Come back again in a few minutes.
Notice permission is not saved how you left it.

**Comment by casperiv0** [comment]
Most likely related to your Discord permissions overwriting your saved permissions.

**Comment by Legacy-TacticalGamingInteractive** [comment]
> Most likely related to your Discord permissions overwriting your saved permissions.

There is nothing in the Discord permissions that has anything to do with Business permissions though

**Comment by Legacy-TacticalGamingInteractive** [comment]
Do we have to hit Save twice or something? Is that the issue?

So we click Save here:
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/25211271/ccc77ac6-0c25-49a8-8e21-d303557bc9e6)

Do we have to then click Save again here?
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/25211271/7ebe75d9-8808-4e2d-be04-43516bd3d351)

**Comment by Infiniti-Development** [comment]
Hey @Legacy-TacticalGamingInteractive yes the best way is to press save every page you see when you edit something :)

**Comment by Infiniti-Development** [comment]
@Legacy-TacticalGamingInteractive Did this work for you?
