### ISSUE TITLE
User Search - Show Their Citizens and Units

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1896]
### Describe the feature

Can we have a feature added for more admin function.

If we go to Manage Users
And we search for a user.

Could we have a section added that shows us their Citizens created
Could we have a section added that shows their Officers created

Additionally if possible - typing in the users name also shows results on Manage Units and Manage Citizens search query.

This would make management so much easier. Because a lot of times someone gets fired from a department or something but we don't have their officer name on hand right away for example. And we need to remove them from a department, or other things. But the only search term we have is their username. Typing a username into the Manage Units or Citizens does not produce any results.

**Comment by Legacy-TacticalGamingInteractive** [comment]
@casperiv0 im not sure if its notifying you of new issues

**Comment by casperiv0** [comment]
Will allow username search for the citizen & unit management searches. This will indeed greatly improve your use
