### ISSUE TITLE
 Miscellaneous Tab Settings and CAD Open Graph Description Not Updating

### ISSUE THREAD

**Issue by MarshyMelloow** [SnailyCAD/snaily-cadv4#1898]
### What version of Node.js are you using?

18.19.0

### What operating system are you using?

Ubuntu 22.04

### What version of SnailyCAD are you currently using?

1.79.0

### Describe the Bug

When modifying value in any of the settings under the Miscellaneous tab, the changes are successfully saved in the database. However, they are not reflected properly when switching to a different tab and then returning to the Miscellaneous tab. The value resets to the default, even though the updated data is saved. After a full page refresh the data displays correctly. 

Additionally, the CAD Open Graph Description setting does not save at all.

### Expected Behavior

1. Changes made in the Miscellaneous tab settings should persist when switching between different setting categories.

2. The CAD Open Graph Description setting should save.

### To Reproduce

1. Go to the Miscellaneous tab.
2. Modify any setting value.
3. Save Changes.
4. Switch to a different setting category.
5. Return to the Miscellaneous category.
6. Notice that the modified value has reset to the default. (A full page refresh will display the correct updated value)

Regarding the CAD Open Graph Description, add some text and save the setting.

**Comment by casperiv0** [comment]
Fixed now!
