### ISSUE TITLE
Subject: CAD Display Issue - Only "Other" Category Visible

### ISSUE THREAD

**Issue by EWANZO101** [SnailyCAD/snaily-cadv4#1899]
### What version of Node.js are you using?

Node version: 20.11.0

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

Latest as of 31/01/2024 - 7:00 am UK TIME 

### Describe the Bug

 I am currently experiencing an issue with our CAD system where only the "other" category is displaying. Despite my attempts to resolve the issue by restarting the CAD, the problem persists.

### Expected Behavior

I have a dual CAD setup on different drives, and interestingly, the second CAD on a different drive does not exhibit this problem. I have also attempted to reinstall the CAD depicted in the attached screenshots without deleting the database, but unfortunately, the issue remains unresolved.

Our CAD system is meticulously configured with all the necessary categories to reflect a realistic representation of different types. I am unsure if there is a limit on the number of categories that can be displayed or if there might be another underlying issue affecting the visibility of categories.

Any insights or assistance you can provide in troubleshooting and resolving this matter would be greatly appreciated.

Thank you for your attention to this issue.

### To Reproduce

![image](https://github.com/SnailyCAD/snaily-cadv4/assets/107235474/70e4297c-5dda-4cf7-8b9a-c8b02936422a)

**Comment by casperiv0** [comment]
This is expected behaviour. You have enabled license exams, therefore only licenses can be granted via the License Exams section in LEO

**Comment by EWANZO101** [comment]
Thanks man u was right i feel so dumb for not noticing this
