### ISSUE TITLE
Cad keeps sending u it’s 10-7 randomly 

### ISSUE THREAD

**Issue by Ffemt** [SnailyCAD/snaily-cadv4#1903]
### What version of Node.js are you using?

Unk

### What operating system are you using?

Windows

### What version of SnailyCAD are you currently using?

Newest

### Describe the Bug

Keep sending units 10-7 after random amounts of time usually the one five minute range sometimes longer sometimes it doesn’t do it

### Expected Behavior

Keep sending units 10-7 after random amounts of time usually the one five minute range sometimes longer sometimes it doesn’t do it

**Comment by casperiv0** [comment]
Duplicate from Discord. No dubbel posting please.
