### ISSUE TITLE
Feature: Manage Rank Only

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1905]
### Describe the feature

Possible permission for people to be able to manage officer rank only. What I mean by that is change an officers rank. Right now it seems to be tied to Manage Unit which means they can also do so many other things. 

To be clear. I don't mean Manage Value Officer Rank. I mean Manage Unit Rank.
I don't want these people to be able to create ranks or edit ranks on the CAD as a whole.
I only want them to be able to change someone's rank when someone gets promoted or demoted.

### Additional Context

Recently, that causes a security issue. If someone decides they want to mess with peoples officers they can easily do that. We only want to add the rank editing feature to some people so they cannot edit peoples officers any deeper than that.

**Comment by WhitigolProd** [comment]
In most cases, anybody in a position of power to manage a unit's rank, would also be able to manage the reset of the fields found on the Manage Units page. Is this incorrect?

**Comment by Legacy-TacticalGamingInteractive** [comment]
> In most cases, anybody in a position of power to manage a unit's rank, would also be able to manage the reset of the fields found on the Manage Units page. Is this incorrect?

This unfortunately leaves security issues. Editing their Callsigns/Name etc. Some trolls can easily (and have) gone in and changed peoples Officer or Callsign unit names.

**Comment by WhitigolProd** [comment]
Interesting. I will take a look this evening and see what might be possible!

**Comment by Legacy-TacticalGamingInteractive** [comment]
> Interesting. I will take a look this evening and see what might be possible!

any luck

**Comment by Legacy-TacticalGamingInteractive** [comment]
> Apologies for not replying, I thought I had lol. I've found a few possible implementations that could work, however I haven't had any time to test any out. Unfortunately my day-to-day is still quite busy, so I'm not sure I can give a time estimate for when this will be looked into.

On this topic I also noticed that LEO Supervisor is missing some options for permissions. At the moment they cannot change anyones callsign for example. It doesnt let us put that option even in for them. Unless we make them admin.

![image](https://github.com/SnailyCAD/snaily-cadv4/assets/25211271/c34f9f24-0074-4e94-a66b-db14fdf8acce)
