### ISSUE TITLE
Import values as a .json list / logo image and background watermark 

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#192]
### Additional Ease of Use Admin Functions

**1) Please add an Import button for some admin values, this allows an admin to select a .json file with an uncountable amount of values. Eg. A list for 10-Codes. A list of vehicle models etc.** As some of our servers have over 1000 vehicles for instance. Entering one at a time is not feasible. **However,** I do think we also need a **custom text field option** instead of vehicles as a drop down list for the front end. So people can just name their car as they see fit for the model as we do in many other CADs rather than having a list of vehicles. Perhaps a toggle option for this method.

### GUI Design Options
1) Please add a small .png image option for the logo of server as well at the top.

2) Add an image as a background perhaps that fills the screen. That can have a transparency level. (I picture a server logo or screenshot from in game, thats barely visible but adds some visual flavour.

**Comment by Dev-CasperTheGhost** [comment]
Importing from a .json file is now supported! [Check the documentation how to get started](https://cad-docs.netlify.app/other/importing-values)

**Comment by ViolentMinds** [comment]
Awesome! Thank you for the quick turnaround on this!
