### ISSUE TITLE
Not able to install SnailyCAD

### ISSUE THREAD

**Issue by Fluffyss** [SnailyCAD/snaily-cadv4#1920]
### What version of Node.js are you using?

20.11.1

### What operating system are you using?

Windows Server 2022

### What version of SnailyCAD are you currently using?

1.79.0

### Describe the Bug

Error: Request failed with status code 404
    at Object.queryFn (http://<cadlink>/_next/static/chunks/5848-ddb02da021395a1d.js:1:1185)
  When starting up the website. Registering is impossible because you always get an error.
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/63029838/0d348ce6-68b0-45aa-8202-8c69274175e3)
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/63029838/5d738356-f875-4430-9979-17de21b27152)

### Expected Behavior

No errors shown at login/register
Being to register and login

### To Reproduce

Install SnailyCAD with the Manager app or follow the on-site instructions for manual installation.

**Comment by Fluffyss** [comment]
update: i found this error, but have no idea why it isnt accessible...
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/63029838/3808cc9a-cec6-4e1b-a60e-1118be8cefcd)

**Comment by MarshyMelloow** [comment]
Hello @Fluffyss, go ahead and update the cad and this should fix your issue. https://docs.snailycad.org/docs/installations/updating/methods/standalone

**Comment by EWANZO101** [comment]
It seems there might be a confusion regarding the API and CAD URLs, both pointing to the same address, namely https://ang.scheldestadrp.be/v1. To address this, I suggested a modification: changing https://ang.scheldestadrp.be/v1 to https://api-ang.scheldestadrp.be/v1
