### ISSUE TITLE
Vehicle Trim levels don't work

### ISSUE THREAD

**Issue by sl1ki0** [SnailyCAD/snaily-cadv4#1923]
### What version of Node.js are you using?

-

### What operating system are you using?

Alma Linux

### What version of SnailyCAD are you currently using?

1.79.1

### Describe the Bug

I added a trim level, then applied it to a specific car, but then I trying to register new car trim level doesn't appear and it simply shows "No Options"

### Expected Behavior

I expect to have ability to add trim level then registering the car

**Comment by Infiniti-Development** [comment]
please provide more info and photo's

**Comment by sl1ki0** [comment]
Original support thread >> https://discord.com/channels/792479048457912360/1226560773447356447

Text >> "Hello, I've setup a number of different trim levels and I've also applied these to their respective vehicles. However our civilian characters can't view or apply the trim levels to the vehicle upon registration. Need help please, thank you"

![image](https://github.com/SnailyCAD/snaily-cadv4/assets/126953670/c815fe00-bef6-421e-b0a0-e23b2f929206)
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/126953670/7812877a-dafe-40ae-97ff-569b1de73322)

**Comment by MarshyMelloow** [comment]
Trim levels where made optional while we investigate this issue.

**Comment by WhitigolProd** [comment]
> Trim levels where made optional while we investigate this issue.

Trim levels were already optional. The recent client changes do not impact this issue.

**Comment by MikeyInfiniteDev** [comment]
looking at the latest version the Trim Levels were not optional , we are looking further into the issue at the moment 

but for at the moment vehicles are able to be registerd without the trim level

**Comment by WhitigolProd** [comment]
Vehicles have always been able to be registered without trim level. The field was always optional, just not shown as optional in the client code.

It's always a good idea to test things before making changes 🙂

**Comment by Gameruxstudiosnz** [comment]
Was there something that's been changed in last month that could have changed the trim level 

As I had it work start may and end of April

**Comment by casperiv0** [comment]
Looks like this was indeed a bug which didn't allow a citizen to attach a trim level to the vehicle, even if it was defined in the settings. This is now fixed, a release will follow soon.
