### ISSUE TITLE
API Failure

### ISSUE THREAD

**Issue by bracarey** [SnailyCAD/snaily-cadv4#1926]
### What version of Node.js are you using?

20.13.1

### What operating system are you using?

Windows 10

### What version of SnailyCAD are you currently using?

1.79.1

### Describe the Bug

API failure to start with a TypeError: request.headers.split is not a function

### Expected Behavior

API should launch with no errors

### To Reproduce

![image1](https://github.com/SnailyCAD/snaily-cadv4/assets/44170328/11db53cd-a786-40d3-88e2-973a5a1a0be7)
Line 248 is the culprit. the above is the line currently.
the file path to this is \snaily-cadv4\node_modules\.pnpm\@sentry+node@7.81.0\node_modules\@sentry\node\cjs\integrations\undici\index.js
the fix I found is  below. Taking out the ".split('\r\n')" fixed the issue for me.
![image2](https://github.com/SnailyCAD/snaily-cadv4/assets/44170328/4ddb9a8a-d54d-4356-8e36-b044139e12f1)

**Comment by shivkun** [comment]
Hi there,

SnailyCAD only supports NodeJS v18.x, as stated in the docs. Please make sure you're using the appropriate version. 

Source: https://docs.snailycad.org/docs/installations/methods/standalone

**Comment by sl1ki0** [comment]
> Hi there,
> 
> SnailyCAD only supports NodeJS v18.x, as stated in the docs. Please make sure you're using the appropriate version.
> 
> Source: https://docs.snailycad.org/docs/installations/methods/standalone

It looks like undici problem which fixed in newer versions. Check out Github issue >> https://github.com/getsentry/sentry-javascript/issues/10936

**Comment by burnoutprojects** [comment]
I'm running the SnailyCAD with version 20 and I have not any issue. This issue is related to Sentry package not on SnailyCAD itself. I'm going to update and test the newest version of the package and I create a PR if working.

**Comment by Infiniti-Development** [comment]
Can you please send a screenshot or log file instead of the code it self.
We can't find an error in a code only in a log.
@bracarey

**Comment by sl1ki0** [comment]
> Can you please send a screenshot or log file instead of the code it self. We can't find an error in a code only in a log. @bracarey

What's not really a SnailyCAD code problem, that is the problem in Node modules, exacrly in Undici. Maybe switching versions can help
