### ISSUE TITLE
(LiveMap) Support more tiles

### ISSUE THREAD

**Issue by WhitigolProd** [SnailyCAD/snaily-cadv4#1947]
### Describe the feature

With more map additions coming to FiveM, like Roxwood, Cayo Perico, etc. Many of these map additions use additional map tiles to show in the pause menu. I think it would be awesome to support additional map tiles that would use the file names to position. (e.g., `minimap_sea_0_-1`, `minimap_sea_-1,-1`, etc)

This is by no means a feature that needs to be rushed. Feel free to ask for any additional information you might need for this feature.

Thanks! 🙂

**Comment by casperiv0** [comment]
Do you have a ZIP folder/link that I can use to test with additional map tiles?

**Comment by WhitigolProd** [comment]
I do not unfortunately. This was something that was mentioned to me by a community member. Roxwood hasn't yet expanded to the need for an additional map tile yet to my knowledge (besides just a small sliver of roadway), but they do plan to. So this feature request was more of a thing to prepare for the future of different map modifications.

**Comment by casperiv0** [comment]
Has this been tried before? Since this should already be supported actually.

**Comment by casperiv0** [comment]
Updated validation to support this now
