### ISSUE TITLE
"Allow multiple units with the same callsign and department per user" is broken

### ISSUE THREAD

**Issue by Georgie15** [SnailyCAD/snaily-cadv4#1948]
### What version of Node.js are you using?

18

### What operating system are you using?

Windows

### What version of SnailyCAD are you currently using?

1.80.0

### Describe the Bug

When enabling "Allow multiple units with the same callsign and department per user" in the CAD settings under features, officers are still unable to use the same call-sign, despite the feature being enabled to allow them.
![Screenshot_14](https://github.com/SnailyCAD/snaily-cadv4/assets/75462145/e117f9f0-bed0-4bdd-980b-0032bb96965c)
![Screenshot_15](https://github.com/SnailyCAD/snaily-cadv4/assets/75462145/b68d20cd-91c4-418a-808f-5167855af921)

### Expected Behavior

It should allow officers to use the same call-sign as an existing officer with this feature enabled.

### To Reproduce

Enable "Allow multiple units with the same callsign and department per user" in the CAD feature settings, then attempt to create the same call-sign as another officer.

**Comment by casperiv0** [comment]
This feature does work properly. The callsign `1B-01` is already used by another officer **by a different user**. Only the same user may have the same callsign for a different officer
