### ISSUE TITLE
[Function / Feature Request] IFRAME EMBEDDING Support

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#196]
### Describe the feature

Add ability to load the CAD in an Iframe. Currently if you do, you cannot login. It just reloads the page. This is imperative for using it in game with tablet scripts such as ones that use the command /cad to open it up in the game. They always use iframes. Most CAD's do work with these embeds such as Sonoran and Gen-Cad etc but unfortunately Snaily does not.

**Comment by ViolentMinds** [comment]
For reference http://nightfallroleplay.com/
Just a test page I'm running for now to show you.

**Comment by Dev-CasperTheGhost** [comment]
I've just pushed a commit that should allow this now. Let me know if you're able to test this out :)!

To enable it add the following to your .env file, make sure to run the command after updating the .env file.

```bash
SECURE_COOKIES_FOR_IFRAME="true"
```

**Comment by ViolentMinds** [comment]
After adding SECURE_COOKIES_FOR_IFRAME="true" then running the command and restarting client, api

With https:// turned on for my domain name, the CAD does not respond in the iframe at all
With http:// and no SSL turned on, the CAD loads, but will not allow logins.

An error message shows in the console for the API

`[2021-12-28T04:17:34.677] [ERROR] [TSED] - {
  method: 'POST',
  url: '/v1/user',
  headers: {
    host: 'MY IP TO CAD:8080',
    connection: 'keep-alive',
    'content-length': '0',
    accept: 'application/json, text/plain, */*',
    'is-from-dispatch': 'false',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36',
    session: 'snaily-cad-session=undefined',
    origin: 'MY IP TO CAD:3000/',
    referer: 'MY IP TO CAD:3000/',
    'accept-encoding': 'gzip, deflate',
    'accept-language': 'en-US,en;q=0.9'
  },
  body: {},
  query: {},
  params: {},
  reqId: 'f6c3d043c2fc4f4b8b3b2eae4724f276',
  time: 2021-12-28T10:17:34.677Z,
  duration: 6,
  error: {
    name: 'UNAUTHORIZED',
    message: 'Unauthorized',
    status: 401,
    errors: [],
    stack: undefined
  },
  stack: 'UNAUTHORIZED: Unauthorized\n' +
    '    at getSessionUser (C:\\Users\\Administrator\\Documents\\snaily-cadv4\\packages\\api\\src\\lib\\auth.ts:39:11)\n' +
    '    at IsAuth.use (C:\\Users\\Administrator\\Documents\\snaily-cadv4\\packages\\api\\src\\middlewares\\IsAuth.ts:58:34)\n' +
    '    at C:\\Users\\Administrator\\Documents\\snaily-cadv4\\node_modules\\@tsed\\platform-params\\src\\builder\\PlatformParams.ts:88:16'
}`

**Comment by Dev-CasperTheGhost** [comment]
You require working `https` to enable `SECURE_COOKIES_FOR_IFRAME`. Secure cookies require https. 

I recommend you setup a proxy such as NGINX or Apache to add a free SSL certificate from Let's Encrypt

**Comment by Dev-CasperTheGhost** [comment]
@ViolentMinds since you got SSL working; is this working now?

**Comment by ViolentMinds** [comment]
Iframe issue seems to be fixed now! Thank you!
