### ISSUE TITLE
Changing the status of another unit in the 

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#204]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

When you are in the dispatch portal and you change another units state, your unit will return back off duty.

### Expected Behavior

This may be by design but if so it should alert the unit that this will occur or at least provide some notification?

### To Reproduce

Have two units go to an on duty stage including your own officer, then in the dispatch portal trigger an update to the status of the other officer.

**Comment by Dev-CasperTheGhost** [comment]
Do you maybe have a video reproduction of this?

**Comment by jxckUK** [comment]
https://user-images.githubusercontent.com/48030374/147677187-9ff69e79-238b-4fb7-bf5d-acd8b740ac86.mp4

**Comment by Dev-CasperTheGhost** [comment]
Should be all fixed!
