### ISSUE TITLE
Allow disabling of weapon registration

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#205]
### Describe the feature

Similar to the fine grained controls for Tow, Courthouse etc under Features. Allow the ability for us to disable weapon registration.

### Additional Context

For UK roleplay weapons aren't something you'd want civilians registering and as such it would be good if like other features there was a way to disable this.

I really like the ability to disable certain features and functionality and I'd like to see this extended to more sections. As well as areas like disabling the CCW field or even just fine grained controls for all of the fields in a user profile that are not essential to the cads operation.

I'd also like to see the language changes be more consistent for example some areas that reflect '911' seem to be unaffected by the language file changes.

**Comment by Dev-CasperTheGhost** [comment]
> or even just fine grained controls for all of the fields in a user profile that are not essential to the cads operation.

I think this is possible

> I'd also like to see the language changes be more consistent for example some areas that reflect '911' seem to be unaffected by the language file changes.

If there are translations missing, this would actually be defined as a bug but I'll go over the code and find some.

**Comment by jxckUK** [comment]
https://user-images.githubusercontent.com/48030374/147677153-f2881ae2-c7e6-4758-9bd0-be85462c56bc.mp4

**Comment by Dev-CasperTheGhost** [comment]
@jxckUK are you able to open a separate issue with missing translations you find? That'd be helpful for me to add them :)

**Comment by jxckUK** [comment]
> @jxckUK are you able to open a separate issue with missing translations you find? That'd be helpful for me to add them :)

Sure can - let me collect it all together and submit it. I know I might need to update my language file as well since there's been a few updates.

**Comment by Dev-CasperTheGhost** [comment]
This would also disable weapon search and such right?

**Comment by jxckUK** [comment]
> This would also disable weapon search and such right?

That would be the ideal scenario to be honest - just a total 'disable' of that feature. Similar to how businesses and towing are currently handled.

In the UK there isn't really the same requirement for weapon searches, registration and licensing. 

It's not a major missing 'feature' as for most use cases I'd expect this to be core functionality, but it would be a nice to have to extend the flexibility of the CAD to different regions.

**Comment by Dev-CasperTheGhost** [comment]
Alright cool!

>  but it would be a nice to have to extend the flexibility of the CAD to different regions.

Maybe I'll figure out a good system in the future to further manage the CAD, what we have now works 😄
