### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#207]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

After I updated my language files its only a couple that I still can't seem to update:

- dispatch/map - "Create 911 Call"
- admin/dashboard - "in BOLO"

### Expected Behavior

These are the only translations that you cannot amend currently via the JSON language files.

**Comment by jxckUK** [comment]
Found a new really minor one so didn't want to open another issue, on the Citizen homepage the title doesn't seem to be tied to a translation as I've modified them all but this one remains.

![image](https://user-images.githubusercontent.com/48030374/150782220-06f32b5d-c455-439c-9450-52cdc95141a9.png)

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed now 🚀!

**Comment by jxckUK** [comment]
Just happened to find another, sorry! D: 

![image](https://user-images.githubusercontent.com/48030374/150783273-c499d7e9-ca8d-424b-b800-aeb1e10e1023.png)

Unless I'm missing something I think where it says BOLOs/BOLO isn't a translatable entry.

**Comment by Dev-CasperTheGhost** [comment]
No worries haha! Will be fixed later today!

**Comment by Dev-CasperTheGhost** [comment]
Should all be fixed in this commit 488dd27
