### ISSUE TITLE
Recalling/Cancelling Warrants

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#208]
### Describe the feature

At the moment warrants can be issued but cannot be re-called or cancelled for civilians.

It would be good if the message that notified you of an outstanding warrant also had a button allowing you to 'revoke' the active warrant.

### Additional Context

![image](https://user-images.githubusercontent.com/48030374/147687307-78af9c84-4873-47ec-b11d-4f85efa48fe3.png)

**Comment by Dev-CasperTheGhost** [comment]
You can now change the status of a warrant and revoke the warrants via name search! Enjoy
