### ISSUE TITLE
Enhanced Logging

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#209]
### Describe the feature

This is quite a broad suggestion as it would cover a large amount of the activities undertaken within the client. Some form of overall 'event' log would be really nice.

The ability to see what users have done inside of the CAD such as:

- Arrest Reports
- Warrants
- Warnings
- Tickets

It would be good to have the ability to see this as an administrator or even as a dispatcher. It would be ideal if the format matched the existing 'Officer Logs' section where we could filter events by the type above.

Additionally it would be nice if this also had contextual links that could send you to the specific record that had been logged.

### Additional Context

![image](https://user-images.githubusercontent.com/48030374/147687629-60e2b880-c1a9-4f53-8209-5a1001f4d664.png)

**Comment by Dev-CasperTheGhost** [comment]
Would this only be arrest reports, warrants, warnings and tickets, or more data? Would this page be located per citizen or per user in admin management?

**Comment by jxckUK** [comment]
> Would this only be arrest reports, warrants, warnings and tickets, or more data? Would this page be located per citizen or per user in admin management?

Ideally this would cover all LEO activities against a citizen yes - would be good if this activity was visible to LEO supervisors. Could be all activities from all officers with a filter option for individual officers and individual event types?

**Comment by Dev-CasperTheGhost** [comment]
Where would this page be located at? In the officer dropdown, admin management sidebar, ...?

**Comment by jxckUK** [comment]
> Where would this page be located at? In the officer dropdown, admin management sidebar, ...?

Good question - maybe the best place for it is under the Dispatch dropdown? Otherwise yes probably the admin management sidebar.

**Comment by Dev-CasperTheGhost** [comment]
I'd guess it would look something like this?

https://user-images.githubusercontent.com/53900565/147773380-1077ffb7-7146-49f0-887d-2e3780214112.mov

**Comment by jxckUK** [comment]
> I'd guess it would look something like this?
> 
>  2021-12-30.18-10-14.mov

Yeah looks good to me! - would you be able to see what officer had applied that record and what timestamp? That would be quite important.

**Comment by Dev-CasperTheGhost** [comment]
> > I'd guess it would look something like this?
> > 2021-12-30.18-10-14.mov
> 
> Yeah looks good to me! - would you be able to see what officer had applied that record and what timestamp? That would be quite important.

Yup!

**Comment by Dev-CasperTheGhost** [comment]
this should be the final UI, let me know if you've got some improvements to be made :)

https://user-images.githubusercontent.com/53900565/147811296-0a000fb2-ee3e-466b-8ea4-06b8b8065cd0.mov
