### ISSUE TITLE
[BUG] Update Issue - Cannot Start API - Something to do with Weapons

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#214]
### What version of Node.js are you using?
16.13.1

### What operating system are you using?
Windows Server 2019

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/147714400-0060eecc-6a4b-4e53-a6f2-c7949470f3a2.png)

Update did not go through when starting the api. I followed the usual update steps as per the documentation.

**_Note_**
_A fresh install of the CAD from the start using the latest release beta 27 works. Its just the update that would not._

### Expected Behavior

To be able to start the API.

### To Reproduce

I simply ran the latest update as per instructions in the documentation and when I got to the final step thats what happened in the screenshot.

**Comment by Dev-CasperTheGhost** [comment]
Make sure to run `yarn workspace @snailycad/api generate` after updating.
