### ISSUE TITLE
[BUG] Error on Edit Penal Code

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#217]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### Describe the Bug

Getting error when press Save button
![fXWSRcU 1](https://user-images.githubusercontent.com/4976837/147752266-5d8ac47e-5f3f-40d8-aad7-6c1aeb7a3b4c.png)

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed now!
