### ISSUE TITLE
[BUG] Edit Citizen - Eye/Hair Input Field Errors

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#219]
### What version of Node.js are you using?

16.13.1

### What operating system are you using?

Windows Server 2019

### Describe the Bug

Edit Citizen page does not let you edit Hair Colour or Eye Colour. It bugs out and somehow they become linked together.

### Expected Behavior

Ability to adjust Eye Colour or Hair Colour

### To Reproduce

Just create a new citizen and give it a try.

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed now!
