### ISSUE TITLE
[FEATURE REQUESTS] Input Field Options, Top Menu Wording, Top Menu Logo & Authorization Headers / Landing Index Page

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#220]
### Describe the feature

**Great work so far**, very excited for the progress of V4! Some constructive feedback, if I may request. :) 

1) **Vehicle Models** - Add a custom enterable text input field option that is optional in case people have a vehicle/boat/aircraft whatever that is not on the list.
_____________________________________

2) **Weapon Models** - Same request. Especially since in FiveM for instance people are often pretending to have real life weapons and have different names for them, they might want to put a custom one in. 

Admin Option? Have custom vehicle & weapon fields be an option for Admin to turn on and off. Would be nice to have.
_______________________________________

3) **Top Menu** - Ability to change "Officers" word to "LEO", under FD/EMS ability to change "Deputies" to "Firefighter" and and add "Paramedic" maybe, or simply "FD/EMS Member" instead.

_______________________________________

4) **Small Logo** Image Option In Menu Top Left (Imgur/Upload) Maybe 256x100px.

_______________________________________

5) **_Function/Starting The CAD_**
Please see if there is a way you can add HTTP Authorization Headers so the api can load even though the CAD is displayed in a iframe/div container. (Non-SSL option) - so the connection doesn't break. It has been done before. Perhaps even just make a landing index page that simply has a button where you click it, which then loads the api and client. So a separate index page from the main client/api that can be independent of the CAD instead of the existing one or alternatively just a very simple welcome page that takes you to the login.

### Additional Context

_Regarding Starting The CAD_
A major drawback is the way the CAD is initialized. Especially for those of us who cannot use SSL or Linux Systems to host it where NGINX is not a working viable option either. It would be nice to be more standalone in the sense of being able to set up the parameters more easily for a URL instead of running off of an IP address. As you cannot secure an IP address with SSL and honestly proxy setup is a pain for novice users.. This makes it hard to self host. I love the CAD so far but its a major obstacle to overcome. I am fairly tech savvy too so I can only imagine the pain it would for some others who would give up and go to another provider.

**Comment by Dev-CasperTheGhost** [comment]
> 4. Small Logo Image Option In Menu Top Left (Imgur/Upload) Maybe 256x100px.

Would this replace the CAD's name? So instead of the name it would show the icon?

**Comment by Dev-CasperTheGhost** [comment]
> Admin Option? Have custom vehicle & weapon fields be an option for Admin to turn on and off. Would be nice to have.

Will have this. Sorry for the bad naming on that feature lol, the system I had in the beginning was bad for handling disabled features

![image](https://user-images.githubusercontent.com/53900565/147812797-d1076da7-a0e4-432c-8da0-0bc005b9b969.png)

**Comment by ViolentMinds** [comment]
> > 4. Small Logo Image Option In Menu Top Left (Imgur/Upload) Maybe 256x100px.
> 
> Would this replace the CAD's name? So instead of the name it would show the icon?

No that would be favicon.ico, thats another thing though haha. I meant up here 
![image](https://user-images.githubusercontent.com/25211271/147813311-1b5eca8d-8002-4b27-8f30-0a5bedb7cdbb.png)

**Comment by Dev-CasperTheGhost** [comment]
Yeah, that's what I meant 😅!

**Comment by ViolentMinds** [comment]
> Yeah, that's what I meant 😅!

Though we could do this too 
![image](https://user-images.githubusercontent.com/25211271/147813436-1d9408c5-e8e4-4169-a4e0-8a1c1a8d774a.png)

**Comment by Dev-CasperTheGhost** [comment]
Yeah, the favicon is what I'll be adding soon. The image in the top left next to the CAD's name is what [I meant here](https://github.com/SnailyCAD/snaily-cadv4/issues/220#issuecomment-1003308303)

**Comment by Dev-CasperTheGhost** [comment]
> 5. Function/Starting The CAD
Please see if there is a way you can add HTTP Authorization Headers so the api can load even though the CAD is displayed in a iframe/div container. (Non-SSL option) - so the connection doesn't break. It has been done before. Perhaps even just make a landing index page that simply has a button where you click it, which then loads the api and client. So a separate index page from the main client/api that can be independent of the CAD instead of the existing one or alternatively just a very simple welcome page that takes you to the login.

Hm, I think this is possible, but it should be a flag  set in the .env file because this will make the CAD a bit less secure

**Comment by Dev-CasperTheGhost** [comment]
> I think this is possible, but it should be a flag set in the .env file because this will make the CAD a bit less secure

actually, this won't be so simple.. The CAD does server-side requests as well which cannot access localStorage so either I'll have to find some magic to postpone server-side requests to the client, or find a better way to store the token on the client

**Comment by Dev-CasperTheGhost** [comment]
Favicons are now supported: https://cad-docs.netlify.app/other/favicon

**Comment by ViolentMinds** [comment]
Outstanding Requests From This Would Be:

- Small Logo Image Option In Menu Top Left (Imgur/Upload) Maybe 256x100px.
![image](https://user-images.githubusercontent.com/25211271/148481770-a1e75640-3c91-4888-86ad-84cc51b4663e.png)

- Top Menu - Ability to change "Officers" word to "LEO", under FD/EMS ability to change "Deputies" to "Firefighter" and and add "Paramedic" maybe, or simply "FD/EMS Member" instead.

It would be cool! Or if  you can let me know if I can change these words in from the database? If it works like that. Or if there is some way I can edit a file. But I guess it would end up getting overwritten on an update probably. But if its possible to edit that would be cool. 

Thank you! If these features are not possible at this time, noted. I will leave this open though for now.

**Comment by Dev-CasperTheGhost** [comment]
> It would be cool! Or if you can let me know if I can change these words in from the database? If it works like that. Or if there is some way I can edit a file. But I guess it would end up getting overwritten on an update probably. But if its possible to edit that would be cool.

This is already possible! Check the docs: https://cad-docs.netlify.app/other/translating#adding-a-custom-locale

**Comment by Dev-CasperTheGhost** [comment]
> Small Logo Image Option In Menu Top Left (Imgur/Upload) Maybe 256x100px.
![image](https://user-images.githubusercontent.com/53900565/148506931-adbea3e7-b3b8-4742-833a-cb8d9964bd31.png)


Soon:tm:!
![image](https://user-images.githubusercontent.com/53900565/148506923-2e9377f9-0edf-430a-b16e-d867a4cde49a.png)

**Comment by Dev-CasperTheGhost** [comment]
Alrighty, all these requests should be implemented now 🎉!
