### ISSUE TITLE
Discord hook doesn't show complete callsign

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#230]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

![image](https://user-images.githubusercontent.com/48030374/147876116-5eba8def-9b79-48c4-b3bb-371b665cebc3.png)

As you can see it is only posting through the first callsign record and not both of them.

### Expected Behavior

It would be nice if the hook followed the callsign format that is set in the administration section.

Ideally (possibly something for me to move to feature requests) this hook would be amendable in the admin panel.

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed now!
