### ISSUE TITLE
[BUG] Regarding input form and db maybe

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#231]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/147880360-5b991c69-138e-4ea5-89fd-db1d00338bc5.png)

### Expected Behavior

Building the client after the latest update.

**Comment by Dev-CasperTheGhost** [comment]
try this:

1. `yarn`
2. `yarn workspace @snailycad/schemas build`
3. `yarn`
4. restart API/client

**Comment by ViolentMinds** [comment]
I've ran that a few times now, restarted the update process from the beginning as per documentation. For some reason it just doesn't want to build that. Maybe I should delete that directory and retry? Hmm

**Comment by Dev-CasperTheGhost** [comment]
Yeah, can you also try removing the node_modules folder in the root?

**Comment by ViolentMinds** [comment]
I removed the node_modules in root and was able to past that error, but now there is another I've never seen before. Could be a windows issue. But I don't know. Any thoughts?

![image](https://user-images.githubusercontent.com/25211271/147881111-11cc7d2c-6463-4bee-87dc-171692e1dd94.png)

**Comment by Dev-CasperTheGhost** [comment]
A simple restart of your PC should work, this error means the port is in-use

**Comment by Dev-CasperTheGhost** [comment]
Any news on this @ViolentMinds?

**Comment by ViolentMinds** [comment]
I had to reinstall uninstall node.js, npm completely then reinstall, then install the cad entirely as well. not sure what happened there. 

as for the port issue for some reason the system stopped listening to any ports lol so i had to renable.

we can close this now
