### ISSUE TITLE
[FEATURE REQUEST] Security Feature

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#233]
### Describe the feature

**1) Automatically direct people to `/auth/login` instead of `/en/citizen`** by default. 
 _Or make it an option in admin panel for server owner to choose which they prefer?_

**2) Give the option for people to click a checkbox that says** **"Log Me In Automatically"**

_This way they can choose if they want to have cookies be cached or not essentially.
Cookies otherwise will be temporary and deleted when the browser session exits I believe._

**Comment by Dev-CasperTheGhost** [comment]
> 1) Automatically direct people to /auth/login instead of /en/citizen by default.
Or make it an option in admin panel for server owner to choose which they prefer?

I can do:

-> Authorized: redirect to /en/citizen
-> not authorized: redirect to /auth/login

Although this may not work instantly since the redirect seems to be cached.

**Comment by Dev-CasperTheGhost** [comment]
> 2) Give the option for people to click a checkbox that says "Log Me In Automatically"

This way they can choose if they want to have cookies be cached or not essentially.
Cookies otherwise will be temporary and deleted when the browser session exits I believe.

When it's cached, would this mean you'd want the user to be logged in all the time? (never gets logged out)

**Comment by ViolentMinds** [comment]
> > 2. Give the option for people to click a checkbox that says "Log Me In Automatically"
> >    This way they can choose if they want to have cookies be cached or not essentially.
> >    Cookies otherwise will be temporary and deleted when the browser session exits I believe.
> 
> When it's cached, would this mean you'd want the user to be logged in all the time? (never gets logged out)

Yes, most websites when you choose Log Me In Automatically the cookie is saved permanently and they are automatically logged in when they visit the CAD so they basically will bypass the login screen. But only if they so choose. Rather than having it be automatic. Because some people don't want to login automatically - in case they share their PC with more than one person for example.

**Comment by Dev-CasperTheGhost** [comment]
this feature would be useful, I'm not sure whether it's the most secure option to do though. I'll need to take a deeper look into this stuff.

**Comment by Dev-CasperTheGhost** [comment]
This seems to be harder then anticipated so I'm going to place this in the backlog and close this for now.
