### ISSUE TITLE
Arrest/Warning/Ticket Penal Code Description

### ISSUE THREAD

**Issue by Wilson159** [SnailyCAD/snaily-cadv4#239]
### Describe the feature

When selecting a penal code, it would be nice to see the description of the penal code.

Also, for some reason, the written warning wont let me select a penal code

**Comment by Dev-CasperTheGhost** [comment]
> Also, for some reason, the written warning wont let me select a penal code

Only penal codes that have `Warning Applicable` are selectable

**Comment by Wilson159** [comment]
> > Also, for some reason, the written warning wont let me select a penal code
> 
> Only penal codes that have `Warning Applicable` are selectable

Ah I gotchu, what do you think about the suggestion at the top though? 😉

**Comment by Dev-CasperTheGhost** [comment]
> Ah I gotchu, what do you think about the suggestion at the top though? 😉

Yup, I will have to look into how the style it.

**Comment by Dev-CasperTheGhost** [comment]
When hovering over the penal code, it will display a simple popup with the title and description. Don't mind the bad test data 😅!

https://user-images.githubusercontent.com/53900565/148228672-cd24c685-b4f7-45dd-a919-41b668bbd5d4.mov

**Comment by Wilson159** [comment]
Thats kinda bussin ngl

**Comment by Wilson159** [comment]
d
