### ISSUE TITLE
Penal code "groups" in dropdown

### ISSUE THREAD

**Issue by Wilson159** [SnailyCAD/snaily-cadv4#241]
### Describe the feature

Add penal code "groups" to the dropdown for selecting the penal code for an arrest/warning/ticket, makes it a lot easier to find what you're looking for

**Comment by Dev-CasperTheGhost** [comment]
Would this show "Group here - Penal code name", or would it be a list of the groups, when a group is pressed it would show all the penal codes in that group? @Wilson159

**Comment by Wilson159** [comment]
> Would this show "Group here - Penal code name", or would it be a list of the groups, when a group is pressed it would show all the penal codes in that group? @Wilson159 

the second one 😅

**Comment by Wilson159** [comment]
Yeah that definitely works, way better than having to sort through the list of all of them to find the one you wanted! 😅

**Comment by ViolentMinds** [comment]
This is a great feature, a solid suggestion! Love it!
