### ISSUE TITLE
[FEATURE REQUESTS] Text Color / Officer Dashboard Addition / Department Approval / Business Approval / Department Admin User etc

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#248]
### Describe the feature

1) Categories: Content Text Color Change
Change the color of the text to be grey so it is different than "Drivers License/Pilot License" label color etc.
Easier to read this way
--- SOLVED/APPROVED
______________________________________________________________________

2) Change "Surname" text to "Surname/Last Name"
(nobody in USA knows what Surname means lol)
--- SOLVED/APPROVED
______________________________________________________________________

3) Add User Name to top-right of CAD beside the people avatar icon
--- SOLVED/APPROVED
______________________________________________________________________

4) Ability for Officer to be in multiple Divisions
--- SOLVED/APPROVED
______________________________________________________________________
5) **Officer Dashboard Addition**
Add **Truck Logs** to be able to be searched up

_Log Results:_ 
Date, Time
Name of Citizen
--- SOLVED/APPROVED
______________________________________________________________________

**Department Permissions & Roles**
______________________________________________________________________
1) Department Whitelist/Approval Feature

2) New Admin Type called _Department Admin_
- _Owner/Admin_ can give _Department Admin_ role to _Users_

- Department Admin can approve Officers into their Department only
- Department Admin can make Officer a LEO Supervisor of their Department only
- Department Admin can edit Division/Callsign/Rank of Officers in their Department

- LEO Supervisor can edit Division/Callsign/Rank of Officers only

______________________________________________________________________
**Business Approval**
1) Please add Whitelist for people to be able to Create Business. Admin must approve. Because this way people cannot spam businesses/fake businesses/troll etc.
--- SOLVED/APPROVED

**Comment by Dev-CasperTheGhost** [comment]
> 2. Change "Surname" text to "Surname/Last Name"
(nobody in USA knows what Surname means lol)


This is already possible! Check the docs: https://cad-docs.netlify.app/other/translating#adding-a-custom-locale

**Comment by Dev-CasperTheGhost** [comment]
> Add User Name to top-right of CAD beside the people avatar icon

Coming very soon! I'm actually a big fan of this one :)

https://user-images.githubusercontent.com/53900565/148500283-fe854cd1-7b4c-4780-94b1-e8ea4db8b232.mov

**Comment by Dev-CasperTheGhost** [comment]
> 5. 
    Officer Dashboard Addition
    Add Truck Logs to be able to be searched up
Log Results:
Date, Time
Name of Citizen

Would the officer search by name or by plate of the truck-log vehicle, or both?

**Comment by ViolentMinds** [comment]
> > Officer Dashboard Addition
> > Add Truck Logs to be able to be searched up
> > Log Results:
> > Date, Time
> > Name of Citizen
> 
> Would the officer search by name or by plate of the truck-log vehicle, or both?

Truck Log should be linked to the Plate I think so that way they can find all logs linked to this vehicle. 
When LEO are inspecting if a driver has checked their truck they must have logs written for that specific truck in real life. So it makes sense like that :)

**Comment by Dev-CasperTheGhost** [comment]
> Truck Log should be linked to the Plate I think so that way they can find all logs linked to this vehicle.

Yup, when entering a vehicle for truck-logs, all data linked to that vehicle can be retrieved. Should this have its own modal or should there be a table shown in the vehicle search?

**Comment by Dev-CasperTheGhost** [comment]
> 1. Categories: Content Text Color Change
Change the color of the text to be grey so it is different than "Drivers License/Pilot License" label color etc.
Easier to read this way

Not exactly sure what you mean here, can you elaborate?

**Comment by ViolentMinds** [comment]
> > Truck Log should be linked to the Plate I think so that way they can find all logs linked to this vehicle.
> 
> Yup, when entering a vehicle for truck-logs, all data linked to that vehicle can be retrieved. Should this have its own modal or should there be a table shown in the vehicle search?

Would be nice to have its own table in the vehicle search

> > 1. Categories: Content Text Color Change
> >    Change the color of the text to be grey so it is different than "Drivers License/Pilot License" label color etc.
> >    Easier to read this way
> 
> Not exactly sure what you mean here, can you elaborate?

The Values should be Grey color maybe so its easier to read
![image](https://user-images.githubusercontent.com/25211271/148513340-e3f86cbd-e141-4cc8-a571-b6647090b17a.png)

See how hard it is to read "Valid" text it kind of just blends in with everything
![image](https://user-images.githubusercontent.com/25211271/148513451-28ebb35a-6a7d-4537-83b4-346ad2d4a41d.png)

**Comment by Dev-CasperTheGhost** [comment]
> The Values should be Grey color maybe so its easier to read

Maybe something like this is a bit more readable?

![image](https://user-images.githubusercontent.com/53900565/148517166-08ee9b6b-6643-465c-aa33-a2d0b5f71a6b.png)

**Comment by ViolentMinds** [comment]
Yes, I like it :)

**Comment by Dev-CasperTheGhost** [comment]
Cool! Should be all done very soon!

![image](https://user-images.githubusercontent.com/53900565/148521137-80a87dbe-e3de-4921-afc2-f68ec95d0f01.png)

**Comment by ViolentMinds** [comment]
Also I added Business Approvals and let me know about Department Permissions & Roles when you get time
Thank you for these great updates so fast!

**Comment by Dev-CasperTheGhost** [comment]
> Also I added Business Approvals and let me know about Department Permissions & Roles when you get time

Yup, currently working on business approval. Still thinking about the department permissions.

**Comment by Dev-CasperTheGhost** [comment]
> Ability for Officer to be in multiple Divisions

An officer can be in multiple divisions at the same time?

**Comment by ViolentMinds** [comment]
> > Ability for Officer to be in multiple Divisions
> 
> An officer can be in multiple divisions at the same time?

Yes lol. For example....

You can be part of AIR UNIT but also be in TRAFFIC DIVISION or something like that. Since AIR UNIT aren't always in the sky.
Or... SWAT OFFICER (on call) but also DETECTIVE BUREAU for example.
or... DOT ENFORCEMENT VISION & MAINTENANCE DIVSION
You could be MARINE DIVISION but also part of TRAFFIC DIVISION for example.
:)

Since not all RP are active for every division at the same time people need/want to be able to be doing both when the time is needed.

**Comment by Dev-CasperTheGhost** [comment]
I'd guess it looks like this in the table then: (for example)
![image](https://user-images.githubusercontent.com/53900565/148635329-01c97bf8-aed8-45a9-b0ca-cf2dfe512c0d.png)

**Comment by ViolentMinds** [comment]
Seems fine to me :)

**Comment by Dev-CasperTheGhost** [comment]
Would there be a max set of divisions an officer can be in?

**Comment by ViolentMinds** [comment]
> Would there be a max set of divisions an officer can be in?

Its probably best to not limit it, as some peoples servers might not care.
Personally though I'd say 4.

**Comment by Dev-CasperTheGhost** [comment]
> Its probably best to not limit it, as some peoples servers might not care.
Personally though I'd say 4.

I'll make it an option in the cad-settings. Default is no-limit, but CAD owners can also set it back to 1 if they only allow 1 division, etc.

**Comment by Dev-CasperTheGhost** [comment]
How would the callsign be generated for the divisions? Would it take it for the first division?

**Comment by ViolentMinds** [comment]
> How would the callsign be generated for the divisions? Would it take it for the first division?

Call sign can be the same as the main callsign for the officer. Usually they have the same callsign. Just one callsign for the entire department no matter which division they are in. Its easier that way to organize. Often times just one callsign and one badge number. :)

**Comment by pp2amd6** [comment]
> 4\. Ability for Officer to be in multiple Divisions

I agree. This situation is quite common on RP servers.



> 2\. New Admin Type called _Department Admin_

The "chief of the department" would be more correct

**Comment by ViolentMinds** [comment]
> > 4. Ability for Officer to be in multiple Divisions
> 
> I agree. This situation is quite common on RP servers.
> 
> > 2. New Admin Type called _Department Admin_
> 
> The "chief of the department" would be more correct

They can call it whatever they want in their server. They won't see it in the backend which is what I meant.
Department Admin is OOC.
Also not every department has a chief. Some go by Commissioner etc.

**Comment by Dev-CasperTheGhost** [comment]
> Department Admin can make Officer a LEO Supervisor of their Department only

Would this mean when an admin selects the Department admin role, they need to select a department they can manage?

**Comment by ViolentMinds** [comment]
Yes

**Comment by ViolentMinds** [comment]
It is working like Businesses. Except that Owner/Admin can make someone a
Department Admin. And Owner/Admin can select what department the Department
Admin can administer.

Otherwise people will try to administer a Department they are not in if
they are trying to cause problems.
