### ISSUE TITLE
[FEATURE REQUEST] - Occupation

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#249]
### Describe the feature

Please add OCCUPATION field to the Citizen info so someone can type in what they do for work.

**Comment by Dev-CasperTheGhost** [comment]
Wouldn't this defeat the purpose of having businesses in the CAD 😅? Citizens can already join and create citizens, this field should also show up on name search, etc

**Comment by ViolentMinds** [comment]
> Wouldn't this defeat the purpose of having businesses in the CAD 😅? Citizens can already join and create citizens, this field should also show up on name search, etc

Not at all because not every business is official. In our server we only have a select few businesses that we know are serious active RPers with a roster of citizens that could be in it. 

But for everyone else they like to just put a few things about what they do for their back story as a personality. Some extra info for LEO to find out about them etc.
