### ISSUE TITLE
[BUG] Display Bug - Status

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#250]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/148498754-386b4a02-740c-452e-8d9a-cbd6120bfff3.png)

### Expected Behavior

Should be aligned with the other sections. I'm not sure why its doing that.

**Comment by Dev-CasperTheGhost** [comment]
I'm unable to reproduce this bug. However, I did a few small changes that could fix this

![image](https://user-images.githubusercontent.com/53900565/148499486-4aff2de3-dfa9-493f-8b0b-9e92d059a91c.png)

**Comment by ViolentMinds** [comment]
Hmm might have to do with padding or something.
Alright, thanks though for trying! Its not a major problem :)
