### ISSUE TITLE
[FEATURE REQUEST] Bolo Text Alignment Justify + Login Screen Design Options / Logo / Background Image

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#260]
### Describe the feature

**BOLO TEXT ALIGNMENT**
![image](https://user-images.githubusercontent.com/25211271/148637565-7877800d-998f-449c-81f4-54dc5583e845.png)

Can we make these text blocks justify alignment?

For example:
![image](https://user-images.githubusercontent.com/25211271/148637601-8f3ac678-47b6-47dd-8259-8bf48c10139a.png)

**LOGIN SCREEN DESIGN OPTIONS**
1) Optional Logo or Text / Maximum Width Maybe Same As Login Form or 100px More
2) Full page cover background image that scales with width of window. Zindex -1 so it stays behind the logo and login form.

![image](https://user-images.githubusercontent.com/25211271/148637915-09a6fea6-4ae9-4c9d-9d25-6fd69c5cb242.png)

**Comment by Dev-CasperTheGhost** [comment]
> **BOLO TEXT ALIGNMENT** ![image](https://user-images.githubusercontent.com/25211271/148637565-7877800d-998f-449c-81f4-54dc5583e845.png)
> 
> Can we make these text blocks justify alignment?

Something like this maybe? 
![image](https://user-images.githubusercontent.com/53900565/148638160-2de7924e-8ed7-4a1e-a3a2-1103759add22.png)

**Comment by Dev-CasperTheGhost** [comment]
The auth could look like this? *Sorry for the bad images lol, just testing*

![image](https://user-images.githubusercontent.com/53900565/148638573-f1d4d2b5-0952-43e4-b34d-b15c6f9d2e22.png)

**Comment by ViolentMinds** [comment]
BEAUTIFUL. YESSSS! AMAZING WORK.

**Comment by Dev-CasperTheGhost** [comment]
This can't be closed yet. The PR hasn't been merged yet. Will be merged very soon!

**Comment by Dev-CasperTheGhost** [comment]
Should be good to go now!
