### ISSUE TITLE
[FEATURE] Penal Code Group Sorting

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#263]
### Describe the feature

![image](https://user-images.githubusercontent.com/25211271/148695941-0fd314fa-b82d-4950-8dd8-a09ab56de60c.png)

Wondering if you can also add sorting to this page :)

Thank you!

**Comment by Dev-CasperTheGhost** [comment]
Yeah, this is definitely do-able!
