### ISSUE TITLE
[BUG] Login Auth Issue - CSS Not Displaying

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#264]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

Latest

### What operating system are you using?

Windows 10

### Describe the Bug

Some users who go to my login screen at https://cad.nightfallroleplay.com have an issue with the login form elements in CSS. They disappear. Its very strange that only some people have this problem and not others. Even though they are on the latest browser, and they have it in multiple browsers. A workaround for them is to disable the CSS for that page via the Sources via Inspect.

![image](https://user-images.githubusercontent.com/25211271/148702702-db077edb-4dc3-4413-aa13-2e61e953c18e.png)

The only workaround for them right now is to delete the .css content via the Inspect > Sources
![image](https://user-images.githubusercontent.com/25211271/148702727-eda5ad15-635b-49db-8ca0-746b36005199.png)

Once they are logged in the rest of the CAD is fine.

Update upon checking. The z-index for the background is not taking hold so the background image is sitting on top of the form. You may try adjusting it or adjusting z-index of the form for the div `class="flex mb-3 flex-col"`
![image](https://user-images.githubusercontent.com/25211271/148717103-de628bd0-e728-4156-b692-a587612844fd.png)
![image](https://user-images.githubusercontent.com/25211271/148716974-64cd1f43-0fe9-4bdd-a0c6-f49b02e41c95.png)

### Expected Behavior

Login screen css code seems to break or something. 

### To Reproduce

It works fine for some people and not others. Hard to say why its happening. I can't figure it out. For many of us its totally fine but others it just does that.

To get this error, go to https://cad.nightfallroleplay.com/auth/register
For example. You can do this in your CAD too. But this error shows for me on this page but doesn't on the regular Login screen. Only for some people do they see this error on both pages.

**Comment by Dev-CasperTheGhost** [comment]
I'll have to debug this later today in several different browsers and figure out this problem lol. Sorry for any inconvenience

**Comment by ViolentMinds** [comment]
The z-index for the background is not taking hold so the background image is sitting on top of the form. You may try adjusting it or adjusting z-index of the form for the div class="flex mb-3 flex-col" perhaps. Being sure the background is behind everything. I know its a pain sometimes haha.

For me, any browser I tried would get the same error if I went directly to the register page. The front page login form would be fine. But for others they experienced it on both.

**Comment by Dev-CasperTheGhost** [comment]
Looks like I missed a CSS style. Should be fixed now, thanks for reporting this bug!
