### ISSUE TITLE
[BUG] Bad color style for light theme

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#269]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### Describe the Bug

Bad color style for light theme
![s9vD0TR 1](https://user-images.githubusercontent.com/4976837/148925885-bccb53de-1165-4117-91a2-2b2f1e18fbc3.png)

### Expected Behavior

![vbMemf0 1](https://user-images.githubusercontent.com/4976837/148926030-bf07f0c9-7d8d-409f-9a40-0d91e04c68cc.png)

**Comment by Dev-CasperTheGhost** [comment]
Ah whoops! Will get this fixed later today.
