### ISSUE TITLE
[IMPROVEMENTS] Postal code - Add field validation

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#272]
### Describe the feature

Add validation for the "postal code" field: only use numbers, no spaces.

I analyzed the main maps that are used in projects (New and Improved Postals, Original Postals, OCRP Postals) and noticed that the code values are only digital

Wrong code:
![EpJxXnE 1](https://user-images.githubusercontent.com/4976837/148938072-7012f49b-9d8d-4be2-a40f-f349b78f4d3e.png)
![gz7iGqu 1](https://user-images.githubusercontent.com/4976837/148938263-e884fc7b-ded0-43eb-8efa-1b64c06c44ad.png)

Correct:
![GZRDgcx 1](https://user-images.githubusercontent.com/4976837/148939083-d22c24bb-3e4d-40d8-bdb3-8390193d8fb9.png)

### Additional Context

Also, this validation will avoid problems when using the "Set marker" button on the **Live map** page

**Comment by Dev-CasperTheGhost** [comment]
Are we 100% sure that will not break current postal codes?

**Comment by jxckUK** [comment]
We have postal codes in the UK that contain letters (eg. PL2 1QY) but we use a postal code map at the moment that is just digits.

In the future we would likely want to change this to UK postal format and this change would block that.

**Comment by pp2amd6** [comment]
> We have postal codes in the UK that contain letters (eg. PL2 1QY) but we use a postal code map at the moment that is just digits.
> 
> In the future we would likely want to change this to UK postal format and this change would block that.

It's cool, but I'm talking about in-game reality. There are three main cards used in GTA and they only have numerical values.

Example:

- [Postal Code Map & Minimap - New & Improved - v1.2](https://forum.cfx.re/t/release-postal-code-map-minimap-new-improved-v1-2/147458)
- [Original-Street-Names-w-Postal-Numbers](https://forum.cfx.re/t/release-original-street-names-w-postal-numbers/8717)
- [OCRP Community Releases](https://forum.cfx.re/t/release-ocrp-community-releases/166277)

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost a question for you. 
Is it possible to place markers on a live map using postal codes? If so, then such a validation will avoid errors.

**Comment by Dev-CasperTheGhost** [comment]
> Is it possible to place markers on a live map using postal codes?

Auto-place markers where a postal code is located?

**Comment by jxckUK** [comment]
> It's cool, but I'm talking about in-game reality. There are three main cards used in GTA and they only have numerical values.

I understand - but if for example we were to introduce our own postal map this change would mean the CAD would be unable to accept the values we'd defined (as they would include UK postcode formats). It reduces the flexibility of the CAD across servers that are roleplayed in different regions outside of the U.S.

There is probably a better solution to the issue/feature request than denying formats that may be in use across the world, in my opinion.

**Comment by pp2amd6** [comment]
Ok. Let's leave it as it is.
