### ISSUE TITLE
[FEATURE] Department Admin Role Powers

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#274]
### Describe the feature

Once created, **Department** Admin power

- Approve members into their department (whitelisting like businesses)
- Can give Officer (LEO) Access & Dispatch Access / FD Access for their members

Note: This would be giving them access to the user management page.

They will be able to see only their department members. (Like it is with Businesses)
_*But you would have to disable their power to delete users!*_
I think that power should be for only Owner and Admin!
Department Admin should not be able to delete users from CAD. For security reasons.

Because in our case we once had someone who was an Admin with too much powers who left the community. He deleted everyone in CAD. (Not this CAD, a different one) 

Reasoning: At the moment only the Owner and regular Admins have to approve everyone for LEO, Dispatch, Fire etc manually.
Which takes a long time. Especially checking to see if they are in a department in the community. When I have only a few very trusted admins because they have so much power. The Department Admin role having less power, but can take away the stress of these Department related issues.

:) Thank You!

**Comment by Dev-CasperTheGhost** [comment]
This would be the task of #248 right?

**Comment by ViolentMinds** [comment]
> This would be the task of #248 right?

Yeah part of that. Can be merged.

**Comment by Dev-CasperTheGhost** [comment]
Now that I think about: 

> Department Admin can make Officer a LEO Supervisor of their Department only

The department isn't linked to users but to officers, so this would be pretty much impossible to check against.

**Comment by ViolentMinds** [comment]
:( what about the approval of officers into department, like businesses do

**Comment by Dev-CasperTheGhost** [comment]
> what about the approval of officers into department, like businesses do

Would it look something like this?: 

1. Officer is created
2. CAD has department whitelisting enabled
3. Officer gets put in a "PENDING" state and awaiting approval of a supervisor
4. Gets accepted -> Officer able to use
   Gets denied -> officers stays in db but is disabled? (or removed from db)


> or some way to add a supervisor role to officers so they can help out hmm

Something that could be possible is to add a property to the user of what departments they can manage when the user is a supervisor? This could simplify some stuff

**Comment by ViolentMinds** [comment]
1) Officer is created
2) CAD has department whitelisting enabled
3) Officer gets put in a "PENDING" state and awaiting approval of a supervisor
4) Gets accepted -> Officer able to use 
else Gets denied -> officers stays in db but is disabled? (or removed from db)

#4

- "Disabled" Alternative
Create a default department in CAD that does not require approval, it is where the Officer will be automatically.  For example "Public Law Enforcement Department" or "Training Camp" will be given to the Officer automatically.

Until they choose a new department for their Officer that requires approval. :)

(many servers have this anyways, like ours has public officers who can still go on as LEO but they aren't a member yet of an official department)

**Comment by Dev-CasperTheGhost** [comment]
> Create a default department in CAD that does not require approval, it is where the Officer will be automatically. For example "Public Law Enforcement Department" or "Training Camp" will be given to the Officer automatically.

Sure! I'll make this an option in the create department modal. ("Default Department: true/false", there can only be 1 default department) What do you think about that?

**Comment by Dev-CasperTheGhost** [comment]
**To confirm, cuz I got a bit confused 😅**


1. > Create a default department in CAD that does not require approval, it is where the Officer will be automatically. For example "Public Law Enforcement Department" or "Training Camp" will be given to the Officer automatically.

 Would this be when they're awaiting access ("PENDING state")? Or when they were declined to a department?
If this is when they were declined, what should happen when the officer is a "PENDING state"?

--- 

2. Each department can have an option `whitelisted` that enables whitelisting for that department and creates the entire process of accepting/declining officers.

---

3. one department can have an option as "Default Department?", this department would be given when the officer is awaiting access or declined (depends on 1st comment)

cc @ViolentMinds

**Comment by ViolentMinds** [comment]
Option 3!

one department can have an option as Default Department, this department would be given when the officer is awaiting access or declined

**Comment by Dev-CasperTheGhost** [comment]
Progress:

- Officer is able to an officer that has a default department, whether they're accepted or declined
- Departments can be set as whitelisted or default department

still loads of things todo :)!

![image](https://user-images.githubusercontent.com/53900565/151120023-85e2ddb1-de21-439a-a9aa-f1bd8cd9ac16.png)

![image](https://user-images.githubusercontent.com/53900565/151120048-c84a5301-a1b2-43d9-832c-ceacd9731f3d.png)

**Comment by Dev-CasperTheGhost** [comment]
What do you think so far of the images in the previous post, @ViolentMinds?

**Comment by Dev-CasperTheGhost** [comment]
This was a fairly large change of the department stuff. Let me know if you're experiencing issue so I can fix them :). 

*I should setup some automated testing stuff 😄*

**Comment by ViolentMinds** [comment]
Love it! updating now!

**Comment by ViolentMinds** [comment]
![image](https://user-images.githubusercontent.com/25211271/151315900-7cc03b50-57ce-4030-8e14-aff61cd251d0.png)

Heres what I have set up. Does this look correct for you?

So basically anyone will be in "Public LEO" in my case by default. While the rest (except Fire I guess) are Whitelisted.
Who does the approval for the whitelist for each department? Is that coming later with Department Admin role because I don't see that role option yet to give to people just User and Admin only.

**Comment by Dev-CasperTheGhost** [comment]
Manage Units -> Department whitelisting tab! This can be accessed by supervisors and admins

**Comment by ViolentMinds** [comment]
![image](https://user-images.githubusercontent.com/25211271/151316288-eeb532b8-8c6c-4d4a-b319-863840e3edc9.png)
oh here

ok
is it general supervisors... like... any supervisor from any department can accept anyone into any department?

I will tell them to only accept members into their department and not others haha

**Comment by Dev-CasperTheGhost** [comment]
>  is it general supervisors... like... any supervisor from any department can accept anyone into any department?

currently, yeah. I have some plans in my mind to add the Department Admin role, somewhat like this FR but then to the user instead of the officer.
