### ISSUE TITLE
[BUG] User values not saving when updating from Owner. (LEO Access etc)

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#277]
### What version of Node.js are you using?

16.13.1

### What operating system are you using?

Windows Server 2019

### Describe the Bug

I believe since the last update (could have been earlier) I cannot save the User access changes.
Such as, I'm trying to update LEO Access, Dispatch Access etc. But when I hit Save I get Unexpected Error

![image](https://user-images.githubusercontent.com/25211271/149071374-73625af4-d9a3-4a83-bcb7-e21bbf82d820.png)

### Expected Behavior

Should be able to save user values

**Comment by Dev-CasperTheGhost** [comment]
Whoops, minor typo. Not sure how it wasn't picked up by the typechecker. Fixed now though!
