### ISSUE TITLE
[FEATURE] Dispatch alarms trigger in game

### ISSUE THREAD

**Issue by Vatoka** [SnailyCAD/snaily-cadv4#278]
For example 911 call of fire dispatcher can press a button on cad and select station and units 

Using Text to speech api to generate message eg. *beep sound Station 1 Structure fire engine 1 truck 2 

Use interact sound to play this sound in game at a specified fire station.

**Comment by Dev-CasperTheGhost** [comment]
This might be possible to do in the CAD’s frontend. But I do not have the expertise in FiveM scripting so for now I will close this issue and put it in a backlog.

**Comment by Vatoka** [comment]
The FiveM server side is fairly simple. I can make the FiveM part when I get home I would just need a way to add a button which sends a http request to FiveM http wrapper and then the rest is done server side. I will make it and show you it and you can decide weather you would want to publicly implement it.

**Comment by jxckUK** [comment]
> The FiveM server side is fairly simple. I can make the FiveM part when I get home I would just need a way to add a button which sends a http request to FiveM http wrapper and then the rest is done server side. I will make it and show you it and you can decide weather you would want to publicly implement it.

Custom action buttons/forms would be a really nice touch actually. Would allow us to integrate with resources like SmartSigns to send targeted traffic messages similar to the integration SonoranCAD has [here](https://info.sonorancad.com/integration-plugins/integration-plugins/available-plugins/smart-signs).

**Comment by Vatoka** [comment]
Another way if the cad and FiveM server were both hosted on the same server you can use a local host redis pub sub to trigger events in game from the cad. (New to redis but could work)
