### ISSUE TITLE
[FEATURE REQUEST] Add postal code (block) field

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#28]
Add postal code (block) field to all places where user enter address:
1. citizen controller
- create citizen
![kiss_12kb 1634929589 1](https://user-images.githubusercontent.com/4976837/138509896-08b3ac57-d99d-43d0-8bae-971deed4e3c0.png)

- tow call
- taxi call
- 911 call

2. business controller

3. Other places :)

Postal block
![kiss_106kb 1634930259 1](https://user-images.githubusercontent.com/4976837/138511140-8e620e33-0a21-4353-bf3f-d274262edfa9.png)

For what? For creating routes to block in game.

Example:
1. Dispatch or police officer create BOLO record
2. I select BOLO records from FiveM through API
3. Create route to block (using [Nearest Postal](https://forum.cfx.re/t/release-nearest-postal-script/293511), for example)

**Comment by Dev-CasperTheGhost** [comment]
Sorry for taking so long to get back to this issue! Should be released by tomorrow/Wednesday.
