### ISSUE TITLE
[FEATURE] Officer Dashboard Updates

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#280]
### Describe the feature

1) **Rank - Add To Dashboard** Could we get rank added here?
![image](https://user-images.githubusercontent.com/25211271/149220246-e27d4d96-75be-4d65-a872-7bcd8eeaf1d1.png)

2) **Could we change Badge to Callsign on here somehow?**
_Since Callsign is what people need to know the most not badge number._

Additionally, I actually would love to know if I can remove the Badge sections entirely from the CAD. Because we don't use it. We basically use the Callsigns as their one and only identifier. 

Thank you!

**Comment by Dev-CasperTheGhost** [comment]
For now I'll have to keep the badge-numbers since I don't want to bloat the Features tab. I'll have to figure out how I want it to look, or figure out a better design pattern for the features 😅
