### ISSUE TITLE
[FEATURE] Businesses - Vehicles

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#290]
### Describe the feature

![image](https://user-images.githubusercontent.com/25211271/149677814-29cbc201-0822-4196-80cf-7600c91a1c62.png)

Would it be possible to have a feature where we can have vehicles registered to a business? Like fleet vehicles.
For example a trucking and transport business. Or a taxi business which has vehicles owned by the business and not just one citizen.

**Comment by Dev-CasperTheGhost** [comment]
Yes, this can be done. It could be its own tab called ‘Company Vehicles’ orso. In this tab you can register new vehicles to the company.
