### ISSUE TITLE
[FEATURE REQUEST] Add text editor functionality

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#294]
### Describe the feature

Add text editor functionality, for example Editor.js ([Site](https://editorjs.io/) / [GitHub](https://github.com/codex-team/editor.js))

![image](https://user-images.githubusercontent.com/4976837/149714610-a5a1222a-91d8-44dc-8e65-546422c9f4e7.png)

**Comment by Dev-CasperTheGhost** [comment]
I have worked with these and are quite a pain to work with IMO. Not sure if I'll be doing it this way, will see other possibilities

**Comment by pp2amd6** [comment]
> I have worked with these and are quite a pain to work with IMO. Not sure if I'll be doing it this way, will see other possibilities
Editor.js is interesting as solution because have a plugins.

Do you mean that we should look for another solution?

**Comment by Dev-CasperTheGhost** [comment]
For now I have another editor package in the back of my mind. Will have to look into it later today/tomorrow

**Comment by Dev-CasperTheGhost** [comment]
I think Slate will be a better option, it's less bulky, the CAD doesn't need all its features. 

here's an example of Slate:https://www.slatejs.org/examples/richtext

**Comment by pp2amd6** [comment]
> here's an example of Slate:https://www.slatejs.org/examples/richtext (UI can be changed to match CAD's UI, Editor.js is harder to style)

Cool! The most important features for editor: images embedding and tables (for creating reports for detective roles).

**Comment by Dev-CasperTheGhost** [comment]
@pp2amd6, got this working. Now gotta work on the db stuff. let me know what you think 

https://user-images.githubusercontent.com/53900565/150292511-62b3274f-c0f3-415f-840c-42be93eac1d6.mov
