### ISSUE TITLE
[FEATURE] Automatic LEO Access Option

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#302]
### Describe the feature

Could we have this option added perhaps? :) Thanks!

**Comment by Dev-CasperTheGhost** [comment]
Can you elaborate?

**Comment by ViolentMinds** [comment]
When a User is created - they are given LEO Access by default. Instead of manually by Admin.

Owner can toggle option in CAD settings.

- Because every time a user joins I have to go and give them LEO access and its very time consuming.

**Comment by Dev-CasperTheGhost** [comment]
Hm. I'm not sure about this, this could have some security concerns, even when it's a togglable option. 
Example:

1. user registers with auto-LEO access
2. Starts spamming calls, bolos, giving tickets to unneeded citizens, etc.

**Comment by ViolentMinds** [comment]
I see what you are saying but it would be nice as a server owner to be able to decide if they want this risk or not.
In our case we have public officers. So having to literally accept everyone is extremely time consuming.

I would say the time saved to deal with one bad public officer is less of a risk than the time spent having to deal with accepting every single person into our CAD for LEO access.

I understand there is no way to link it to Discord roles like some FiveM scripts do. But that would be the ultimate solution as well. Though, realistically, any LEO if even given manual access can still choose to cause problems.

One way around this if people are worried about automatic LEO access is to simple whitelist their CAD at the start.

**Comment by jxckUK** [comment]
> I understand there is no way to link it to Discord roles like some FiveM scripts do. But that would be the ultimate solution as well. Though, realistically, any LEO if even given manual access can still choose to cause problems.

This would be a nice feature! You could take it further and assign Discord role IDs to departments so if the user has the tag they're automatically enrolled in the department too.

**Comment by Dev-CasperTheGhost** [comment]
👍 will take a look tomorrow to implement this. Maybe in the near future I'll take a look for automatic Discord role stuff

**Comment by ViolentMinds** [comment]
> > I understand there is no way to link it to Discord roles like some FiveM scripts do. But that would be the ultimate solution as well. Though, realistically, any LEO if even given manual access can still choose to cause problems.
> 
> This would be a nice feature! You could take it further and assign Discord role IDs to departments so if the user has the tag they're automatically enrolled in the department too.

Indeed! Would be very cool.

You could always link with a script like Badgers Discord API or something like a lot of people do. Since its such a commonly used existing FiveM script. But eh. Just ideas.
