### ISSUE TITLE
Cannot read properties on API PUT call

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#305]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Error:
```
    name: 'TypeError',
    message: "Cannot read properties of undefined (reading 'isDispatch')",
    status: 500
```

### Expected Behavior

The call should succeed and the target user's status should be updated with the value sent.

### To Reproduce

![Uploading image.png…]()

**Comment by Dev-CasperTheGhost** [comment]
fixed in 3ac41f6
