### ISSUE TITLE
Allow LEO actions (warning/arrests/warrants) against non-registered civilians

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#309]
### Describe the feature

Will probably help to add some context to this request. For our use case we actually do a lot of player vs AI with random peds within the game alongside our normal roleplay. 

When we write reports for these suspects they obviously don't have records within the CAD so is there a way we can enable these records to be populated against civilians that aren't registered in the CAD?

I understand it's probably too heavily linked to the civilians in the CAD system so my follow up ask would be:

Is there a way we can mass 'import' civilians that aren't assigned to user accounts for this use case? That way we could still register actions against a civilian record.

**Comment by Dev-CasperTheGhost** [comment]
This will require a bit more thought process, but definitely possible

**Comment by ViolentMinds** [comment]
Does he mean putting in a random Civilians name who are from out of state so to speak who are not in the CAD? Won't that just fill up the database with useless information though taking up space? Since most of those people will never use that name again. I mean I guess it depends on what you do in your server but.

**Comment by jxckUK** [comment]
> Does he mean putting in a random Civilians name who are from out of state so to speak who are not in the CAD? Won't that just fill up the database with useless information though taking up space? Since most of those people will never use that name again. I mean I guess it depends on what you do in your server but.

It's a good question and a good point but the names would likely be re-occurring and not single use so the names will come up frequently. Which makes me think the follow up ask is probably a more appropriate option.

It certainly needs some finessing but it's a major feature for myself and my server as we can't utilise the CAD for these sort of actions when we're dealing with AI.

**Comment by Dev-CasperTheGhost** [comment]
> Is there a way we can mass 'import' civilians that aren't assigned to user accounts for this use case? That way we could still register actions against a civilian record.

What data would be imported? I'd guess name, gender and ethnicity?

**Comment by jxckUK** [comment]
> What data would be imported? I'd guess name, gender and ethnicity?

Yeah doesn’t require much more than that - as long as it doesn’t need to be tied to a user account! Would be an extra bonus if the user could be edited by admins if required?

**Comment by Dev-CasperTheGhost** [comment]
> Would be an extra bonus if the user could be edited by admins if required?

I can make it work without a user account yeah, no problem with this.

**Comment by Dev-CasperTheGhost** [comment]
What about something like this? @jxckUK 

https://user-images.githubusercontent.com/53900565/150669366-b7297435-3bc8-44b1-a31c-2f808f285520.mov

**Comment by jxckUK** [comment]
Thanks for this @Dev-CasperTheGhost! - is there any way we can get a JSON import option like the ones you implemented for values?

**Comment by Dev-CasperTheGhost** [comment]
> Thanks for this @Dev-CasperTheGhost! - is there any way we can get a JSON import option like the ones you implemented for values?

Sure, will add that soon!

**Comment by Dev-CasperTheGhost** [comment]
Done! Docs can be found here: https://cad-docs.netlify.app/other/importing-values#citizens
