### ISSUE TITLE
Selecting 'clear' on the date option in civ creation causes an error

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#310]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

When creating a civilian and using the date picker, if you select the clear button inside the drop down widget you will trigger a client side error.

### Expected Behavior

This should probably just set the field back to default as you wouldn't necessarily want to clear this field, I just happened to click it by accident.

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/150579061-dd78d160-4947-4935-a62e-573f83bf366b.png)

**Comment by Dev-CasperTheGhost** [comment]
iirc this was the same issue reported in Discord a few hours ago. This should be fixed on the latest commit

**Comment by jxckUK** [comment]
Just updated and can confirm it's fixed - sorry must have missed this in the Discord!

**Comment by Dev-CasperTheGhost** [comment]
> Just updated and can confirm it's fixed - sorry must have missed this in the Discord!

no worries! Glad it works 😅
