### ISSUE TITLE
Update on LEO panel

### ISSUE THREAD

**Issue by XComatoseX** [SnailyCAD/snaily-cadv4#311]
### Describe the feature

At this point, any LEO employee can connect to the call. This is great when there is no dispatcher available. But let's say an employee is assigned to a call, but they can no longer be disconnected/available, they would have to leave their shift to become available again. Only the dispatcher would be able to set the status to "available" anymore. Maybe add a "disconnected/available" feature? I think that would be a useful feature.

**Comment by Dev-CasperTheGhost** [comment]
Sure! Will try work on this tomorrow.

**Comment by Dev-CasperTheGhost** [comment]
🚀 

https://user-images.githubusercontent.com/53900565/150927196-54900ae6-23eb-4b42-bc77-8a07acc7240a.mov
