### ISSUE TITLE
Time shows on date of birth

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#318]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

I'm not sure if this is intentional or not but time seems to be displayed on on date of births which probably shouldn't.

### Expected Behavior

It should display the date standalone as its unlikely that we have access to the specific time they were born.

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/150679952-b39fc449-d4ce-44c1-bd9d-7da881ad4e00.png)

**Comment by Dev-CasperTheGhost** [comment]
ah this was missed in #315 probably. Will fix this later today.
