### ISSUE TITLE
Filter civilians by account registered and imported/unregistered

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#321]
### Describe the feature

With the addition of imports and non-connected civilians (thanks again!) the list of civilians can be quite large and although pagination solves this it would be good to be able to filter the list to only see either connected or non-connected civs.

**Comment by Dev-CasperTheGhost** [comment]
🚀 
https://user-images.githubusercontent.com/53900565/150736823-ac869ff9-b82c-4b2b-a7cf-933f7991725d.mov
