### ISSUE TITLE
FiveM Framework Integration

### ISSUE THREAD

**Issue by Smithandjosh** [SnailyCAD/snaily-cadv4#322]
### Describe the feature

It would be great if you were able to work closely with Andyyy7666 to be able to use the integrate the cad with his "ND Framework" (https://youtu.be/_wZxperCsa0)

**Comment by Dev-CasperTheGhost** [comment]
Sure, but I think it's best for you to contact Andy, since I don't have any contact with him

**Comment by Smithandjosh** [comment]
I have also suggested the idea in his discord
