### ISSUE TITLE
Allow registration of vehicles against non-user civilians

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#323]
### Describe the feature

The ability to add non-user civilians has opened up a lot of use cases for me and it would be great if the same flexibility was extended to vehicles. 

At the moment the civilians we register against non-users won't have any vehicles registered as they can't be added.

The feature request contains two parts, firstly can we get the ability within the CAD to register individual vehicles against other civilians. Potentially something to lock behind the Dispatch permissions?

Secondly, as we have with civilians could this also support bulk registrations using a JSON file? So we can provision large amounts of vehicles to the non-user civilians?

**Comment by Dev-CasperTheGhost** [comment]
> The feature request contains two parts, firstly can we get the ability within the CAD to register individual vehicles against other civilians. Potentially something to lock behind the Dispatch permissions?

Would this match with the "Common citizen cards" too? 

cc @pp2amd6

**Comment by jxckUK** [comment]
> > The feature request contains two parts, firstly can we get the ability within the CAD to register individual vehicles against other civilians. Potentially something to lock behind the Dispatch permissions?
> 
> Would this match with the "Common citizen cards" too? (#60)
> 
> cc @pp2amd6

Certainly looks similar in the ability however missing the bulk registrations which would be key!

**Comment by Dev-CasperTheGhost** [comment]
hey @jxckUK, in the \#343 PR, it should now allow you to register a vehicle to a citizen without being authenticated. Please let me know if that already works!

route: POST /v1/vehicles [properties](https://github.com/SnailyCAD/snaily-cadv4/blob/f368a48519108275e9ec80bb6e54fec270818ee9/packages/schemas/src/citizen.ts#L16)

**Comment by jxckUK** [comment]
> hey @jxckUK, in the #343 PR, it should now allow you to register a vehicle to a citizen without being authenticated. Please let me know if that already works!
> 
> route: POST /v1/vehicles [properties](https://github.com/SnailyCAD/snaily-cadv4/blob/f368a48519108275e9ec80bb6e54fec270818ee9/packages/schemas/src/citizen.ts#L16)

Thanks! - is there a way I can do this via JSON importing too? I'll give the API call a go shortly along with the other ones. 🙂

**Comment by Dev-CasperTheGhost** [comment]
> is there a way I can do this via JSON importing too?

Yep, this will be implemented too!

**Comment by Dev-CasperTheGhost** [comment]
I'm not sure where we could have a button for the vehicles/weapons import. If I add the option in the citizen import, all the citizens would be re-imported again, adding a separate button could also clutter the UI a bit 🤔.

**Comment by jxckUK** [comment]
> I'm not sure where we could have a button for the vehicles/weapons import. If I add the option in the citizen import, all the citizens would be re-imported again, adding a separate button could also clutter the UI a bit 🤔.

Possibly a new section above the values section in the admin panel?

**Comment by Dev-CasperTheGhost** [comment]
Something like this mabye? 

![image](https://user-images.githubusercontent.com/53900565/151421813-140d700f-feed-47ac-95fa-8b22c3952676.png)

**Comment by jxckUK** [comment]
Perfecto!

**Comment by Dev-CasperTheGhost** [comment]
This feature has landed! You can find the [documentation here for the JSON format](https://cad-docs.netlify.app/other/importing-values#vehicles)
