### ISSUE TITLE
[bug]: cannot update licenses in name-search / said features aren't hidden while disabled

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#325]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

When editing licenses, if you only change the value for one license it will result in a foreign key error.

### Expected Behavior

If you don't change the values for a license type it should not attempt to submit any value to the database.

As a side note, it shouldn't show CCW & Firearms if the feature is disabled within the admin panel.

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/150771993-4bf788a4-cecd-4467-aa47-eb6744d8ebbd.png)
![image](https://user-images.githubusercontent.com/48030374/150772095-d048cc25-28d0-4bb9-baba-69885148a3a4.png)

**Comment by Dev-CasperTheGhost** [comment]
Will fix this shortly!

**Comment by Dev-CasperTheGhost** [comment]
Should be all fixed 🎉!

**Comment by jxckUK** [comment]
Thanks Casper - It fixed the issue but I think the wrong fields have been hidden:

![image](https://user-images.githubusercontent.com/48030374/150777765-a77ea36c-20f8-4db4-908f-3f53fec62abb.png)

No longer see pilots but do see firearms!

**Comment by Dev-CasperTheGhost** [comment]
Should now all be fixed. The text `toggle vehicles and weapons` will stay as is. You can always translate it in `leo.json` -> `toggleVehiclesWeapons`
