### ISSUE TITLE
Incidents formatting and buttons

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#327]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

There are a few formatting issues with the incident reporting. Firstly, the additional officers if more than one is selected there is no space between them when displayed. Secondly, when viewing a description for a case I noticed that there is a save button but this isn't an editable model and there should probably just be a close option.

### Expected Behavior

A space should be present for additional officers, not sure how well it will format with large numbers of officers either?

Only a close option should be present on the description pop out as there is no editable content to save.

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/150787045-5f4287f1-4119-4d4b-b20b-5ffc663176dd.png)
![image](https://user-images.githubusercontent.com/48030374/150787165-aa3f9872-0948-4b50-ac4f-2c733d3d8742.png)

**Comment by Dev-CasperTheGhost** [comment]
> not sure how well it will format with large numbers of officers either?

for now I'll keep it as-is. If this becomes a problem in the future we can definitely change this!
