### ISSUE TITLE
Separate vehicle and civilian license types

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#328]
### Describe the feature

At the moment these share the same value and you end up with some odd options for driving licenses when you add vehicle registration statuses.

If we could add an option to specify if its a driving or a vehicle license status that would be fantastic!

**Comment by Dev-CasperTheGhost** [comment]
This would separate "Vehicle registration status" and "Drivers license", right 😅?

**Comment by jxckUK** [comment]
Exactly yeah! As you can have different statuses that don't apply to each other, would be cleaner if they were somewhat seperated?

**Comment by Dev-CasperTheGhost** [comment]
What about something like this? 

![image](https://user-images.githubusercontent.com/53900565/151002621-2f3de761-ae56-4d45-b951-4eee904d2387.png)

@jxckUK

**Comment by jxckUK** [comment]
> What about something like this?
> 
> ![image](https://user-images.githubusercontent.com/53900565/151002621-2f3de761-ae56-4d45-b951-4eee904d2387.png)
> 
> @jxckUK

Nailed it as always!

**Comment by Dev-CasperTheGhost** [comment]
Thanks, also added some simple notes to indicate what each type is 

![image](https://user-images.githubusercontent.com/53900565/151004516-3cd2819c-c97e-4015-b36f-fb32e04c454c.png)

**Comment by Dev-CasperTheGhost** [comment]
Merged 🚀!
