### ISSUE TITLE
[BUG] Create button not working 

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#329]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### Describe the Bug

The Create button for Firefighter/Ems has stopped working. I fill out everything and it just gives a not permitted red circle and won't let me click on the Create button. 

```
index.js:101 Uncaught TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Mt (index.js:101:35)
    at hotkeyMatchesEvent (command-palette.ts:147:24)
```

_Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'._

### Expected Behavior

To be able to click Create

**Comment by Dev-CasperTheGhost** [comment]
All fixed now!
