### ISSUE TITLE
Allow assignment of 911 calls to departments

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#335]
### Describe the feature

When creating a 911 call some of them would be for example for Fire/EMS and it would be good to have the ability to specify which call would be routing where. When you call 911 you're asked what service you're calling for so this would line up.

To extend this functionality it would be good if Dispatch could assign a division, for example if its a call requiring detectives it can be assigned to that division.

You can then use the API to filter calls displayed to each user!

**Comment by Dev-CasperTheGhost** [comment]
Would this then also filter the 911-calls list, or a toggle button for that?

For example:

 - Unit is EMS/FD -> will only see EMS/FD calls
 - Unit has `X` division -> will only see `X` division calls

**Comment by jxckUK** [comment]
> Would this then also filter the 911-calls list, or a toggle button for that?
> 
> For example:
> 
> * Unit is EMS/FD -> will only see EMS/FD calls
> * Unit has `X` division -> will only see `X` division calls

Oooh yes it would be good if they were filtered, but probably needs to be behind a button like you say!

**Comment by Dev-CasperTheGhost** [comment]
Another quick question: Would this show in the active-calls table? ifso, I think 2 columns would take up to much space for example:

|Location| Department | Division | .... |
| ---------|--------------|----------|----|
| bla bla | blablabla | bla bla | ....|

Do you have any suggestions? Maybe a call-info modal that holds all info about a call instead of a table full of columns?

**Comment by jxckUK** [comment]
> Another quick question: Would this show in the active-calls table? ifso, I think 2 columns would take up to much space for example:
> 
> Location	Department	Division	....
> bla bla	blablabla	bla bla	....
> or even 1 column
> 
> Location	Department/Division	....
> bla bla	bla bla	....
> Do you have any suggestions? Maybe a call-info modal that holds all info about a call instead of a table full of columns?

I like the call info modal idea! Just the real basics in the table then each call has a modal option?

**Comment by Dev-CasperTheGhost** [comment]
> I like the call info modal idea! Just the real basics in the table then each call has a modal option? 

Yep!

**Comment by Dev-CasperTheGhost** [comment]
Yet another quick question: Would this allow multiple departments/divisions to be connected to the call or only 1? @jxckUK

**Comment by jxckUK** [comment]
> Yet another quick question: Would this allow multiple departments/divisions to be connected to the call or only 1? @jxckUK 

I think that should be something defined either by the admin of the CAD or on a call by call basis?

**Comment by Dev-CasperTheGhost** [comment]
> I think that should be something defined either by the admin of the CAD or on a call by call basis?

hm, yeah. Will have be multiple so the dispatcher can decide

**Comment by Dev-CasperTheGhost** [comment]
> I like the call info modal idea! Just the real basics in the table then each call has a modal option?

Decided to take to manage 911 call modal and make everything readOnly

https://user-images.githubusercontent.com/53900565/151690943-ca67de15-699e-41a6-bf2d-a39c46503681.mov

**Comment by Dev-CasperTheGhost** [comment]
Working filters:

https://user-images.githubusercontent.com/53900565/151695959-3b9fb34b-d362-465a-8b4e-a4df12eb5f9d.mov

**Comment by Dev-CasperTheGhost** [comment]
Done 🚀! Let me know if there are improvements to be made!

**Comment by jxckUK** [comment]
> Done 🚀! Let me know if there are improvements to be made!

Awesome stuff! - just a couple of things from initial usage:

- Is this supported in the API (creating 911 calls and setting department/division using IDs?
- It would be ideal if when you're selecting departments and divisions that once you select a department only divisions from that department can be selected? Just to reduce UI clutter?

**Comment by Dev-CasperTheGhost** [comment]
> Is this supported in the API (creating 911 calls and setting department/division using IDs?

Yep

> It would be ideal if when you're selecting departments and divisions that once you select a department only divisions from that department can be selected? Just to reduce UI clutter?

Sure, I'll work on this later today!
