### ISSUE TITLE
Missing message continuous error

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#336]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

As below image, not sure what this is but it seems to occur frequently in the logs and it also transfers to the F8 menu when you're loading the CAD within the game.

### Expected Behavior

N/A - Error

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/151213390-9e642242-3564-4671-93e7-8aae0864a029.png)

**Comment by Dev-CasperTheGhost** [comment]
This shouldn't case any harm. But this errors will come up if there are missing translations. If you're using a custom locale, you must keep it up-to-date with the `en` version.
