### ISSUE TITLE
Disabling Discord integration after adding it to ENV doesn't work

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#337]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

Due to the iFrame limitations of Discord authentication I disabled it by removing the Discord client ID and secret in the ENV. Unfortunately it still shows the login with discord option which subsequently breaks the CAD in game.

### Expected Behavior

Can we either get an option to disable this button when used in an iFrame or support for removing it after its been enabled?

**Comment by Dev-CasperTheGhost** [comment]
It should be disabled by default if it's not in the .env file 🤔. Did you also disable it in the CAD-settings?

**Comment by Dev-CasperTheGhost** [comment]
Follow-up, did you run the command to update the .env file and then restart the API?

**Comment by jxckUK** [comment]
> It should be disabled by default if it's not in the .env file 🤔. Did you also disable it in the CAD-settings?

Oh dear - I'm not on the ball today, completely missed the setting in CAD settings doh!

**Comment by jxckUK** [comment]
Sorry - just noticed that I can disable the sign in but that will disable users abilities to connect their account which is how I use the API to link users to.

Is there anyway that I can disable sign in with Discord but still allow them to connect their account so it adds their Discord ID. I know as admins we can add this (although saving doesn't work for that) but this would mean we need to go in and add this for every user.

**Comment by Dev-CasperTheGhost** [comment]
How does "Connect Discord account" work, but not "Login in via Discord" 🤔?

**Comment by jxckUK** [comment]
> How does "Connect Discord account" work, but not "Login in via Discord" 🤔?

It doesn't inside of the iframe, but I can have the users access the CAD from outside an iframe to link their account.

It's not ideal (best scenario is to just hide these options in an iframe) but I'm just trying to work around the Discord limitation.

**Comment by jxckUK** [comment]
I'm over complicating this actually, they just need the ability in their profile page to add a Discord ID as plain text. No integration, no redirect.

**Comment by Dev-CasperTheGhost** [comment]
> I'm over complicating this actually, they just need the ability in their profile page to add a Discord ID as plain text. No integration, no redirect.


Yeah, that could work! I could make a few more options writable if that's something you'd also like to get added?

**Comment by jxckUK** [comment]
> > I'm over complicating this actually, they just need the ability in their profile page to add a Discord ID as plain text. No integration, no redirect.
> 
> Yeah, that could work! I could make a few more options writable if that's something you'd also like to get added?

That would be great! I got there eventually, just had to work it out in my head. 😆

**Comment by Dev-CasperTheGhost** [comment]
Will work on this tomorrow!

**Comment by Dev-CasperTheGhost** [comment]
![image](https://user-images.githubusercontent.com/53900565/151311522-d8a02af9-30f0-425a-86de-5318390792a8.png)

![image](https://user-images.githubusercontent.com/53900565/151311569-2f33740e-7a8b-4a5a-9d9f-8aa65920f21d.png)
