### ISSUE TITLE
Extend the existing API

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#338]
### Describe the feature

Can we make as many of the API calls as possible be utilised without requiring an authenticated user. 

So far I've only come across creating 911 calls, assigning users to calls and the panic (which has already been added) but may be an issue for things like creating call events etc.

### Additional Context

`src/controllers/dispatch/Calls911Controller.ts:71 -> remove userId property`

**Comment by Dev-CasperTheGhost** [comment]
So I've removed some redundant checks, if the user is API_TOKEN, then it will not check if it's a valid user. I've also removed userId's where they aren't necessary. PR will be merged soon!
