### ISSUE TITLE
[feat]: select all units checkbox

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [SnailyCAD/snaily-cadv4#342]
### Describe the feature

Add a checkbox to select **all** the units in manage units

**Comment by Dev-CasperTheGhost** [comment]
soon:tm:

https://user-images.githubusercontent.com/53900565/151335009-55ed5931-b75d-454e-8764-81f43ecbef04.mov

**Comment by Dev-CasperTheGhost** [comment]
cc @ViolentMinds, this has been added 🎉!

**Comment by ViolentMinds** [comment]
💙🙏
