### ISSUE TITLE
Steam/discord id for api

### ISSUE THREAD

**Issue by Andyyy7666** [SnailyCAD/snaily-cadv4#349]
### Describe the feature

I think it would be really useful if we could get the steam or discord id attached to the citizen or vehicle they belong to. For example, when getting all citizens you could include the steam so we can filter out specific users citizens. The same thing goes for vehicles.

**Comment by jxckUK** [comment]
> ### Describe the feature
> I think it would be really useful if we could get the steam or discord id attached to the citizen or vehicle they belong to. For example, when getting all citizens you could include the steam so we can filter out specific users citizens. The same thing goes for vehicles.
> 
> ### Additional Context
> _No response_

If we could also extend this to officers and deputies too then it would save me looping through all the users first, getting the ID then looping through all the officers registered against that ID.

**Comment by Dev-CasperTheGhost** [comment]
> I think it would be really useful if we could get the steam or discord id attached to the citizen or vehicle they belong to. For example, when getting all citizens you could include the steam so we can filter out specific users citizens. The same thing goes for vehicles.

When using `/v1/admin/manage/citizens`, it will return all it's data: Records, vehicles, weapons, user, etc.

> If we could also extend this to officers and deputies too then it would save me looping through all the users first, getting the ID then looping through all the officers registered against that ID.

When using any route that returns unit info, it will return the user info as well
