### ISSUE TITLE
API POST Error

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#353]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

When submitting a call VIA the API the call gets created but returns an error and has not set the department.

### Expected Behavior

The call should be created successfully including the allocation of department.

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/151702939-196a67b3-24b5-4165-9eec-c12badbea7e7.png)

**Comment by Dev-CasperTheGhost** [comment]
Whoops, fixed now!
