### ISSUE TITLE
Setting a unit to off duty in dispatch portal results in an error

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#355]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

Bit of an odd one but I went to set my user off duty in the dispatch portal and got the attached error?

### Expected Behavior

The unit should be set the the desired state.

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/151710707-007fc1a7-2908-4dd4-a83c-ad948aa241a0.png)

**Comment by Dev-CasperTheGhost** [comment]
🤔 not sure where this comes from. Will need to take a look tomorrow unfortunately

**Comment by jxckUK** [comment]
> 🤔 not sure where this comes from. I can only take a look tomorrow unfortunately

No worries! - if you need to see any other logs tomorrow just let me know and I'll try and replicate it and add them here.

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed now!
