### ISSUE TITLE
Duplicate Vehicles/Weapon Registration

### ISSUE THREAD

**Issue by Crazy-Zack** [SnailyCAD/snaily-cadv4#360]
### What version of Node.js are you using?

16.6

### What version of npm are you using?

7.10.0

### What operating system are you using?

Windows

### Describe the Bug

If you have a single citizen made, And have vehicles and weapons registered to that citizen, The registered weapons and vehicles will duplicate to any new citizen you create. It is mainly a cosmetic issue, when you reload the page the registered weapons and vehicles will update.

### Expected Behavior

When creating a new citizen, the vehicles and weapon registration lists would be empty.

### To Reproduce

Create a citizen, Register some vehicles or weapons, Then create a new citizen. You may need to reload the page.

**Comment by Dev-CasperTheGhost** [comment]
Are you able to provide a video of this bug? I'm unable to reproduce it.
