### ISSUE TITLE
UI issue in iframes

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#364]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

![image](https://user-images.githubusercontent.com/48030374/152599494-b46c5e0d-6477-43c3-9971-3d223d1c8268.png)

When using the CAD in an iframe some odd behaviour occurs with drop downs.

### Expected Behavior

The drop down should function within the iframes existing space to some degree.

**Comment by jxckUK** [comment]
In a similar but not quite iframe related UI issue, when multiple divisions are assigned to a user it can push the manage controls for the dispatch out of the existing space which makes it quite difficult as you need to drag across to change a units state. 

If a unit has more than one division is there a way we can condense it down? Maybe some sort of modal or hover option?

![image](https://user-images.githubusercontent.com/48030374/152600004-b3f52dbd-5a4a-4d7e-b23b-9b5a374a51cd.png)

![image](https://user-images.githubusercontent.com/48030374/152600018-04a47f69-1eea-46cc-8b53-33b3a59f3fbb.png)

**Comment by Dev-CasperTheGhost** [comment]
> EDIT: In fact it would be much improved if the manage was right next to names for speed of changing the status.

What about a fixed column? This would make it so the `actions` column would always be on the screen

**Comment by jxckUK** [comment]
> > EDIT: In fact it would be much improved if the manage was right next to names for speed of changing the status.
> 
> 
> 
> What about a fixed column? This would make it so the `actions` column would always be on the screen
> 
> 
> 
> https://user-images.githubusercontent.com/53900565/152632804-be55dc25-5fe7-46fe-a3df-56215e4b5179.mov
> 
> 
> 
> 

Yeah that works! Although it still might be more handy to have it fixed on the left hand side? 😄

**Comment by Dev-CasperTheGhost** [comment]
going to make this a feature request as well. I like to have it on the right side, so why not make it an option 😄!

![image](https://user-images.githubusercontent.com/53900565/152640160-7ecd6fdc-e7bf-4dfd-a803-b6bf9a81a332.png)

**Comment by Dev-CasperTheGhost** [comment]
Table actions alignment is now supported! The main problem in this issue doesn't seem to be fixable :/

**Comment by jxckUK** [comment]
> Table actions alignment is now supported! The main problem in this issue doesn't seem to be fixable :/
Awesome on the alignment options 😄 

Oh no! Is there anything I can do on the iframe side potentially?

**Comment by Dev-CasperTheGhost** [comment]
> Is there anything I can do on the iframe side potentially?

is there an option for fixed max-heights? I think this can be enabled to it doesn't add that extra transparent area below the CAD

**Comment by jxckUK** [comment]
> > Is there anything I can do on the iframe side potentially?
> 
> is there an option for fixed max-heights? I think this can be enabled to it doesn't add that extra transparent area below the CAD

Hmm, yes there is and that doesn't seem to help. It only happens in the modals and not in standard drop downs etc.
