### ISSUE TITLE
Client side error occurred, unknown origin

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#365]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

I've managed to capture the error messages but unfortunately I don't have a good point of origin for it, not sure what happened right before the error as it was passed to me by another player. I've tried to get them to go back over events and they mentioned it occurred during a state change in the LEO section.

Within an iframe they also couldn't refresh, not sure if its possible but can the client error have a refresh/reload button?

### Expected Behavior

N/A

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/152610664-3c21dc9a-f6af-4277-aff2-3c6627d38196.png)
![image](https://user-images.githubusercontent.com/48030374/152610677-85616180-fcf2-4de1-9dc2-b158ec79cd55.png)

**Comment by Dev-CasperTheGhost** [comment]
> they mentioned it occurred during a state change in the LEO section.

When changing their officer status? Or just another state change?

**Comment by jxckUK** [comment]
> > they mentioned it occurred during a state change in the LEO section.
> 
> 
> 
> When changing their officer status? Or just another state change?

I believe this was their own status changed as they're not dispatch etc. would have been via the LEO panel.

**Comment by Dev-CasperTheGhost** [comment]
> I believe this was their own status changed as they're not dispatch etc. would have been via the LEO panel.

I'm not able to reproduce this error. Are you able to retrieve the data (calls, bolos, etc.) that were on that page when it happened?

**Comment by jxckUK** [comment]
> > I believe this was their own status changed as they're not dispatch etc. would have been via the LEO panel.
> 
> I'm not able to reproduce this error. Are you able to retrieve the data (calls, bolos, etc.) that were on that page when it happened?

Ah I did expect it wouldn't be enough information - I can't unfortunately so I'll close this and if it happens again I'll try and get a better overview of everything prior to the exception.

In terms of the refresh option is that something we can do? Obviously would help a lot as otherwise they are stuck in the error state.

**Comment by Dev-CasperTheGhost** [comment]
> In terms of the refresh option is that something we can do? Obviously would help a lot as otherwise they are stuck in the error state.

will look into creating a custom error page!

**Comment by Dev-CasperTheGhost** [comment]
I've added a simple custom 500 error page that now has a button to reload the page. And is now also in dark-mode so it doesn't blind someone when they're playing in the dark 😅

**Comment by jxckUK** [comment]
> I've added a simple custom 500 error page that now has a button to reload the page. And is now also in dark-mode so it doesn't blind someone when they're playing in the dark 😅

Absolute legend! That is perfect.
