### ISSUE TITLE
Ability for all unit information to be updated in /admin/manage/units/

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#367]
### Describe the feature

At the moment we have a limited set of data we can update for the units. Could we extend this to every attribute so that if there is a mistake or something requiring changing it can be carried out by administrators?

### Additional Context

Things like:

Callsigns
Badge numbers
Names

etc

**Comment by Dev-CasperTheGhost** [comment]
> Names

The name is connected to a citizen, so if the name changes for officer x, it will change the name of the citizen from officer x
