### ISSUE TITLE
[FEATURE] Select All For Users

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#370]
### Describe the feature

The option to select all users checkbox and delete bulk users would be nice.
Also option to remove their Citizen Profiles/Officers etc associated with the User. If thats even possible to do at once.

For example, I moved my CAD to a new server. And wanted to delete most users and citizens. :)

**Comment by Dev-CasperTheGhost** [comment]
I think this is better if this is done via a visual database editor? This would be used rarely I think, and could clutter the UI 🤔

**Comment by Dev-CasperTheGhost** [comment]
@ViolentMinds following up ☝️
