### ISSUE TITLE
discord role integration 

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#372]
### Describe the feature

basically a feature where in the backend of cad you can link departments in the cad to discord roles by id , so when people are logging in the api can check the roles and give people what they need

**Comment by Dev-CasperTheGhost** [comment]
This is sort-of already in development. Soon the CAD-owner will be able to connect to Discord and set roles for LEO, EMS-FD, dispatch, etc. 

I can add this option to the department values as well
