### ISSUE TITLE
Detailed Webhook Logging

### ISSUE THREAD

**Issue by marshular** [SnailyCAD/snaily-cadv4#375]
### Describe the feature

Basically allows you to have separate logging for different things. So like #duty-logs or #911-logs

**Comment by Dev-CasperTheGhost** [comment]
This can be done after #373, instead of entering a webhook url, owners can select the channels they’d like for each type.

**Comment by Dev-CasperTheGhost** [comment]
For now, these are the supported types: 

![image](https://user-images.githubusercontent.com/53900565/155184362-1dbf99c9-9f09-4425-a3e0-0fc2b4473aeb.png)

More types will be added if needed
