### ISSUE TITLE
Amending collar numbers doesn't save

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#377]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

When making a change to a units collar number it says the change has been applied but it never seems to update the value.

### Expected Behavior

When the value is modified in the new field under manage units it should update it for the user.

### To Reproduce

Should be able to re-produce, I've tried an array of different values and it seems consistent.

**Comment by Dev-CasperTheGhost** [comment]
Seems like that field wasn’t added in the API. Will fix this when I get home!
