### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by MichaelSasser** [SnailyCAD/snaily-cadv4#378]
### Describe the feature

The API documentation is currently only useful for TS and probably JS developers. If someone, like me, is not in the realm of those programming languages, it is actually unnecessarily difficult to follow through. The API should be programming language independent.

### Additional Context

Tools like [swagger.io](https://swagger.io/) can make the documentation process simple. Here is an [example for Ts.ED](https://tsed.io/tutorials/swagger.html).

**Comment by Dev-CasperTheGhost** [comment]
This will be a fairly large feature request, but I think I can gradually do this over time.

**Comment by MichaelSasser** [comment]
It doesn't need to be a swagger.io or any tool like this. In general, if it is somewhat useful documented to adopt the API to own projects, I would be happy.

I don't know, how much time and effort it needs to implement such features into this codebase. In some frameworks (I can't speak about TS, especially Ts.Ed), it can be done in a couple of minutes, with minimal effort (besides writing examples). I put it in "Additional Context" because it was just an idea. The [OpenAPI Specification](https://www.openapis.org/faq) Swagger uses (and originally invented) is widely used and adopted by many developers and programs to quickly work with an API or browse and learn through it.

**Comment by Dev-CasperTheGhost** [comment]
> It doesn't need to be a swagger.io or any tool like this.

I'll either go with Swagger and have docs locally for the API, or have a section in the current docs for it. Most likely swagger since it integrates better with the code

> I don't know, how much time and effort it needs to implement such features into this codebase.

The implementation will be easy. The writing of docs will take a bit more time since there are a lot of features 😅.

**Comment by Dev-CasperTheGhost** [comment]
Progress can be tracked on [this branch](https://github.com/SnailyCAD/snaily-cadv4/tree/feature/sna-372)

**Comment by Dev-CasperTheGhost** [comment]
Most of the routes now have a simple description. They are grouped by Controller name. Some of them are hidden because they're not able to be used with the API token.

After updating, the API can be viewed at: `http://my-api-here.com/api-docs`. This will open up Swagger UI
