### ISSUE TITLE
Disable Discord options (authentication & connection) in an iframe

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#389]
### Describe the feature

As discussed in Discord:

Please can we hide the options for Discord authentication when in an iframe as Discord does not support this.

Additionally can we make it so we can enable Discord integration so users can link accounts to CAD accounts without the ability to sign in/register with Discord. They should be two separate toggles if possible? 

So we can enable the integration without enabling the authentication.

### Additional Context

https://gist.github.com/tommcfarlin/eba5a69b4a5f25633ef7#file-page-is-displayed-in-iframe-js

**Comment by Dev-CasperTheGhost** [comment]
discord auth will now be hidden when in an iframe. I've also removed the ability to change discordId as a user. This is still possible as admin via manage users.
