### ISSUE TITLE
discord 911 and cad integration 

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#390]
### Describe the feature

might be a lot to ask for but here it is

when making a 911 call in cad maybe somehow add a live audio input feature where the user can talk through cad and interact with dispatch . maybe make it with the api if this was added that it can take input and give output so you can link this through a discord bot and it will join the users channel and the user can talk to dispatch 

sorry if its worded weird i dont rly know how to word it

**Comment by Dev-CasperTheGhost** [comment]
If I read this correctly, you, as a user want to talk into your microphone and "talk" to the Discord bot to manage dispatch?

**Comment by subtosharki** [comment]
no , it would be cool if you could add that to the api fully to work with it to be able to add it to a discord bot , but im just requesting a feature where you can talk with 911 in civ cad to be more realistic

**Comment by Dev-CasperTheGhost** [comment]
oh, yeah. This is going a bit to far 😅. This would then also require me to maintain a Discord bot
