### ISSUE TITLE
Add sounds to panic & signal 100

### ISSUE THREAD

**Issue by rhys19** [SnailyCAD/snaily-cadv4#394]
### Describe the feature

Possibility to add sounds to the signl 100, and panic button? would be useful if signal 100 was enabled but some of the officers had the cad minimized, etc. or closed in the steam browser.

Signal 100 Tone: https://rhys19.xyz/downloads/signal100.mp3
For signal 100 I'd add TTS voices after the tone saying like Signal 100 is in effect standby for details

Panic tone: https://rhys19.xyz/downloads/panic-button.mp3

**Comment by XComatoseX** [comment]
It would be even cooler if you could change the sound in the settings, according to the principle of changing the locale. If possible)

**Comment by Dev-CasperTheGhost** [comment]
Now supported, thanks for providing these sounds \<3! Documentation for changing the sounds [can be found here](https://cad-docs.caspertheghost.me/docs/guides/how-set-custom-sounds)
