### ISSUE TITLE
Restrict EMS/FD to one unit per department

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#398]
### Describe the feature

The option to enable a limit of one unit per department in EMS/FD. This would mean they could create a unit per department but never more than one.

**Comment by Dev-CasperTheGhost** [comment]
Would this also account for LEO, or only EMS/FD?

**Comment by jxckUK** [comment]
> Would this also account for LEO, or only EMS/FD?

That would be good yes!

**Comment by Dev-CasperTheGhost** [comment]
Cool! So, something like `maxUnitsPerDepartmst` in cad-settings? So it’s even more customisable.

**Comment by jxckUK** [comment]
> Cool! So, something like `maxUnitsPerDepartmentsPerUser` in cad-settings? So it’s even more customisable.

Yeah that works, would allow us to set it to one unit per department 🙂
