### ISSUE TITLE
10-Codes only display first 10 entries

### ISSUE THREAD

**Issue by nick-perry14** [SnailyCAD/snaily-cadv4#400]
### What version of Node.js are you using?

16.14.0

### What version of npm are you using?

8.3.1

### What operating system are you using?

Ubuntu Server

### Describe the Bug

After 10 or so 10-codes, the system stops displaying the rest.  The new code gets placed at the top of the list, then everything gets shifted down, and one code gets shifted out of frame

### Expected Behavior

The list should just continue iterating through the entries

### To Reproduce

Keep adding 10-codes

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed now! Didn't realize it was broken lol. Thanks for reporting!
