### ISSUE TITLE
On Duty Button

### ISSUE THREAD

**Issue by nick-perry14** [SnailyCAD/snaily-cadv4#402]
### Describe the feature

Have the on-duty button **NOT** ask for the officer they want to use when they are already on duty.  Many use the "on-duty" button as available and it's kind of annoying to keep having to pick an officer when going back to in-service

**Comment by Dev-CasperTheGhost** [comment]
Where should this button be located at? Maybe a different select option somewhere else?

**Comment by nick-perry14** [comment]
The on-duty button should remain the exact same, however the "officer picker" should only appear if the user is off-duty.  If the user has already picked an on-duty officer, pushing the button should just switch that officer back to the status

**Comment by Dev-CasperTheGhost** [comment]
oh yeah, that could work too! Will work on this tomorrow
