### ISSUE TITLE
Penal Codes have dissapeared.

### ISSUE THREAD

**Issue by Crazy-Zack** [SnailyCAD/snaily-cadv4#405]
### What version of Node.js are you using?

16.6

### What version of npm are you using?

7.10.0

### What operating system are you using?

Windows

### Describe the Bug

Whenever I attempt to view/edit the Penal codes it comes up as NaN/3 on the penal code page. Officers are still able to add arrest reports and create tickets, but we are unable to modify any penal codes.

![image](https://user-images.githubusercontent.com/98304567/154204791-e80018c2-fccf-4d75-ab6a-cd505dcc11a7.png)

### Expected Behavior

We would usually be able to modify our penal codes.

### To Reproduce

To be honest, I am not exactly sure what caused this.

**Comment by Dev-CasperTheGhost** [comment]
Does refreshing the page fix this issue?

**Comment by Dev-CasperTheGhost** [comment]
Fixed!
