### ISSUE TITLE
discord only login

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#413]
### Describe the feature

add an option under cad settings to have a discord only register , basically removing the normal signup text on the landing page and leaving only login and login with discord

**Comment by Dev-CasperTheGhost** [comment]
This could work, but not for the first account. The first account that registers must use username/password, then they can enable Discord only login and such. After that, only Discord auth will work

**Comment by Dev-CasperTheGhost** [comment]
This feature can be found in the Features tab in CAD-settings: 
![image](https://user-images.githubusercontent.com/53900565/154789200-c76e453f-6c24-42fc-ad10-5401343e2761.png)
