### ISSUE TITLE
Extend importing of citizens

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#423]
### Describe the feature

Can we extend the importing of citizens via JSON files to also allow us to provide details of a vehicle and licenses to register against the user upon creation?

**Comment by Dev-CasperTheGhost** [comment]
You mean the DMV/weapon license fields, or the ability to register vehicles/weapons directly from the citizens import?

**Comment by jxckUK** [comment]
> You mean the DMV/weapon license fields, or the ability to register vehicles/weapons directly from the citizens import?

Directly from the citizens import, so I can add vehicles to citizens I import at the time of importing if possible?

**Comment by Dev-CasperTheGhost** [comment]
You can now simply append `vehicles` or `weapons` to a citizen object. It does not require the `ownerId` property.

Example:

```json
[
  {
    "name": "Jane",
    "surname": "Doe",
    "gender": "ckzv88zfa0318dwo516ccyotn",
    "ethnicity": "ckzv893a90382dwo57dpsnaed",
    "dateOfBirth": "1978-02-19",
    "vehicles": [
      {
        "plate": "HELLO",
        "modelId": "ckzvm24ya1265hymt0vjjr2z5",
        "color": "white",
        "registrationStatusId": "ckzv88umy0252dwo5c2q5hitt"
      }
    ]
  }
]
```

**Comment by jxckUK** [comment]
> You mean the DMV/weapon license fields, or the ability to register vehicles/weapons directly from the citizens import?

It's just occurred to me what you meant when you asked this - is it possible to also add licenses to the import system?

**Comment by Dev-CasperTheGhost** [comment]
Sure! Will add after school.

**Comment by Dev-CasperTheGhost** [comment]
> It's just occurred to me what you meant when you asked this - is it possible to also add licenses to the import system?

Should work now! Will update the docs soon
