### ISSUE TITLE
EMS/FD can't change state after going on duty

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#425]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

When a unit registers and clocks on as EMS/FD the other state codes are locked out.

We don't use active dispatcher so don't think its that.

### Expected Behavior

They should be able to select other statuses.

**Comment by Dev-CasperTheGhost** [comment]
I can't seem to reproduce this bug 🤔

https://user-images.githubusercontent.com/53900565/154789542-0934ee58-b365-4b0c-ac63-6da0c1fe341c.mov

**Comment by jxckUK** [comment]
![image](https://user-images.githubusercontent.com/48030374/154799163-701908b6-568d-47e1-971f-78d231ea6eb9.png)


You can see I'm state 1 down at the bottom but the options are greyed out for some reason?

**Comment by Dev-CasperTheGhost** [comment]
Are you able to provide a video reproduction? I can't reproduce this 😅

**Comment by jxckUK** [comment]
https://medal.tv/games/requested/clips/byHwDY_6MRxVz/d1337r9LxhIH?invite=cr-MSxEWk0sMzk0MjcxMjUs

**Comment by Dev-CasperTheGhost** [comment]
Are you also able to provide the results of the requests that are being sent from /v1/ems-fd/active-deputies and /v1/ems-fd/active-deputy?

Not sure what's happening here 🤔

**Comment by jxckUK** [comment]
active deputies:

[{"id":"ckzk4ramx1636554mr1h6h6pgnvd","departmentId":"ckxjne1zg6385s41hj23iia67","callsign":"A","callsign2":"5","divisionId":"ckyy9ygu6264090gx1hspxnxwbi","rankId":null,"statusId":"9d0a905e-14cf-4853-bb12-2101a3e39155","suspended":false,"badgeNumber":331,"imageId":null,"citizenId":"ckxrmafkd15057161hxu37azgz","userId":"ckxkinu7919734rl1hmk7sxvsw","createdAt":"2022-02-12T17:46:19.161Z","updatedAt":"2022-02-18T23:17:04.440Z","department":{"id":"ckxjne1zg6385s41hj23iia67","valueId":"ckxjne1z86378s41h9s3skty6","callsign":null,"whitelisted":false,"isDefaultDepartment":false,"type":"EMS_FD","value":{"id":"ckxjne1z86378s41h9s3skty6","type":"DEPARTMENT","value":"London Ambulance Service","isDefault":false,"createdAt":"2021-12-24T00:20:43.268Z","updatedAt":"2022-01-28T10:42:10.319Z","position":null,"licenseType":null}},"division":{"id":"ckyy9ygu6264090gx1hspxnxwbi","valueId":"ckyy9ygu6264091gx1hew1pvibz","departmentId":"ckxjne1zg6385s41hj23iia67","callsign":"","value":{"id":"ckyy9ygu6264091gx1hew1pvibz","type":"DIVISION","value":"Accident & Emergency","isDefault":false,"createdAt":"2022-01-28T10:40:55.998Z","updatedAt":"2022-01-28T10:40:55.998Z","position":null,"licenseType":null},"department":{"id":"ckxjne1zg6385s41hj23iia67","valueId":"ckxjne1z86378s41h9s3skty6","callsign":null,"whitelisted":false,"isDefaultDepartment":false,"type":"EMS_FD"}},"status":{"id":"9d0a905e-14cf-4853-bb12-2101a3e39155","valueId":"ckxjn72o25662s41h698vxjgu","shouldDo":"SET_ASSIGNED","whatPages":[],"color":"#ff8700","type":"STATUS_CODE","value":{"id":"ckxjn72o25662s41h698vxjgu","type":"CODES_10","value":"State 5","isDefault":false,"createdAt":"2021-12-24T00:15:17.570Z","updatedAt":"2022-01-21T13:12:05.635Z","position":4,"licenseType":null}},"citizen":{"name":"tel","surname":"boy","id":"ckxrmafkd15057161hxu37azgz"},"user":{"id":"ckxkinu7919734rl1hmk7sxvsw","username":"Telboy","rank":"ADMIN","isLeo":true,"isSupervisor":true,"isEmsFd":true,"isDispatch":true,"isTow":false,"banned":false,"banReason":null,"avatarUrl":null,"steamId":"","whitelistStatus":"ACCEPTED","isDarkTheme":true,"tempPassword":null,"statusViewMode":"FULL_ROW_COLOR","discordId":"812028752531030017","tableActionsAlignment":"RIGHT"},"rank":null},{"id":"ckz1uzphn2014884k1hgtpumi2s","departmentId":"ckz1uxzuj1996534k1hugm2hu8o","callsign":"Z","callsign2":"1","divisionId":"ckz1uzaa82008414k1h74u5e6sm","rankId":null,"statusId":"8ea7fef6-1dce-4b4e-9d86-62d6e3258c04","suspended":false,"badgeNumber":231312,"imageId":null,"citizenId":"ckxkjsaf125758rl1hhvb1zxxs","userId":"ckxjm4ye50020s41h0rk30tpg","createdAt":"2022-01-30T22:53:04.331Z","updatedAt":"2022-02-19T12:06:52.527Z","department":{"id":"ckz1uxzuj1996534k1hugm2hu8o","valueId":"ckz1uxzuj1996544k1hx8q3yf9o","callsign":"","whitelisted":false,"isDefaultDepartment":false,"type":"EMS_FD","value":{"id":"ckz1uxzuj1996544k1hx8q3yf9o","type":"DEPARTMENT","value":"National Highways","isDefault":false,"createdAt":"2022-01-30T22:51:44.443Z","updatedAt":"2022-01-30T22:51:44.443Z","position":null,"licenseType":null}},"division":{"id":"ckz1uzaa82008414k1h74u5e6sm","valueId":"ckz1uzaa82008424k1h487t833j","departmentId":"ckz1uxzuj1996534k1hugm2hu8o","callsign":"","value":{"id":"ckz1uzaa82008424k1h487t833j","type":"DIVISION","value":"Response","isDefault":false,"createdAt":"2022-01-30T22:52:44.624Z","updatedAt":"2022-01-30T22:52:44.624Z","position":null,"licenseType":null},"department":{"id":"ckz1uxzuj1996534k1hugm2hu8o","valueId":"ckz1uxzuj1996544k1hx8q3yf9o","callsign":"","whitelisted":false,"isDefaultDepartment":false,"type":"EMS_FD"}},"status":{"id":"8ea7fef6-1dce-4b4e-9d86-62d6e3258c04","valueId":"ckxjn2z5l4380s41hmwm3gtpz","shouldDo":"SET_ON_DUTY","whatPages":[],"color":"#005e00","type":"STATUS_CODE","value":{"id":"ckxjn2z5l4380s41hmwm3gtpz","type":"CODES_10","value":"State 1","isDefault":false,"createdAt":"2021-12-24T00:12:06.393Z","updatedAt":"2022-01-21T13:12:05.639Z","position":0,"licenseType":null}},"citizen":{"name":"Jack","surname":"Fox","id":"ckxkjsaf125758rl1hhvb1zxxs"},"user":{"id":"ckxjm4ye50020s41h0rk30tpg","username":"Jack","rank":"OWNER","isLeo":true,"isSupervisor":true,"isEmsFd":true,"isDispatch":true,"isTow":true,"banned":false,"banReason":null,"avatarUrl":null,"steamId":"","whitelistStatus":"ACCEPTED","isDarkTheme":true,"tempPassword":null,"statusViewMode":"DOT_COLOR","discordId":"323231395981819904","tableActionsAlignment":"LEFT"},"rank":null}]

active deputy:

{"id":"ckyy9yr9x264524gx1hp5i6b01x","departmentId":"ckxjne1zg6385s41hj23iia67","callsign":"Z","callsign2":"1","divisionId":"ckyy9ygu6264090gx1hspxnxwbi","rankId":null,"statusId":null,"suspended":false,"badgeNumber":50493,"imageId":null,"citizenId":"ckxkjsaf125758rl1hhvb1zxxs","userId":"ckxjm4ye50020s41h0rk30tpg","createdAt":"2022-01-28T10:41:09.525Z","updatedAt":"2022-02-19T12:06:52.520Z","department":{"id":"ckxjne1zg6385s41hj23iia67","valueId":"ckxjne1z86378s41h9s3skty6","callsign":null,"whitelisted":false,"isDefaultDepartment":false,"type":"EMS_FD","value":{"id":"ckxjne1z86378s41h9s3skty6","type":"DEPARTMENT","value":"London Ambulance Service","isDefault":false,"createdAt":"2021-12-24T00:20:43.268Z","updatedAt":"2022-01-28T10:42:10.319Z","position":null,"licenseType":null}},"division":{"id":"ckyy9ygu6264090gx1hspxnxwbi","valueId":"ckyy9ygu6264091gx1hew1pvibz","departmentId":"ckxjne1zg6385s41hj23iia67","callsign":"","value":{"id":"ckyy9ygu6264091gx1hew1pvibz","type":"DIVISION","value":"Accident & Emergency","isDefault":false,"createdAt":"2022-01-28T10:40:55.998Z","updatedAt":"2022-01-28T10:40:55.998Z","position":null,"licenseType":null},"department":{"id":"ckxjne1zg6385s41hj23iia67","valueId":"ckxjne1z86378s41h9s3skty6","callsign":null,"whitelisted":false,"isDefaultDepartment":false,"type":"EMS_FD"}},"status":null,"citizen":{"name":"Jack","surname":"Fox","id":"ckxkjsaf125758rl1hhvb1zxxs"},"user":{"id":"ckxjm4ye50020s41h0rk30tpg","username":"Jack","rank":"OWNER","isLeo":true,"isSupervisor":true,"isEmsFd":true,"isDispatch":true,"isTow":true,"banned":false,"banReason":null,"avatarUrl":null,"steamId":"","whitelistStatus":"ACCEPTED","isDarkTheme":true,"tempPassword":null,"statusViewMode":"DOT_COLOR","discordId":"323231395981819904","tableActionsAlignment":"LEFT"},"rank":null}

**Comment by Dev-CasperTheGhost** [comment]
This does not happen for LEO?

**Comment by Dev-CasperTheGhost** [comment]
I've just pushed a commit that uses the same logic for EMS/FD as LEO. I'm not sure but I think that should fix it. Are you able to verify :)?

**Comment by jxckUK** [comment]
> I've just pushed a commit that uses the same logic for EMS/FD as LEO. I'm not sure but I think that should fix it. Are you able to verify :)?

Will do now!

**Comment by jxckUK** [comment]
Yep - looks all fixed to me! Thanks Casper 😄
