### ISSUE TITLE
Application errors when performing usual actions

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#426]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

Application error: a client-side exception has occurred (see the browser console for more information).

Just performing usual actions, had it occur when I also wasn't performing any actions at all and had it in the background.

### Expected Behavior

N/A - Error

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/154773842-5126f7e9-7639-46c2-ac38-a5a85010d4e8.png)
[1645226503424.log](https://github.com/SnailyCAD/snaily-cadv4/files/8100986/1645226503424.log)

**Comment by Dev-CasperTheGhost** [comment]
On what page has this occurred?

**Comment by Dev-CasperTheGhost** [comment]
@jxckUK I've added a few more checks. Are you able to verify if this is fixed?

**Comment by jxckUK** [comment]
> @jxckUK I've added a few more checks. Are you able to verify if this is fixed?

I'll update and give it a whirl, it didn't seem to have any particular triggers so might be one that needs a day or so of use.

**Comment by Dev-CasperTheGhost** [comment]
👍, will close this issue for now. If you're getting this error again, feel free to re-open this/create a new github issue
