### ISSUE TITLE
Granular access permissions

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#432]
### Describe the feature

Provide the ability to go even more granular for permissions for example:

Administrator:

- Allow a subset of users to modify values but not amend any other settings

LEO: 

- Allow a subset of users to access Jail/Custody section
- Allow a subset of users to access Map

Every pane in the CAD should have an associated permission that can be assigned to users as this would be the best way to manage permissions as the CADs features scale out and new things are added.

**Comment by Dev-CasperTheGhost** [comment]
Something like Discord's permissions would probably be a great example for this I'd guess?

**Comment by jxckUK** [comment]
> Something like Discord's permissions would probably be a great example for this I'd guess?

Exactly that yeah - as I have for example, some users I'd like to grant access to edit laws but that requires admin permissions which are too broad. The principle of least privilege is much preferred when dealing with permissions.

**Comment by Dev-CasperTheGhost** [comment]
yup, this is something I'll have to look into to making scalable. This will definitely not be an easy task 😅!

**Comment by Dev-CasperTheGhost** [comment]
Would there be a permission per each value, or a toggle for all values?

**Comment by jxckUK** [comment]
> Would there be a permission per each value, or a toggle for all values?

Per value would be better but I understand that's probably more effort

**Comment by Dev-CasperTheGhost** [comment]
No should be fine :). Will try get information together for permissions and such the coming week

**Comment by Dev-CasperTheGhost** [comment]
I've been able to look into how to handle these permissions and have decided to use bits (like Discord's permission system). This is a complex and simple solution IMO. 
*Note: I'm not yet sure if I this is the solution that will be in production.*

**Comment by Dev-CasperTheGhost** [comment]
*Status announcement:* Making quite a bit of progress right now. However it may still take some time since I've gotta refactor all the buttons to check for permissions lol. But it'll be worth it IMO :)

**Comment by Dev-CasperTheGhost** [comment]
Looks like that wasn't the best way to go. There's a limit of digits that can be used it seems. I'll need to use a different system, *back to the drawing board*

**Comment by Dev-CasperTheGhost** [comment]
Very soon:tm:!!

![image](https://user-images.githubusercontent.com/53900565/159112089-993ae013-5a0c-4944-9875-85195df41d0b.png)

**Comment by jxckUK** [comment]
> Very soon™️!!
> 
> ![image](https://user-images.githubusercontent.com/53900565/159112089-993ae013-5a0c-4944-9875-85195df41d0b.png)
> 
> **Current Permissions**
> 
> ![image](https://user-images.githubusercontent.com/53900565/159112182-67d318dc-145b-4851-a8e1-19ec270d12b4.png)

This looks fantastic, as always! 🚀

**Comment by Dev-CasperTheGhost** [comment]
Now supported 🚀! Let me know if you're experiencing issues, have questions, etc!!
