### ISSUE TITLE
[IMPROVEMENTS] Multiple Discord roles per category

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#433]
### Describe the feature

Add the ability to specify multiple Discord roles for a category.

Now you can specify only one role, and this is not very convenient and correct from the logic of the Discord community
![image](https://user-images.githubusercontent.com/4976837/154802315-7f6b8f84-9b4d-436e-9d52-5ecc54d3d2b5.png)

Example: LEO roles in Discord are LSPD, LSSD, SAHP and others. 
![image](https://user-images.githubusercontent.com/4976837/154802437-2ec2158c-bdc4-4351-8924-e92c79e5f719.png)

But now only one role can be specified in CAD

I propose to use a mechanism that allows you to specify multiple roles for a category.
A similar mechanism is used to specify an officer's divisions or on the page for attaching units to a call.
![image](https://user-images.githubusercontent.com/4976837/154802531-f4776714-1f43-42b9-9290-d340e33186db.png)
![image](https://user-images.githubusercontent.com/4976837/154802541-50c30f07-55a3-478d-848d-d3db178ba49e.png)

**Comment by Dev-CasperTheGhost** [comment]
Currently, this is only for the **LEO Permission**. I'm already planning to add this to departments, I'd divisions would fit better then departments?

**Comment by pp2amd6** [comment]
Roles for divisions instead of departments?

The roles for divisions would be more flexible if there was a mechanism for rights to CAD elements.

I believe that specifying multiple roles for LEO is sufficient.

What do you think?

**Comment by Dev-CasperTheGhost** [comment]
> Roles for divisions instead of departments? The roles for divisions would be more flexible if there was a mechanism for rights to CAD elements.

yes, I agree. Will try to prioritize this.

**Comment by Dev-CasperTheGhost** [comment]
I've hit a minor roadblock. Would the role be added to all the units of the user? 

@pp2amd6 @jxckUK

**Comment by jxckUK** [comment]
> I've hit a minor roadblock. Would the role be added to all the units of the user?
> 
> @pp2amd6 @jxckUK

Oh I'm not too sure to be honest, maybe @pp2amd6 has some thoughts. I guess it would be any units created by the user.

**Comment by Dev-CasperTheGhost** [comment]
I don't think adding the divisions to all units the user created feels right. Maybe there's a better way? 

For the user LEO permission, I don't think that's necessary since you can add a main role called e.g. `Officer`?

**Comment by jxckUK** [comment]
> I don't think adding the divisions to all units the user created feels right. Maybe there's a better way?
> 
> For the user LEO permission, I don't think that's necessary since you can add a main role called e.g. `Officer`?

From my perspective it should be a "these groups can access this role" setup, rather than a unique role that is then required to be added to everyone in the Discord guild. So if the user is a member of any of the assigned groups, they get LEO permission or whatever the assignment is.

Then for division/department access that can be a single group assignment as that is a more one to one match with Discord roles.

**Comment by Dev-CasperTheGhost** [comment]
> From my perspective it should be a "these groups can access this role" setup, rather than a unique role that is then required to be added to everyone in the Discord guild. So if the user is a member of any of the assigned groups, they get LEO permission or whatever the assignment is.

Alright, yeah. Seems like I misunderstood this feature request 😅. Will work on this very soon, cc @pp2amd6
