### ISSUE TITLE
more frequent discord permission sync 

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#436]
### Describe the feature

have the cad check the discord roles everytime you go to a new page or something like that instead of only re-login .

**Comment by Dev-CasperTheGhost** [comment]
I think every request will be prone to ratelimits, therefore I'm adding a `lastDiscordSyncTimestamp`, it will sync the roles every 3min per request. 

So: 

```mermaid
flowchart TD
	A[Incoming API Request] --> B{Have 3 minutes passed since last sync?}
	B -- Yes --> C[Sync Discord roles]
	B -- No --> D[Skip sync]
	C ----> E[Continue ]
	D ----> E[Continue ]
```
