### ISSUE TITLE
Channel management on the dispatch portal

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#441]
### Describe the feature

Most servers have radios that use different channels when units are involved in incidents/pursuits etc. Having a column for units radio channel that can be quickly switched in the dispatch portal would allow us to leverage the API to switch their radio channel in game.

**Comment by pp2amd6** [comment]
Here you need to clarify what kind of voice resource we are talking about.
Someone uses mumble, someone uses pma-voice, there are projects with teamspeak, and someone generally uses the own developed voice resource

**Comment by jxckUK** [comment]
> Here you need to clarify what kind of voice resource we are talking about. Someone uses mumble, someone uses pma-voice, there are projects with teamspeak, and someone generally uses the own developed voice resource

That's fine as the only thing the CAD will do is represent a channel number. How you integrate that with voice resources is up to you and gives users the flexibility to leverage the API.

For instance, with PMA voice you would just set the channel using the export. For teamspeak I'm not sure maybe theres some TS API you can leverage but frankly thats out of scope of what the CAD can provide. It would just be a value assigned to the unit.

**Comment by Dev-CasperTheGhost** [comment]
🚀 

dispatch: 
![image](https://user-images.githubusercontent.com/53900565/155323869-84119689-1771-41d6-9b14-b71422b7535b.png)

non-dispatch

![image](https://user-images.githubusercontent.com/53900565/155323924-9eea7a63-8ca7-437d-8ae9-4bd24a55c35d.png)
