### ISSUE TITLE
Dispatch improvements

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#443]
### Describe the feature

Just a few things I've noticed while running as dispatch lately (which has otherwise been amazing):

- [x] The right click options for state setting which are super helpful would also be super helpful for EMS/FD units.
- [x] The formatting of 911 call events could be improved to use more of the blank space before requiring a scroll bar (see below).
- [x] Extend the use of incidents so that there is an extra section very similar to 911 calls that allows Dispatch to create incidents that units can be assigned to. This is useful in scenarios where off the cuff incidents occur that aren't 911 calls. It would be good if this was also a column for units so you can see where units are assigned if they are with a pop out modal button for the full call/incident details.

### Additional Context

![scroll](https://user-images.githubusercontent.com/48030374/154856231-54778307-b6db-44c2-8cfa-a36186feade0.png)

**Comment by Dev-CasperTheGhost** [comment]
>  Extend the use of incidents so that there is an extra section very similar to 911 calls that allows Dispatch to create incidents that units can be assigned to. This is useful in scenarios where off the cuff incidents occur that aren't 911 calls. It would be good if this was also a column for units so you can see where units are assigned if they are with a pop out modal button for the full call/incident details.

Are you able to share an image/video demonstration for this? I'm not 100% sure what you mean with this 😅.

**Comment by jxckUK** [comment]
![image](https://user-images.githubusercontent.com/48030374/154860038-d1a41596-7a5f-4a98-9608-7bb81b2be67c.png)

![image](https://user-images.githubusercontent.com/48030374/154860154-4529bd1d-ecf0-43ac-8536-a004ae3b540e.png)

Hmm... something along the lines of this?

**Comment by Dev-CasperTheGhost** [comment]
Would these incidents also show on the incidents page?

**Comment by jxckUK** [comment]
> Would these incidents also show on the incidents page?

Sure! The officer might just be listed as 'Dispatch' or something for ones created via that method.

**Comment by Dev-CasperTheGhost** [comment]
@jxckUK, only 1 call can have an active incident?

**Comment by jxckUK** [comment]
> @jxckUK, only 1 call can have an active incident?

Not too sure what you mean? In this use case you should be able to have multiple incidents not linked to calls

**Comment by Dev-CasperTheGhost** [comment]
Oh, right! Lol, totally forgot about that, nevermind that question

**Comment by Dev-CasperTheGhost** [comment]
Something like this for the table view? 
![image](https://user-images.githubusercontent.com/53900565/154990700-f6c67900-e2de-4efd-8a6a-d4a5d754653d.png)

**Comment by jxckUK** [comment]
> Something like this for the table view? ![image](https://user-images.githubusercontent.com/53900565/154990700-f6c67900-e2de-4efd-8a6a-d4a5d754653d.png)

Looks good to me, and you can assign units above and see that they're active on an incident?

**Comment by Dev-CasperTheGhost** [comment]
> Looks good to me, and you can assign units above and see that they're active on an incident?

Yup, will be working on that soon. First doing to active incidents stuff.

**Comment by Dev-CasperTheGhost** [comment]
I'm not sure what I should name the "end"/"deactive" active incident button. Since non-active incidents will go to the officers incidents page and do not show on the dispatch page; Suggestions :)?

**Comment by Dev-CasperTheGhost** [comment]
@jxckUK, would this `#5` be an action? What would it do if it were one? 

![image](https://user-images.githubusercontent.com/53900565/155004771-700cd0c4-2b60-4a1b-9250-e91dddcb4c38.png)

**Comment by Dev-CasperTheGhost** [comment]
🚀

https://user-images.githubusercontent.com/53900565/155008495-4bdb878e-bf5b-485a-bcee-27a99b2ce27e.mov

**Comment by jxckUK** [comment]
> 🚀
> 
>  2022-02-21.19-16-39.mov

Yes! This is spot on - I now get the previous question about the #5 it wasn't from the incident panel it was from the active units one right? In that case it might be good for it to open the incident? :D

**Comment by Dev-CasperTheGhost** [comment]
> it wasn't from the incident panel it was from the active units one right? In that case it might be good for it to open the incident? 😄

Yeah. Should it open in read-only mode for the officer?

**Comment by jxckUK** [comment]
> > it wasn't from the incident panel it was from the active units one right? In that case it might be good for it to open the incident? 😄
> 
> Yeah. Should it open in read-only mode for the officer?

Erm - not necessarily as they should be able to add details if they're in the CAD but then again maybe they shouldn't do that until its ended. Tough one, maybe a settings toggle?

**Comment by Dev-CasperTheGhost** [comment]
> Erm - not necessarily as they should be able to add details if they're in the CAD but then again maybe they shouldn't do that until its ended. Tough one, maybe a settings toggle?

Meh. I think it should be fine tbh. Will see if there's feedback for it later down the road :)

**Comment by Dev-CasperTheGhost** [comment]
This was quite a fun feature to implement! Enjoy 🚀!
