### ISSUE TITLE
Incident button links to wrong modal

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#448]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

The new incident dispatch section is awesome, good work. Only thing I've noticed is the incident modal on active officers opens incident creation not the incident in question.

### Expected Behavior

It should open that incident that has been allocated to the unit.

### To Reproduce

1. Assign a unit to an incident via the Dispatch portal
2. Select the linked incident on that units active officer line item

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed now
