### ISSUE TITLE
Incident event log

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#449]
### Describe the feature

When an incident is created via dispatch, it would be good if it replicated the layout of a 911 call.

While the incident is active and live in dispatch it should allow for incident events to be created in the same timestamped manner as 911 calls. Then once the incident is ended by dispatch, it will move to the incidents page as it does now where the officer can add the 'description' also known as an incident report.

This then provides the full picture of an incident, from the timeline of events to the officers report post incident.

### Additional Context

![image](https://user-images.githubusercontent.com/48030374/155140945-742e6c31-c5f1-474c-9495-82e6af61f28b.png)

**Comment by Dev-CasperTheGhost** [comment]
The officer can still see (readonly) the live-chat Dispatch had when it was ended? Or will the chat be fully hidden?

**Comment by jxckUK** [comment]
> 

Yes read only would be perfect, so they can use it as they create their post incident report :smile:

**Comment by Dev-CasperTheGhost** [comment]
@jxckUK, Are officers able to add events when the incident is still active? Or should it be read-only then too?

**Comment by jxckUK** [comment]
> @jxckUK, Are officers able to add events when the incident is still active? Or should it be read-only then too?

Good question, as officers can create incidents as well, those they can add events to. If the incident has been created by dispatch they should be read only both during and after the incident.
