### ISSUE TITLE
[FEATURE REQUEST] Improvement of Dispatch 911 Call

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#45]
### Describe the feature

1. Move the block of events. This arrangement will allow you to place more information and make it easier to perceive.
![kiss_26kb 1635109582 1](https://user-images.githubusercontent.com/4976837/138613450-068ca271-1615-49a3-b974-1b07f8603f65.png)

2. Add the ability to edit and delete events (show icons on focus)
![kiss_8kb 1635109604 1](https://user-images.githubusercontent.com/4976837/138613495-452ed121-5488-428a-b8b0-ad7899e81c91.png)

3. Fast events
The dispatcher can quickly add events as requested by units.

Quick events are created in CAD settings, like 10 codes

Example:
- L12 reported firing
- The dispatcher right-clicks on unit L12 in the list of attached units and selects a quick event
- The event is added to the call log
![kiss_28kb 1635110073 1](https://user-images.githubusercontent.com/4976837/138613508-c46e83e5-53bc-470e-83bb-659e391e78a1.png)

**Comment by Dev-CasperTheGhost** [comment]
@pp2amd6 I think i've already asked this before, but the Quick Events should be a `Value` correct?

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost Give me an hour. I will think over the function and write down the functionality.

**Comment by Dev-CasperTheGhost** [comment]
> 
> 
> @Dev-CasperTheGhost Give me an hour. I will think over the function and write down the functionality.

yup, no worries. No rush!

**Comment by pp2amd6** [comment]
Let's deal with tencodes.

Let's take fictional tencodes and divide them into two types: status (officer) codes and situation codes.
![kiss_19kb 1636039334 1](https://user-images.githubusercontent.com/4976837/140400791-c6e7d011-612f-4d6e-947c-da6a5ff14189.png)

Status codes can change the status of an officer.
Situation codes can create a challenge.

===================================================

Tencode table changes

Add a radio button to the tencodes table, which allows you to select the type of code: status code (officer) and situation code.
![kiss_35kb 1636051221 1](https://user-images.githubusercontent.com/4976837/140400965-25603fd5-ef76-4baf-9cbe-66495759fd2a.png)


The officer's panel will show ONLY status codes.

===================================================

**Dispatch - 911 Call card**

If you press the right mouse button on a unit in the call card, a menu will be called
![kiss_85kb 1636049586 1](https://user-images.githubusercontent.com/4976837/140401071-3b8cf9f7-31f5-45ab-bcc0-1e8722eeff51.png)

If a status code is selected in the menu, the status will change for the officer
If a situation code is selected in the menu, an entry will be added to the event log

Recording format: date time: callsign - event

Example: 2021.11.04 20:28:00: 1L-99 Ethan West / 10-13 - Shots Fired!

===================================================

**Dispatch - Unit list**

If you press the right mouse button on an entry in the list of units, a menu will be called
![kiss_85kb 1636049586 1](https://user-images.githubusercontent.com/4976837/140401071-3b8cf9f7-31f5-45ab-bcc0-1e8722eeff51.png)

If a status code is selected in the menu, the status will change for the officer
If the situation code is selected in the menu and the unit is attached to the call, an entry will be added to the event log
If the situation code is selected in the menu and the unit is **NOT** attached to the call, then the call will be automatically created (if the checkbox is set) and an entry will be added to the event log
