### ISSUE TITLE
Custom form submissions

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#462]
### Describe the feature

_This is a rather big feature request so I'm expecting it to either be out of scope of what the project is or be placed onto the backlog._

Something that would allow us to extend the usage of the CAD beyond its current usage would be the creation, submission and management of custom forms. In policing there is a lot of paperwork involved and at the moment communities are likely either using Google Forms or some other external resource to do this.

It would be good to have this integrated into the CAD, leveraging what has already been developed. For example, for incidents that are created with the 'firearms involved' tick, upon closure it could provide a firearms deployment form for the LEO to complete. This would then be reviewed by an LEO Supervisor before being archived.

You could also leverage the same system, if it was permitted, to create other forms such as sign up forms for divisions and keep a track record of them within the CAD.

This ties in to another suggestion I was going to make about having the incidents require sign off from an LEO supervisor. (You can also 'prettify' this by putting a signature font with the LEO supervisors name underneath upon approval.

### Additional Context

The core functions I'd believe you'd need to build out are:

1.  A form builder
2.  Form triggers for things like firearms discharge
3.  A new section on the CAD for reviewing and submitting forms
4. The ability to set reviewers for the forms
5. The ability to archive forms once reviewed

**Comment by jxckUK** [comment]
Reference Items:

https://info.sonorancms.com/tutorials/getting-started/creating-custom-forms

https://albo1125.com/fms - See HR/Forms

**Comment by Dev-CasperTheGhost** [comment]
I love this idea, but I don't think I can implement this on my own. This FR seems to be quite a bit to much for SnailyCAD at it's current state.
