### ISSUE TITLE
Dispatch table sizing

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#465]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

Table formatting on dispatch portal could be optimised to scale slightly better depending on length of the name. 

It might also be worth truncating divisions if they have more than two for example as this would free a lot of space?

### Expected Behavior

N/A

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/155388824-0168ec50-5514-45f2-94f0-1d6a54ed3a45.png)

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed now!
