### ISSUE TITLE
Ended incidents and 911 calls don't show events

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#467]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

Ended incidents don't seem to show all the events added by control. There is also no mechanism to see events from a 911 call once the call has been ended.

### Expected Behavior

Ended incidents should display read only events when an incident is over and this behaviour should also occur on 911 calls.

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/155513628-12cbfc71-ba1a-4fe6-92c5-1e6ee7b73778.png)

**Comment by Dev-CasperTheGhost** [comment]
Is this talking about 911 call events or incident events? Since incident events should show up 🤔. Will need to debug when home

**Comment by jxckUK** [comment]
> Is this talking about 911 call events or incident events? Since incident events should show up 🤔. Will need to debug when home

So incident events show 'no current events' when it should show historic read only ones. 911 call events currently can't be viewed after the call.

**Comment by Dev-CasperTheGhost** [comment]
All fixed now 🎉!
