### ISSUE TITLE
Incident/call improvements

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#468]
### Describe the feature

When creating an incident from Dispatch there are a couple of tweaks that would go a long way. I ran as Dispatch for a couple of hours yesterday and noticed the following:

- [x] Incident involved officers should show a list of active officers only, not the entire list.
- [ ] There should be the ability to add EMS/FD units to active incidents same as 911 calls.
- [ ] The ability to add merged units to incidents
- [ ] When adding a unit it would be amazing if it logged that as an event, for example "A2 has been assigned to this incident", "A2 has been unassigned from this incident".
- [x] Having a large number of units assigned to an incident (I had about ten on one incident) seems to cause some issues with closing it down/ending it? I removed some units and it ended fine.
- [x] Allow merging of units within the Dispatch portal by Dispatch, at the moment only LEO can do it for themselves.
- [x] Allow the merging of units from different divisions getting different paired callsign prefixes. Eg. Firearms division are TROJAN1,2,3, Roads are just {callsign1}{callsign2} this would require a {random} value or something that allows it to stepped.

Other than that, the new incidents make Dispatch 100x simpler! Thank you 😀

**Comment by Dev-CasperTheGhost** [comment]
> Incident involved officers should show a list of active officers only, not the entire list.

This would only be the case when the incident is active?

**Comment by jxckUK** [comment]
> > Incident involved officers should show a list of active officers only, not the entire list.
> 
> 
> 
> This would only be the case when the incident is active?

Yes this would only apply to incidents created through the dispatch portal for example. Where dispatch are creating an incident they would only ever assign active units.

**Comment by jxckUK** [comment]
Adding to this on the main list (apologies! :D) 

- Allow merging of units within the Dispatch portal by Dispatch, at the moment only LEO can do it for themselves.
- Allow the merging of units from different divisions getting different paired callsign prefixes. Eg. Firearms division are TROJAN1,2,3, Roads are just {callsign1}{callsign2} this would require a {random} value or something that allows it to stepped.
- Allow the merging of EMS/FD units, its a great feature and I'd love to see it expanded.

**Comment by Dev-CasperTheGhost** [comment]
> this would require a {random} value or something that allows it to stepped.

What exactly do you mean by this? How would this random value work?

**Comment by jxckUK** [comment]
> > this would require a {random} value or something that allows it to stepped.
> 
> What exactly do you mean by this? How would this random value work?

So that the first unit paired in that department would have the number 1, second would have 2 etc. 

TROJAN-1
TROJAN-2
TROJAN-3

**Comment by Dev-CasperTheGhost** [comment]
> > > this would require a {random} value or something that allows it to stepped.
> > 
> > 
> > What exactly do you mean by this? How would this random value work?
> 
> So that the first unit paired in that department would have the number 1, second would have 2 etc.
> 
> TROJAN-1 TROJAN-2 TROJAN-3

And how exactly would the end callsign look like? I'm not understanding this fully 😅

**Comment by jxckUK** [comment]
> > > > this would require a {random} value or something that allows it to stepped.
> > > 
> > > 
> > > What exactly do you mean by this? How would this random value work?
> > 
> > 
> > So that the first unit paired in that department would have the number 1, second would have 2 etc.
> > TROJAN-1 TROJAN-2 TROJAN-3
> 
> And how exactly would the end callsign look like? I'm not understanding this fully 😅

Hahah thats okay it is a niche very UK specific use case but essentially each paired unit is just suffixed with a number, a single unrelated number incrementing with each active paired unit.

If I pair two firearms officers, they will be TROJAN-1. The next firearms unit I pair will be TROJAN-2, continuing as so.

If TROJAN-1 becomes unpaired, that number is available for use again.

**Comment by Dev-CasperTheGhost** [comment]
Seemed easier than I thought, implemented a function that finds the first smallest missing number from the already created units :). I've also added support for `callsign2` for the paired unit template!

![image](https://user-images.githubusercontent.com/53900565/156872409-8908895d-f406-48da-9751-5cb4eef5d0e8.png)
![image](https://user-images.githubusercontent.com/53900565/156872417-43891b42-2683-4bb4-9709-bd3d52ff3a47.png)

**Comment by Dev-CasperTheGhost** [comment]
>  When adding a unit it would be amazing if it logged that as an event, for example "A2 has been assigned to this incident", "A2 has been unassigned from this incident".

When multiple units are added at the same time, would the message say: `L-39, L-40, L-41 have been assigned to this incident`? Or would it simply send an events for each unit?

> The ability to add merged units to incidents

This wouldn’t be possible because merged units get deleted when they go off-duty.

**Comment by Dev-CasperTheGhost** [comment]
>  When adding a unit it would be amazing if it logged that as an event, for example "A2 has been assigned to this incident", "A2 has been unassigned from this incident".

Unfortunately, with the current code setup, this is very difficult to implement. Will try to get back to this in the future.
