### ISSUE TITLE
[FEATURE REQUEST] The mechanism for combining units

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#47]
### Describe the feature

The function refers to #45 
The function refers to #46 

The function allows officers to independently unite in a paired unit.

When combined, two units receive a common callsign according to the formula specified in the settings

What should an officer do?
- Find a partner in the list of units
![kiss_21kb 1635116409 1](https://user-images.githubusercontent.com/4976837/138627154-1cda596c-7004-4f18-9a0f-ef3a0bdd8cb5.png)

- Click on the corresponding button (or the functionality of the right mouse button)
![kiss_20kb 1635116718 1](https://user-images.githubusercontent.com/4976837/138627184-044e2520-26bc-4dbe-9d15-5acbfc92b3ad.png)

- units will be combined into a paired unit. 
![kiss_18kb 1635120272 1](https://user-images.githubusercontent.com/4976837/138627193-c380d245-c08f-478f-906b-3e2508fbd376.png)

In the general callsign for $callsign2$, the value of the officer who merged the records is taken

For pair units, the department and division are not displayed because they can be differs.

Status becomes shared
The control button changes the status for the general unit, i.e. for two officers at once and separates the units back
![kiss_8kb 1635122262 1](https://user-images.githubusercontent.com/4976837/138627210-fae71e50-c193-4bd4-8471-2d172f56286e.png)

Additionally, a paired unit can be shown visually in the table.

**Comment by Dev-CasperTheGhost** [comment]
This could be released by Friday :)
