### ISSUE TITLE
Ability to disable the ability of civilians to set the status of their vehicles themselves

### ISSUE THREAD

**Issue by Justin2211** [SnailyCAD/snaily-cadv4#473]
### Describe the feature

I would like to have the possibility to disable the function that civilians can change the status of their vehicles, such as VALID or INVALID, in the admin settings.

That e.g. the vehicle which one adds first goes on a waiting list and then must be confirmed by the DMV.

**Comment by Dev-CasperTheGhost** [comment]
Who would be able to manage DMV?

**Comment by Justin2211** [comment]
There could be e.g. on a RP server a DMV place where people can register their vehicles.

You could also integrate it so that you can switch a DMV function on or off.

**Comment by Justin2211** [comment]
Yes, but if it is not yet approved, the police officers can see that and take action
