### ISSUE TITLE
Incident Creator

### ISSUE THREAD

**Issue by Smithandjosh** [SnailyCAD/snaily-cadv4#476]
### Describe the feature

Units and Dispatch being able to create incidents not just 911 calls. Then you can mark these with situation codes to code what job it is. IE. setting indent to a 11-95 which would mark the incident as that which would be a traffic stop.

**Comment by Dev-CasperTheGhost** [comment]
Leo is already able to create incidents. Not sure if you’re talking about that? Or do you mean to have the ability to connect situation codes to incidents?

**Comment by Smithandjosh** [comment]
I see that now, I think it would be better if you could create them from the dashboard and be able to connect situation codes to incidents. Another thing that would be cool is having 'involved citizens' with an option for an id and vehicle drop down.

**Comment by Dev-CasperTheGhost** [comment]
> I think it would be better if you could create them from the dashboard

This would bring in more redundancy 😅. I think having it in the incidents page is fine?. 

> be able to connect situation codes to incidents

Sure!
