### ISSUE TITLE
Default License

### ISSUE THREAD

**Issue by nick-perry14** [SnailyCAD/snaily-cadv4#480]
### Describe the feature

On the creation of citizens, assign certain licenses to a default field (such as "active, no license," etc.)

**Comment by Dev-CasperTheGhost** [comment]
Something like this maybe?

<img width="571" alt="Screenshot 2022-03-01 at 07 27 15" src="https://user-images.githubusercontent.com/53900565/156116604-398e4a27-54f2-4a1e-a419-a9c16a66eece.png">
