### ISSUE TITLE
Citizen Deletion Whitelist

### ISSUE THREAD

**Issue by nick-perry14** [SnailyCAD/snaily-cadv4#481]
### Describe the feature

Create a setting so that deletions must be approved by an admin.  This will prevent users from deleting their character and remaking it to change their LEO arrest history

**Comment by Dev-CasperTheGhost** [comment]
Maybe it’s better if only admins can delete the citizen if the feature is enabled?

**Comment by Dev-CasperTheGhost** [comment]
@nick-perry14 following up to my previous comment :)

**Comment by nick-perry14** [comment]
That also works!  Whichever is easier

**Comment by Dev-CasperTheGhost** [comment]
This is now a feature which should be disabled to apply this feature request: 
![image](https://user-images.githubusercontent.com/53900565/156228048-4df283c3-7771-487f-bfa6-67a047491792.png)
