### ISSUE TITLE
Vehicle enhanced details

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#491]
### Describe the feature

The following fields would be useful for vehicles:

- MOT / vehicle inspection Status
- Tax Status
- [x] Insurance Status (I did see a value for this in the database?)
- [x] Flags (This would be useful as an array and a vehicle can have multiple tags added by LEO) could include, drugs marker, weapons marker etc.

These should all be accessible to the vehicle importing system so we can import randomised values for vehicles.

**Comment by jxckUK** [comment]
> > * MOT / vehicle inspection Status
> > * Tax Status
> > * Flags (This would be useful as an array and a vehicle can have multiple tags added by LEO) could include, drugs marker, weapons marker etc.
> 
> Would these be values managed in the admin panel?

They should be manageable  by LEO when viewing a vehicle / citizens vehicles.

**Comment by Dev-CasperTheGhost** [comment]
Yes, but the individual values would be added via the admin values, or would these just be simple textinput fields?

**Comment by jxckUK** [comment]
> Yes, but the individual values would be added via the admin values, or would these just be simple textinput fields?

Oh I see - yes admin values system works well and it would be good to see that used here 😄

**Comment by Dev-CasperTheGhost** [comment]
Vehicle flags and insurance status are now supported 🚀

**Comment by Dev-CasperTheGhost** [comment]
> MOT / vehicle inspection Status
> Tax Status

I'm not sure how these work, are you able to provide an example for this :)? @jxckUK

**Comment by jxckUK** [comment]
> > MOT / vehicle inspection Status
> 
> > Tax Status
> 
> 
> 
> I'm not sure how these work, are you able to provide an example for this :)? @jxckUK 

MOT is British and VIS is American but they're both verification that a vehicle is safe to be on the road, a simple Passed/Failed should be sufficient!

Tax status is again just road tax and the vehicle is either Taxed or Untaxed.

**Comment by Dev-CasperTheGhost** [comment]
Something like this then?

![image](https://user-images.githubusercontent.com/53900565/156933295-e02ead01-c3c9-4d72-bfd4-33ef5816e6d5.png)

**Comment by jxckUK** [comment]
Looks great @Dev-CasperTheGhost sorry for the delayed response! Will all these fields be available with the import vehicles?

**Comment by Dev-CasperTheGhost** [comment]
> Will all these fields be available with the import vehicles?

Sure will add that soon!

**Comment by Dev-CasperTheGhost** [comment]
> Will all these fields be available with the import vehicles?

Should be supported now!
