### ISSUE TITLE
Contextual links

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#493]
### Describe the feature

When viewing vehicle or citizen records, links to the citizen and vehicle should be added so LEO can quickly and efficiently switch between records.

For example when searching a vehicle and seeing the name, you should be able to select that name and it open up the citizen modal.

### Additional Context

Owner on this screen: ![image](https://user-images.githubusercontent.com/48030374/156384257-7ea3c43e-895e-4d35-a779-17c34828d5e2.png)

Registration on this screen: ![image](https://user-images.githubusercontent.com/48030374/156384324-4d33971b-3944-46af-bb1b-777681ad7f58.png)

**Comment by Dev-CasperTheGhost** [comment]
This works well where it opens the modal to display information, however due to the way modals are handled, it won't be possible to use any of the modal's buttons/inputs :/

**Comment by Dev-CasperTheGhost** [comment]
Got it working 🚀! Will release tomorrow :D

https://user-images.githubusercontent.com/53900565/156635980-1ffb9718-1218-4771-8cea-1dd7017c0b58.mov
