### ISSUE TITLE
[BUG] Missing Category On Manage Licenses/Citizen Pageq

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#502]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Latest

### Describe the Bug

You can see that the category for Water is not showing up anywhere on Citizen info.
(Don't worry about my Locale I've changed it quite a bit.)

![image](https://user-images.githubusercontent.com/25211271/156896785-b6d18749-ed2b-407c-a4a5-a7a995c866e9.png)
From Admin Panel

On Citizen Edit Page
![image](https://user-images.githubusercontent.com/25211271/156896915-3e2f02c9-13ac-4fe2-89d7-6a1e6a70fa7f.png)

### Expected Behavior

To see a section for Water related Licenses (Boating License etc)

**Comment by Dev-CasperTheGhost** [comment]
Would there be a “water license” too then?

**Comment by Dev-CasperTheGhost** [comment]
@ViolentMinds following up to my previous comment :) https://github.com/SnailyCAD/snaily-cadv4/issues/502#issuecomment-1059836398
