### ISSUE TITLE
Snaily-Cad-v4 Network error when trying to sign up or sign in

### ISSUE THREAD

**Issue by Karrot0** [SnailyCAD/snaily-cadv4#503]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.1.2

### What operating system are you using?

Windows

### Describe the Bug

I load into the page, when I put in my information and click the register or sign in button it shows me a pop-up saying Network Error, and it says to contact an administrator here's the picture of the problem: 
 [https://cdn.discordapp.com/attachments/903877466572087347/949720123973963836/Screenshot_28.png](url)

### Expected Behavior

I expected when I set the PostgreSQL correctly the second time it would work but the same happened. I also tried Port Forwarding and nothing.

### To Reproduce

Run the installation in Node.js Command Prompt version: 16.13.1 using NPM version: 8.1.2 Once the installation is complete go to your website or IP. Mine was http://localhost:3000/. Click the sign up button, Type in your information, press the register button. Then the popup happens and it doesn't let you continue to the next part

**Comment by Dev-CasperTheGhost** [comment]
Please use Discord for support
