### ISSUE TITLE
[Improvements] Citizen Card - Changing the block of medical records

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#51]
### Describe the feature

1. Add a field (optional) to select a blood group (the table is already in the settings)
2. Add the ability to indicate diseases (multi), for example: asthma, mental disorder, etc.
3. Show calls to hospitals (will be added by doctors, for the user only read) (TBD)

**Comment by Dev-CasperTheGhost** [comment]
> Add the ability to indicate diseases (multi), for example: asthma, mental disorder, etc.

Would these also be database tables? Or just a regular input field?

@pp2amd6

**Comment by pp2amd6** [comment]
regular input field

**Comment by Dev-CasperTheGhost** [comment]
Not sure on that last item for now but will implement at a later stage in development. Will be closing this for now tho
