### ISSUE TITLE
Support for FiveM Framework v2

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#516]
### Describe the feature

Hello, my friend would like to know if you could add support for [FiveM Framework v2](https://store.nat2k15.xyz/store/framework-v2). It is a paid resource, but possibly you could get it to work? If not, we aren't completely torn up about it. If you'd like, I can have my friend (who paid for it) contact the mod developer if you need resources. Thank you!

(Also, one thing my friend pointed out to me, Framework v2 uses MySQL, not PostgreSQL. Not sure if this would affect your ability to add it or not.)

**Comment by Dev-CasperTheGhost** [comment]
You should be able to use the [Public API](https://cad-docs.caspertheghost.me/docs/developer/public-api) for this? *Also, I don't think this resource will play well with the CAD, since by the looks of it you'll have 2 CAD's, IMO.*
