### ISSUE TITLE
More & Custom Sounds

### ISSUE THREAD

**Issue by fk-1997** [SnailyCAD/snaily-cadv4#52]
### Describe the feature

It would be great to have the option to implement more sounds.
Especially for 
Updates on the active calls,
new events on active calls,
new BOLOs,
dangerous Citizen,
active warrents,
CCW holders,
etc.

**Comment by pp2amd6** [comment]
I can suggest small changes

1. Make settings for appearance, sounds and notifications in a separate tab of your account settings.
![kiss_10kb 1635845462 1](https://user-images.githubusercontent.com/4976837/139821333-559d0bd9-dbdb-4fac-958a-23ad1a1ff52d.png)

2. On the page, place settings for theme, data view options, sounds.
![kiss_16kb 1635845799 1](https://user-images.githubusercontent.com/4976837/139822165-b21f2a20-92be-4f25-968f-d75514e1d76e.png)

**Comment by Dev-CasperTheGhost** [comment]
Maybe options in the CAD-settings to upload custom sounds for certain types of actions? Maybe start with a few supported actions, more can be added in the future if needed?

**Comment by Dev-CasperTheGhost** [comment]
I'm closing this in favor of #394
