### ISSUE TITLE
Firearms License - Combine CCW with it.

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#527]
### Describe the feature

1) Can we make Firearms License work the same way as normal licenses? So that I can put CCW inside Firearms License? Because most of the time people have i) Open Carry Firearms License ii) Concealed Carry Weapons License iii) Basic Weapons License.

But right now the CCW is totally separate from Firearms.
They could be combined easier like how I have it for other licenses.

![image](https://user-images.githubusercontent.com/25211271/158078636-3c91ee66-1d75-44ab-b6e8-9130d259c6f5.png)
![image](https://user-images.githubusercontent.com/25211271/158078661-0d9bf304-b7b1-4241-9511-e39a6af65acd.png)

2) Am I able to **Edit Licenses** because I am Owner/Admin? **Or** can all LEO Edit Civilians Licenses? If so this could be a serious problem if LEO can remove peoples licenses. LEO being able to change peoples status is not a bad thing though.
![image](https://user-images.githubusercontent.com/25211271/158078760-99b53a9a-fea0-4bbf-8464-80ab3b4e565f.png)

**Comment by Dev-CasperTheGhost** [comment]
> Can we make Firearms License work the same way as normal licenses? So that I can put CCW inside Firearms License? Because most of the time people have i) Open Carry Firearms License ii) Concealed Carry Weapons License iii) Basic Weapons License.

Sure!

> Am I able to Edit Licenses because I am Owner/Admin? Or can all LEO Edit Civilians Licenses? If so this could be a serious problem if LEO can remove peoples licenses. LEO being able to change peoples status is not a bad thing though.

All LEO are able to edit the licenses (this was requested some time ago). I'll remove the option to remove them, but keep the option to change it :)
