### ISSUE TITLE
multiple roles for all departments 

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#530]
### Describe the feature

make it so you can assign multiple discord roles to all departments instead of only police.

**Comment by Dev-CasperTheGhost** [comment]
This was discussed in #433, I’m not sure if this works well. Since the departments would be given to all officers that user has. 

Not sure if there’s a better way? @subtosharki

**Comment by subtosharki** [comment]
all its just to have the feature coo had for discord roles but for every option, so you can pick multiple roles for ADMIN or EMS etc

**Comment by Dev-CasperTheGhost** [comment]
> all its just to have the feature coo had for discord roles but for every option

What 😅?

**Comment by subtosharki** [comment]
sorry that was early this morning lmao, for cops under the discord role management you can choose more than one discord role for it to sync with

**Comment by Dev-CasperTheGhost** [comment]
Right I understand, but did you read what I said here: 

> This was discussed in https://github.com/SnailyCAD/snaily-cadv4/issues/433, I’m not sure if this works well. Since the departments would be given to all officers that user has.

**Comment by subtosharki** [comment]
im confused what do u mean by it will be given to all officers the user has, im just asking for a feature that lets us choose multiple discord roles for all the options and not limited to only police

**Comment by jxckUK** [comment]
> im confused what do u mean by it will be given to all officers the user has, im just asking for a feature that lets us choose multiple discord roles for all the options and not limited to only police

_My understanding and what I think Casper is trying to say is:_ 

The Discord role sync is bi-directional. Which means any user that has the Administrator role for example in the CAD would get the Discord role that has been assigned to it. The best way to set up this is to have roles like "CAD Administrator" in Discord and assign the users you'd like to have the access to that group.

**Comment by jxckUK** [comment]
In addition if you have a user that has MULTIPLE units then all their units will get the role assigned.

**Comment by Dev-CasperTheGhost** [comment]
> , im just asking for a feature that lets us choose multiple discord roles for all the options and not limited to only police

So you’re not talking about LEO departments? I think this was a bit of miscommunication lol

**Comment by subtosharki** [comment]
no ahaha, im talking about a feature where you can assign multiple discord roles to more departments then just leo

**Comment by Dev-CasperTheGhost** [comment]
Wait, I'm more confused now. LEO/EMS/FD units have departments. Users have permissions.

You're talking about Discord role permissions here? @subtosharki

**Comment by Dev-CasperTheGhost** [comment]
> both, when you go to the discord role management in cad it lets you select multiple discord roles for the leo department. i was wondering if it was possible to do that with the other permissions/departments

I think I'll add it for EMS/FD but not for admin, etc. I don't think it's necessary to add support for multiple roles in the CAD since you can add a simple Discord role to Discord members

**Comment by subtosharki** [comment]
sounds great
