### ISSUE TITLE
Cpanel friendly Installation

### ISSUE THREAD

**Issue by athens-networking** [SnailyCAD/snaily-cadv4#534]
### Describe the feature

I'm not too sure about how they went about it, however on https://opencad.io/ (opencad) they have it so that once you install the files on your server you just input all the information and boom your done, it installs it for you. Would this be possible?

**Comment by nick-perry14** [comment]
Opencad is written in PHP.  This is written in TS, which compiles to JS.  Most of the code is client sided, with api calls to the server.  NodeJS may work on Cpanel if your host supports it, but it won't work out of the box like PHP does.

**Comment by Dev-CasperTheGhost** [comment]
This wouldn’t really be possible. SnailyCAD requires you to have node.js. This is in some cases not possible via cPanel, or any other website hosting service. I would recommend a Linux/Windows VPS instead.

> Most of the code is client sided

most is actually server-side, for fetching at least. Thanks to Next.js
