### ISSUE TITLE
Option to randomise flags on vehicle/citizen import

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#544]
### Describe the feature

When importing vehicles or citizens, for my use case it would be really handy to have an option that allows me to randomise the flags for citizens and vehicles. 

If possible adding weight of the flags for the randomisation would be super super helpful but otherwise just having more weight on no flags vs. any combination of flags would still be an excellent addition.

**Comment by Dev-CasperTheGhost** [comment]
This is not necessary. You can fetch the flags from the API, then write some randomizer function to randomize the fetched flags, then add those to the citizen. 

Implementing this would add "bloat" into the somewhat already complex API 😅.

**Sudo code example**

```sudo

myFlags = [FlagId1, FlagId2, FlagId3]

function fetchFlags() {
	response =  fetch("http://api.example.com/v1/admin/values/vehicle_flag")
	myFlags = response.json()
}
// fetch latest flags
fetchFlags()


function randomize(flags) {
 return flags randomized
}

function createCitizen() {
 return {  ...., flags: randomize(myFlags) }
}
