### ISSUE TITLE
Toggle All Permissions Deselects other categories

### ISSUE THREAD

**Issue by nick-perry14** [SnailyCAD/snaily-cadv4#549]
### What version of Node.js are you using?

Latest

### What operating system are you using?

Ubuntu Server

### Describe the Bug

Selecting a "toggle all" in the permissions tab automatically untoggles ALL items in other categories

### Expected Behavior

The toggle all button should only affect that category.

**Comment by Dev-CasperTheGhost** [comment]
Will take a look after school!

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed now!
