### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by nick-perry14** [SnailyCAD/snaily-cadv4#553]
### Describe the feature

Allow admins to create custom fields (Fingerprint id, Phone number, work ID, etc.) that can be searched upon later.  Good so that police/fire can search based on additional characteristics.

**Comment by Dev-CasperTheGhost** [comment]
Are you able to elaborate? Maybe show screenshot demos?

**Comment by nick-perry14** [comment]
So basically, this allows CAD owners to create custom fields for citizens that can be searched up later.  For example, the CAD officer page may look like this:

![dispatch](https://user-images.githubusercontent.com/6935777/161111465-faaece7b-dfc5-4b5a-b916-cee9a6e526b1.png)

Upon clicking the field search, another form comes up like this

![mockup1](https://user-images.githubusercontent.com/6935777/161111532-5c7434a5-4815-48d0-b666-110d4317ec7c.png)
![mockup2](https://user-images.githubusercontent.com/6935777/161111538-7f371e13-5188-47e5-b933-c61d549cc936.png)
The search would bring up a list of citizens with matching fields.
Open opening the citizen page, additional fields would be displayed under all the standard ones
![citizenpage](https://user-images.githubusercontent.com/6935777/161111652-b514d97f-ee49-4c04-af4b-cda4e6dfbd72.png)

**Comment by Dev-CasperTheGhost** [comment]
@nick-perry14 to what items can these fields be linked to? I'd guess citizens, maybe weapons and vehicles too?

**Comment by nick-perry14** [comment]
Yeah.  So what I was thinking is generate the select field by using <optgroup> so it looks something like this.  Then you could autopopulate each category.  If there are no items for that category, don't add the <optgroup>


![optgroup](https://user-images.githubusercontent.com/6935777/161299387-893aabff-f7ee-4f6e-9e1f-36b90ad4488e.png)

**Comment by Dev-CasperTheGhost** [comment]
No, I meant to what type of database model would this append too? Citizens, vehicles, weapons, more?

**Comment by nick-perry14** [comment]
Well, my primary thought is citizens. but you do raise a good point in that maybe weapons and vehicles should have custom fields too.  So maybe make it it's own table with a field that describes the category.  Or append it to all three.

**Comment by Dev-CasperTheGhost** [comment]
Will try the former and see how that goes :)

**Comment by Dev-CasperTheGhost** [comment]
*probably, last question*: how would an admin define these values? I had something like this in mind: 
![image](https://user-images.githubusercontent.com/53900565/161371439-18943f49-1d11-4a66-b4f4-f3b0384f4268.png)

**Comment by nick-perry14** [comment]
Looks great!

**Comment by Dev-CasperTheGhost** [comment]
How would the values of a custom field be changed? Via the name/weapon/vehicle search respectively? Would citizens be allowed to manage these values?

**Comment by nick-perry14** [comment]
Good question.  Same place the citizens and LEOs can edit the other fields.  If possible maybe add another flag that either permits or restricts editing by the civilian

**Comment by Dev-CasperTheGhost** [comment]
Sure!

**Comment by Dev-CasperTheGhost** [comment]
Let me know if you've got improvements/feedback! @nick-perry14 

https://user-images.githubusercontent.com/53900565/161492999-4d4308cb-f19b-4658-ae8f-88b92c94641f.mov

**Comment by nick-perry14** [comment]
That looks fantastic!

**Comment by Dev-CasperTheGhost** [comment]
Now available 🚀!
