### ISSUE TITLE
Publish/expose assigned incident and call IDs to unit API data

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#555]
### Describe the feature

As we have done with other levels of data such as the user data assigned to a unit, could we please publish a simple array of assigned calls and incidents to the user data so that we can leverage the API to identify assigned calls without iterating the entire call list.

**Comment by Dev-CasperTheGhost** [comment]
After updating, you should be able to find: `assignedUnit` for LEO and `AssignedUnit` for EMS/FD units. This will have information about the call they're assigned to etc.

**Comment by Dev-CasperTheGhost** [comment]
Incidents should be exposed now too, you can access them via: `LeoIncident`

**Comment by jxckUK** [comment]
Thanks Casper, this helps massively - just wondering what occurs in the event a unit is assigned to multiple incidents and/or calls. Incidents seems to only pull one incident through, is this by design?

**Comment by Dev-CasperTheGhost** [comment]
ah, I may have selected the `activeIncident` instead of the assigned incidents. Will fix soon! 

*This should only be the case for incidents 🤔?*

**Comment by jxckUK** [comment]
> ah, I may have selected the `activeIncident` instead of the assigned incidents. Will fix soon!
> 
> _This should only be the case for incidents 🤔?_

Awesome! - Yes 911 calls are represented in an array which expands out depending on how many calls the unit is assigned to :)

**Comment by Dev-CasperTheGhost** [comment]
incidents should be now shown if the unit is assigned to an incident. It will use the key: `LeoIncidentInvolvedOfficers` on the unit

**Comment by jxckUK** [comment]
> incidents should be now shown if the unit is assigned to an incident. It will use the key: `LeoIncidentInvolvedOfficers` on the unit

Just gave this a spin, this shows historical incidents as well right? So I have a massive list for the user when they're actually only *assigned* to a single active incident for example?

**Comment by Dev-CasperTheGhost** [comment]
> EDIT: I notice, and surprised I haven't seen this before, that units are automatically unattached from calls when they go off duty. I guess this being applied to incidents would solve this issue and also some others like having inactive officers listed on active incidents!

when an officer is assigned to an activeIncident goes off-duty, it will remove that officer from the incident?

> Just gave this a spin, this shows historical incidents as well right? So I have a massive list for the user when they're actually only assigned to a single active incident for example? 

Should be a simple fix. Will fix tomorrow since I’m not home this evening.

**Comment by jxckUK** [comment]
> when an officer is assigned to an activeIncident goes off-duty, it will remove that officer from the incident?

That would be an additional improvement that I think would help control for sure - I notice that sometimes I'll have a unit go off duty and they're still assigned to an active incident (that has other on duty members on scene) and it can get a little confusing.

> Should be a simple fix. Will fix tomorrow since I’m not home this evening.

Ah perfect - thanks again Casper.

**Comment by Dev-CasperTheGhost** [comment]
All should be fixed now!
