### ISSUE TITLE
Citizens, vehicles and weapons only for admins 

### ISSUE THREAD

**Issue by PrisonIndustry** [SnailyCAD/snaily-cadv4#565]
### Describe the feature

I would like to have that only admins or people with certain roles can create citizens, vehicles and weapons, because the whole thing should run through an office

**Comment by Dev-CasperTheGhost** [comment]
> because the whole thing should run through an office

What type of office would this be? Or do you specifically only want admins to create citizens, vehicles and weapons?

**Comment by PrisonIndustry** [comment]
It would be best if you could create this directly as admin only. And you could then still give a function that it could then make the judiciary

**Comment by Dev-CasperTheGhost** [comment]
Moving into backlog for now
