### ISSUE TITLE
Automatically check user's Discord roles periodically

### ISSUE THREAD

**Issue by Dalrae1** [SnailyCAD/snaily-cadv4#568]
### Describe the feature

Having to reauthenticate every time a role is changed in Discord is very annoying. I was thinking maybe checking the user's roles every time they login, or, better yet, have a hook so when a user's role is updated in Discord it is immediately taken effect in the CAD.

**Comment by Dev-CasperTheGhost** [comment]
There should be a request to Discord per request every 3 min. See https://github.com/SnailyCAD/snaily-cadv4/issues/436#issuecomment-1046178065. It may be that this isn't working correctly, therefore this feature request?

**Comment by Dalrae1** [comment]
Oh thank you! I must've missed that.
