### ISSUE TITLE
[UI improvement] Citizen card - Show citizen status by filter on photo

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#57]
### Describe the feature

Display citizen status:
- arrested (set when the officer makes an arrest)
- BOLO (set when the officer creates a BOLO record)
- died (set manually by a police officer or a medic - add button to citizen card)

**Setting statuses unavailable for a citizen**

![kiss_240kb 1635269040 3](https://user-images.githubusercontent.com/4976837/138930851-dc43bfb7-752f-472b-860c-ebe8c8aa7566.png)

**Comment by Dev-CasperTheGhost** [comment]
@pp2amd6 is this still wanted? I'm not sure if this realistic? 

*Sorry for taking so long to get back to this issue 😅!*
