### ISSUE TITLE
Restrict assignments to calls and incidents

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#570]
### Describe the feature

It occurred to me while we were discussing https://github.com/SnailyCAD/snaily-cadv4/issues/555 that in some instances or for some departments you wouldn't want a unit to be attached to another incident and/or 911 call.

How difficult would it be to add an option for each department to have a setting that is user toggled that allows it to support assignment of multiple incidents/calls to one unit?

Or at least a global CAD option that specifies (similar to the current configurations for how many units they can create) how many assignments they can have for 911 and for incidents.

Eg. A cap of 1 x incident assignment and 1 x 911 call assignment per unit.

**Comment by Dev-CasperTheGhost** [comment]
Unfortunately this will not show in the UI whether the unit can be assigned. In the API it will skip the unit if it cannot be assigned anymore
