### ISSUE TITLE
Client-side exception

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#575]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

![image](https://user-images.githubusercontent.com/48030374/161521543-aafd0221-4a94-46a6-a8b2-13195abedb86.png)

An error occurs just when sat on the dispatch screen.

### Expected Behavior

N/A - Error

**Comment by Dev-CasperTheGhost** [comment]
Page refresh fixes it?

**Comment by jxckUK** [comment]
> Page refresh fixes it?

Yes but then it occurs again a few moments later.

**Comment by jxckUK** [comment]
![image](https://user-images.githubusercontent.com/48030374/161523032-366d311c-3af0-41a2-9a99-6e543e2ea8cb.png)


It seems to happen when I'm tabbed out so a video probably isn't going to be possible in this instance. I've also tried checking the API and client consoles but they're either full of missing message or unauthorised messages.

**Comment by jxckUK** [comment]
> weird, I'm unable to reproduce this error. Is it still happening?

Seems to be fairly sporadic and not linked to any specific action to be honest - was hoping the web console might provide some insight.

It hasn't happened for a few minutes now.

**Comment by Dev-CasperTheGhost** [comment]
yeah, it doesn't when in production mode really. I'm going to close this issue for now, let me know if you're still experiencing this issue.
