### ISSUE TITLE
Add case/reference numbers to 911 and show them on dispatch

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#576]
### Describe the feature

The incident reference is one of the most useful features especially for a dispatcher and it works perfectly. However its exclusive to incidents, so 911 calls don't have the same functionality.

Could we get both a 'Case Reference' applied to a 911 as well as show it in the dispatch panel if they're assigned to a 911.

**Comment by Dev-CasperTheGhost** [comment]
Are you able to elaborate? I think I know what you mean, but not 100% sure.

**Comment by jxckUK** [comment]
Yes so:

![image](https://user-images.githubusercontent.com/48030374/161575408-44fa778a-e65c-459a-b759-1250e8be8f0b.png)

Add case numbers to 911 calls also, and then where you added the neat column for a units active incident:

![image](https://user-images.githubusercontent.com/48030374/161575513-759537c6-df7b-4208-8496-892da268ab58.png)


Add either an additional one for active 911 call or merge it with the incident one.

**Comment by Dev-CasperTheGhost** [comment]
How would it be handled if a unit is assigned to multiple calls?

**Comment by jxckUK** [comment]
> How would it be handled if a unit is assigned to multiple calls?

That's a good question & currently incident just shows the most recent one. 

This is better than not showing any call but maybe there's a better solution for when a unit is assigned to multiple calls or incidents?

Potentially an 'active' marker against a call and incident and if the user has no 'active' calls or incidents when one is assigned it automatically becomes the active one?

**Comment by Dev-CasperTheGhost** [comment]
I think going for the latest is fine for now. 

> Potentially an 'active' marker against a call and incident and if the user has no 'active' calls or incidents when one is assigned it automatically becomes the active one?

You mean that an officer could have `activeCall` that can be updated by Dispatch?

**Comment by jxckUK** [comment]
> > Potentially an 'active' marker against a call and incident and if the user has no 'active' calls or incidents when one is assigned it automatically becomes the active one?
> 
> You mean that an officer could have `activeCall` that can be updated by Dispatch?

Yes, activeCall/activeIncident would be perfect because I could leverage the API to route players to the active record.

**Comment by pp2amd6** [comment]
> if a unit is assigned to multiple calls?

In terms of unit management, a unit can be attached to one call at a time.
