### ISSUE TITLE
Error when attempting to end incident

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#582]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

![image](https://user-images.githubusercontent.com/48030374/161967278-db1f4825-51c1-41e6-9640-4aeb359e5603.png)

Occurs when I attempt to end the incident, I've tried refreshing and attempting again and get the same result.

### Expected Behavior

The incident should close down and end.

**Comment by Dev-CasperTheGhost** [comment]
Not an API error. Looks like the API isn't online yet?

**Comment by jxckUK** [comment]
It's odd that its reporting a CORS error but only for this specific request?

**Comment by jxckUK** [comment]
> Not an API error. Looks like the API isn't online yet?

If the API wasn't online I wouldn't be able to access the dashboard and clock on etc though?

**Comment by Dev-CasperTheGhost** [comment]
hm, weird. Works fine for me

**Comment by Dev-CasperTheGhost** [comment]
Did the API crash?

**Comment by jxckUK** [comment]
Not that I can see - I can perform every single other action. I don't usually have issues with closing incidents either? It's really odd that its just that specific action.

![image](https://user-images.githubusercontent.com/48030374/161968208-5cb5c228-bdea-42d0-9996-6f70da6722c9.png)

Here is what is output in the console when I attempt to close.

**Comment by Dev-CasperTheGhost** [comment]
hmmm, weird. Are you able to increase the max body size for your hosting?

**Comment by jxckUK** [comment]
> hmmm, weird. Are you able to increase the max body size for your hosting?

I've set it to no limit:

`client_max_body_size 0;`

No change unfortunately, same error.

**Comment by Dev-CasperTheGhost** [comment]
hm, will debug this

**Comment by Dev-CasperTheGhost** [comment]
Looks like there was a default set. I've bumped this to 500kb, are you able to try that. Simple update should suffice

**Comment by jxckUK** [comment]
> Looks like there was a default set. I've bumped this to 500kb, are you able to try that. Simple update should suffice

That's fixed it! Thank you.

**Comment by Dev-CasperTheGhost** [comment]
alright, cool!
