### ISSUE TITLE
Contextual option leads to client side exception

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#584]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

When viewing a civilian and selecting the button to view a related vehicle it triggers a client side exception every time.

### Expected Behavior

It should load the related vehicle details via the contextual button.

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/162039401-3f9bb7ad-32df-4119-83f1-cb63b4a85590.png)

**Comment by Dev-CasperTheGhost** [comment]
> When viewing a civilian and selecting the button to view a related vehicle it triggers a client side exception every time.

On what page does this occur?

**Comment by Dev-CasperTheGhost** [comment]
That'd be helpful!

**Comment by Dev-CasperTheGhost** [comment]
Fixed it already, actually!

**Comment by jxckUK** [comment]
> Fixed it already, actually!

:fire: way too fast, thanks!
