### ISSUE TITLE
Birthdates are displayed incorrectly.

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#589]
### What version of Node.js are you using?

v16.14.0

### What version of npm are you using?

8.5.3

### What operating system are you using?

Ubuntu Server 20.04

### Describe the Bug

Birthdates of civilians are displayed incorrectly in browsers:
- Chrome
- Edge
- Firefox

On operating systems: 
- Windows 10
- Windows 11
- Android 12

The correct birthdate is stored and displayed correctly on civilian edit screen, just no where else.

Images:
![Chrome](https://user-images.githubusercontent.com/34800953/162557688-c6929fee-fc3f-44b5-9ceb-0855e66fe796.png)
![Android](https://user-images.githubusercontent.com/34800953/162557944-85c64330-f8fe-42ea-90d9-e6b5690b0598.jpg)
![Char-edit](https://user-images.githubusercontent.com/34800953/162557714-ce4d592d-8f9b-47cd-913d-402217bcea78.png)

### Expected Behavior

The birthdate should be September 15, 2000

### To Reproduce

Create a civilian, set a birthdate, and view the birthdate.

**Comment by Dev-CasperTheGhost** [comment]
Does it correctly display in the citizen search? I'm also still unable to reproduce this error 🤔

**Comment by Thomaswill1** [comment]
It also does not display correctly on citizen search.
![image](https://user-images.githubusercontent.com/34800953/162558944-412c13bd-2665-46da-a334-77ba2a0c8766.png)

**Comment by Dev-CasperTheGhost** [comment]
What version of PostgreSQL are you using?

**Comment by Thomaswill1** [comment]
14.2

**Comment by Dev-CasperTheGhost** [comment]
Can you update

**Comment by Dev-CasperTheGhost** [comment]
Are you able to update and see if it was fixed?

**Comment by Thomaswill1** [comment]
One of two things happened:
I updated it, and it didn't work
I didn't update it because I don't know Postgres that much. ¯\_(ツ)_/¯

**Comment by Thomaswill1** [comment]
Okay, I flushed cache and now it works. Thanks!
