### ISSUE TITLE
[feat]: Panic button and signal 100

### ISSUE THREAD

**Issue by casperiv0** [SnailyCAD/snaily-cadv4#59]
### Describe the feature

- [x] Ability for deputies and officers to press a panic button
- [x] 🏃‍♂️ Ability for dispatch to enable/disable signal 100

### Additional Context

`useSignal100` `usePanicButton`
https://github.com/Dev-CasperTheGhost/snaily-cadv3/blob/main/src/pages/leo/dash.tsx#L175

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost 

1. Pressing the panic button does not turn off the mode
2. Turning on the panic button does not change the officer's status
![kiss_66kb 1635598956 1](https://user-images.githubusercontent.com/4976837/139533847-5d18460e-a56d-4b0c-a4ed-e8e23f83ead6.png)
