### ISSUE TITLE
More Sounds

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#590]
### Describe the feature

More sounds in the CAD would be great.

- [x] Added to call
- [x] 'Stop Roleplay' sound (triggered when a Stop Roleplay is issued)
- [ ] Fire and EMS tones
- [ ] A secondary sound tone played after the first Signal 100 tone, which is also repeated after some time. ~30 secs.

These could be disabled by default, as it may be annoying to some users.

**Comment by Dev-CasperTheGhost** [comment]
> Fire and EMS tones

Are you able to elaborate here?

**Comment by Thomaswill1** [comment]
> > Fire and EMS tones
> 
> Are you able to elaborate here?

Some CADs, in real life or in roleplay, have specific Fire and EMS tones to them. I don't know much else, as someone else asked me to make that request, so I'll try and ask what they meant, though that might take some time.

**Comment by buck20073** [comment]
Hows it going on fire tones?

**Comment by Dev-CasperTheGhost** [comment]
Still waiting for the reply of ThomasWill. Maybe you're also able to provide insight of my previous comment: https://github.com/SnailyCAD/snaily-cadv4/issues/590#issuecomment-1093730459

**Comment by buck20073** [comment]
So for the Fire/EMS tones, if there was a 911 call for Fire/EMS, the dispatch can press a button and it will play a tone & it will grab the Fire/EMS attention, then once the tone is finished dispatch will explain the call. I have a fire tone you could use if you want.

**Comment by Thomaswill1** [comment]
Yeah, that's the best we can do for now, as I've been practically ignored by my friend for the past few weeks. I'm sure other people in the Discord also know about Fire/EMS tones too.

**Comment by pp2amd6** [comment]
> the dispatch can press a button and it will play a tone

It won't be right, I think.
A good solution is to play the tone for the units to pass, the dispatcher will assign a call.
At the same time, if paramedics and firefighters are assigned to the call, then play both tones for them.

Tones examples (By 72will):
[DispatchTones.zip](https://github.com/SnailyCAD/snaily-cadv4/files/8542013/DispatchTones.zip)

**Comment by buck20073** [comment]
Its realistic, Its for FIRE/Dispatch ONLY. And helps gets their attention. Lets say dispatch assigned them on a call and called it through radio but they were busy do something else, so they didnt hear it. But with the fire tone its loud, & attention grabbing & they will start to listen to dispatch.

**Comment by pp2amd6** [comment]
> what's the use for EMS/FD tones, if there's already a sound that plays when they are assigned to a call?

The call tone allows fire station personnel to understand which unit (fireman or paramedic) will be used on the call.

**Comment by Dev-CasperTheGhost** [comment]
So, there would be a button called "Trigger EMS/FD tone" or would there be a different sound played when an EMS/FD unit gets assigned to a call?

**Comment by Sampuke** [comment]
it should probably be made so it only sends the sound to firestation like this https://github.com/inferno-collection/Fire-Alarm

**Comment by Dev-CasperTheGhost** [comment]
> [Sampuke](https://github.com/Sampuke):
> more sounds for lets say someone has a warant and he is serched it woul say that the person has warants,
also a app wich would let you use global keybinds would be usefull. Also that would be cool if the cad could like grap the IDs and stuff from MySQL so everyone wouldn't to make characters in the cad
and also more 10 codes to choose from

**Comment by Dev-CasperTheGhost** [comment]
> a feature where dis[patch can play tones to either fire/ems or leo (would be like a multiple choice checkbox)
tone examples can be found here: http://brics.butlersheriff.org/help/radio/tones-on-brics/
this would make it more realistic and easier for dispatch

Would this allow the dispatcher to also provide a message for this tone? @subtosharki

**Comment by Dev-CasperTheGhost** [comment]
What does everyone think? 
![image](https://user-images.githubusercontent.com/53900565/172038636-640fccc5-c75f-443e-b80e-c6b549e89ebc.png)

cc @pp2amd6 @Sampuke @buck20073 @Thomaswill1
