### ISSUE TITLE
Officers cannot end calls or add events even if "active dispatchers" are disabled

### ISSUE THREAD

**Issue by nick-perry14** [SnailyCAD/snaily-cadv4#596]
### What version of Node.js are you using?

Latest

### What operating system are you using?

Ubuntu

### Describe the Bug

Enabling the "active dispatchers" feature says that it will disable "curtain ***(sic)*** buttons" (I assume you meant certain).  Even with this option disabled, police officers cannot add events or end calls.  This requires supervisors (with dispatch access) to have to clear every call.  

### Expected Behavior

When the "active dispatchers" feature is disabled, police should be permitted to end calls, update descriptions, and update events.  Additionally, if "active dispatchers" is enabled but no dispatchers are on duty, the same logic above should apply

### To Reproduce

![2LWqNOKOVj](https://user-images.githubusercontent.com/6935777/162587757-3b45d6fd-4ee8-4f4c-9cfb-b71ec38b7fe3.png)

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed now!
