### ISSUE TITLE
Drag and drop to assign to call

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#599]
### Describe the feature

Dispatchers can drag and drop an officer or deputy to an active call to automatically assign said officer/deputy to call.

**Comment by Dev-CasperTheGhost** [comment]
Was fairly simple to setup. Something like this works?

https://user-images.githubusercontent.com/53900565/162675150-305ef23a-99b9-474d-a0c1-fdbfe49ef393.mov

**Comment by Thomaswill1** [comment]
Yep, that's it. (Though, probably could look nicer in terms of UI, but functionally the same thing)

**Comment by Dev-CasperTheGhost** [comment]
A minor drop-area indicator :)
https://user-images.githubusercontent.com/53900565/162678539-79d9cdc4-91fd-4d0e-a7c0-241c6d95d92d.mov

**Comment by Thomaswill1** [comment]
I like it

**Comment by Dev-CasperTheGhost** [comment]
I do to :D!

**Comment by Dev-CasperTheGhost** [comment]
This is also now available!
