### ISSUE TITLE
[FEATURE REQUEST] Common Citizen Cards Mode

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#60]
### Describe the feature

There are projects where citizens' cards are created by employees of state structures: the police, medics. Civilians simply don't have access to CAD.

The scenario is simple:
- the player arrives in the state (create player on server)
- goes to the police to get a driver's license, for example
- a police officer creates a citizen card and carries out procedures for issuing a driver's license

In this scenario, the citizen's card is not assigned to the policeman, but is common to everyone. Any police officer or medic can see it and can edit it.

This mode is an option and is enabled in the CAD settings.
![kiss_13kb 1635274752 1](https://user-images.githubusercontent.com/4976837/138944622-57032805-144c-4d1d-9f9f-ec19363a9e6a.png)

_In my experience, this is the most common use case for CAD._

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost any chance this feature will be implemented?

**Comment by Dev-CasperTheGhost** [comment]
> @Dev-CasperTheGhost any chance this feature will be implemented?

Are you able to explain a bit more in-detail? I'm not sure what you mean with this feature

**Comment by pp2amd6** [comment]
I will try to explain in simple terms with examples.

There is a project with 100 players online in prime time and uses a third party CAD (less functional, but anyone can edit records). ONLY government employees are allowed in the CAD. services (police, sheriffs, EMS, FD). Citizen records are created via an API.

Sometimes a mistake is made when creating a record about a citizen, in which case any other police officer can correct the mistake.

Now in SnailyCADv4, only the user who created it can see and edit the entry. This creates problems:
1. Can't edit records created via API
2. When a user is blocked, you cannot edit his records

"Common card" mode will allow any CAD user to change records

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost need further explanation?

**Comment by Dev-CasperTheGhost** [comment]
> @Dev-CasperTheGhost need further explanation?

I think I understand yeah. Will have to check when I'm home

**Comment by Dev-CasperTheGhost** [comment]
> Sometimes a mistake is made when creating a record about a citizen, in which case any other police officer can correct the mistake.

The "common cards" would allow officers to edit created tickets, arrest reports, etc? @pp2amd6

**Comment by pp2amd6** [comment]
> The "common cards" would allow officers to edit created tickets, arrest reports, etc?

Yes.

**Comment by Dev-CasperTheGhost** [comment]
With \#345 you can now edit created records! Warrants are already editable :)

**Comment by Dev-CasperTheGhost** [comment]
name, ethnicity, etc. is not currently supported, therefore this issue is still open. In the comment above I was talking about tickets, arrest reports and written warnings

**Comment by Dev-CasperTheGhost** [comment]
Will try work on this today/tomorrow!

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost 
Any plans for this functionality?
We create citizens automatically on the project through the API, but now we are facing problems:
- officers cannot edit citizen cards (cards created by system account)
- officers cannot register vehicles, because can't see cards
- officers cannot register weapons, because can't see cards

This functionality is in demand, because there are no civilian users in CAD, only those players who play as the police

**Comment by Dev-CasperTheGhost** [comment]
Will see what I can do. It's a quite a bit of work 😅!

**Comment by pp2amd6** [comment]
Is there progress on this task and will it be implemented?

The problem of the inability to edit citizen cards by officers is quite critical.

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost

**Comment by Dev-CasperTheGhost** [comment]
Progress hasn't started on this yet. This is not an easy task, nor do I have the greatest time this week. By "cards", you mean all the citizen information?

**Comment by pp2amd6** [comment]
> By "cards", you mean all the citizen information?

Card - entire citizen page.

**Comment by Dev-CasperTheGhost** [comment]
@pp2amd6 where would officers edit the citizen's card? Would this be done in a name search?

**Comment by pp2amd6** [comment]
I think the simplest solution is to see citizens on the /citizen page, because all the fields in the citizen's profile are displayed.
When an officer visits the page, he sees ALL citizens, even those created by other users or through the API.
![image](https://user-images.githubusercontent.com/4976837/166140275-b1fe7870-9232-4f62-959d-7d3d487b5f9e.png)

> Would this be done in a name search?
You can do this if the officer can edit the citizen (change the name, address, eye color, etc.)

**Comment by pp2amd6** [comment]
Any progress on this feature?

**Comment by Dev-CasperTheGhost** [comment]
Sorry for the late replies, this would allow **any** officer to edit **any** citizen?

**Comment by pp2amd6** [comment]
> Sorry for the late replies, this would allow **ANY** officer to edit **ANY** citizen?

Yes. Exactly.

**Comment by Dev-CasperTheGhost** [comment]
@pp2amd6 this would the correct wording?
![image](https://user-images.githubusercontent.com/53900565/167160223-572fee90-8158-4922-ad58-ef3ec644a42a.png)

**Comment by pp2amd6** [comment]
I can't answer 100% that yes (English is not my native language), but the context is correct

**Comment by Dev-CasperTheGhost** [comment]
Hi, 

I apologize for taking sooo long to get to this feature. I probably didn't fully understand it 🤔. Anyway, it should be implemented now! 

Let me know if there are missing pieces to this feature request :).

After 6.5months, this issue can finally be closed 😅...!

- Casper.
