### ISSUE TITLE
Automated Radio Channel switching with Discord

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#602]
### Describe the feature

Using Discord's API and events, when a user who is logged into the CAD as an On Duty officer or deputy, joins a voice channel under a specific Channel Category, the CAD will automatically update the Radio Channel field in the Dispatcher dashboard and Officer/Deputy MDT.

![image](https://user-images.githubusercontent.com/34800953/162699216-c0aae03e-7e79-4d92-a075-610380be8da5.png)

**Comment by Dev-CasperTheGhost** [comment]
this won't be possible without hosting a Discord bot. I think adding a Discord bot to SnailyCAD, it will become very bloated.

**Comment by Bujee-Ob** [comment]
> this won't be possible without hosting a Discord bot. I think adding a Discord bot to SnailyCAD, it will become very bloated.

What about with mumble-voips radio??

**Comment by Dev-CasperTheGhost** [comment]
> What about with mumble-voips radio??

Can you provide more info please.
