### ISSUE TITLE
Fire/EMS

### ISSUE THREAD

**Issue by Bujee-Ob** [SnailyCAD/snaily-cadv4#603]
### Describe the feature

When making a Fire/EMS personal on the CAD it says Deputy. Can you change it something else?

**Comment by Dev-CasperTheGhost** [comment]
What do you mean by "Personal"?

**Comment by Bujee-Ob** [comment]
> 

I mean The people who go on duty as Fire/EMS they have to create a citizen then go to create a deputy, instead of it saying deputy maybe it say something else?

**Comment by Dev-CasperTheGhost** [comment]
You should be able to translate this. See docs: https://cad-docs.caspertheghost.me/docs/features/translating
