### ISSUE TITLE
Panic Button

### ISSUE THREAD

**Issue by Bujee-Ob** [SnailyCAD/snaily-cadv4#604]
### Describe the feature

When someone presses the panic button make it where they can put the location so its Realistic, & Easier for the LEOS/Dispatch.

**Comment by Dev-CasperTheGhost** [comment]
The panic-button isn't connected to the game 😅. This won't be done unfortunately

**Comment by Bujee-Ob** [comment]
> The panic-button isn't connected to the game 😅. This won't be done unfortunately

I don't mean connect it to the game, but make it where when they press it they have to type out the location, Like a Spot for Postal, a Spot for Road, a Spot for sub-road, etc.
