### ISSUE TITLE
Call/Incident clean up routine/timeout

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#610]
### Describe the feature

I'm often running into the issue of having a number of calls & incidents that haven't been closed out properly by LEO/EMS-FD. 

It would be good if there was some functionality to create a global timeout for them or at least trigger a routine every X amount of time to close outstanding calls/incidents?

**Comment by Dev-CasperTheGhost** [comment]
How would I check if the calls are inactive?

**Comment by jxckUK** [comment]
> How would I check if the calls are inactive?

Easiest way to tell is that it has no assigned units for a period of time that could be configured in the settings?

**Comment by Dev-CasperTheGhost** [comment]
Will take a look tomorrow :)
