### ISSUE TITLE
Default Rank

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#611]
### Describe the feature

Can we assign a default rank to a unit in the default department?

For instance I have a Public Law Enforcement department as default but I want to give them the Public Officer rank so they aren't trying to make themselves Sergeants and everything lol.

**Comment by Dev-CasperTheGhost** [comment]
Sure, will implement this tomorrow.

**Comment by Dev-CasperTheGhost** [comment]
Something like this @ViolentMinds 

![image](https://user-images.githubusercontent.com/53900565/163108670-f41a6587-904b-459a-a0cb-483d063b2d1b.png)

**Comment by ViolentMinds** [comment]
Yes sir!
