### ISSUE TITLE
Drag and Drop does not always work.

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#612]
### What version of Node.js are you using?

N/A

### What version of npm are you using?

N/A

### What operating system are you using?

N/A

### Describe the Bug

When attempting to drag and drop a unit, the unit does not always attach to the mouse, and it can take several tries to get the unit to attach to the mouse. (It seems it will only work after you've clicked or dragged something else relating to the officer.)

(In this video, I only grabbed it by accident)

https://user-images.githubusercontent.com/34800953/163093888-7de07958-5002-477c-850e-1b01668bf3c5.mp4

### Expected Behavior

The unit should attach right away.

(Also, could you by chance make the UI more obvious that you can pick up the unit? Such as an inset button that only appears when you've hovered over the unit. If clicked once, you can set the unit status, like right-clicking, but if dragged, you can assign that unit to a call as normal.)

**Comment by Dev-CasperTheGhost** [comment]
Looks like a chromium-only bug. Will investigate
