### ISSUE TITLE
Permissions Bug For Users

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#618]
### Describe the feature

When I try to update peoples permissions nothing changes. Then I look at console and i see these errors.
I look at 

![image](https://user-images.githubusercontent.com/25211271/163204624-2dd7f4cf-9df4-485b-99ee-9db526aa93f1.png)

and this doesnt seem to update either 
![image](https://user-images.githubusercontent.com/25211271/163204887-5b800fed-ee8a-4458-903d-e4b33e8dd33f.png)

**Comment by Dev-CasperTheGhost** [comment]
>When I try to update peoples permissions nothing changes. Then I look at console and i see these errors.
I look at

See docs here: https://cad-docs.caspertheghost.me/docs/errors/missing-translation-message. The permissions should've been saved successfully

> and this doesnt seem to update either

They have actually updated, that table is till outdated. Will fix soon!

**Comment by ViolentMinds** [comment]
Roger. Don't forget about this 
![image](https://user-images.githubusercontent.com/25211271/163205507-e8eaa2c7-71aa-4530-9412-9fb5d736011e.png)

Not sure if it still applies? Because it doesnt update either
