### ISSUE TITLE
Change Citizen or Officer Names / Badge Numbers

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#619]
### Describe the feature

1) Is it possible for Owner to be able to change citizen names?
**Unit 701 - 701 - 701 jason anderson anderson** has changed their status to 10-8/10-41 • On Duty

I have people who make really messy looking stupid names like this in the CAD and it makes me go crazy lol

2) Will it be possible to remove/hide Badge numbers. I know I asked this months ago but its annoying as well because we only use Callsign and we dont have badge numbers. So everyone ends up just duplicating their callsign number or writes some random thing in there.

Alternatively make Badge number optional field not required.

**Comment by Dev-CasperTheGhost** [comment]
> Is it possible for Owner to be able to change citizen names?
Unit 701 - 701 - 701 jason anderson anderson has changed their status to 10-8/10-41 • On Duty

Users with `Manage Citizens` permission can already do this.

> Will it be possible to remove/hide Badge numbers. I know I asked this months ago but its annoying as well because we only use Callsign and we dont have badge numbers. So everyone ends up just duplicating their callsign number or writes some random thing in there.

Sure;, will probably make this a feature that can be disabled.
