### ISSUE TITLE
Ability to disable Callsign Symbol 1 (or make it optional)

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#621]
### Describe the feature

To prevent having duplicate department and callsign symbols. I know you can hide the first callsign symbol from appearing in misc settings, but that feels like it would still be confusing to players who don't know this.

### Additional Context

![good](https://user-images.githubusercontent.com/34800953/163404903-a3962fc6-2913-4331-ac83-5a32ad863710.png)

![bad](https://user-images.githubusercontent.com/34800953/163404925-ba7babfc-9d29-4a7a-9cea-4e82ba51d0b2.png)

**Comment by Dev-CasperTheGhost** [comment]
I mean, that's what the template is for really. I could probably add more CAD related information the docs.
