### ISSUE TITLE
Federal Department / ATF Plates / People

### ISSUE THREAD

**Issue by FluxLord** [SnailyCAD/snaily-cadv4#625]
### Describe the feature

Allow a option for a federal department. (FIB)
So when someone not within the Federal department looks something up relating to anyone with credentials tagged as Federal they will be blocked along with a notification will be sent to someone within the Federal department.
OR something similar to how plates work on ATF cars but it send a notification when looked up.

**Comment by Dev-CasperTheGhost** [comment]
Are you able to provide screenshots for this? I’m not familiar of this 😅.

**Comment by FluxLord** [comment]
I don't really have a screenshot.
Only a concept / idea.

Add another department and allow the ability for a toggle on a per user basis so when its on all of its information is redacted when another law enforcement officer looks it up. It would send a notification to someone within the Federal department notifying them someone looked them up.

**Comment by FluxLord** [comment]
Similar to that yes.
But when someone searches anything related to that "Special" department it sends a red flag / message to people in that department.

**Comment by Dev-CasperTheGhost** [comment]
the CAD doesn't have notifications yet. But might have it in the future.
