### ISSUE TITLE
Empty Discord role results in removal when authenticated

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#635]
### What version of Node.js are you using?

16.3.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

Linux (ubuntu 20.04)

### What version of SnailyCAD are you currently using?

1.0.0-beta.86

### Describe the Bug

When I don't specify a Discord role for CAD administrator as I prefer to do this manually with the new permission system, every time a user authenticates who has been granted access via the system using Discord it removes the custom permissions assigned.

### Expected Behavior

Custom permissions should not be overwritten by Discord permissions, they should take precedence even if the user authenticates via Discord.

**Comment by pp2amd6** [comment]
Have same bug. User moves to pending every time when try to authenticate after I grant access

**Comment by Dev-CasperTheGhost** [comment]
Haven't been able to test this, but should be fixed now
