### ISSUE TITLE
Header Text Overlap

### ISSUE THREAD

**Issue by ProfessionalWumpus** [SnailyCAD/snaily-cadv4#638]
### What version of Node.js are you using?

18.0.0

### What version of npm are you using?

7.10.0

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

v1.0.0-beta.87

### Describe the Bug

We encountered an issue where text is shown overlapping the the title in the header.

Discord Link: https://discord.com/channels/792479048457912360/903877466572087347/966779114084257792
Video: https://user-images.githubusercontent.com/104166803/164537105-aacbcdc7-8165-4276-9bc7-dadd8142f5a1.mov

### Expected Behavior

The text not to be there, it seems to be replacing an non-existant logo.

**Comment by Dev-CasperTheGhost** [comment]
You haven't set an icon for the CAD? Can you still try remove the logo via the CAD settings. Simply click "Delete" on the logo field, then click save
