### ISSUE TITLE
Name search when looking up vehicle plate

### ISSUE THREAD

**Issue by AstroBallistic** [SnailyCAD/snaily-cadv4#639]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows

### What version of SnailyCAD are you currently using?

1.0.0-beta.86

### Describe the Bug

When search the plate of a vehicle you can't click the name for an automatic names search anymore

### Expected Behavior

When doing a vehicle search on beta 85 you could click the name and automatically be taken to the civilian page

### To Reproduce

Search a plate and click the name of the owner

**Comment by Dev-CasperTheGhost** [comment]
This has been fixed in the latest version. Please update your CAD. Updating documentation can be found here: https://cad-docs.caspertheghost.me/docs/installations/updating
