### ISSUE TITLE
[Improvement] Improved search

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#64]
### Describe the feature

Implement a search on a piece of data.
The functionality refers to the search for citizens, vehicles, weapons.

Now, to search for a citizen, you must specify the full name (first name and last name). 
The new search will allow you to find citizens by name, surname, part of data, address.
Entering "john" will display the following entries:
- John Borland
- Johnny Depp
- Carl Johnson

Weapon search will remain by serial number, but will also work by full serial number or part of the number

Search by transport will remain by state number, but will also work by full number or part of the number.

**Comment by Dev-CasperTheGhost** [comment]
@pp2amd6 new name search flow, wasn't able to record a video but see screenshots below :D

![image](https://user-images.githubusercontent.com/53900565/139525372-91a1b142-0c50-4c8a-bfc4-9a0667e98bbe.png)

![image](https://user-images.githubusercontent.com/53900565/139525373-255240e1-17c6-48a1-9dce-ea786fc0bd86.png)

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost works, but not for all cases

**Citizen**
Work
![kiss_17kb 1635596708 1](https://user-images.githubusercontent.com/4976837/139532797-49662da7-56b7-428f-92fb-61f89242166c.png)

Doesn't work, but should
![kiss_11kb 1635596754 1](https://user-images.githubusercontent.com/4976837/139532817-ddd6cba1-bc09-49e2-8ac6-d7ac993bc49a.png)

**Vehicles**
Work
![kiss_27kb 1635597099 1](https://user-images.githubusercontent.com/4976837/139532960-b6b45311-d2ec-41a0-8b7e-25f6b3671bf7.png)

Doesn't work, but should
![kiss_10kb 1635597122 1](https://user-images.githubusercontent.com/4976837/139532969-0fb2e11b-a027-4ebc-954d-fa4e84ca3c48.png)

**Comment by Dev-CasperTheGhost** [comment]
This should now be fixed! @pp2amd6
