### ISSUE TITLE
Incident data is not passed to EMS/FD unit data

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#642]
### What version of Node.js are you using?

N/A

### What version of npm are you using?

N/A

### What operating system are you using?

N/A

### What version of SnailyCAD are you currently using?

v1.0.0-beta.87

### Describe the Bug

Unlike LEO, EMS/FD active incidents are not passed through the unit data.

### Expected Behavior

When collecting unit data it should provide an array of the assigned incidents for the unit.

(Side note: currently the LEO array only includes one incident, this should probably include all active incidents.)

**Comment by Dev-CasperTheGhost** [comment]
Should have the correct data now.
