### ISSUE TITLE
Individual API keys

### ISSUE THREAD

**Issue by nick-perry14** [SnailyCAD/snaily-cadv4#646]
### Describe the feature

Allow officers/users to set up an individual API key so they can set their own officer status, enable panic button, etc.  This way things like stream decks can be used to change status and communicate information without having to open the cad.

**Comment by Dev-CasperTheGhost** [comment]
This sounds like something interesting, will try this out next week

**Comment by pp2amd6** [comment]
For security, it is imperative to implement a mechanism for viewing the generated keys for the administrator.
Users should be allowed to use only some GET methods, I think

**Comment by Dev-CasperTheGhost** [comment]
This shouldn’t matter though, the user’s api token will only be able to perform actions they would be able to perform without

**Comment by pp2amd6** [comment]
Why give the user permission to use POST, PUT, DELETE API methods?

**Comment by Dev-CasperTheGhost** [comment]
Because they can already do that if they're logged in 😅.

**Comment by pp2amd6** [comment]
I can't understand why an API is needed for a regular user.
Will this feature be disabled in the settings?

**Comment by Dev-CasperTheGhost** [comment]
Yes, it'll be optional.

**Comment by nick-perry14** [comment]
> I can't understand why an API is needed for a regular user. Will this feature be disabled in the settings?

This is suggested so individuals with technical knowledge can set up automation tasks for themselves without having to disclose the admin API key.  For example I own a stream deck that can make arbitrary web requests.  I would love it if I could use a personal API key to set the status of my officer without having to reopen the cad.  I hope this kind of explains one of the use cases

**Comment by pp2amd6** [comment]
> I would love it if I could use a personal API key to set the status of my officer without having to reopen the cad

This is a very cool example and I like this scenario.

But I look a little further and I can give a bad example: a player can quarrel with the project team and through the API can start creating a huge number of 911 calls to harm the rest and prevent them from playing.

For such cases, the administrator must be able to see the list of created user keys and the ability to manage them (turn off / delete).

**Comment by Dev-CasperTheGhost** [comment]
> For such cases, the administrator must be able to see the list of created user keys and the ability to manage them (turn off / delete).

Yup, I have the same thought. I'll add the ability for admins to revoke their API tokens and the ability to remove their permissions for the API token

**Comment by Dev-CasperTheGhost** [comment]
Docs have been updated a bit, it includes an example for the user token. https://cad-docs.caspertheghost.me/docs/developer/public-api

Note: the header name is different from the CAD's API Token.
