### ISSUE TITLE
Custom Error Message When Submitting Arrest Report 

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#652]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

Latest

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/164954510-104e09e7-d00a-4138-99d8-ed9db387ecb4.png)

At the moment if someone makes an arrest report but forgets to select an offense and only selects the category of offense they will just get a BAD REQUEST error. If we can add an error popup that says "Must add offence and fine or jail time amount to submit arrest report." or something that would be good.

### Expected Behavior

A better detailed error message.

### To Reproduce

Try to submit an arrest report with no offence or fines.

**Comment by Dev-CasperTheGhost** [comment]
Are you able to provide the error message from that error? Or send the entire object here @ViolentMinds

**Comment by ViolentMinds** [comment]
![image](https://user-images.githubusercontent.com/25211271/164962674-888562c2-6343-493e-a0a2-b0101fe7f264.png)
THAT???



{
  "DEBUG": {
    "message": "Request failed with status code 400",
    "status": 400,
    "response": {
      "data": {
        "name": "BAD_REQUEST",
        "message": "fine_invalidDataReceived",
        "status": 400,
        "errors": []
      },
      "status": 400,
      "statusText": "Bad Request",
      "headers": {
        "content-length": "84",
        "content-type": "application/json; charset=utf-8"
      },
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "Content-Type": "application/json",
          "Session": "snaily-cad-session=undefined",
          "is-from-dispatch": "false"
        },
        "url": "https://api.enemyofthestaterp.com/v1/records",
        "method": "post",
        "data": "{\"type\":\"TICKET\",\"citizenId\":\"cl1wxrsca71402xwtmano84k7g\",\"citizenName\":\"John harris 111\",\"violations\":[{\"penalCodeId\":\"cky5nfkzk5560d4tmych4sv0v\",\"bail\":null,\"jailTime\":null,\"fine\":231}],\"postal\":\"2341\",\"notes\":\"\",\"seizedItems\":[]}",
        "withCredentials": true
      },
      "request": {}
    },
    "method": "post",
    "data": "{\"type\":\"TICKET\",\"citizenId\":\"cl1wxrsca71402xwtmano84k7g\",\"citizenName\":\"John harris 111\",\"violations\":[{\"penalCodeId\":\"cky5nfkzk5560d4tmych4sv0v\",\"bail\":null,\"jailTime\":null,\"fine\":231}],\"postal\":\"2341\",\"notes\":\"\",\"seizedItems\":[]}",
    "url": "https://api.enemyofthestaterp.com/v1/records"
  }
}

**Comment by Dev-CasperTheGhost** [comment]
yup, works. Thanks!

**Comment by Dev-CasperTheGhost** [comment]
Alright, got this working 🎉. Will be released soon!

![image](https://user-images.githubusercontent.com/53900565/164965537-dced24b1-013a-4d70-87c1-1b88f4b08347.png)
