### ISSUE TITLE
[FEATURE] Qualifications and awards

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#656]
### Describe the feature

Add the ability to specify qualifications and awards in the profiles of officers and deputies.

### Who specifies
Supervisor LEO or FD / EMS

### Complex implementation

**1. CAD Settings**

Create a new dictionary in the CAD settings.

The directory will contain the following fields:
- Image
- Name
- Department (drop-down list with the values of the Departments dictionary)

**2. Officer / deputy card on manage units page**

There will be two blocks in the officer / deputy profile: qualifications and awards.

The Supervisor can add a qualification / award, suspend it or remove it.

![image](https://user-images.githubusercontent.com/4976837/164972338-63638b2f-14ea-4538-a9c6-28b131a8170b.png)

**Qualifications and awards are separate blocks**

**3. Unit card**

The officer / deputy card displays two separate blocks: qualifications and awards.

The block for each entry displays the image, title, date of assignment and the officer who assigned the qualification

If the qualification/award has been suspended, then the text of the entry is displayed in gray. Additionally, the date of suspension and the name of the officer are displayed.

If a qualification/award has been removed, it is not displayed.

![image](https://user-images.githubusercontent.com/4976837/164973461-c851e6cd-7b4b-4a65-b5d5-3f30e679042d.png)

**Comment by Dev-CasperTheGhost** [comment]
I've updated the description to only include the complex version. This makes it easier to scale by doing it to "complex" way.

**Comment by Dev-CasperTheGhost** [comment]
> Qualifications and awards

What would define the difference between qualifications and awards?

**Comment by pp2amd6** [comment]
> What would define the difference between qualifications and awards?
Context.
The officer receives qualifications for his professional skills, for example, the skill of handling heavy weapons.
The officer receives awards for some achievements or deeds, for example, saving people.

> What would this be used for?
To indicate which department the qualification or award belongs to. Obviously, the fireman and the policeman will have different qualifications.

**Comment by Dev-CasperTheGhost** [comment]
Current progress: 

https://user-images.githubusercontent.com/53900565/165127800-4c7ced89-dcfc-412f-ae1b-8c8b406346f9.mov

**Comment by Dev-CasperTheGhost** [comment]
> To indicate which department the qualification or award belongs to. Obviously, the fireman and the policeman will have different qualifications.

@pp2amd6 wouldn't it be better to support multiple departments per qualification/award?

**Comment by pp2amd6** [comment]
> @pp2amd6 wouldn't it be better to support multiple departments per qualification/award?

I wanted to write about it right now. Yes, qualifications/awards can be listed in the dictionary for multiple departments.

**Comment by jxckUK** [comment]
Sorry to jump in on this one, but really like this feature and the progress so far.

Would it be possible to also add dates to this? An awarded or assigned date or effective start date etc?
