### ISSUE TITLE
URGENT: CAD won't load after last update

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#657]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

Latest

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/164989045-6b238316-7d80-4653-906d-5e4b1579f0ff.png)

I'm suddenly getting a BAD REQUEST error when I try to load CAD after the most recent update. (Method Automatic)

### Expected Behavior

To load CAD as normal

**Comment by Dev-CasperTheGhost** [comment]
Remove the `packages/client/.next` folder. Then run `yarn turbo run build` before starting the CAD.
