### ISSUE TITLE
[FEATURE] Extend functionality for Individual API keys

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#665]
### Describe the feature

Related to Individual API keys #646

There is currently an option to enable a feature to generate custom API keys, but there is no admin functionality to control key usage.

### What do I suggest?

1. Add menu item "Manage API Keys"

![image](https://user-images.githubusercontent.com/4976837/165162031-bf2a3f69-4549-4278-b7da-9d39435b2899.png)

2. Implement output of existing keys in tabular form. The table will have the following columns:

- Username
- Key generation date
- Number of uses (total)
- Buttons with actions

![image](https://user-images.githubusercontent.com/4976837/165184633-202c5e2f-9bc6-4cf3-ada3-63ad98da75fb.png)

3. Add journaling

By clicking on the "journal" (or "logs", doesn't matter) button, a table with data is loaded:
- API call date
- method
- status

![image](https://user-images.githubusercontent.com/4976837/165185604-0d7efbe7-acdd-4980-a71a-869486a288a0.png)

Administrators with such functions can monitor the use of keys and respond in time to different situations.

**Comment by Dev-CasperTheGhost** [comment]
> but there is no admin functionality to control key usage.

Admins can revoke the API key from a user, and disable their permissions from making other API keys. However, this could also be useful to implement.

**Comment by Dev-CasperTheGhost** [comment]
> 3. Add journaling

I'm not sure on this one. I feel like this would add a lot of "junk" data to the database.

**Comment by pp2amd6** [comment]
> I'm not sure on this one. I feel like this would add a lot of "junk" data to the database.

For example, if a user (@nick-perry14) sets the status of a unit through the API, then these are several dozen entries per day (30, for example).

1 day - 30 entries
1 week - 210
1 month - 840
1 year - 10 080

This is not much, I think that there will be more call records per day.

If you think that the log can be detrimental to performance, then you can turn it off

**Comment by Dev-CasperTheGhost** [comment]
Currently it seems to not be possible to get the `statusCode` from the request. I'll release this feature without it and maybe include it in a later release.
