### ISSUE TITLE
Qualifications additions

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#668]
Couple of things one of which I did mention previously that would be fantastic for the new qualifications section. (which is already a great function so thanks for this!)

_Originally posted by @jxckUK in https://github.com/SnailyCAD/snaily-cadv4/issues/656#issuecomment-1108791281_

1. Can we please get a view for standard LEO/EMS/FD to see qualifications of others? Maybe a hover over the name and it shows?

2. Can we introduce Discord role assignment to training, so we can assign Discord roles to the qualifications and if they have that role they get the qualification in the CAD on next auth etc. The presented at time and any revocation could just be tied to the point at which the Discord auth identified that role on the user.

**Comment by jxckUK** [comment]
> To avoid loading even more data for units, I think this can be done with _lazy loading_, when the mouse hovers over the unit, it will then fetch the latest qualifications.

Sounds perfect!

> I'm not sure on this one yet. Will see what I can do for this.

It's just because we tend to allocate roles for example Advanced Medic in Discord and it adds an extra layer if the supervisors are then also allocating this in the CAD separately. It would just be nice to have the same level of synchronisation we have with roles (in terms of how it functions it would be like for like) so that the CAD is the centrepiece but all the data is lined up with Discord.

**Comment by pp2amd6** [comment]
> 2\. Can we introduce Discord role assignment to training, so we can assign Discord roles to the qualifications and if they have that role they get the qualification in the CAD on next auth etc. The presented at time and any revocation could just be tied to the point at which the Discord auth identified that role on the user.

I'll critique your post a bit 😄 

A very strange scenario. Awarding qualifications or awards is part of the role play and should be done by the senior officer in the CAD (Qualifications and Awards - IC). Working with roles in discord is OOC and has nothing to do with role playing. It will be right to leave this functionality on the CAD side

**Comment by pp2amd6** [comment]
In addition: Separate qualifications and awards.
Qualification != reward.

![image](https://user-images.githubusercontent.com/4976837/165409457-8ed5ad7b-be43-40ba-8b12-fc238d15ca42.png)

**Comment by Dev-CasperTheGhost** [comment]
![image](https://user-images.githubusercontent.com/53900565/165552430-ef5cf92d-5564-422b-8ad4-4e1ae206256c.png)

![image](https://user-images.githubusercontent.com/53900565/165552515-89fa0dc9-a629-4a5e-9733-85f6e9ff1fac.png)

![image](https://user-images.githubusercontent.com/53900565/165552561-2c343692-a146-4178-94ac-bd68ed8435dc.png)

*note: this is test data*

**Comment by pp2amd6** [comment]
> ![image](https://user-images.githubusercontent.com/53900565/165552430-ef5cf92d-5564-422b-8ad4-4e1ae206256c.png)
> 
> ![image](https://user-images.githubusercontent.com/53900565/165552515-89fa0dc9-a629-4a5e-9733-85f6e9ff1fac.png)
> 
> ![image](https://user-images.githubusercontent.com/53900565/165552561-2c343692-a146-4178-94ac-bd68ed8435dc.png)
> 
> _note: this is test data_

Awesome!

But do not forget that there should be two blocks in the popup: qualifications and awards :)

**Comment by Dev-CasperTheGhost** [comment]
yep, working on that rn!

**Comment by Dev-CasperTheGhost** [comment]
![image](https://user-images.githubusercontent.com/53900565/165559222-73cc66cd-dc5c-4bd5-a928-ce0247768469.png)

![image](https://user-images.githubusercontent.com/53900565/165559306-064af0fc-9793-4f42-b6a8-b559ce032934.png)

**Comment by pp2amd6** [comment]
> ![image](https://user-images.githubusercontent.com/53900565/165559222-73cc66cd-dc5c-4bd5-a928-ce0247768469.png)
👍 

> ![image](https://user-images.githubusercontent.com/53900565/165559306-064af0fc-9793-4f42-b6a8-b559ce032934.png)
It is dictionary in CAD settings? Ok. Acceptable

**Comment by Dev-CasperTheGhost** [comment]
> It is dictionary in CAD settings? Ok. Acceptable

yeah
