### ISSUE TITLE
[BUG] Citizen - Medical records - Wrong type of field "Blood type"

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#674]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.0.0-beta.90

### Describe the Bug

Wrong type of field "Blood type". I didn't notice this before. Now the "Blood type" field is multiple, which is not correct. A person can have **one** blood type and it does not change throughout life.

### Expected Behavior

The "Blood type" field must be one. If the implementation is complex, then the "Diseases" field can also be made one, so that diseases are entered separated by commas.

**Comment by Dev-CasperTheGhost** [comment]
The blood group field isn't multiple? I'm unable to reproduce this error. 

![image](https://user-images.githubusercontent.com/53900565/165443971-2c62ffea-d625-4641-bc31-89199de4d384.png)

**Comment by pp2amd6** [comment]
> The blood group field isn't multiple?

@Dev-CasperTheGhost you missed an important detail in the message. The "Blood type" field is multiple and it`s NOT correct.
A person's blood type is ONE for life, but I can specify as many as I like. This is wrong

![image](https://user-images.githubusercontent.com/4976837/165448738-ad3d2487-d1cd-4782-884f-fffa3df82744.png)

**Comment by Dev-CasperTheGhost** [comment]
Ahhh! Like that. sure, that can be changed. Maybe if someone creates a new medical record with a different blood group, it will change it for all the other medical records the citizen has?

**Comment by pp2amd6** [comment]
> it will change it for all the other medical records

Ok, sounds good. 👍 

An employee can make a mistake with the indication of the blood type and then it will be incorrectly indicated in other records, but this will already be part of the role-play. :)

**Comment by Dev-CasperTheGhost** [comment]
Sorry for taking a few days to get back to this. Should be fixed shortly!

https://user-images.githubusercontent.com/53900565/166150412-0cbb4a0f-ab57-4473-abe6-79cd2ad8728d.mov
