### ISSUE TITLE
[IMPROVEMENT] Jail - Add citizen info

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#678]
### Describe the feature

Currently there is no additional information about the citizen.
For example, in a prison there are two prisoners with the same name - John Doe.

You can't figure out who is who.

I propose to either show the citizen's social security number next to the name or make the citizen's name a link to the citizen's profile.

![image](https://user-images.githubusercontent.com/4976837/165419596-edd312e2-73a4-4fe1-b989-ae8b89966e8b.png)

**or**

![image](https://user-images.githubusercontent.com/4976837/165419777-dbf9f335-275a-45b4-9233-8d15c8fed2a0.png)

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost 
I looked at the commit and remembered that social security numbers are a feature that can be turned off.

If it is turned off or not used, then citizens with the same name cannot be identified, so you still need to add a link to the citizen's profile.

**Comment by jxckUK** [comment]
I think a good general rule of thumb is that where the user is presented with civilian or vehicle data, a contextual button is added for them to view the full modal.

This has saved countless hours for LEOs in the dashboard since it was added and applying the same principle to all areas will save even more.

**Comment by pp2amd6** [comment]
> I think a good general rule of thumb is that where the user is presented with civilian or vehicle data, a contextual button is added for them to view the full modal.
> 
> This has saved countless hours for LEOs in the dashboard since it was added and applying the same principle to all areas will save even more.

I have long had a plan to write a task to improve the interface, but it's a lot of work. You started it 😄

**Comment by Dev-CasperTheGhost** [comment]
Something like this could work @pp2amd6 @jxckUK 

https://user-images.githubusercontent.com/53900565/165584310-4575e339-8c22-45a2-88fe-4190ec94d72a.mov

**Comment by jxckUK** [comment]
Yeah looks great to me!
