### ISSUE TITLE
[BUG] Admin - Qualification values - Sorting working incorrectly

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#680]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.0.0-beta.90

### Describe the Bug

Sorting of "Assigned At" field is not working correctly

https://user-images.githubusercontent.com/4976837/165455868-9fd58afc-a9a6-417f-8f84-2366a4a2ddd6.mp4

The entry "Basic Life Support" (green ribbon) was added first, but it is not specified when sorting at the beginning or end of the list.

### UPD

I looked into the database and it turned out that sorting works correctly.

![image](https://user-images.githubusercontent.com/4976837/165459335-164efecf-265f-4ee7-800c-c33a93c83b72.png)

I did some research and found a problem - if you suspend a qualification and then resume it, the sorting will use the suspension date, not the qualification assignment date

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
I think if you reload the page, this fixes the issue?

**Comment by pp2amd6** [comment]
> I think if you reload the page, this fixes the issue?

No

**Comment by Dev-CasperTheGhost** [comment]
ah okay, I'll take a look later today then.

**Comment by pp2amd6** [comment]
> ah okay, I'll take a look later today then.

When sorting, you probably use the "updatedAt" column, but you need to sort by the "createdAt" column.

I tested sorting on column "updatedAt" and got exactly the same behavior as it is now.

**Comment by pp2amd6** [comment]
Also sorting does not work correctly with records that do not have an image
![image](https://user-images.githubusercontent.com/4976837/165484574-e6dfd3e9-2e24-46f1-bc2b-f090b0b11e11.png)

**Comment by Dev-CasperTheGhost** [comment]
All the data is correct. I don't think this is something I can fix rn, it looks like it's an issue with a 3rd party module :/.

**Comment by pp2amd6** [comment]
> All the data is correct. I don't think this is something I can fix rn, it looks like it's an issue with a 3rd party module :/.

If I find out under what condition the error appears and how to reproduce it, I will write.
