### ISSUE TITLE
[BUG] Officer - Driver license exams - The form is not working properly

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#684]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.0.0-beta.90

### 1. Unfriendly error
![image](https://user-images.githubusercontent.com/4976837/165506373-b71aeb8b-084c-4ad3-85b0-1de8b3a8083e.png)

### 2. Licenses
Now the field displays values from the "Value" table with "type" = 'LICENSE'.
The field must show values from the "DriversLicenseCategoryType" type, excluding the value "FIREARM" (although I don't understand why FIREARM is in the **Drivers**LicenseCategoryType).
![image](https://user-images.githubusercontent.com/4976837/165508285-f6a44998-f52b-4002-b822-90111b9eedfb.png)

### 3. Categories
Now ALL values are shown and this is not correct.
Categories should be shown depending on the value that was selected in the "Licenses" field

If nothing is selected in the "Licenses" field, the "Categories" field should be unavailable for interaction.
![image](https://user-images.githubusercontent.com/4976837/165513137-fe7d7c90-bc98-4a70-b032-6386befdae79.png)

### 4. Not all text values have a translation
![image](https://user-images.githubusercontent.com/4976837/165513586-29a37d91-018b-4edd-a2f4-ca1695c415a8.png)

**IMPROVING**
Make citizen name as link button to citizen card page
![image](https://user-images.githubusercontent.com/4976837/165513840-93936c8c-c0ba-4546-9c01-fe25cb74ba06.png)

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
> 1. Unfriendly error
> image

This can unfortunately not be changed.

**Comment by pp2amd6** [comment]
> This can unfortunately not be changed.

Sad. I thought that the form field had validation, just like the citizen search form through an officer.

**Comment by Dev-CasperTheGhost** [comment]
> IMPROVING
> Make citizen name as link button to citizen card page
> image

This will be done together with #668

**Comment by Dev-CasperTheGhost** [comment]
> 3. Categories
Now ALL values are shown and this is not correct.
Categories should be shown depending on the value that was selected in the "Licenses" field
If nothing is selected in the "Licenses" field, the "Categories" field should be unavailable for interaction.
image

These values are nowhere connected with each other. I'm not sure what you mean here.

**Comment by pp2amd6** [comment]
> > 3. Categories
> >    Now ALL values are shown and this is not correct.
> >    Categories should be shown depending on the value that was selected in the "Licenses" field
> >    If nothing is selected in the "Licenses" field, the "Categories" field should be unavailable for interaction.
> >    image
> 
> These values are nowhere connected with each other. I'm not sure what you mean here.

Now this field shows values for **ALL** licenses (car, water, air)

This field should show values **ONLY** for the license that was selected

**Comment by Dev-CasperTheGhost** [comment]
> Now this field shows values for ALL licenses (car, water, air)

> This field should show values ONLY for the license that was selected


Yeah, that I understood, but the license type is not connected to the category type. Therefore it's impossible to filter them

**Comment by pp2amd6** [comment]
> > Now this field shows values for ALL licenses (car, water, air)
> 
> > This field should show values ONLY for the license that was selected
> 
> Yeah, that I understood, but the license type is not connected to the category type. Therefore it's impossible to filter them

Ok, you can link values through DB tables except FIREARM

![image](https://user-images.githubusercontent.com/4976837/165520087-ec326207-24c4-4a4d-8481-a23ad45316d6.png)

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost 
The bug is not completely fixed.
The "Licenses" field should not display license statuses, but should display categories of licenses.
![image](https://user-images.githubusercontent.com/4976837/165544541-5f233f30-d3b1-499d-8cc2-ef3af9f7bbee.png)
