### ISSUE TITLE
[BUG] Officers dashboard - Unit combine

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#689]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.0.0-beta.91

### Describe the Bug

Related to #46
Related to #47

The mechanism for combining units does not work correctly.
I have two units:
![image](https://user-images.githubusercontent.com/4976837/165592768-a8179b76-6aa1-4ccd-8930-ea6a31c59a0c.png)

When I merge them, I get the wrong callsign
![image](https://user-images.githubusercontent.com/4976837/165592904-934e08c4-338d-469d-9fe8-510fec48e499.png)

Template in CAD settings
![image](https://user-images.githubusercontent.com/4976837/165593116-f26da5db-c7d6-46bc-a861-180cb5a287fc.png)

### Expected Behavior

The initiator of the association was 2R-40 Fernan Villagomez

The mechanism was to take the department and callsign2 of the officer who initiated the merge (quote from task #47: In the general callsign for $callsign2$, the value of the officer who merged the records is taken).

Final call sign must be 1A-40
![image](https://user-images.githubusercontent.com/4976837/165593841-3c79a8f4-cc36-4d2f-9ddc-935eeafa3f96.png)

**Comment by Dev-CasperTheGhost** [comment]
You cannot use `department` for paired unit templates. Nor will it be possible since other departments can be merged together. The `callsign2` should be fixed now

**Comment by pp2amd6** [comment]
> You cannot use `department` for paired unit templates. Nor will it be possible since other departments can be merged together.

Can you add support for this behavior? I understand that this is logically wrong, but there is such a need. Users will use such tags at their own risk.
