### ISSUE TITLE
Expire jail sentences after expiration automatically

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#693]
### Describe the feature

At the moment jailed citizens remain in jail indefinitely, it would be good if this factored in there conviction time and if spent it released them.

We would need an option for scaling, for example we might sentence a suspect to 15 years, there is little point expiring this automatically but if this is scaled to 15 days/15 hours etc. (for game purposes) then it makes it more practical.

**Comment by jxckUK** [comment]
> that logic is a little bit different, I'm not sure if I could re-use the logic for this. what would the option in the cad settings look like anyway 😅?

There would be two configuration options added to CAD settings:

- Enable/Disable Automatic Jail Sentence Expiration (Simple toggle)
- Set Jail Sentence Scaling (Not sure how to present this but so you can set 1 year in the CAD to equal 1 day, week etc in the timing of the feature.)

Then when the custody sentence hits its expiration according to the scaling, the citizens sentence is set to a spent conviction.

**Comment by jxckUK** [comment]
> So if there are already created penal codes that have a jail time set in years (10), this should have to be converted to the scale option in the CAD-Settings. With the scaled time, this would start counting until it has ended, then allow checkout from the jail?
> 
> For example:
> 
> 1. Penal code with "Jail Time: 10"
> 2. Cad-Settings: "Jail Time represented in "from years to minutes""[1](#user-content-fn-1-1e1309f226fd12a0b3bb4034c40283dd)
> 3. Some function: convert 10 years to 10 minutes
> 4. Automatically checkout the citizen from the jail.
> 
> ## Footnotes
> 1. Selection: "from years to minutes", "from years to seconds", more needed? [↩](#user-content-fnref-1-1e1309f226fd12a0b3bb4034c40283dd)

Yes exactly this - couldn't have summed it up better. I would say not to use the term "years" anywhere as I suspect people have used the jail time format freely as its something that wasn't set in stone. For example we use it to represent months. But the scaling system doesn't change either way because the scaling will be set in CAD settings.

Sounds like you have the concept nailed though! It'll be a really important feature for us.

**Comment by Dev-CasperTheGhost** [comment]
> I would say not to use the term "years" anywhere as I suspect people have used the jail time format freely as its something that wasn't set in stone.

I'd guess removing the "from years" will suffice?

**Comment by Dev-CasperTheGhost** [comment]
PS: something like this?

![image](https://user-images.githubusercontent.com/53900565/168216651-ab807039-e78e-4ded-b021-3316649f6206.png)

**Comment by jxckUK** [comment]
> > I would say not to use the term
> I'd guess removing the "from years" will suffice?

Yeah that works, preview looks good too 😄
