### ISSUE TITLE
[BUG] Wrong css style in dropdown navbar

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#701]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.0.0-beta.91

### Describe the Bug

On different css pages, the styles of the navbar dropdown menu are different. Adds an unnecessary border to the item

Example 1
![image](https://user-images.githubusercontent.com/4976837/165913960-57629440-5e8b-49ac-bbf5-6e7cc6d7e9fa.png)

Example 2
![image](https://user-images.githubusercontent.com/4976837/165914131-ea1b0116-d26c-4b0f-802b-3d3eff533441.png)

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
This is expected behaviour.

**Comment by pp2amd6** [comment]
> This is expected behaviour.

Is it ok to have different styles? Right?

![image](https://user-images.githubusercontent.com/4976837/165917040-4aa79a78-581e-4bef-a0d5-52dc5acff3a9.png)![image](https://user-images.githubusercontent.com/4976837/165917117-eabd2c08-0c36-4611-aae8-cefd337c2843.png)

**Comment by Dev-CasperTheGhost** [comment]
Yeah, it’s something for keyboard navigation
