### ISSUE TITLE
have callsign 2 optional

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#708]
### Describe the feature

its weird when i go to fill out my callsign and i have to put a space under callsign 2 because i dont have a second one. is there anyway to have callsign 2 optional because right now it's mandatory and i have to put a space to save my first callsign

**Comment by jxckUK** [comment]
Callsign formats work perfectly and adjusting this behaviour would have massive repercussions across I suspect most users deployments. What is your callsign? If it is for example A56 then your callsign format should be Callsign 1: A, Callsign 2: 56.

**Comment by subtosharki** [comment]
1-A-56

**Comment by Dev-CasperTheGhost** [comment]
You can always use the department/division's callsign symbol too.
