### ISSUE TITLE
more webhook features 

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#710]
### Describe the feature

have webhooks for when cars get impounded and citations get sent out, and if possible add variables in those text boxs like {discordId} so we can tag the user

**Comment by Dev-CasperTheGhost** [comment]
> citations get sent out

What should I sent in the webhook? I'm not sure if this is useful.

**Comment by subtosharki** [comment]
> What should I send in the webhook? I'm not sure if this is useful.

the cost, the infractions, the name, the time, and like i said being able to get the user id in the message to @ the user

**Comment by Dev-CasperTheGhost** [comment]
> like i said being able to get the user id in the message to @ the user

This won't be possible for every webhook message. Only for the citations.

**Comment by subtosharki** [comment]
> This won't be possible for every webhook message. Only for the citations.

thats fine👍

**Comment by subtosharki** [comment]
any update on this
