### ISSUE TITLE
rank and division discord role link

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#711]
### Describe the feature

this feature would let us link discord roles to officer ranks and divisions and then sync them on.

**Comment by Dev-CasperTheGhost** [comment]
This won't happen, same reason as discussed in #433 

> This was discussed in https://github.com/SnailyCAD/snaily-cadv4/issues/433, I’m not sure if this works well. Since the departments/divisions would be given to all officers that user has.
