### ISSUE TITLE
[BUG] Method /v1/leo/panic-button - Panic button create extra record if unit in pair

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#720]
### What version of Node.js are you using?

v16.11.0

### What version of npm are you using?

8.0.0

### What operating system are you using?

Ubuntu 20.04.4 LTS

### What version of SnailyCAD are you currently using?

v1.0.0-beta.93

### Describe the Bug

Panic button create extra record if unit in pair

We have pair unit
![image](https://user-images.githubusercontent.com/4976837/166165577-08812821-3815-427d-b0ee-5c13ec4f081f.png)

Call /v1/leo/panic-button method for your officer
![image](https://user-images.githubusercontent.com/4976837/166165729-719d8e2d-4bf7-411b-bfb9-c1b2a80a0cf0.png)

In addition, you cannot change the status for the current unit or disband a paired unit - the user will receive an error
```json
{
  "DEBUG": {
    "message": "Request failed with status code 400",
    "status": 400,
    "response": {
      "data": {
        "name": "BAD_REQUEST",
        "message": "officerIsCombined",
        "status": 400,
        "errors": []
      },
      "status": 400,
      "statusText": "Bad Request",
      "headers": {
        "content-length": "77",
        "content-type": "application/json; charset=utf-8"
      },
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
          "FormData": null
        },
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "Content-Type": "application/json",
          "Session": "snaily-cad-session=undefined",
          "is-from-dispatch": "false"
        },
        "url": "https://api.example.com/v1/dispatch/status/cl1y6rnn547818y5dm78eczvf",
        "method": "put",
        "data": "{\"status\":\"cae3e6df-43b4-4e07-a277-4a9428a93743\"}",
        "withCredentials": true
      },
      "request": {}
    },
    "method": "put",
    "data": "{\"status\":\"cae3e6df-43b4-4e07-a277-4a9428a93743\"}",
    "url": "https://api.example.com/v1/dispatch/status/cl1y6rnn547818y5dm78eczvf"
  }
}
```

### Expected Behavior

Panic button will be applied to a paired unit
![image](https://user-images.githubusercontent.com/4976837/166165632-070953ae-1d00-4f7f-89d5-34094b5b4073.png)

### To Reproduce

1. Merge with other unit
2. Call /v1/leo/panic-button method for your officer

**Comment by Dev-CasperTheGhost** [comment]
> Call /v1/leo/panic-button method for your officer

This is not really a bug. You will need to use the id for the combined unit instead of the officer id to enable the panic button for the combined unit.

> In addition, you cannot change the status for the current unit or disband a paired unit - the user will receive an error

this is expected behavior
