### ISSUE TITLE
Per Division Paired Unit Template

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#721]
### Describe the feature

Our paired unit template at the moment is TROJAN{incremental} which is a paired callsign for the firearms division. However because its a global paired template it means other units that are not firearms are also marked as TROJAN{incremental}.

The requested feature would allow us to set per division paired unit templates so that the unit merging will use a callsign format from their own division and not one they are not in.

Eg. Roads - RAPTOR{incremental}, Firearms TROJAN{incremental} etc.

**Comment by Dev-CasperTheGhost** [comment]
closes by #722
