### ISSUE TITLE
[IMPOROVEMENTS] API - Add ability to use direct image links

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#724]
### Describe the feature

When you create citizen through API, method allow imgur links only.

Support any direct link for images will be good feature.

For example, when I create citizen in FiveM I get photo of character and save photo in discord (get direct image link in discord).

**Comment by Dev-CasperTheGhost** [comment]
For security and privacy reasons, I don't think this should be added. You can simply upload the image to imgur instead of Discord.

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost 
Can you add exception mechanism, like add trusted hosts?
For variable reason I can register imgur account, but Discord works fine.
