### ISSUE TITLE
live map button

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#727]
### Describe the feature

can there be a live map button when you click officer like there is for dispatch

**Comment by Dev-CasperTheGhost** [comment]
Can you elaborate?

**Comment by subtosharki** [comment]
![image](https://user-images.githubusercontent.com/49736448/166607521-0eb7236b-1b0b-4f01-9329-ff83fe68a3e0.png)
![image](https://user-images.githubusercontent.com/49736448/166607985-633a6695-b3cd-4ff5-8b63-ab64fb8ce80d.png)

hopefully that helps

**Comment by Dev-CasperTheGhost** [comment]
I'm not sure how this is useful 😅! Seems quite redundant if it's in the Dispatch dropdown.
