### ISSUE TITLE
Adding custom roles

### ISSUE THREAD

**Issue by Shimeat** [SnailyCAD/snaily-cadv4#728]
### Describe the feature

Of course, a huge step towards advanced moderation of access levels for users was the detailed differentiation of access. However, manually granting separate access to a certain group of people each time through the settings panel is not very convenient. Therefore, I propose to create a separate system with roles that the administrator can create himself, give them names and corresponding icons. There is no need to say much about access control, the same privileges as in the detailed user settings item. Also, I would like to see a direct integration with the discord, which will allow you to associate roles on the server with roles in SnailyCAD. Oh yes, icons. I wouldn't mind seeing these icons next to the user character's initials, but would also give the option to disable this feature in the settings

**Comment by Dev-CasperTheGhost** [comment]
> Also, I would like to see a direct integration with the discord, which will allow you to associate roles on the server with roles in SnailyCAD.

This is already possible. You can select Discord roles for all the permissions in the CAD, for example: LEO, EMS/FD, Dispatch, Admin, tow and taxi

**Comment by Shimeat** [comment]
No, I didn't mean it. I would like to see integration with custom roles that are granularly configurable (like permissions on the user page)

**Comment by Dev-CasperTheGhost** [comment]
I like the idea of creating custom roles. I've started development on this feature, however I'm not sure if this will be implemented since there's a ton of complexity that will be added or have to get around. 

Will keep this issue updated whenever I have questions or would need some extra help.
