### ISSUE TITLE
Automatic Off Duty

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#731]
### Describe the feature

Can we add a feature to automatically make all Active Officers off duty at a certain time per day. In my case I would like to make them go off duty every 24 hours at 04:00am or something.

Because this...
![image](https://user-images.githubusercontent.com/25211271/166749350-20e056b3-13bd-4935-ae3b-e49eb67ce0b2.png)

THEY NEVER DO hahaha. They always forget.

**Comment by Dev-CasperTheGhost** [comment]
*Note to self: `lastStatusChangeTimestamp DateTime?` -> `.find({where:{ lastStatusChangeTimestamp : {ge: <time-here>}  }})`*

**Comment by Dev-CasperTheGhost** [comment]
There's currently an `Inactivity Filter` option within the misc cad settings. Would this be used for that, or should there be a separate option?

**Comment by ViolentMinds** [comment]
It should be separate.
Because thats more if someone is going to be inactive for a few weeks or something like on vacation.

**Comment by Dev-CasperTheGhost** [comment]
> It should be separate. Because thats more if someone is going to be inactive for a few weeks or something like on vacation.

What? Currently, it's used for inactive calls and incidents 😅! I think using the same property could be done?
