### ISSUE TITLE
Courthouse Improvements

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#732]
### Describe the feature

Could we add sections to the Courthouse section.

• Court Dates
(upcoming/past dates for court proceedings)
• Court Results
(for a list of outcomes/notes by the justice department for the outcome of cases to keep track)
• Court Notes
(other various notes of interest by the court system about a case such as more security needed for a hearing or high profile case)

**Comment by Dev-CasperTheGhost** [comment]
This would only be for expungement requests, or also for name change requests?

**Comment by Dev-CasperTheGhost** [comment]
@ViolentMinds I'm unsure where these would be added to, would this be added to the creation of an arrest report?

**Comment by ViolentMinds** [comment]
![image](https://user-images.githubusercontent.com/25211271/167222810-18de09c9-1746-4560-bdf8-a80653685689.png)


They can be added as new sections/new tabs here

**Comment by Dev-CasperTheGhost** [comment]
Can you elaborate as to what these would do? I'm not sure what you're trying to request.

**Comment by ViolentMinds** [comment]
These could be simple text fields. Like notes.
Kind of how the Penal Codes look like on the admin page.

Something for anyone to view with DOJ Access.

A simple text field with a Title and Text Box.

This is separate from Arrest Report. DOJ is not done by LEO. Its for the Judges and Lawyers to use to keep track of cases easier.

**Comment by Dev-CasperTheGhost** [comment]
Could these maybe be combined into 1 tab? I feel like this is a lot of "bloat" for some simple text fields.

I think it's better to combine these things into 1 field, so:

`title`, `case number`, `description`, `court dates`, `court results`. 

If needed, a filter can be added to find results easier?

**Comment by ViolentMinds** [comment]
Yes thats fine I suppose
