### ISSUE TITLE
[BUG] Citizens controller - Getting HTTP 500 error

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#739]
### What version of Node.js are you using?

v16.11.0

### What version of npm are you using?

8.0.0

### What operating system are you using?

Ubuntu 20.04.4 LTS

### What version of SnailyCAD are you currently using?

v1.0.0-beta.94

### Describe the Bug

Getting HTTP 500 error when "Common Citizen Cards" feature enabled and citizen was created through API (citizen don`t have userId). When I set userId for citizen, page was loaded.

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
What route is this? I'm unable to reproduce this error.

**Comment by pp2amd6** [comment]
> What route is this? I'm unable to reproduce this error.

/citizen

https://user-images.githubusercontent.com/4976837/167257653-b7e9b8cc-669e-4782-9d3d-e6b962c0f7c4.mp4

**Comment by Dev-CasperTheGhost** [comment]
ah, I actually fixed that this morning. Make sure to update the CAD :)
