### ISSUE TITLE
Add the option back from v3 to register cars that are not in the cad system 

### ISSUE THREAD

**Issue by Cobra-sm** [SnailyCAD/snaily-cadv4#741]
### Describe the feature

You would be able to add the addon vehicles to the cad system as a civ.

As this just makes it way to hard on servers that have over 400 vehicles and its a waste of time to manully put them in 

### Additional Context
![image](https://user-images.githubusercontent.com/105087188/167251991-48d635ae-b503-4bf1-b6d7-c3db1a398cac.png)

_No response_

**Comment by Dev-CasperTheGhost** [comment]
This is already possible, you can search for `Custom values` or similar in the features tab in cad settings
