### ISSUE TITLE
client port option not working

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#747]
### What version of Node.js are you using?

16.15.0

### What version of npm are you using?

8.9.0

### What operating system are you using?

windows 10

### What version of SnailyCAD are you currently using?

1.0.0-beta.96

### Describe the Bug

when putting thee client port in the cad it dosnt edit the json file to launch the client on the port specified. i can try and open a pr with a fix

### Expected Behavior

the client will launch on whatever port is deinfed in .env

### To Reproduce

run the build and watch the client package.json with the start node command not get edited to -p (port number)

**Comment by Dev-CasperTheGhost** [comment]
Sure, you can try fix it!

**Comment by Dev-CasperTheGhost** [comment]
hm, just tested this, and it works fine for me. It copies the port correctly over. What did you try to do?

**Comment by subtosharki** [comment]
https://github.com/SnailyCAD/snaily-cadv4/blob/main/scripts/copy-env.mjs#L15 why is this needed

**Comment by Dev-CasperTheGhost** [comment]
The linux file system works a bit differently.
