### ISSUE TITLE
Duplicated navigation tab

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#749]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

N/A

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

v1.0.0-beta.96

### Describe the Bug

As discussed in Discord there is a duplicate civilian logs tab.

### Expected Behavior

These should be in the same section or titled differently

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/167381415-5bb429ca-4cde-4374-82d9-b14beeed707e.png)

**Comment by Dev-CasperTheGhost** [comment]
Note to self: https://github.com/SnailyCAD/snaily-cadv4/blob/9bb79d51ab9857ee6ec1ff1b5c1140a2e6ad4c72/packages/client/src/pages/officer/supervisor/citizen-logs.tsx#L33
