### ISSUE TITLE
Can't Login To CAD After Todays Update to 1.0.0-beta.96 (2022-05-08)

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#751]
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

7.10.0

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

1.0.0-beta.96 (2022-05-08)

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/167452411-330a0de2-c190-4490-b1b4-aed5cfb400bc.png)

![image](https://user-images.githubusercontent.com/25211271/167452059-194d82da-bb89-4fc1-99a2-6867fd386af5.png)

![image](https://user-images.githubusercontent.com/25211271/167452648-3d11fb58-1d16-4b64-9cf5-59c51af18a56.png)

### Expected Behavior

To be able to login to cad

**Comment by Dev-CasperTheGhost** [comment]
Try update again. Should be fixed now?
