### ISSUE TITLE
The possibility if you are looking for a person, but it does not exist yet, to create it.

### ISSUE THREAD

**Issue by Justin2211** [SnailyCAD/snaily-cadv4#757]
### Describe the feature

I would like to have the function that if a police officer searches for a person under "Name Search", but this person does not yet exist, he can create the person himself.

The same with license plates.

Sincerely

**Comment by Dev-CasperTheGhost** [comment]
Would this citizen be linked to the authenticated user?

**Comment by Dev-CasperTheGhost** [comment]
> **posted by Justin: you can also add license plates as officers that do not yet exist, i.e. have not yet been created by a citizen.**

**Comment by Justin2211** [comment]
Yes, that's about it, you can make it an extra feature which only people who want to turn it on in the CAD settings.

But this is exactly how it should work and if the person created by the officer does log in, they can add the missing data of their person.

Sincerely

**Comment by Justin2211** [comment]
I have a question, could you make this function also for vehicles? Or is that planned?

I tried it with the people, it's perfect!

**Comment by Dev-CasperTheGhost** [comment]
> I have a question, could you make this function also for vehicles? Or is that planned?

Still planned

**Comment by Justin2211** [comment]
Oh okay, great, thanks a lot!

**Comment by Dev-CasperTheGhost** [comment]
should be implemented now! Enjoy!

**Comment by Justin2211** [comment]
Yes thank you, it works!
Now I would still wish that the button with create, is always displayed in the people / vehicle search, so that you can also create a person / vehicle, which is also called so or has a different first or last name.

Sincerely

**Comment by Justin2211** [comment]
Just great!
Now I would only wish that someone would not have to specify an owner when creating a vehicle.
So as an optional input.

Sincerely

**Comment by Dev-CasperTheGhost** [comment]
> Now I would only wish that someone would not have to specify an owner when creating a vehicle.
So as an optional input.

This isn't possible at the moment since the vehicle must have an owner. 

Please provide all your requests in one comment and not multiple next time.

**Comment by Justin2211** [comment]
> This isn't possible at the moment since the vehicle must have an owner.

Oh okay, no problem.

> Please provide all your requests in one comment and not multiple next time.

Yes I do, only unfortunately the last just occurred to me when testing.
What I did not know before

Sincerely
