### ISSUE TITLE
[BUG] Sorting does not apply the correct position

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#76]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### Describe the Bug

Sorting does not apply the correct position.
When dragging an element, it is assigned the index {current index} + 1 (- 1)

https://user-images.githubusercontent.com/4976837/139346252-160cb995-f3ff-4de9-8df6-6f4c3b95b780.mp4

### Expected Behavior

Correct position is applied when sorting

**Comment by Dev-CasperTheGhost** [comment]
@pp2amd6 are you able to verify if this is still an issue?

**Comment by pp2amd6** [comment]
Now all works fine. Thanks!
