### ISSUE TITLE
BOLO message in Plate Search

### ISSUE THREAD

**Issue by Justin2211** [SnailyCAD/snaily-cadv4#765]
### Describe the feature

When a vehicle is set as BOLO by the police, and a police officer searches for this license plate in "Plate Search", it is displayed that this vehicle is on the BOLO list, if he has not seen it before on the main page.

**Comment by Dev-CasperTheGhost** [comment]
Soon:tm:
![image](https://user-images.githubusercontent.com/53900565/168418340-8a0c64db-3892-43e7-9d34-6fb5498db590.png)

**Comment by Justin2211** [comment]
Okay great, thanks!
