### ISSUE TITLE
Page 403

### ISSUE THREAD

**Issue by KNA7022** [SnailyCAD/snaily-cadv4#767]
### What version of Node.js are you using?

v18.1.0

### What version of npm are you using?

8.8.0

### What operating system are you using?

windows10

### What version of SnailyCAD are you currently using?

1.0.0-beta98

### Describe the Bug

I can't open the CAD setting page and admin page. When I use other methods to enter the admin page, I can't set the value(vehicles, weapons, genders )

### Expected Behavior

I need to be able to manage levels, weapons, skin color, gender, etc. in CAD

### To Reproduce

https://user-images.githubusercontent.com/89156599/168421208-ce0cfeeb-46ed-4353-980e-aaa90f1a16a7.mp4

**Comment by Dev-CasperTheGhost** [comment]
ah, as stated in the documentation, you **cannot** use `localhost` for the CAD. You must use your WAN or LAN IP, or use a domain name. See here: https://cad-docs.caspertheghost.me/docs/installations/methods/standalone#accesing-snailycadv4
