### ISSUE TITLE
The possibility to add vehicle license plates and suspects entries, as well as to delete them.

### ISSUE THREAD

**Issue by Justin2211** [SnailyCAD/snaily-cadv4#771]
### Describe the feature

I would like very much that you can add license plates and suspects, entries (notes).
So no warning or so but only a note that then every officer can see and delete.

**Comment by Dev-CasperTheGhost** [comment]
so, the ability to add/edit/delete notes to a citizen or registered vehicle?

**Comment by Justin2211** [comment]
Exactly, that's what I mean.
And what I would like to add to my request of the day before yesterday is that you can also add license plates as officers that do not yet exist, i.e. have not yet been created by a citizen.
