### ISSUE TITLE
[BUG] Removing the Discord bot or moving it to another server removes permissions from all accounts, including owner.

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#774]
### What version of Node.js are you using?

NA

### What version of npm are you using?

NA

### What operating system are you using?

NA

### What version of SnailyCAD are you currently using?

1.0.0

### Describe the Bug

If you use the Discord role integration, and for some reason, you decided to remove the bot, or someone does it maliciously, and you are using a whitelisted CAD (or, at least I was when I discovered this) all accounts will be stuck in a pending state and will not be allowed to log in, even if they have a separate username and password for login. 

The only way (at least as far as I can see) is to reinstall the entire CAD.
![EFcqvy0VUAA3Jta](https://user-images.githubusercontent.com/34800953/168494597-69d3d6b7-0a4b-43a6-8f5a-094d0fbad609.jpg)

### Expected Behavior

To allow login even if the Discord bot is not present.

**Comment by Dev-CasperTheGhost** [comment]
> The only way (at least as far as I can see) is to reinstall the entire CAD.

You could have turned off the Discord features in the .env file. Simply remove the DISCORD_... stuff. I'll take a look this afternoon so this doesn't happen again
