### ISSUE TITLE
Temporary password function window overlaps

### ISSUE THREAD

**Issue by Justin2211** [SnailyCAD/snaily-cadv4#776]
### What version of Node.js are you using?

Unknown

### What operating system are you using?

Linux Debian 10

### What version of SnailyCAD are you currently using?

1.1.0 (2022-05-15) newest main branch

### Describe the Bug

When I want to give a temporary password to a certain user and press: "yes, continue", this window does not close and the new window where the temporary password is displayed is under there so you can't see it.

### Expected Behavior

-

**Comment by Dev-CasperTheGhost** [comment]
ah, this was caused by #769. This is weird, will fix this soon!
