### ISSUE TITLE
Possibility to play a specific sound for each status

### ISSUE THREAD

**Issue by Justin2211** [SnailyCAD/snaily-cadv4#782]
### Describe the feature

I would wish for the future, that you can upload and play a user specific sound for each status (ten-code).

So exactly what there is now already with the tones but just that you can play for each code an extra sound.

Sincerely

![image](https://user-images.githubusercontent.com/36715641/168808858-a0dde3d2-7d6c-49a3-a473-9a34a1a04c75.png)

**Comment by Dev-CasperTheGhost** [comment]
Due to complexity this won't be very easily possible. Maybe in the future this could be implemented.
