### ISSUE TITLE
Modal scroll on laptop does not work

### ISSUE THREAD

**Issue by Justin2211** [SnailyCAD/snaily-cadv4#783]
### What version of Node.js are you using?

Unknown

### What operating system are you using?

Linux Debian 10

### What version of SnailyCAD are you currently using?

1.2.1-2b8f4f0

### Describe the Bug

When I open the CAD on a laptop, and the page does not quite fit on the display so I can scroll, but when I open a modal e.g. the name search modal I cannot scroll it up further so I cannot see the modal below.

I don't have a mouse connected, and there is no scroll bar in the modal window.

What would be the best option?

### Expected Behavior

-

**Comment by Dev-CasperTheGhost** [comment]
Are you able to provide a screenshot or a video for this?

**Comment by Dev-CasperTheGhost** [comment]
What browser are you using?

**Comment by Justin2211** [comment]
Microsoft Edge

**Comment by Dev-CasperTheGhost** [comment]
I'm still unable to reproduce this in any browser. Are you able to provide a visual reproduction so I can maybe watch what's wrong?

**Comment by Dev-CasperTheGhost** [comment]
There's a scrollbar: 
![image](https://user-images.githubusercontent.com/53900565/169045935-b6f65fe8-e007-4365-9a3d-c186b08dedf1.png)

**Comment by Justin2211** [comment]
Yes but this is for the main page and not for the modal

As soon as I click on this the modal closes.

**Comment by Justin2211** [comment]
What would be the best solution?

Sincerely

**Comment by Dev-CasperTheGhost** [comment]
Does this only happen for the name search

**Comment by Justin2211** [comment]
This is not a bug, it is simply the case when the browser window is smaller than the page.

So you would have to somehow make it so that you either have another scroll bar in the modal or that you can scroll with the current scroll bar also the modal without that it closes.
