### ISSUE TITLE
Ability to mark someone as Deceased/Dead

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#784]
### Describe the feature

Add ability to mark person as deceased to this page.

![image](https://user-images.githubusercontent.com/25211271/168929147-75e4a565-be54-48ee-88f2-b03f130fa635.png)

**Comment by Dev-CasperTheGhost** [comment]
Ems/fd is already able to do this, leo can have this functionality too?

**Comment by ViolentMinds** [comment]
Yes, please. Because sometimes FD/EMS are not available and we have some LEO they are Coroner/Medical Examiner sometimes
