### ISSUE TITLE
Allow additional callsigns

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#785]
### Describe the feature

Some of our officers use different callsigns when they run as different divisions and with the callsign management stuff it has become quite essential for some units to reserve additional callsigns (sometimes up to two or three) so they can switch between them.

Is it possible to add an optional mechanism for this?

**Comment by Dev-CasperTheGhost** [comment]
So the ability for officers to save different callsigns for individual divisions?

Something like in the graph below?

```mermaid
  graph TD;
      OFFICER-->DefaultCallsign;
      OFFICER-->Division1-->Callsign1;
      OFFICER-->Division2-->Callsign2;
      OFFICER-->Division3-->Callsign3;
```

**Comment by jxckUK** [comment]
> So the ability for officers to save different callsigns for individual divisions?
> 
> Something like in the graph below?

This is absolutely spot on, exactly what I mean yes. Officers in our set up often have multiple divisions with separate callsigns and with the new callsign management I need a way of managing each of their callsigns not just primary/default.

**Comment by Dev-CasperTheGhost** [comment]
> When creating an officer, they can add their own extra callsigns

oh, that was a question @jxckUK haha

**Comment by Dev-CasperTheGhost** [comment]
No worries. Something like "advanced settings" would work?

![image](https://user-images.githubusercontent.com/53900565/169074080-68c0fc1f-fdaf-4d86-9b2a-50a14e818b96.png)

**Comment by Dev-CasperTheGhost** [comment]
![image](https://user-images.githubusercontent.com/53900565/169078349-2aa5cefb-ffbb-4ab9-bf83-d27e581cc5c4.png)

**Comment by Dev-CasperTheGhost** [comment]
>  Just had a thought, will this be manageable through the callsigns admin section? 😄

yep! First doing this on the my-officers side

**Comment by Dev-CasperTheGhost** [comment]
How would the officer be able to set the wanted division? How should this be handled in the UI?

**Comment by jxckUK** [comment]
> How would the officer be able to set the wanted division? How should this be handled in the UI?

Somehow for each division the user adds they should get an additional section to set a callsign for that division?

They'd be able to do this in the my officer section I would expect.

**Comment by Dev-CasperTheGhost** [comment]
No, I mean, how would the callsign be changed from the default to another one saved of the officer?

**Comment by jxckUK** [comment]
> No, I mean, how would the callsign be changed from the default to another one saved of the officer? 

Well I personally would leverage the API if that's possible so that when they select in game a division they will switch to that callsign? 

In terms of the CAD web interface I'm not sure to be honest.

**Comment by Dev-CasperTheGhost** [comment]
> An idea: If the officer has multiple callsigns, add a button at the top of the officer dashboard that says "Switch Callsigns" and it would open a Modal of all callsigns available to the officer. If they don't have any other callsigns, don't show the button at all.

Yeah, I'll probably do this. Would the callsign go back to the default one if the officer goes off-duty, or would it stay consistent between off-duties and on-duties?

**Comment by jxckUK** [comment]
> Yeah, I'll probably do this. Would the callsign go back to the default one if the officer goes off-duty, or would it stay consistent between off-duties and on-duties?

Consistent would be nice!

**Comment by Dev-CasperTheGhost** [comment]
whoops, posted a comment in the wrong issue: 

> Something like this could work? Some small fixes to do though!

> https://user-images.githubusercontent.com/53900565/169327053-14394343-b1d1-480c-afda-7864749c5ac9.mov
