### ISSUE TITLE
Officer Ranks per Deparment

### ISSUE THREAD

**Issue by Thomaswill1** [SnailyCAD/snaily-cadv4#788]
### Describe the feature

It doesn't really make sense in a realistic way to have City, County, and State police, plus Fire and Medical, to use the same ranks. It also looks clunky and weird to add all ranks and use it that way. This would allow the ability to add ranks per department instead of CAD-wide, so if you were managing a unit in a department, you'd only see that department's ranks, and not others.

**Comment by Dev-CasperTheGhost** [comment]
So, allow admins to connect departments to a rank? 

Something like this: 
![image](https://user-images.githubusercontent.com/53900565/169118856-2497066c-47f7-4960-8aa7-571bc88b7737.png)

**Comment by Thomaswill1** [comment]
Yes, that's it

**Comment by Dev-CasperTheGhost** [comment]
just to verify, **multiple** departments can be connected to **1 rank**
