### ISSUE TITLE
Manage Courthouse Link Bug

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#797]
### What version of Node.js are you using?

17.3.0

### What version of npm are you using?

7.10.0

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

1.4.0

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/169657774-54682f08-48e6-4b73-abef-b2cfa250c818.png)

### Expected Behavior

To be able to see Manage Courthouse page

**Comment by Dev-CasperTheGhost** [comment]
I'm unable to reproduce this error. When does this occur?

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed now actually!
