### ISSUE TITLE
Account char length

### ISSUE THREAD

**Issue by nick-perry14** [SnailyCAD/snaily-cadv4#799]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Ubuntu Server

### What version of SnailyCAD are you currently using?

Up to date with repository.

### Describe the Bug

Users are able to create 1-2 char length accounts, but are unable to log in with them.

### Expected Behavior

Prevent accounts of length 1-2 from being created.

**Comment by Dev-CasperTheGhost** [comment]
Weird. They use the same schema. Could this be if the user first registered with Discord, then set a password?
