### ISSUE TITLE
[New Feature Customizable Call Types , EMS Response Codes , Scene Safety , Custom Reports in PDF Format Much More

### ISSUE THREAD

**Issue by smahoney98** [SnailyCAD/snaily-cadv4#801]
Hello, I am new to your CAD / MDT System 
I would love to see the ability to when you create a 911 call you have where you can put your own Call Type For Example 
Create 911 Call 
Name                                        instead of Name, Location, Caller info 
Call Type 
Postal 
Location 
Caller Info 

I Would love to see this be an option where you can turn it on or off in the Admin Panel EMS Response Codes 
this is used irl and should be an option for example for each code for different responses
Alpha = Basic Ems Call No Running Lights or Sirens 
Bravo = Minor Ems Call Like Sick Case, etc 
Charlie =Medim Ems Calls Code 2 Lights Sirens Only Through Intersections 
Delta = Major EMS Calls  Code 3 Lights and Sirens Like Overdoses, Suicidal Subject, Breathing Problems, Chest Pain, Etc.
Echo = Extreme Life / Death EMS Calls Code 3  Lights and Sirens Like Cardiac Arrest, Not Breathing / Unconscious, Etc.
NO Code = Response Descetion Response Code 1 , Code 2, Code 3, Person Sick, Lift Assist, Fall, etc 

I Would love to see this be an option where you can turn it on or off in the Admin Panel Scene Safety 
Depending on the call = Scene Safety 
For Example, this is for the Fire / EMS 
Suicidal Subject Armed With A Knife = Scene Not Secured Meaning Law Enforcement is Needed and Fire/ Ems Units needs to Stage Until the Scene is Safe .
Suicidal Subject not armed just staying they are Suicidal = Scene Secured Fire / EMS can go to the call Law Enforcement would go anyway .

I would like to see where your able to upload PDF Actual Realistic Police Reports Like IRL Example, Accident Report, Incident Report, Supplemental Report Etc.

I Would love to see this be an option where you can turn it on or off in the Admin Panel 
And have This For Fire / EMS Side 
Instead Of 10-8 Etc Have Option where you have 
Available In Quarters 
Available 
En - Route 
Arrived 
Staging 
Out Of Service 
Transporting To Hospital 
At Hospital 
 I Hope to see these Features in the future and hope you enjoy and other enjoy my ideas all these ideas came from IRL what I see and hear I am a Support Staff Volunteer Firefighter IRL .

**Comment by Dev-CasperTheGhost** [comment]
> I Would love to see this be an option where you can turn it on or off in the Admin Panel
And have This For Fire / EMS Side
Instead Of 10-8 Etc Have Option where you have
Available In Quarters
Available
En - Route
Arrived
Staging
Out Of Service
Transporting To Hospital
At Hospital

You can already do this. Instead of creating codes with `10-8`, etc. You can create codes with `On duty`, `available` etc.

**Comment by Dev-CasperTheGhost** [comment]
> I Would love to see this be an option where you can turn it on or off in the Admin Panel EMS Response Codes
this is used irl and should be an option for example for each code for different responses
Alpha = Basic Ems Call No Running Lights or Sirens
Bravo = Minor Ems Call Like Sick Case, etc
Charlie =Medim Ems Calls Code 2 Lights Sirens Only Through Intersections
Delta = Major EMS Calls Code 3 Lights and Sirens Like Overdoses, Suicidal Subject, Breathing Problems, Chest Pain, Etc.
Echo = Extreme Life / Death EMS Calls Code 3 Lights and Sirens Like Cardiac Arrest, Not Breathing / Unconscious, Etc.
NO Code = Response Descetion Response Code 1 , Code 2, Code 3, Person Sick, Lift Assist, Fall, etc

I'm not sure what you mean here. Can you elaborate or provide an example?

**Comment by smahoney98** [comment]
so like a button or a Text that's color-coded
for example 
![download (2)](https://user-images.githubusercontent.com/53837967/170185218-47fc00d6-4cc0-4b60-b85a-beeb349eefa9.png)

**Comment by Dev-CasperTheGhost** [comment]
> so like a button or a Text that's color-coded
> for example

Right, but how would this be presented in SnailyCAD?

**Comment by Dev-CasperTheGhost** [comment]
call types have been added!

**Comment by Dev-CasperTheGhost** [comment]
> > so like a button or a Text that's color-coded
> > for example
> 
> Right, but how would this be presented in SnailyCAD?

@smahoney98 any news?

**Comment by Dev-CasperTheGhost** [comment]
Unfortunately, I'm unable to understand some of the other requested features, or are unrealistic to add on my own right now. If you're able to clarify, feel free to re-open this issue.
