### ISSUE TITLE
Still cannot click on Manage Courthouse 

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#804]
### What version of Node.js are you using?

17.3.0

### What version of npm are you using?

7.10.0

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

1.4.3

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/170280206-9007b74a-30d3-4253-87c7-f35d0cf29463.png)

Still have the error when clicking on Manage Courthouse

### Expected Behavior

To be able to go to Manage Courthouse page

**Comment by Dev-CasperTheGhost** [comment]
I'm unable to reproduce this error. Try rebuild the client and make sure your translated JSON files aren't corrupted.
