### ISSUE TITLE
Updating, Error

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#806]
### What version of Node.js are you using?

17.3.0

### What version of npm are you using?

7.10.0

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

1.4.3

### Describe the Bug

I'm trying to manually update.
I had to delete my next-js file or whatever it was for the locales. As well as my locales folders.
Since I believe they were corrupt.

But when I'm trying to update, I was hoping it would download the new files and just place them in there. But upon manually updating I'm getting this error and I'm not sure how to fix it.

![image](https://user-images.githubusercontent.com/25211271/170317344-67e5be7f-fd66-4e2b-971c-af901b761ac7.png)
![image](https://user-images.githubusercontent.com/25211271/170317384-668572f5-69e0-47bb-b95a-bb7b1faadf0d.png)

### Expected Behavior

To be able to update properly.

**Comment by ViolentMinds** [comment]
Seems to still do it. I'm not sure whats going on, honestly. And I still cannot get the Courthouse link to work in the Admin Panel. Its so weird.

**Comment by Dev-CasperTheGhost** [comment]
> Seems to still do it. I'm not sure whats going on, honestly.

Are you still getting the error above, when updating?

**Comment by ViolentMinds** [comment]
> > Seems to still do it. I'm not sure whats going on, honestly.
> 
> Are you still getting the error above, when updating?

Yes its still happening just tried updating to the 1.6.0

![image](https://user-images.githubusercontent.com/25211271/170821309-2306a50e-3884-4a33-9aff-ced817032a92.png)

**Comment by Dev-CasperTheGhost** [comment]
Try manually updating.

**Comment by ViolentMinds** [comment]
Trying now 
![image](https://user-images.githubusercontent.com/25211271/170821782-aedbbd11-9e5e-4d61-ac5a-cdd2511bfc83.png)

**Comment by ViolentMinds** [comment]
![image](https://user-images.githubusercontent.com/25211271/170821801-a222723a-8c38-4e0c-8039-28d7df985f80.png)

**Comment by Dev-CasperTheGhost** [comment]
Can you send me a screenshot of the full path where those files are located at?

**Comment by ViolentMinds** [comment]
I ended up replacing the locale files manually from downloading the zip. So those are probably fine now but the telemetry folder looking for the .env error still shows 

![image](https://user-images.githubusercontent.com/25211271/170822574-7628c2e8-b535-4645-bece-5b694d5ad603.png)
![image](https://user-images.githubusercontent.com/25211271/170822604-2d07fe9c-d10e-49b7-829a-e2d74701ba11.png)

**Comment by Dev-CasperTheGhost** [comment]
That's fine. You can ignore that warning

**Comment by ViolentMinds** [comment]
Sound good, we can close this now. Also courthouse link is now fixed since I reset my locals to vanilla. Thank you.
