### ISSUE TITLE
[FEATURE REQUEST] Active dispatch mode

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#81]
### Describe the feature

Implement the dispatcher's on-duty mode.

If the dispatcher is not on-duty, then the data controls on the dispatcher page are inactive.
![kiss_31kb 1635534735 1](https://user-images.githubusercontent.com/4976837/139496852-12c19607-8762-4f56-b23c-96e30d6dc2af.png)

Also, if the dispatcher is off-duty, data controls become active on the police and fire department page, for example, the button to assign to 911 call (#79) or create an tow call (#78).

When the dispatcher on-duty, the data controls on the dispatcher page become active. Data controls become inactive on the police and fire department page.

On the page of the police and fire department, the status of the despatcher's activity is displayed.

Dispatcher is offline
![kiss_27kb 1635538293 1](https://user-images.githubusercontent.com/4976837/139497333-667b2760-85a2-4a01-96e2-bc20ce622377.png)

Dispatcher is online
![kiss_27kb 1635538352 1](https://user-images.githubusercontent.com/4976837/139497347-6d01834e-b830-4a76-b6d4-2445f84cd691.png)

**Comment by Dev-CasperTheGhost** [comment]
> Data controls become inactive on the police and fire department page.

@pp2amd6 what sort of data controls would become inactive?

**Comment by pp2amd6** [comment]
> > Data controls become inactive on the police and fire department page.
> 
> @pp2amd6 what sort of data controls would become inactive?

1. button for create 911 call
2. button to assign to 911 call
3. create an tow call

@Dev-CasperTheGhost can you check is dispatch online? For example: dispatch internet connection is down and LEO controls will be inactive. This is unacceptable

If this cannot be checked, then the request can be closed

**Comment by Dev-CasperTheGhost** [comment]
> @Dev-CasperTheGhost can you check is dispatch online? For example: dispatch internet connection is down and LEO controls will be inactive. This is unacceptable

This should be possible yes
