### ISSUE TITLE
Issue Caused CAD To Disconnect From DB

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#810]
### What version of Node.js are you using?

17.3.0

### What version of npm are you using?

7.10.0

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

1.5.0

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/170613745-98218c8e-9c87-4008-b44b-37ee394f7b1d.png)

This issue caused the CAD to disconnect from the DB. First time ever seeing it.

### Expected Behavior

It looks like someone tried to set all units inactive?

**Comment by Dev-CasperTheGhost** [comment]
If this only happens once, I think this can be ignored for now. Seems like I cannot do anything about this error.
