### ISSUE TITLE
Bug when entering bolo

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#812]
### What version of Node.js are you using?

N/A

### What version of npm are you using?

N/A

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

v1.3.0 161fe31

### Describe the Bug

When creating a bolo the user receives the following error:

![image](https://user-images.githubusercontent.com/48030374/170783279-45e84891-72e2-4c45-8535-c7135e7ba216.png)

![image](https://user-images.githubusercontent.com/48030374/170783290-89c9c566-e255-4990-a924-71e91acff2b3.png)

### Expected Behavior

N/A - Bug, this should not create an error.

**Comment by Dev-CasperTheGhost** [comment]
seems to work fine on 1.5.0. Can you try update to the latest version and see if it works?

**Comment by Dev-CasperTheGhost** [comment]
Seems like I was able to reproduce with a combined unit.
