### ISSUE TITLE
Panic button in LEO menu does not output Discord Webhook message

### ISSUE THREAD

**Issue by Justin2211** [SnailyCAD/snaily-cadv4#815]
### What version of Node.js are you using?

Unknown

### What version of npm are you using?

Unknown

### What operating system are you using?

Linux Debian 10

### What version of SnailyCAD are you currently using?

1.6.0 (2022-05-28)

### Describe the Bug

I have Discord webhooks set up but unfortunately the panic button webhook is not working.
I have tried several times to reset this webhook but every time I press the button, Panic is triggered in CAD but nothing happens in Discord and no message is displayed (in Discord).

### Expected Behavior

.

**Comment by Dev-CasperTheGhost** [comment]
1. Are you able to verify your bot has manage channels, manage webhooks and manage roles permissions?
2. Are you able to verify the webhook was created for the correct channel?

**Comment by Dev-CasperTheGhost** [comment]
PS: are you able to verify you're on the latest version by checking the login page like below:
![image](https://user-images.githubusercontent.com/53900565/170822428-ee7bd51e-3dcb-46b0-bec5-6c947f763687.png)

**Comment by Justin2211** [comment]
> PS: are you able to verify you're on the latest version by checking the login page like below: ![image](https://user-images.githubusercontent.com/53900565/170822428-ee7bd51e-3dcb-46b0-bec5-6c947f763687.png)

Hello, yes exactly I can confirm, I am on the latest version

**Comment by Justin2211** [comment]
> 1. bhooks and manage

Yes I have reconnected the bot again with all the permissions needed, all the webhooks are working only the panic webhook is not.

**Comment by Dev-CasperTheGhost** [comment]
Note to self: check discord’s webhook limitations for a channel.

**Comment by Dev-CasperTheGhost** [comment]
I'm unable to reproduce this error. Can you update the very latest version, then try again.

**Comment by Justin2211** [comment]
Hello, I have already installed the latest update 1 or 2 hours ago

![image](https://user-images.githubusercontent.com/36715641/170878821-6ba1eeb3-4137-4655-8a4b-bdd782452d45.png)

**Comment by Justin2211** [comment]
For example, if I change my status in CAD to 10-08 or 10-07, this is also displayed in the Status Update Discord Channel, but nothing happens with the Panic button except that the Panic Message is displayed in CAD and the noise comes.

**Comment by Justin2211** [comment]
Are there any changes?
In the meantime, do you know what the problem might be?

I have set up the application and the bot again on the Discord Developer site, but only the Panic button does not work again.

**Comment by Justin2211** [comment]
I would be interested to know if the Discord webhook for the panic button works for others.

**Comment by Dev-CasperTheGhost** [comment]
Do you have an extra message set for the panic button?

**Comment by Justin2211** [comment]
No, what do you mean exactly?

**Comment by Justin2211** [comment]
No, I have looked, I have not

**Comment by Justin2211** [comment]
Good evening, unfortunately it does not work even after the last commit

**Comment by Justin2211** [comment]
That was meant for that, wasn't it?
