### ISSUE TITLE
[BUG] Dispatch - 911 calls block not updated after call end

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#816]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.5.0 1a2b3fb

### Describe the Bug

When you end 911 active call data block not updated, call still present till you press F5

### Expected Behavior

Data should be refreshed automatically.

**Comment by Dev-CasperTheGhost** [comment]
I'm unable to reproduce this error. Are you able to provide a video example for this?

**Comment by pp2amd6** [comment]
> I'm unable to reproduce this error. Are you able to provide a video example for this?

After rebuild CAD, I can't reproduce problem ¯\_(ツ)_/¯
