### ISSUE TITLE
[BUG] Assign to call not change unit status

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#817]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.5.0 1a2b3fb

### Describe the Bug

When I assign to 911 call, status of unit changed.

For example: I have tencode with "Set assigned" action. When I press "Assign to call" button, code with "Set assigned" action should be applied to my active unit.

This feature worked before.

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
Try refresh the page and make sure that there's an active connection to the socket. Are you able to verify it works after a page refresh?

**Comment by pp2amd6** [comment]
> Are you able to verify it works after a page refresh?

No, status not changed after page refresh.
