### ISSUE TITLE
Weapon's License Exam

### ISSUE THREAD

**Issue by SunlightKim** [SnailyCAD/snaily-cadv4#822]
### Describe the feature

Just like the title says, it would be very nice to have a "Weapon's License Exam", similar to the "Driver's License Exam"... but for weapons haha ^^

**Comment by Dev-CasperTheGhost** [comment]
Would it be best to create a new page for weapon license exams, or have a `type` property within the current exams feature, then rename the feature from "Drivers license exam" to "License Exams"?

What do you think of this?

**Comment by SunlightKim** [comment]
> Would it be best to create a new page for weapon license exams, or have a `type` property within the current exams feature, then rename the feature from "Drivers license exam" to "License Exams"?
> 
> What do you think of this?

hmm.. well i think the first option (creating a new page) would be better, because we don't necessarily want to activate the Drivers License Exam but only the Weapons License Exam. Unless it's possible to put everything in one page, but give the ability to activate either the drivers exam, the weapons exam or both.
I hope you understand what i mean

**Comment by Dev-CasperTheGhost** [comment]
ah yeah, fair enough! Will probably create a different page then.

**Comment by SunlightKim** [comment]
> ah yeah, fair enough! Will probably create a different page then.

yup, sounds good! Thanks for being so open to suggestions ^^

**Comment by Sampuke** [comment]
Could It also be made so police can lock the exams so criminals can't do them

**Comment by SunlightKim** [comment]
> Could It also be made so police can lock the exams for some people, so criminals can't do them

Oh yeah! Or at least give them the ability to revoke WL and block them for passing exams or some kind of BOLO like "This citizen is flagged as a (potential) criminal."
