### ISSUE TITLE
more sounds something like sonoran cad

### ISSUE THREAD

**Issue by Sampuke** [SnailyCAD/snaily-cadv4#823]
### Describe the feature

more sounds for lets say someone has a warant and he is serched  it woul say that the person has warants,
also a app wich would let you use global keybinds would be usefull. Also that would be cool if the cad could like grap the IDs and stuff from MySQL so everyone wouldn't to make characters in the cad
and also more 10 codes to choose from

**Comment by Dev-CasperTheGhost** [comment]
merging this issue with #590
