### ISSUE TITLE
Major Bug! Entire Civilian List Showing To Everyone!

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#824]
### What version of Node.js are you using?

17.3.0

### What version of npm are you using?

7.10.0

### What operating system are you using?

Windows 10

### What version of SnailyCAD are you currently using?

1.6.1

### Describe the Bug

When anyone in the CAD logs in, it takes them to this ADMIN page! Major problem not sure how it happened!
I've even done a manual update from 1.6.0 to 1.6.1 and its still doing it!

![image](https://user-images.githubusercontent.com/25211271/171087312-f2303feb-74bb-44fa-9dd2-68161d7084fd.png)

### Expected Behavior

Normal Function

**Comment by Dev-CasperTheGhost** [comment]
This is expected behaviour. See #60
