### ISSUE TITLE
[Feature] FD/EMS ability to add medical records to Citizens

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#825]
### Describe the feature

Could we have a feature to allow the EMS/FD members to add Medical Records to Citizens? Thank you!

**Comment by Dev-CasperTheGhost** [comment]
This is already possible 😅!

![image](https://user-images.githubusercontent.com/53900565/171095416-0a3b8127-9371-4fdf-b8fc-6126696fde1a.png)
