### ISSUE TITLE
FD/EMS Cannot Go On Duty

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#826]
### What version of Node.js are you using?

17.3.0

### What version of npm are you using?

7.10.0

### What operating system are you using?

Windows 10

### What version of SnailyCAD are you currently using?

1.6.1

### Describe the Bug

I cannot get any of my FD Members to go on duty. There are no error codes either. Everything is selected as normal. Proper FD Deputy and everything. I'm not sure what to do :o any ideas?

### Expected Behavior

To be able to go on duty as FD Deputy

**Comment by Dev-CasperTheGhost** [comment]
Try refresh the page

**Comment by ViolentMinds** [comment]
![image](https://user-images.githubusercontent.com/25211271/171098563-997764ef-0f68-463c-ba76-e702e0602003.png)


I've tried even reinstalled and updated. Also the only thing that comes up in console is this.

But roleplay is not stopped.

LEO can go on duty just fine. Its only FD/EMS who cannot

**Comment by Dev-CasperTheGhost** [comment]
Will take a look once I can, later today

**Comment by Sampuke** [comment]
atleast for me its working

**Comment by ViolentMinds** [comment]
The only thing that happens is what I mentioned nothing much to record I simply click the on duty button and nothing happens for FIRE/EMS deputies. Not sure why. :(

**Comment by ViolentMinds** [comment]
More information from console

![image](https://user-images.githubusercontent.com/25211271/171293180-48a7e63c-474e-474e-8f1f-846056a785bc.png)
