### ISSUE TITLE
Ability to delete used values

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#837]
### Describe the feature

At the moment any linked value records can't be removed, sometimes this is problematic as there is no mechanism to remove associated records.

Please can we add the ability to delete linked values either by removing the linked values or having a mechanism that redirects removed values etc.

**Comment by Dev-CasperTheGhost** [comment]
I'm not sure if this possible, since this would require me to set everything possibly nullable, which can have not so great consequences.

> Please can we add the ability to delete linked values either by removing the linked values or having a mechanism that redirects removed values etc.

What exactly do you mean here?

**Comment by jxckUK** [comment]
> I'm not sure if this possible, since this would require me to set everything possibly nullable, which can have not so great consequences.
> 
> 
> 
> > Please can we add the ability to delete linked values either by removing the linked values or having a mechanism that redirects removed values etc.
> 
> 
> 
> What exactly do you mean here?

We have some charges that are no longer applicable but have been used previously and they now cannot be removed. I guess that's the problem statement.

Rather than making them null can it keep the value it has but instead of pointing to an existing value it could point to a text value that says "redacted" or something vague and generic.

**Comment by Dev-CasperTheGhost** [comment]
Will see what I can do!

**Comment by Dev-CasperTheGhost** [comment]
Seems like this is nearly impossible to implement with the current API. I'm unable to check if there are values used by other values until the error is thrown. But then, I'm also unable to take the error message from that error. 

Maybe for now, you could manually call the value "[redacted]"?

**Comment by jxckUK** [comment]
> Seems like this is nearly impossible to implement with the current API. I'm unable to check if there are values used by other values until the error is thrown. But then, I'm also unable to take the error message from that error.
> 
> Maybe for now, you could manually call the value "[redacted]"?

I have another idea! Could we make it so we can mark value groups as hidden? So for example, I can chuck all the old charges into a group and that group doesn't show anywhere in the CAD except the admin section and the old records? So noone can use them moving forward?
