### ISSUE TITLE
Updating Errors

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#838]
### What version of Node.js are you using?

17.3.0

### What version of npm are you using?

7.10.0

### What operating system are you using?

Windows 10

### What version of SnailyCAD are you currently using?

1.6.1

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/171292388-7c69287a-25cf-49fe-9627-4257dfe8b865.png)

Everytime I try to update I get these errors lately. I haven't even touched the en_gb folder. Its default. Not sure why this keeps happening.

### Expected Behavior

To be able to update cleanly.

**Comment by Dev-CasperTheGhost** [comment]
Please use Discord for this kind of error, this isn’t a bug. Backup your changed files then run `git stash`, then re-run the update process
