### ISSUE TITLE
shootting notifications

### ISSUE THREAD

**Issue by Sampuke** [SnailyCAD/snaily-cadv4#839]
### Describe the feature

Could it be bossible that police / dispach would get like 911 calls fir shooting and stuff something like this https://github.com/thelindat/linden_outlawalert

**Comment by Dev-CasperTheGhost** [comment]
This would be a notification alert?

**Comment by Sampuke** [comment]
i think it would work like the 911 allerts

**Comment by Dev-CasperTheGhost** [comment]
What’s the point of this feature then 😅?

**Comment by Dev-CasperTheGhost** [comment]
I’m not sure what you trying to request. Would this be something in FiveM?

**Comment by Sampuke** [comment]
it would be like the "/call911" script it would send a 911 call to the cad and officers would be able to get the postal and stuff from the cad

**Comment by Dev-CasperTheGhost** [comment]
Like said in a previous feature request, I won’t really be making more FiveM addons since I don’t have the expertise
