### ISSUE TITLE
ForceReg

### ISSUE THREAD

**Issue by Sampuke** [SnailyCAD/snaily-cadv4#840]
### Describe the feature

Forces players to register to the cad before playing by freezing or kicking maybe
also something that would kick ems/police... if they leave the server. must be something that can be turned off because owners may need to use police or ems stuff.
something that would maybe send new 911 calls/missions to police ingame like sonoran cad has with their smart radio.
something like "/trafficstop" for police wich would start a new call for the stop so policve don't get called to other things.

**Comment by Dev-CasperTheGhost** [comment]
This could be achieved using the API. See documentation for public api usage
