### ISSUE TITLE
CAD Shut Down On Its Own

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#858]
### What version of Node.js are you using?

17.3.0

### What version of npm are you using?

7.10.0

### What operating system are you using?

Windows 10

### What version of SnailyCAD are you currently using?

1.6.1

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/171613060-c1fb74d5-20ff-448f-ac61-ba0917a2a1d4.png)

This apparently happened in the middle of the night when I was sleeping. No clue why so I wanted to report it.

### Expected Behavior

Normal operations. They ceased.

**Comment by Dev-CasperTheGhost** [comment]
This seemed to have happend before. I cannot really do anything about this error unfortunately. Try increase max connections allowed to the database
