### ISSUE TITLE
ui creator

### ISSUE THREAD

**Issue by Sampuke** [SnailyCAD/snaily-cadv4#868]
### Describe the feature

it would be nice to have a way to customize the cad:s ui with somekind of app maybe you could change the button places and stuff

**Comment by Dev-CasperTheGhost** [comment]
This is pretty much impossible for a one-man maintainer. Probably will not happen in the near future.

**Comment by Sampuke** [comment]
i thouhg that would be the case if it were to hapen it doesnt need to be a app html would be nice too

**Comment by Dev-CasperTheGhost** [comment]
You're always free to create one yourself and contribute to SnailyCAD ;)!

**Comment by Sampuke** [comment]
ill maybe try but im not good at code exept lua anddd maybe c++
