### ISSUE TITLE
[feat]: report vehicle as stolen

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [SnailyCAD/snaily-cadv4#87]
### Describe the feature

Report a registered vehicle as stolen. When searching the vehicle in `Vehicle Search` it will be displayed that the vehicle was reported as stolen.

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost how this feature should work?

**Comment by Dev-CasperTheGhost** [comment]
When editing a registered vehicle, it will allow you to set it `Report as stolen`
