### ISSUE TITLE
Bodycam

### ISSUE THREAD

**Issue by Sampuke** [SnailyCAD/snaily-cadv4#872]
### Describe the feature

Could it be possible to get bodycams to the cad so superior officers woudl be able to see the cam feed both live and old recordings 
like this but with like its own cad page: https://forum.cfx.re/t/paid-standalone-qb-esx-bodycam-real-time-recording/4805058

**Comment by Dev-CasperTheGhost** [comment]
I don't think there's any place for this. This sounds unrealistic IMO?
