### ISSUE TITLE
Sync Fivem Database with the CAD

### ISSUE THREAD

**Issue by William071130** [SnailyCAD/snaily-cadv4#876]
### Describe the feature

Creating a character in-game automatically makes a citizen in the cad

Then if fore example that citizen buys a car in-game it automatically syncs whit the cad and registers the vehicle to the citizen

So basically a connection between the fivem database and the cad

I would have also like if it was very customizable

**Comment by jxckUK** [comment]
You would need to use the API to create this link and it's entirely possible as Casper has spent a long time making all the routes you'd need.

https://cad-docs.caspertheghost.me/docs/developer/public-api
