### ISSUE TITLE
visual improvement

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#878]
### Describe the feature

idk if this is just my ocd but when you have discord only login there is a small little bar in the middle and it dosnt look like it belongs

### Additional Context

![chrome_bWVYAYmWg6](https://user-images.githubusercontent.com/49736448/172970428-141c2ec4-2109-4c73-a334-bf278a721c0c.png)

**Comment by Dev-CasperTheGhost** [comment]
Yeah, looks like that isn’t in the correct spot. Will take a look this afternoon
