### ISSUE TITLE
no password when signing up with discord

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#882]
### Describe the feature

so when i first released the cad to the community i decided to make it discord only because i thought it would be more simple, turns out it was not and i am regretting it now because i want to go to a normal username and password sign in with discord too, but users that signed up with discord (mostly everyone) wouldnt be able to sign in because they dont have a password. i have thought of a work around for this. when the user logs in have it check if the user has a password, if they dont it is going to prompt them to create one.

**Comment by Dev-CasperTheGhost** [comment]
The user can login via Discord, set a new password. The current password should empty.
