### ISSUE TITLE
[UI improvements] Cititzen - Add SSN field to edit page

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#889]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.8.1 618aeae

### Describe the Bug

Now SSN field not presented in edit page, but exist in schema and citizen page
![image](https://user-images.githubusercontent.com/4976837/173658504-69e51500-e5a3-4b17-8618-afd83c56be05.png)

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
Should a citizen be allowed to change their own SSN?

**Comment by pp2amd6** [comment]
Good question but I don't have a clear answer.
On projects where I was play, users have permission for edit SSN.

In scope of "Common citizen card" it is necessary option, because LEO shout have perm for edit SSN
