### ISSUE TITLE
[BUG] Citizen - LEO can't edit ethnicity, phone number

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#892]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.8.1 618aeae

### Describe the Bug

LEO can't edit ethnicity, phone number with enabled "Common citizen card" feature

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
where would this issue occur? Like on what page?

**Comment by pp2amd6** [comment]
> where would this issue occur? Like on what page?

/citizen/{id}

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost sorry, it was bug with browser or something else. Now all work
