### ISSUE TITLE
[CRITICAL BUG] CAD crashes if number of penal code groups = 50

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#893]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.8.1 618aeae

### Describe the Bug

CAD crashes if number of penal code groups = 50

### Expected Behavior

--

### To Reproduce

- Create 49 penal code groups / All Ok
- Create another one (50) group / Get error
![image](https://user-images.githubusercontent.com/4976837/173731725-b09b1617-f4b5-47e4-a781-b2f05db7f78e.png)

![image](https://user-images.githubusercontent.com/4976837/173731944-25b838c6-2388-406b-87e5-10eaac5c71ed.png)

**Comment by Dev-CasperTheGhost** [comment]
Does a page refresh “fix” the issue until a new one is added?

**Comment by pp2amd6** [comment]
> Does a page refresh “fix” the issue until a new one is added?
No. Issue is permanent

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost sorry, I misunderstood the question.
The first 49 groups were added without problems and were immediately visible without reloading the page.
When adding group 50, an error appears. Reloading the page does not fix the problem.
