### ISSUE TITLE
user independent locals

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#899]
### Describe the feature

let each user choose what locales they would like to use on the cad under their settings, not to sure if this is possible because of how nextjs locales works but its worth a shot

**Comment by Dev-CasperTheGhost** [comment]
Yeah, this is possible. But not sure why this should be implemented, since members of a community mostly speak the same languages

**Comment by subtosharki** [comment]
just some members are from other areas and would prefer another language then others

**Comment by Dev-CasperTheGhost** [comment]
I’ll take a look today
