### ISSUE TITLE
URGENT! TypeError

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#905]
### What version of Node.js are you using?

17.3.0

### What version of npm are you using?

7.10.0

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

1.11.1

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/174199053-8644d642-4013-404b-8457-3613bd0d2a2b.png)
![image](https://user-images.githubusercontent.com/25211271/174199210-1945dbd6-7983-482d-b5f0-d19dcf1c1c90.png)
![image](https://user-images.githubusercontent.com/25211271/174200067-548d5897-6ec7-4ff2-99a5-b97bec6321e9.png)

Everyone is getting this I've had 30 reports today alone since the 1.11 update. Not sure what it is. 

### Expected Behavior

To be able to go to officer.

### To Reproduce

I click on Officer then Dashboard then this happens.

**Comment by Dev-CasperTheGhost** [comment]
Try updating again, should’ve been fixed.

**Comment by ViolentMinds** [comment]
But I cant its saying Im already updated

**Comment by Dev-CasperTheGhost** [comment]
Are you still experiencing  this issue @ViolentMinds? Please open a new issue with updated information. This specific issue has been fixed, please provide the following:

- page of error
- screenshot of browser error
- possible API error
- versions
