### ISSUE TITLE
action logging

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#914]
### Describe the feature

whenever any moderation/higher-privilege action is done (basically any leo supervisor/cad admin action) it should be logged somewhere incase of a feature being abused

**Comment by subtosharki** [comment]
possibly discord webhook logging too

**Comment by Dev-CasperTheGhost** [comment]
Currently very wack, but this will probably be the way it's displayed: 
![image](https://user-images.githubusercontent.com/53900565/174650349-3d62cc9d-5871-4f42-bfbd-35d43f8461d0.png)

**Comment by Dev-CasperTheGhost** [comment]
Sure. Soon.

**Comment by subtosharki** [comment]
of course no rush

**Comment by subtosharki** [comment]
eta? @Dev-CasperTheGhost

**Comment by Dev-CasperTheGhost** [comment]
Not really, it's quite complex to work on this myself.

**Comment by Dev-CasperTheGhost** [comment]
Closing since I currently can't figure out a way to do this properly. Hopefully will be able to get back to this in the future
