### ISSUE TITLE
Callsigns

### ISSUE THREAD

**Issue by Xanex-JS** [SnailyCAD/snaily-cadv4#917]
### Describe the feature

Add an option in CAD Settings to remove Callsigns in the officer creation tab and overall the CAD 

As some communitys including mine just use Badger numbers and not Callsigns + badge numbers.

would help others who don't have the skills and knowladge on how to remove said code.

**Comment by pp2amd6** [comment]
> As some communitys including mine just use Badger numbers and not Callsigns + badge numbers.

You can set any random value in callsign field in this case :)
