### ISSUE TITLE
[improvements] Add "hash" field for weapon and vehicle tables

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#92]
### Describe the feature

Add "hash" field for weapon and vehicle tables.

This will allow correct use of the API for working with vehicles and weapons in the future.

Field type: string, required

![kiss_8kb 1635598628 1](https://user-images.githubusercontent.com/4976837/139533689-9909249f-c736-4097-be2c-64e0bc4f0063.png)

**Comment by Dev-CasperTheGhost** [comment]
I think keeping this optional is better because not everyone will need this feature

**Comment by pp2amd6** [comment]
> I think keeping this optional is better because not everyone will need this feature
Yes, you are right.

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost for weapons, it was also necessary to add a field

**Comment by Dev-CasperTheGhost** [comment]
> 
> 
> @Dev-CasperTheGhost for weapons, it was also necessary to add a field

oh whoops. Didn't notice that, sorry. Will add in the next commit
