### ISSUE TITLE
business issue

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#923]
### What version of Node.js are you using?

16.15.1

### What version of npm are you using?

8.11.0

### What operating system are you using?

windows server

### What version of SnailyCAD are you currently using?

latest

### Describe the Bug

i have my limit set to infinity but one of my members can only create 2 (the create button goes away after that) and when he tries to join he gets the error below. he is in a total of 3 (2 owned 1 joined)

https://media.discordapp.net/attachments/988075841160351804/989498808717152356/Screenshot_2022-06-23_at_12.54.57.png?width=1082&height=676

### Expected Behavior

allow him to create/join a business

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed
