### ISSUE TITLE
Major UX Improvement

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#928]
> Try refresh the page. That should fix this

Failure and errors need to be handled better because the user then has to re-enter all of the details they've spent time filling out if it requires a refresh to fix some errors.

This is also the case when accidentally clicking outside of the modal. It's a terrible experience to spend 10 minutes filling a detailed arrest report only for you to lose it all because the system hasn't correctly identified you as active or you had a minor mis-click from the modal.

_Originally posted by @jxckUK in https://github.com/SnailyCAD/snaily-cadv4/issues/925#issuecomment-1164350915_

**Comment by pp2amd6** [comment]
> It's a terrible experience to spend 10 minutes filling a detailed arrest report only for you to lose it all because the system hasn't correctly identified you as active or you had a minor mis-click from the modal.

One of the reasons why I wanted to suggest changing the design as a whole 😃

**Comment by Dev-CasperTheGhost** [comment]
> One of the reasons why I wanted to suggest changing the design as a whole 😃

Feel free to do so! I'm not 100% sure it will be done, but I will definitely take a look at it!

**Comment by Dev-CasperTheGhost** [comment]
I might be able to take a look today/tomorrow, I was busy working on something else this past week 😅 (#934)

**Comment by Dev-CasperTheGhost** [comment]
So, I've tried adding some functionality where it would save current modal progress in sessionStorage, but can be a bit buggy so I'll need to experiment more with it. When should the local data be removed automatically? When the user leaves the site entirely?

**Comment by jxckUK** [comment]
> So, I've tried adding some functionality where it would save current modal progress in sessionStorage, but can be a bit buggy so I'll need to experiment more with it. When should the local data be removed automatically? When the user leaves the site entirely?

Also when the modal is cancelled via the specific "cancel" button/option. Not when the modal is clicked off as this happens a lot accidentally and it can be infuriating.

Obviously once submitted and successful it should also clear that progress.

**Comment by Dev-CasperTheGhost** [comment]
Another quick question: which modals should this be applied to? I don't think this is necessary for all modals?

**Comment by jxckUK** [comment]
> Another quick question: which modals should this be applied to? I don't think this is necessary for all modals?

I honestly think it should be the majority, not so important for smaller modals such as search ones but any forms where you're adding *new* data its critical. Modifying existing records is also not as important. Just anywhere you're filling out information eg:

- New civilian/vehicle registration
- New records of any type incl. Arrest Reports
- New incidents/911s
- New unit registration

**Comment by Dev-CasperTheGhost** [comment]
A modal will now appear if the session has ended, this allows the user to stay in action after quickly reauthorizing their account:). 

For the persistent modals, I'm a bit stuck 😅

**Comment by jxckUK** [comment]
> A modal will now appear if the session has ended, this allows the user to stay in action after quickly reauthorizing their account:).

Ah so will this appear over existing open modals and allows for re-auth then continuation of details in the modal behind? Either way will be a massive, massive improvement!

> For the persistent modals, I'm a bit stuck 😅

Ah - it was an *if* possible, I assume there are some stability issues?

**Comment by Dev-CasperTheGhost** [comment]
> Ah so will this appear over existing open modals and allows for re-auth then continuation of details in the modal behind? Either way will be a massive, massive improvement!

Yep, correct! Check the video in the pull request :) #978

**Comment by Dev-CasperTheGhost** [comment]
> Ah - it was an if possible, I assume there are some stability issues?

yeah, it's quite a wack system right now 😅. I've gotta find out a better solution probably

**Comment by Dev-CasperTheGhost** [comment]
I've found a package that could play nicely with this, it should save "form state" (input fields' data) to localStorage until not needed anymore. This should integrate with the current state solution that SnailyCAD uses. 

Will keep you updated on this issue.

**Comment by Dev-CasperTheGhost** [comment]
Going to close this issue since it's currently to complex to implement this without major changes
