### ISSUE TITLE
Poedit support

### ISSUE THREAD

**Issue by maximehery** [SnailyCAD/snaily-cadv4#93]
### Describe the feature

Add Poedit support for easier and better translation of texts

**Comment by Dev-CasperTheGhost** [comment]
Can you elaborate on "Poedit"?

**Comment by pp2amd6** [comment]
I assume that https://poedit.net/

**Comment by maximehery** [comment]
Yes, the goal would be to convert the texts of the json files to a translatable .pot file and then convert the translated file to the .json format

a diagram explains the process :

![image](https://user-images.githubusercontent.com/15076136/139535550-b59923a8-3adc-428c-aec7-5cf20fce29ff.png)

**Comment by Dev-CasperTheGhost** [comment]
I think will be to complex for some. Maybe I can consider this in the future.
