### ISSUE TITLE
Bug updating divisions for officer

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#930]
### What version of Node.js are you using?

17.3.0

### What version of npm are you using?

7.10.0

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

1.13

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/175465364-f9546446-fdec-4e52-aab6-dd0107484d91.png)

### Expected Behavior

To be able to update divisions for officer without error

### To Reproduce

An Unexpected Error message pops up when I clicked Save when removing divisions from an officer under Manage Units page

**Comment by Dev-CasperTheGhost** [comment]
This is not a bug? You cannot clear all the divisions from a unit. I've added a error message now if it happens

**Comment by ViolentMinds** [comment]
But I wasnt trying to remove them all only some

**Comment by Dev-CasperTheGhost** [comment]
I wasn't able to reproduce that then. Can you show the full error, not just part of it?
