### ISSUE TITLE
cad rank discord role sync

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#932]
### Describe the feature

i know i opened a feature request about this before and it got closed but im opening it again because my members will not stop asking about it. for some odd reason they want the rank in cad to line up with their discord rank.

**Comment by Dev-CasperTheGhost** [comment]
What rank are you talking about. Please be a bit more specific.

**Comment by jxckUK** [comment]
I think he refers to the rank for a unit:

![image](https://user-images.githubusercontent.com/48030374/175773724-ccb7f1ad-7e15-48d0-b666-5b9f15fcd293.png)

I too would like to see this feature, wherever we can add Discord integrations makes things tie together better and automate them.

**Comment by subtosharki** [comment]
yes as jack said, the ranks for a unit

**Comment by Dev-CasperTheGhost** [comment]
> I've hit a minor roadblock. Would the role be added to all the units of the user?

https://github.com/SnailyCAD/snaily-cadv4/issues/433#issuecomment-1046190043

**Comment by subtosharki** [comment]
it would be just like how the permissions are, if the user gets the corporal rank in cad he will get whatever they put the assigned role as in cad, vise versa for if they have the discord role

**Comment by jxckUK** [comment]
> > I've hit a minor roadblock. Would the role be added to all the units of the user?
> 
> [#433 (comment)](https://github.com/SnailyCAD/snaily-cadv4/issues/433#issuecomment-1046190043)

The solution (I think) is to enable mapping of roles to the ranks, so in the values table a new field with the Discord role ID you would like to tie to it. That way the role is applicable only to the departments for which that role applies. It should be added to all civilians registered by that user, for that department.

**Comment by Dev-CasperTheGhost** [comment]
> vise versa for if they have the discord role

Right, but I cannot tell to what officer this rank should be added too.

**Comment by subtosharki** [comment]
such as a feature where when they go to the leo dashboard it will set them available as their "main officer" automatically

**Comment by Dev-CasperTheGhost** [comment]
hm, I'm not sure if I like that idea. Some other ideas might popup soon...

**Comment by Dev-CasperTheGhost** [comment]
Closing this issue for now. However, it will be placed into the backlog
