### ISSUE TITLE
Missing permission or faulty

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#933]
### What version of Node.js are you using?

N/A

### What version of npm are you using?

N/A

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

v1.13.1 a195e96

### Describe the Bug

I can't seem to give access to /officer/supervisor/citizen-logs, I've given users access to this but they still can't see the arrest report logs and have the actions to accept or decline.

### Expected Behavior

That a permission can be given to users in the new permission system that allows for them to access this page and manage arrest reports.

**Comment by Dev-CasperTheGhost** [comment]
I think there's a new permission for it, try add it again

**Comment by jxckUK** [comment]
> I think there's a new permission for it, try add it again

I tried recently just before the bug report but when they try to accept/decline it says forbidden.
