### ISSUE TITLE
mobile bugs

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#935]
list of mobile bugs from community:

"When searching someone’s user as Fire/Ems Vertically, the whole CAD Looks weird, I’d like something just like the registration where it adjusts to the tilt of your mobile"

"When you’re holding your phone portrait, the buttons overlap each other and can’t press the ones you want"

just overall the mobile UI is not always the best and could use some reworking

**Comment by Dev-CasperTheGhost** [comment]
Are you able to provide screenshots for these too? Might make it easier for me to debug :).

**Comment by subtosharki** [comment]
ill get them for you

**Comment by Dev-CasperTheGhost** [comment]
First item should be fixed!

**Comment by Dev-CasperTheGhost** [comment]
any news on a screenshot of the second item? @subtosharki

**Comment by subtosharki** [comment]
another bug is when filling out a arrest report or citation it dosnt automatically put the cost like on pc

**Comment by Dev-CasperTheGhost** [comment]
> another bug is when filling out a arrest report or citation it dosnt automatically put the cost like on pc

Again, I need you to provide a bit more info, this isn't very useful information 😕.
