### ISSUE TITLE
[FEATURE] Possibility for select any citizen when create deputy

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#938]
### Describe the feature

With enabled "Common citizen card" feature, deputies (EMS/FD) cant select any citizen for creating deputy.
On project I using API for automatic creating citizens.
EMS/FD employee should create additional citizen for create deputy and its incorrect.

If "Common citizen card" feature enabled, EMS/FD employee should have ability for create deputy from any citizen in /ems-fd/my-deputies page.
In this time EMS/FD employee should not have ability seeing all citizens in /citizen page

**Comment by Dev-CasperTheGhost** [comment]
This was supported before, correct?

**Comment by Dev-CasperTheGhost** [comment]
This is already supported, I just checked the code and tried it.

**Comment by Dev-CasperTheGhost** [comment]
haven't tested it, but should be fixed now?

**Comment by pp2amd6** [comment]
Now EMS/FD employee can select citizen when create deputy but employee also see all citizens in /citizen page.

EMS/FD employee _**should have**_ ability for create deputy from any citizen in /ems-fd/my-deputies page
and
EMS/FD employee _**should not have**_ ability seeing all citizens in /citizen page

**Comment by Dev-CasperTheGhost** [comment]
@pp2amd6 is this still an issue? Should this be reopened? 

PS: I'm looking at previous issues to see if there are things that I can add now, since the CAD has been changed a lot.
