### ISSUE TITLE
[BUG] Panic button does not work correctly

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#94]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### Describe the Bug

1. Pressing the panic button does not turn off the mode
2. Turning on the panic button does not change the officer's status
![139533847-5d18460e-a56d-4b0c-a4ed-e8e23f83ead6 1](https://user-images.githubusercontent.com/4976837/139576532-aec1e48d-0992-40af-af4e-59ee814e9ee4.png)

### Expected Behavior

Panic button work correctly

**Comment by Dev-CasperTheGhost** [comment]
Sorry for taking this long to get back to this issue! Had to figure out some stuff, which was actually pretty simple. In the video below you'll see the fix, this will be merged shortly!

https://user-images.githubusercontent.com/53900565/147852648-0f510869-be18-46db-991d-3e5725cb7ac3.mov
