### ISSUE TITLE
[BUG] Getting an error when trying to edit an auto

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#95]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### Describe the Bug

Getting an error when trying to edit an auto: `Application error: a client-side exception has occurred (see the browser console for more information).`

### Expected Behavior

--

### To Reproduce

- create vehicle
- press Edit button on record

**Comment by Dev-CasperTheGhost** [comment]
What page does this happen @pp2amd6?

**Comment by pp2amd6** [comment]
/citizen/{id]
