### ISSUE TITLE
priority status

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#951]
### Describe the feature

many servers use a priority timer/status system to manager chaos in their server, i think it would be cool if there was a way that everyone could have a button that would turn the priority status on/off, with a option in settings to put a timer (per minute)

**Comment by subtosharki** [comment]
the statuses the timer could be would be something like

available
active
cooldown
disabled

**Comment by Dev-CasperTheGhost** [comment]
Where would this timer/status be located?

**Comment by Dev-CasperTheGhost** [comment]
>  that everyone could have a button that would turn the priority status on/off

Everyone, like all the citizens, leo, ems-fd, etc?

**Comment by Dev-CasperTheGhost** [comment]
Also, who is able to edit the priority status?

**Comment by subtosharki** [comment]
civilians can

**Comment by Dev-CasperTheGhost** [comment]
Are you able to provide an example or a screenshot? I'm not 100% sure how the status should be changed.

**Comment by subtosharki** [comment]
yea ill find one

**Comment by subtosharki** [comment]
anyway it can be like sonoran cad?

**Comment by subtosharki** [comment]
when a priority is active there is a red bar across the top saying active priority in the middle

**Comment by Dev-CasperTheGhost** [comment]
Are you able to provide screenshots please? I do not have a SonoranCAD, nor do I fully understand what you’re trying to request.

**Comment by subtosharki** [comment]
![image](https://user-images.githubusercontent.com/49736448/178111408-38888919-d02a-451d-b880-e40451fb0d58.gif)

ignore the animation it has nothing to do with it, but that red bar at the top

**Comment by Dev-CasperTheGhost** [comment]
![image](https://user-images.githubusercontent.com/53900565/178112611-25a971a0-5782-418f-8b23-0a263ea1305f.png)

this is just the signal 100? This already exists. 

![image](https://user-images.githubusercontent.com/53900565/178112629-567f4b0b-f58a-4c98-9c8b-f226c8b18b3d.png)

Not sure what this is..

**Comment by subtosharki** [comment]
i dont really know a good place to put it, the idea was from a member

**Comment by Dev-CasperTheGhost** [comment]
Is your member able to explain it here, please?

**Comment by Dev-CasperTheGhost** [comment]
@subtosharki any news 😅?

**Comment by subtosharki** [comment]
no unfortunately i havnt been able to get a hold of him, just went MIA

**Comment by Dev-CasperTheGhost** [comment]
That's unfortunate :/, I'll close this issue for now then due to not having enough information. If the member ever gets back, don't hesitate to re-open this issue!
