### ISSUE TITLE
[UI improvement] /officer - show description for 911 call

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#959]
### Describe the feature

Now officer can see call description only in modal by click on button.
![image](https://user-images.githubusercontent.com/4976837/177689182-f10f5bb3-a8a3-4da7-89b0-83302d4833a6.png)

Propose to show description in 911 calls table on page.
![image](https://user-images.githubusercontent.com/4976837/177689863-5600e301-d554-4539-bc97-b4c71f75c1be.png)

Trim text, if description is too long, make column fixed width and add popup with full description text.
![image](https://user-images.githubusercontent.com/4976837/177690962-76cdf01d-9c9f-4c83-9ed9-aa2ee1141a73.png)

**Comment by Dev-CasperTheGhost** [comment]
What do you think about a "call title"? I feel like showing the description within the table will remove quite some valuable space. So instead of showing the description, it'd show the call title

**Comment by pp2amd6** [comment]
Call title? What is it?
I see Caller field in call modal. You talk about that?

**Comment by Dev-CasperTheGhost** [comment]
it would be a new field, it would be like the description, but shorter.

**Comment by pp2amd6** [comment]
This new field can/should be filled by user or it will be filled automatically?
Like Description field will be trimmed to 20 chars for example?

**Comment by Dev-CasperTheGhost** [comment]
Yeah, why not both 😅

**Comment by pp2amd6** [comment]
The new field that the user will have to fill in is extra work and a waste of time.
Can you technically display the description in the call list shortened at once? If the officer needs to see the full description, he can go to the call card.
