### ISSUE TITLE
[improvements] Add "Rank" field

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#96]
### Describe the feature

Add the "Rank" field to the page for creating and editing police officers and FD officers

**Comment by Dev-CasperTheGhost** [comment]
I didn't include this because it could be that they select the incorrect rank and could sabotage stuff. It's only possible for supervisors to change ranks, maybe there is a better way @pp2amd6?

**Comment by pp2amd6** [comment]
I thought to implement two scenarios:
1. A user with LEO rights has full access
- Can work in the officer's panel
- Can create officers
- Can edit officers
- Can indicate callsign
- Can indicate department / division
- Can indicate rank

2. A user with LEO rights has partial access
- Can work in the officer's panel
- The officer can view the list of officers in read-only mode
- The officer is created by the supervisor
- Officer is edited by a supervisor
- Callsign indicated by the supervisor
- The department / division is indicated by the supervisor
- The rank is indicated by the supervisor

What do you think?

**Comment by pp2amd6** [comment]
@Dev-CasperTheGhost the rank field can be added at this stage.
For the rights of the supervisor, I will write the task separately

**Comment by Dev-CasperTheGhost** [comment]
Closing in favor of #432
