### ISSUE TITLE
discord rpc

### ISSUE THREAD

**Issue by subtosharki** [SnailyCAD/snaily-cadv4#963]
### Describe the feature

discord rpc integration, i am going to open a pr later today but wanted to open this so i dont forget

casper if you can look over discord rpc docs and maybe get some options in cad as i have no idea how to do any of that front end stuff, then ill get them from there

**Comment by Dev-CasperTheGhost** [comment]
I'm going to close this since it's not possible. I'm pretty sure you need to a proxy since Discord doesn't allow requests from third-party domains

**Comment by Dev-CasperTheGhost** [comment]
However, feel free to still try it out.
