### ISSUE TITLE
No way to set User Rank

### ISSUE THREAD

**Issue by dexslab** [SnailyCAD/snaily-cadv4#973]
### What version of Node.js are you using?

16.15.0

### What version of npm are you using?

yarn 1.22.18

### What operating system are you using?

Winblows 10

### What version of SnailyCAD are you currently using?

v1.16.1 e351f56

### Describe the Bug

You cannot set anyones rank without directly modifying the DB so You cannot add persons as Admins or Owners to give access to CAD settings allowing persons to modify the main settings of the CAD

### Expected Behavior

Combo Select to change persons rank when you manage a user

### To Reproduce

Go to manage a user attempt to change from USER to ADMIN or OWNER etc

**Comment by Dev-CasperTheGhost** [comment]
There can only be 1 user with the OWNER rank. Adding back the ability to manage a user's rank will **not** do anything since it's managed via the permissions not ranks.
