### ISSUE TITLE
[BUG] API method "/record" throw UNAUTHORIZED error

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#975]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.16.0 ee360bd

### Describe the Bug

json data, I sent to CAD from FiveM:
```json
{
    "citizenId": "cl4d6fw7k178998125dn5xshxd6",
    "type": "TICKET",
    "postal": "--",
    "notes": "",
    "violations": [
        {
            "fine": 40,
            "penalCodeId": "cl4eydfp8780455125d3mxho0z0"
        }
    ]
}
```

Console output:
![image](https://user-images.githubusercontent.com/4976837/178906557-c51a3902-9200-4343-bd8e-0f83fe791b06.png)

If I send same json from api-docs (swagger), all works fine, record will be created for citizen

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
This route requires an active officer, so this method isn't supported with the API token

**Comment by pp2amd6** [comment]
Ohhh. Can you make support for using with API token?
