### ISSUE TITLE
[BUG] /citizen - Lost ability to edit driver license categories

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#979]
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.17.0 13d3103

### Describe the Bug

![image](https://user-images.githubusercontent.com/4976837/179341992-8a435d18-3a8b-4ae3-8d35-390c7cdf70ec.png)

![image](https://user-images.githubusercontent.com/4976837/179342000-63ad42e5-3604-4913-935a-8fdb1ea285f2.png)

### Expected Behavior

--

**Comment by Dev-CasperTheGhost** [comment]
This is expected behaviour if you have driver’s license feature enabled.

**Comment by pp2amd6** [comment]
> This is expected behaviour if you have driver’s license feature enabled.

Yeap, feature is enabled. I open another ticket in this case :)
