### ISSUE TITLE
[FEATURE REQUEST] Driver license exam

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#98]
### Describe the feature

Implement the functionality of the driver's license exam

The feature is enabled on the Features page.
![kiss_13kb 1635681380 1](https://user-images.githubusercontent.com/4976837/139591460-acb28cd7-3f48-4b3f-9810-f7cac6d7a6af.png)

If the function is active, the "DL exam" item is displayed in the sidebar.
![kiss_11kb 1635682328 1](https://user-images.githubusercontent.com/4976837/139591464-b8c7e895-1185-418e-a043-93ae035adf7e.png)

The page specifies the parameters of the function:
- the need to pass a theoretical exam
- the need to pass a practical exam
- exam cost settings
- setting the cost of the categories of the driver's license
![kiss_24kb 1635688980 1](https://user-images.githubusercontent.com/4976837/139591477-2bc4a93e-1da6-472c-a068-3b221a95a90d.png)

When enabled, the license block is read-only on the citizen page.
![kiss_35kb 1635681828 1](https://user-images.githubusercontent.com/4976837/139591483-8c6ec874-d900-4cbf-8dce-0f248449006c.png)

When enabled, a link to the exam administration page is displayed in the police controller menu
![kiss_21kb 1635690241 1](https://user-images.githubusercontent.com/4976837/139591486-836483d2-9efa-4212-be4b-db90e11cdcb0.png)

The exam page displays data:
- examinee
- the status of passing the theoretical exam
- the status of passing the practical exam
- the categories that the examinee receives
- total cost of passing the exam
- general status of passing the exam

The number of columns is determined by the function settings
![kiss_28kb 1635692580 1](https://user-images.githubusercontent.com/4976837/139591491-630ab797-3820-4f0b-a874-c9145568253c.png)

On the exam page, you must select a citizen who will pass the exam and categories
Cost is automatically calculated
![kiss_15kb 1635695457 1](https://user-images.githubusercontent.com/4976837/139591663-e789e4b9-d0f8-4eb9-a3eb-731dbf0fd65d.png)

Theory exam block will not be displayed if disabled in the function settings

If the theory exam fails, the entire exam fails.

If the entire exam is passed, the citizen is automatically given the categories declared in the exam.

**Comment by Dev-CasperTheGhost** [comment]
Does still allowing editing of other licenses such as weapon and ccw? @pp2amd6

**Comment by pp2amd6** [comment]
The functionality is very similar, but these are different exams.
The exam for a driver's license and possession of a weapon can have different settings, so you cannot show all of them together
